



<div id="page-title">
    <h2>Agent Details</h2>
    <p>The most complete user interface framework that can be used to create stunning admin dashboards and presentation websites.</p>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="panel">
            <div class="panel-body">
                <h3 class="title-hero">View/Edit/Remove Agents</h3>
                <div class="example-box-wrapper">
                    <table id="datatable-responsive" class="table table-striped table-bordered responsive no-wrap" cellspacing="0" width="100%">
                        <thead>
                            <tr>
                                <th>First Name</th>
                                <th> Last name </th>
                                <th> User Name </th>
                                <th> Email</th>
                                <th>City</th>
                                <th> Status </th>
                                <th> Action </th>
                                <th> View/Delete</th>

                            </tr>
                        </thead>
                        <tfoot>
                            <tr>
                                <th>First Name</th>
                                <th> Last name </th>
                                <th> User Name </th>
                                <th> Email</th>
                                <th>City</th>
                                <th> Status </th>
                                <th> Action </th>
                                <th> View/Delete</th>

                            </tr>
                        </tfoot>
                        <tbody>

                            <?php
                            $i = 1;
                            if (isset($this->agentdetails)) {
                                foreach ($this->agentdetails as $value) {
                                    ?>

                                    <tr>
                                        <td><?php echo $value['loginname']; ?></td>
                                        <td><?php echo $value['first_name']; ?></td>
                                        <td><?php echo $value['last_name']; ?></td>
                                        <td><?php echo $value['email']; ?></td>
                                        <td><?php echo $value['city']; ?></td>


                                        <?php if ($value['agent_status'] == 1): ?>
                                            <td id="activeagent_<?php echo $value['agent_id']; ?>" class="agentactive">Active</td>
                                            <td class="center"><a style="cursor:pointer"  id="<?php
                                                if (isset($value['agent_id'])): echo "agent_" . $value['agent_id'];
                                                endif;
                                                ?>" class="agentdeactive">
                                                    <span id="activeclass_<?php echo $value['agent_id']; ?>" class="bs-label label-danger">Deactivate</span></a></td>
                                        <?php else: ?>
                                            <td id="activeagent_<?php echo $value['agent_id']; ?>" class="agentdeactive">Suspended</td>
                                            <td class="center" ><a style="cursor:pointer" id="<?php
                                                if (isset($value['agent_id'])): echo "agent_" . $value['agent_id'];
                                                endif;
                                                ?>" class="agentactive">
                                                    <span id="activeclass_<?php echo $value['agent_id']; ?>"  class="bs-label label-success">Activate</span></a></td>
                                        <?php endif; ?> 


                                        <td class="text-center">
                                            <a href="/admin/edit-agent-details/<?php echo $value['agent_id']; ?>" class="btn btn-default"><i class="glyph-icon icon-linecons-eye"></i></a>
                                            <a href="javascript:;" id="<?php echo "agentdelete_" . $value['agent_id']; ?>" class="btn btn-default deleteagent"><i class="glyph-icon icon-linecons-trash"></i></a>
                                        </td>
                                    </tr>
                                <?php
                                }
                            }
                            ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>




</div>

