<?php $alluserdetailsArray = $this->agentdetails; ?>
<div id="page-title">
    <h2>View Agents Details</h2>
    <p>The most complete user interface framework that can be used to create stunning admin dashboards and presentation websites.</p>
</div>
<div class="row">
    <div class="col-md-12">
        <form class="form-horizontal bordered-row" enctype="multipart/form-data" method="POST">
            <div class="row">
                <div class="col-md-6">
                    <div class="panel">
                        <div class="panel-body">
                            <div class="example-box-wrapper">
                                <table class="table table-responsive">
                                    <tbody>
                                        <tr>
                                            <td>
                                                <label class="control-label">User Name</label>
                                            </td>
                                            <td>
                                                <?php echo $alluserdetailsArray['loginname'] ?>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <label class="control-label">Email</label>
                                            </td>
                                            <td>
                                                <?php echo $alluserdetailsArray['email'] ?>
                                            </td>
                                        </tr>

                                        <tr>
                                            <td>
                                                <label class="control-label">First Name</label>
                                            </td>
                                            <td>
                                                <?php echo $alluserdetailsArray['first_name'] ?>
                                            </td>
                                        </tr>

                                        <tr>
                                            <td>
                                                <label class="control-label">Last Name</label>
                                            </td>
                                            <td>
                                                <?php echo $alluserdetailsArray['last_name'] ?>
                                            </td>
                                        </tr>

                                        <tr>
                                            <td>
                                                <label class="control-label">status</label>
                                            </td>
                                            <td>
                                                <?php
                                                if ($alluserdetailsArray['agent_status'] == 1) {
                                                    echo"Active ";
                                                } else {
                                                    echo"Deactivate";
                                                }
                                                ?>                                                                                                     
                                            </td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="panel">
                        <div class="panel-body">
                            <div class="example-box-wrapper">
                                <table class="table table-responsive">
                                    <tbody>
                                        <tr>
                                            <td>
                                                <label class="control-label">MemberShip Status</label>
                                            </td>
                                            <td>
                                                <?php
                                                if ($alluserdetailsArray['membership'] == 1) {
                                                    echo"Active Member";
                                                } else {
                                                    echo"Deactivate Member";
                                                }
                                                ?>
                                            </td>

                                        </tr>

                                        <tr>
                                            <td>
                                                <label class="control-label">City</label>
                                            </td>
                                            <td>
                                                <div class="input-group">
<?php echo $alluserdetailsArray['city'] ?>
                                                </div>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <label class="control-label">Address</label>
                                            </td>
                                            <td>
<?php echo $alluserdetailsArray['address'] ?>
                                            </td>
                                        </tr>
                                    </tbody>
                                </table>                         
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>



