<?php $alluserdetailsArray = $this->agentdetails; ?>
<div id="page-title">
    <h2>View Agents Details</h2>
</div>
<div class="row">
    <div class="col-md-12">
        <form class="form-horizontal bordered-row" enctype="multipart/form-data" method="POST">
            <div class="row">
                <div class="col-md-6">
                    <div class="panel">
                        <div class="panel-body">
                            <div class="example-box-wrapper">
                                <table class="table table-responsive">
                                    <tbody>
                                        <tr>
                                            <td>
                                                <label class="control-label">Agent ID</label>
                                            </td>
                                            <td>
                                                <?php echo $alluserdetailsArray['agent_id'] ?>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <label class="control-label">Agent Image</label>
                                            </td>
                                            <td>
                                                <div class="fileinput fileinput-new" data-provides="fileinput">
                                                    <div class="fileinput-new thumbnail" style="width: 200px; height: 150px;">
                                                        <img src="<?php
                                                        if (isset($alluserdetailsArray['profilepic_url'])) {
                                                            echo $alluserdetailsArray['profilepic_url'];
                                                        }
                                                        ?>" alt="">
                                                    </div>
                                                    <div class="fileinput-preview fileinput-exists thumbnail" style="max-width: 200px; max-height: 150px;"></div>        
                                                </div>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <label class="control-label">Agent Name</label>
                                            </td>
                                            <td>
                                                <?php echo $alluserdetailsArray['loginname'] ?>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <label class="control-label">Email</label>
                                            </td>
                                            <td>
                                                <?php echo $alluserdetailsArray['email'] ?>
                                            </td>
                                        </tr>

                                        <tr>
                                            <td>
                                                <label class="control-label">First Name</label>
                                            </td>
                                            <td>
                                                <?php echo $alluserdetailsArray['first_name'] ?>
                                            </td>
                                        </tr>

                                        <tr>
                                            <td>
                                                <label class="control-label">Last Name</label>
                                            </td>
                                            <td>
                                                <?php echo $alluserdetailsArray['last_name'] ?>
                                            </td>
                                        </tr>  
<!--                                        <tr>
                                            <td>
                                                <label class="control-label">Password</label>
                                            </td>
                                            <td>
                                        <?php //echo ($alluserdetailsArray['password'] ); ?>
                                            </td>
                                        </tr>-->
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="panel">
                        <div class="panel-body">
                            <div class="example-box-wrapper">
                                <table class="table table-responsive">
                                    <tbody>
                                        <tr>
                                            <td>
                                                <label class="control-label">Phone</label>
                                            </td>
                                            <td>
                                                <?php echo $alluserdetailsArray['phonecode']; ?> &nbsp; <?php echo $alluserdetailsArray['phone']; ?>


                                            <td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <label class="control-label">MemberShip Status</label>
                                            </td>
                                            <td>
                                                <?php
                                                if ($alluserdetailsArray['membership'] == 1) {
                                                    echo"Active Member";
                                                } else {
                                                    echo"Deactivate Member";
                                                }
                                                ?>
                                            </td>

                                        </tr>

                                        <tr>
                                            <td>
                                                <label class="control-label">City</label>
                                            </td>
                                            <td>
                                                <div class="input-group">
                                                    <?php echo $alluserdetailsArray['city'] ?>
                                                </div>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <label class="control-label">Address</label>
                                            </td>
                                            <td>
                                                <?php echo $alluserdetailsArray['addresss'] ?>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <label class="control-label">Status</label>
                                            </td>
                                            <td>
                                                <?php
                                                if ($alluserdetailsArray['agent_status'] == 1) {
                                                    echo"Active ";
                                                } else {
                                                    echo"Deactivate";
                                                }
                                                ?>                                                                                                     
                                            </td>
                                        </tr>
                                    </tbody>
                                </table>                         
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>



