<div id="content">
	<h3>Player Stats</h3>
<div class="innerLR">

	<!-- Widget -->
	<div class="widget widget-tabs border-bottom-none">
	
		<!-- Widget heading -->
		<div class="widget-head">
			<ul>
				<li class="active"><a class="glyphicons edit" href="#account-details" data-toggle="tab"><i></i>Manage Stats</a></li>
<!--				<li><a class="glyphicons settings" href="#account-settings" data-toggle="tab"><i></i>Account settings</a></li>-->
			</ul>
		</div>
		<!-- // Widget heading END -->
		
		<div class="widget-body">
                    <form class="form-horizontal margin-none"  method="post">
				<div class="tab-content pad0">
				
					<!-- Tab content -->
					<div class="tab-pane active" id="account-details">
					
						<!-- Row -->
						<div class="row-fluid">						
							<!-- Column -->
                                                    <div class="span6">					      		
                                                            <!-- Group -->
                                                            <div class="control-group">
                                                                    <label class="control-label">Status</label>
                                                                    <div class="controls">
                                                                        <select class="span4" name="status">
                                                                            <option value="">Select</option>
                                                                            <?php if(isset($this->sportsDetails)): foreach($this->sportsDetails as $sportsValue): ?>
                                                                            <option  value="<?php echo $sportsValue['sports_id']; ?>"><?php echo $sportsValue['display_name']; ?> </option>   
                                                                            <?php endforeach; endif; ?>
                                                                                                                                                            
                                                                        </select>										
                                                                            <!--<span class="btn-action single glyphicons circle_question_mark margin-none" data-toggle="tooltip" data-placement="top" data-original-title="Last name is mandatory"><i></i></span>-->
                                                                    </div>
                                                            </div>
                                                            <!-- // Group END -->                                                                

                                                    </div>
						</div>
						<!-- // Row END -->
						
						<div class="separator line bottom"></div>
						
						<!-- Group -->
<!--						<div class="control-group row-fluid">
							<label class="control-label">About me</label>
							<div class="controls">
								<textarea id="mustHaveId" class="wysihtml5 span12" rows="5">Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium.</textarea>
							</div>
						</div>-->
						<!-- // Group END -->
						
						<!-- Form actions -->
						<div class="form-actions" class="margin-none">
							<button type="submit" class="btn btn-icon btn-primary glyphicons circle_ok"><i></i>Save changes</button>
                                                        <a href="<?php $this->baseUrl(); ?>/admin/userdetails?page=<?php echo $this->page;?>">	<button type="button" class="btn btn-icon btn-default glyphicons circle_remove"><i></i>Cancel</button> </a>
						</div>
						<!-- // Form actions END -->
						
					</div>
					<!-- // Tab content END -->
					
				</div>
			</form>
		</div>
	</div>
	<!-- // Widget END -->
	
</div>	
</div>
<script>
    $('#menu_components6').removeClass('collapse').addClass('in collapse');
    $('#game_menu').removeClass('hasSubmenu glyphicons cogwheels').addClass('hasSubmenu glyphicons cogwheels active');
    $('#add_new_game').addClass('active');    
</script>