<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Player Setting
            <small>for your next cool web APP</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-futbol-o"></i> Home</a></li>
            <li>Player Setting</li>
            <li class="active">Player Salary</li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">
        <!-- Info boxes -->
        <div class="row">
            <div class="col-md-12 col-sm-12 no-p-left no-p-right">
                <div class="panel panel-black no-radius">
                    <div class="panel-heading paddingLR-md paddingTB-sm no-radius">
                        <h3 class="font-Russo-One no-margin">Player Salary</h3>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12 col-sm-12">
                <div class="panel panel-gray">
                    <div class="panel-heading paddingLR-md paddingTB-xs">
                        <h4 class="font-Libre-Baskerville">Upload csv file</h4>
                    </div>
                    <div class="panel-body padding-md">
                        <div class="row">
                            <div class="col-md-8 col-sm-8 col-sm-offset-2 col-xs-12">
                                <!--                            	<div class="form-group">
                                                                        <div class="input-group">
                                                                        <input type="file" id="file1">
                                                                    </div>
                                                                </div>
                                                                
                                                                <div class="form-group">
                                                                        <div class="input-group">
                                                                        <input type="file" id="file1">
                                                                    </div>
                                                                </div>
                                                                <div class="form-group">
                                                                        <button class="btn btn-blue paddingLR-lg">Upload Stats</button>
                                                                </div>-->
                                <form class="form-group" action="" method="post" enctype="multipart/form-data">
                                    <div class="form-group">
                                        <div class="input-group">
                                            <input type="file" name="file1" id="file1"><?php echo $this->error; ?>
                                        </div></div>
                                    <div class="form-group">
                                        <div class="input-group">
                                            <input type="file" id="file2" name="file2"><?php echo $this->error; ?>
                                        </div></div>
                                    <input type="submit" class="btn btn-blue paddingLR-lg" value="Upload Stats">

                                </form>    


                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>



    </section><!-- /.content -->
</div>

<!----------------------Modals-------------------------->
<!---------Delete Offer------------>
<div class="modal fade" id="editPlayer" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content modal-content-bg">
            <div class="modal-header model-header-bg no-border-bottom">
                <button type="button" data-dismiss="modal" class="close text-white"><span aria-hidden="true" aria-label="Close">&times;</span></button>

                <h3 class="font-Titillium-Web no-margin text-center">Edit Player</h3>

            </div>
            <div class="modal-body">
                <div class="panel panel-black">
                    <div class="panel-heading paddingLR-md">
                        <h4><span class="m-right-sm"><i class="fa fa-edit"></i></span>Player Details</h4>
                    </div>
                    <div class="panel-body padding-sm">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label for="pName">Player Name</label>
                                    <div class="input-group col-xs-12">
                                        <input id="pName" type="text" class="form-control" value="Miguel Montero" disabled> 
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="pAge">Age</label>
                                    <div class="input-group col-xs-12">
                                        <input id="pAge" type="text" class="form-control" value="28" disabled> 
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="fppg">FPPG</label>
                                    <div class="input-group col-xs-12">
                                        <input id="fppg" type="text" class="form-control" value="6.02"> 
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="fpts">FPTS</label>
                                    <div class="input-group col-xs-12">
                                        <input id="fpts" type="text" class="form-control" value="0"> 
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="pSalary">Player Salary</label>
                                    <div class="input-group col-xs-12">
                                        <span class="input-group-addon">
                                            <i class="fa fa-usd"></i>
                                        </span> 
                                        <input id="pSalary" type="text" class="form-control" value="7500">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="iStatus">Injury Status</label>
                                    <div class="input-group col-xs-12">
                                        <select id="iStatus" class="form-control">
                                            <option>Active</option>
                                            <option>Deactive</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="iReason">Injury Reason</label>
                                    <div class="input-group col-xs-12">
                                        <input id="iReason" type="text" class="form-control" value=""> 
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer light-bg clear-both no-border-top">

                <div class="text-center">
                    <button class="btn btn-blue">Save Changes</button>
                    <button data-dismiss="modal" class="btn btn-gray font-Russo-One">Cancel</button>
                </div>
            </div>
        </div>
    </div>
</div><!---------EditOffer ------------>