<div id="content" class="content">
    <ol class="breadcrumb pull-right">
        <li><a href="index.html">Home</a></li>
        <li><a href="javascript:;">Grocery</a></li>
        <li class="active">Add Grocery</li>
    </ol>
    <!-- end breadcrumb -->
    <!-- begin page-header -->
    <h1 class="page-header">Add Grocery </h1>
    <!-- end page-header -->

    <!-- begin row -->
    <div class="row">
        <!-- begin col-12 -->
        <div class="col-md-12">
            <!-- begin panel -->
            <div class="panel pagination-theme clearfix m-b-0">
                <div class="panel-body">
                    <form class="" role="form" enctype="multipart/form-data" method="POST">
                        <div class="row">
                            <div class="col-md-12">
                                <legend class="heading">Location:</legend>

                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label class="control-label">Select the Country</label>
                                            <select class="form-control selectpicker width-full selectcountry" name="selectcountry" da selectpicker width-full ta-size="10" data-live-search="true">
                                                <optgroup label="Select Country">
                                                    <option> Select Country </option>
                                                    <?php
                                                    if (isset($this->countrylist)) {
                                                        foreach ($this->countrylist as $value) {
                                                            ?>
                                                            <option value="<?php echo $value['location_id']; ?>"><?php echo $value['name']; ?></option>
                                                            <?php
                                                        }
                                                    }
                                                    ?>
                                                </optgroup>
                                            </select>
                                        </div>
                                        <div class="form-group">
                                            <label class="control-label">Select the State</label>
                                            <select id="state" class="form-control selectpicker width-full selectstate" name="selectstate" data-size="10" data-live-search="true">
                                                <optgroup label="Select State" id="state">
                                                    <option> Select State </option>
                                                </optgroup>
                                            </select>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label class="control-label">Select the City</label>
                                            <select id="city" class="form-control selectpicker width-full selectcity" name="selectcity" data-size="10" data-live-search="true">
                                                <optgroup label="Select City" id="city">
                                                    <option> Select City </option>
                                                </optgroup>
                                            </select>
                                        </div>
                                        <div class="form-group">
                                            <label class="control-label">Select the Location</label>
                                            <select id="location" class="form-control selectpicker loc-disable width-full" name="selectlocation" data-size="10" data-live-search="true">
                                                <optgroup label="Select Location" id="location">
                                                    <option value=""> Select Location </option>
                                                </optgroup>
                                            </select>
                                            <small><i>if your location is not listed, Click <a href="javascript:;" class="add-loc">here</a></i></small>
                                            <input type="text" class="form-control m-t-20 new-location" name="location_name" placeholder="Enter your Location" />
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-12">
                                <legend class="heading">Details:</legend>

                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group has-success has-feedback m-b-10">
                                            <label class="control-label">Grocery Name</label>
                                            <input type="text" name="grocery_name" class="form-control" />
                                            <span class="fa fa-check form-control-feedback"></span>
                                        </div>



                                        <div class="form-group has-error has-feedback m-b-10">
                                            <label class="control-label">Grocery Address</label>
                                            <textarea  name="address" class="form-control" rows="3"></textarea>
                                            <span class="fa fa-times form-control-feedback"></span>
                                        </div>
                                        <div class="form-inline m-b-10">
                                            <label class="">Timing</label>
                                            <br/>
                                            <div class="form-group">
                                                <input type="text" placeholder="Opening Time" name="open_time" class="form-control" /> AM &nbsp; &nbsp; &nbsp; &nbsp;
                                            </div>
                                            <div class="form-group">
                                                <input type="text" placeholder="Closing Time" name="closing_time" class="form-control" /> PM
                                            </div>
                                        </div>

                                        <div class="form-group m-b-10">
                                            <label class="control-label">Primary Phone No.</label>
                                            <input type="text" name="primary_phone" class="form-control" />
                                        </div>

                                        <div class="form-group m-b-10">
                                            <label class="control-label">Secondary Phone No.</label>
                                            <input type="text"  name="secondary_phone" class="form-control" />
                                        </div>

                                        <div class="form-group">
                                            <label class="control-label">Status</label>
                                            <select class="form-control selectpicker width-full" name="grocery_status" data-size="10">
                                                <option value="1">Active</option>
                                                <option value="2">Inactive</option>
                                            </select>
                                        </div>
                                    </div>

                                    <div class="col-md-6">
                                        <div class="form-group m-b-10">
                                            <label class="control-label">Grocery Image</label>
                                            <div class="form-group">
                                                <div class="fileinput fileinput-new" data-provides="fileinput">
                                                    <div class="fileinput-new thumbnail" style="width: 200px; height: 150px;">
                                                        <img src="http://placehold.it/200x150" alt="">
                                                    </div>
                                                    <div class="fileinput-preview fileinput-exists thumbnail" style="max-width: 200px; max-height: 150px;"></div>
                                                    <div>
                                                        <span class="btn btn-default btn-file">
                                                            <span class="fileinput-new">Select Image</span>
                                                            <span class="fileinput-exists">Replace</span>
                                                            <input type="file" name="fileToUpload">
                                                        </span>
                                                        <a href="#" class="btn btn-danger fileinput-exists" data-dismiss="fileinput">Remove</a>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="form-group m-b-10">
                                            <label class="control-label">Min. Order</label>
                                            <input type="text" name="minorder" class="form-control" />
                                        </div>
                                        <div class="form-group m-b-10">
                                            <label class="control-label">Delivery Charges</label>
                                            <input type="text" name="deliverycharge" class="form-control" />
                                        </div>
                                        <div class="form-group m-b-10">
                                            <label class="control-label">Grocery Notice</label>
                                            <textarea   name="notice" class="form-control"></textarea>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="text-right m-r-10">
                                <button type="submit" class="btn btn-theme">Add Grocery</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            <!-- end panel -->
        </div>
        <!-- end col-12 -->
    </div>
    <!-- end row -->
</div>
