
<div id="content" class="content">
    <!-- begin breadcrumb -->
    <ol class="breadcrumb pull-right">
        <li><a href="javascript:;">Home</a></li>
        <li><a href="javascript:;">Grocery Details</a></li>
        <li class="active">Grocery Details</li>
    </ol>
    <!-- end breadcrumb -->
    <!-- begin page-header -->
    <h1 class="page-header">Grocery Details </h1>
    <!-- end page-header -->

    <!-- begin row -->
    <div class="row">
        <!-- begin col-12 -->
        <div class="col-md-12">
            <div class="text-right m-b-15">
                <a href="/agent/add-grocery-details" class="btn btn-primary"> <i class="fa fa-plus-circle"></i> Add Grocery </a>
            </div>
            <!-- begin panel -->
            <div class="panel pagination-theme clearfix m-b-0">
                <table id="data-table" data-order='[[1,"asc"]]' class="table table-bordered table-hover">
                    <thead>
                        <tr class="default">
                            <th> Grocery Name </th>
                             <th> Rating </th>
                            <th> Timing </th>
                            <th> Status </th>
                            <th> Status Change </th>
                            <th> Action </th>
<!--                            <th> View Orders </th>-->
                        </tr>
                    </thead>
                    <tbody>
                        <?php
                        if (isset($this->grocerydetails)) {
                            $i = 0;
                            foreach ($this->grocerydetails as $value) {
                                ?>
                                <tr id="<?php echo $value['id']; ?>">
                                    <td><?php echo $value['Grocery_name']; ?></td>
                                    <td><?php echo $value['Grocery_rating']; ?></td>
                                    <td>
                                        <span><?php echo $value['Open_time']; ?>AM</span> - <span><?php echo $value['Closing_time']; ?>PM</span>
                                    </td>
                                    <?php if ($value['grocery_status'] == 1) { ?>
                                        <td>
                                            <label id="activeclass_<?php echo $value['grocery_id']; ?>" class="label label-success js-check-change-field">ACTIVE</label>
                                        </td>

                                        <td class="text-center">
                                            <input type="checkbox" data-render="switchery" id="<?php
                                            if (isset($value['grocery_id'])): echo "grocery_" . $value['grocery_id'];
                                            endif;
                                            ?>"  class="js-switch js-check-change grocerydeactive" data-theme="lime" checked /> 
                                        </td>
                                    <?php }else { ?>
                                        <td >
                                            <label id="activeclass_<?php echo $value['grocery_id']; ?>" class="label label-danger js-check-change-field">SUSPENDED</label>
                                        </td>
                                        <td class="text-center">
                                            <input type="checkbox" data-render="switchery" id="<?php
                                            if (isset($value['grocery_id'])): echo "grocery_" . $value['grocery_id'];
                                            endif;
                                            ?>"  class="js-switch js-check-change groceryactive" data-theme="lime" /> 
                                        </td>
                                    <?php } ?>

                                    <td class="text-center">

                                        <a href="/agent/view-grocery-details/<?php echo $value['grocery_id']; ?>" class="btn btn-purple btn-icon btn-circle btn-sm"><i class="fa fa-eye"></i></a>
                                        <a href="/agent/edit-grocery-details/<?php echo $value['grocery_id']; ?>" class="btn btn-success btn-icon btn-circle btn-sm"><i class="fa fa-pencil"></i></a>
                                        <a href="javascript:;" id="<?php echo "grocerydelete_" . $value['grocery_id']; ?>" class="btn btn-primary btn-icon btn-circle btn-sm deletegrocery">
                                            <i class="fa fa-trash"></i>
                                        </a>
                                    </td>
<!--                                    <td class="text-center">
                                        <a href="/agent/restuarent-orders/<?php echo $value['grocery_id']; ?>">
                                            <button type="submit" class="btn btn-theme">View Orders</button>

                                        </a>
                                    </td>-->
                                </tr>
                                <?php
                            }
                        }
                        ?>

                    </tbody>
                </table>
            </div>

        </div>

    </div>

</div>



