<div id="content" class="content">
    <ol class="breadcrumb pull-right">
        <li><a href="/agent/dashboard">Dashboard</a></li>
        <li><a href="javascript:;">Grocery Details</a></li>
        <li class="active">View Grocery Details</li>
    </ol>
    <!-- end breadcrumb -->
    <!-- begin page-header -->
    <h1 class="page-header">View Grocery Details </h1>
    <!-- end page-header -->

    <!-- begin row -->
    <div class="row">
        <!-- begin col-12 -->
        <div class="col-md-12">
            <!-- begin panel -->
            <div class="panel pagination-theme clearfix m-b-0">
                <div class="panel-body">
                    <form class="" role="form" enctype="multipart/form-data" method="POST">
                        <div class="row">
                            <div class="col-md-12">
                                <legend class="heading">Location:</legend>

                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label class="control-label">Country</label>

                                            <?php
                                            if (isset($this->grocerydetails['countryName'])) {
                                                echo $this->grocerydetails['countryName'];
                                            }
                                            ?>

                                        </div>
                                        <div class="form-group">
                                            <label class="control-label"> State</label>

                                            <?php
                                            if (isset($this->grocerydetails['stateName'])) {
                                                echo $this->grocerydetails['stateName'];
                                            }
                                            ?>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label class="control-label"> City</label>

                                                <?php
                                                if (isset($this->grocerydetails['cityName'])) {
                                                    echo $this->grocerydetails['cityName'];
                                                }
                                                ?>
                                            </div>
                                            <div class="form-group">
                                                <label class="control-label"> Location</label>

                                                <?php
                                                if (isset($this->grocerydetails['areaName'])) {
                                                    echo $this->grocerydetails['areaName'];
                                                }
                                                ?>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <legend class="heading">Details:</legend>

                                    <div class="row">
                                        <div class="col-md-6">
                                            <div class="form-group has-success has-feedback m-b-10">
                                                <label class="control-label">Grocery Name</label>
                                                <?php
                                                if (isset($this->grocerydetails['Grocery_name'])) {
                                                    echo $this->grocerydetails['Grocery_name'];
                                                }
                                                ?>

                                            </div>
                                            <div class="form-group has-success has-feedback m-b-10">
                                                <label class="control-label">Grocery Rating</label>
                                                <?php
                                                if (isset($this->grocerydetails['Grocery_rating'])) {
                                                    echo $this->grocerydetails['Grocery_rating'];
                                                }
                                                ?>

                                            </div>
                                            <div class="form-group has-error has-feedback m-b-10">
                                                <label class="control-label">Grocery Address</label>
                                                <?php
                                                if (isset($this->grocerydetails['Address'])) {
                                                    echo $this->grocerydetails['Address'];
                                                }
                                                ?>
                                            </div>
                                            <div class="form-inline m-b-10">
                                                <label class="">Timing</label>
                                                <br/>
                                                <div style="display: inline-flex;">
                                                    <div class="form-group" style="width: 53%;">
                                                        <?php
                                                        if (isset($this->grocerydetails['Open_time'])) {
                                                            echo $this->grocerydetails['Open_time'];
                                                        }
                                                        ?> AM &nbsp; &nbsp; &nbsp; &nbsp;
                                                    </div>
                                                    <div class="form-group">
                                                        <?php
                                                        if (isset($this->grocerydetails['Closing_time'])) {
                                                            echo $this->grocerydetails['Closing_time'];
                                                        }
                                                        ?>PM
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="form-group m-b-10">
                                                <label class="control-label">Primary Phone No.</label>
                                                <?php
                                                if (isset($this->grocerydetails['grocery_contact_number'])) {
                                                    echo $this->grocerydetails['grocery_contact_number'];
                                                }
                                                ?>
                                            </div>

                                            <div class="form-group m-b-10">
                                                <label class="control-label">Secondary Phone No.</label>
                                                <?php
                                                if (isset($this->grocerydetails['Secondary_phone'])) {
                                                    echo $this->grocerydetails['Secondary_phone'];
                                                }
                                                ?>
                                            </div>
                                            <div class="form-group">
                                                <label class="control-label">Status</label>
                                                <?php
                                                if (isset($this->grocerydetails['grocery_status']) == 1) {
                                                    echo "Active";
                                                } else {
                                                    echo "Inactive";
                                                }
                                                ?>
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group m-b-10">
                                                <label class="control-label">Grocery Image</label>
                                                <div class="form-group">
                                                    <div class="fileinput fileinput-new" data-provides="fileinput">
                                                        <div class="fileinput-new thumbnail" style="width: 200px; height: 150px;">
                                                            <img src="<?php
                                                            if (isset($this->grocerydetails['Grocery_image'])) {
                                                                echo $this->grocerydetails['Grocery_image'];
                                                            }
                                                            ?>" alt="">
                                                        </div>
                                                        <div class="fileinput-preview fileinput-exists thumbnail" style="max-width: 200px; max-height: 150px;"></div>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="form-group m-b-10">
                                                <label class="control-label">Min. Order</label>
                                                <?php
                                                if (isset($this->grocerydetails['Minorder'])) {
                                                    echo $this->grocerydetails['Minorder'];
                                                }
                                                ?>
                                            </div>
                                            <div class="form-group m-b-10">
                                                <label class="control-label">Delivery Charges</label>
                                                <?php
                                                if (isset($this->grocerydetails['Deliverycharge'])) {
                                                    echo $this->grocerydetails['Deliverycharge'];
                                                }
                                                ?>
                                            </div>
                                            <div class="form-group m-b-10">
                                                <label class="control-label">Grocery Notice</label>
                                                <?php
                                                if (isset($this->grocerydetails['Notice'])) {
                                                    echo $this->grocerydetails['Notice'];
                                                }
                                                ?>
                                            </div>
                                        </div>
                                    </div>                                   
                                </div>
                            </div>                
                        </div>
                    </form>
                    <!-- end panel -->
                </div>
                <!-- end col-12 -->
            </div>
            <!-- end row -->
        </div>
    </div>
</div>