<?php
$allstoredetailsArray = $this->allstoredetails;
$allStoreCategorynames = $this->allStoreCategorynames;
?>
<div id="page-title">
    <h2>View Store Details</h2>
</div>
<div class="row">
    <div class="col-md-12">
        <form class="form-horizontal bordered-row" enctype="multipart/form-data" method="POST">
            <div class="row">
                <div class="col-md-6">
                    <div class="panel">
                        <div class="panel-body">
                            <div class="example-box-wrapper">
                                <table class="table table-responsive">
                                    <tbody>
                                        <tr>
                                            <td>
                                                <label class="control-label">Agent ID</label>
                                            </td>
                                            <td>
                                                <?php echo $allstoredetailsArray['agent_id'] ?>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <label class="control-label">Agent Name</label>
                                            </td>
                                            <td>
                                                <?php echo $allstoredetailsArray['loginname'] ?>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <label class="control-label">Store Name</label>
                                            </td>
                                            <td>
                                                <?php echo $allstoredetailsArray['store_name'] ?>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <label class="control-label">Store Rating</label>
                                            </td>
                                            <td>
                                                <?php echo $allstoredetailsArray['store_rating'] ?>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <label class="control-label">Store Address</label>
                                            </td>
                                            <td>
                                                <?php echo $allstoredetailsArray['store_address'] ?>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <label class="control-label">Timing</label>
                                            </td>
                                            <td>
                                                <div class="" style="display: inline-flex;">
                                                    <?php echo $allstoredetailsArray['Open_time'] ?>&nbsp; AM&nbsp; &nbsp;- &nbsp;<?php echo $allstoredetailsArray['Closing_time'] ?>&nbsp; PM
                                                </div>
                                            </td>
                                        </tr>                                  
                                        <tr>
                                            <td>
                                                <label class="control-label">Status</label>
                                            </td>
                                            <td>
                                                <?php
                                                if ($allstoredetailsArray['store_status'] == 1) {
                                                    echo"Active";
                                                } else {
                                                    echo"Deactivate";
                                                }
                                                ?>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <label class="control-label">Primary Phone No.</label>
                                            </td>
                                            <td>
                                                <?php echo $allstoredetailsArray['store_contact_number'] ?>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <label class="control-label">Secondary Phone No.</label>
                                            </td>
                                            <td>
                                                <?php echo $allstoredetailsArray['Secondary_phone'] ?>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <label class="control-label">categories name:</label>
                                            </td>
                                            <td>
                                                <?php
                                                for ($i = 0; $i < count($allStoreCategorynames); $i++) {

                                                    echo $allStoreCategorynames[$i] . ", ";
                                                }
                                                ?>
                                            </td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="panel">
                        <div class="panel-body">
                            <div class="example-box-wrapper">
                                <table class="table table-responsive">
                                    <tbody>

                                        <tr>
                                            <td>
                                                <label class="control-label">Country:</label>
                                            </td>
                                            <td>
                                                <?php echo $allstoredetailsArray['countryName'] ?>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <label class="control-label">State:</label>
                                            </td>
                                            <td>
                                                <?php echo $allstoredetailsArray['stateName'] ?>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <label class="control-label">City:</label>
                                            </td>
                                            <td>
                                                <?php echo $allstoredetailsArray['cityName'] ?>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <label class="control-label">Location:</label>
                                            </td>
                                            <td>
                                                <?php echo $allstoredetailsArray['areaName'] ?>
                                            </td>
                                        </tr>

                                        <tr>
                                            <td>
                                                <label class="control-label">Store Image</label>
                                            </td>
                                            <td>
                                                <div class="fileinput fileinput-new" data-provides="fileinput">
                                                    <div class="fileinput-new thumbnail" style="width: 200px; height: 150px;">
                                                        <img src="<?php
                                                        if (isset($this->allstoredetails['Store_image'])) {
                                                            echo $this->allstoredetails['Store_image'];
                                                        }
                                                        ?>" >
                                                    </div>
                                                    <div class="fileinput-preview fileinput-exists thumbnail" style="max-width: 200px; max-height: 150px;"></div>               
                                                </div>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <label class="control-label">Delivery Charges</label>
                                            </td>
                                            <td>
                                                <?php echo $allstoredetailsArray['Deliverycharge'] ?>

                                            </td>
                                        </tr>                                   
                                        <tr>
                                            <td>
                                                <label class="control-label">Store Notice</label>
                                            </td>
                                            <td>
                                                <?php echo $allstoredetailsArray['Notice'] ?>

                                            </td>
                                        </tr>

                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

<style>
    .select2.select2-container {
        width: 100% !important;
    }
</style>