


<div id="content" class="content">
    <ol class="breadcrumb pull-right">
        <li><a href="index.html">Home</a></li>
        <li><a href="javascript:;">Product</a></li>
        <li class="active">View/Edit Product</li>
    </ol>
    <h1 class="page-header">View/Edit Product <small>header small text goes here...</small></h1>

    <div class="row">
        <div class="col-md-12">
            <form class="" enctype="multipart/form-data" method="POST">
                <div class="row">
                    <div class="col-md-6">
                        <div class="panel pagination-theme clearfix m-b-0">
                            <div class="panel-body">
                                <div class="form-group">
                                    <label class="control-label">Product Name</label>
                                    <input type="text" class="form-control" name="name" value="" placeholder="" required />
                                </div>
                                <div class="form-group">
                                    <label class="control-label">Product Description</label>
                                    <textarea class="form-control" name="prod_desc" value="" placeholder="" required><?php echo $this->allproductdetails['prod_desc'] ?></textarea>
                                </div>
                                <div class="form-group">
                                    <label class="control-label">Product Type</label>
                                    <div>
                                        <label class="radio-inline">
                                            <input type="radio" value="1" name="product_type"  id="type_category" /> Category
                                        </label>
                                        <label class="radio-inline">
                                            <input type="radio" value="2"  name="product_type"  id="type_cusine" /> Cusine
                                        </label>
                                    </div>
                                </div>
                                <div class="form-group show-cusine">
                                    <label class="control-label">Cusine :</label>
                                    <select class="selectpicker width-full form-control" id="cuisine" name="cusine_id" style="width:100%;">
                                        <option disabled selected>Select Cusine</option>

                                    </select>
                                </div>
                                <div class="form-group show-category">
                                    <label class="control-label">Category :</label>
                                    <select class="selectpicker width-full form-control"  id="category" name="category_id" style="width:100%;">
                                        <option disabled selected>Select Category</option>

                                    </select>
                                </div>
                                <div class="form-group">
                                    <label class="control-label">Hotel Name</label>
                                    <select class="selectpicker width-full form-control" name="hotel_id" style="width:100%;">
                                        <option disabled selected>Select Hotel</option>
                                        <?php foreach ($this->hotelslist as $value) { ?>
                                            <option value="<?php echo $value['id'] ?>">
                                                <?php echo $value['hotel_name'] ?>
                                            </option>
                                        <?php } ?>
                                    </select>
                                </div>
                                <div class="form-group">
                                    <label class="control-label">Product status</label>
                                    <select class="selectpicker width-full js-example-basic-hide-search form-control" name="prod_status"> 
                                        <option value="1">
                                            Active 
                                        </option>
                                        <option value="2">
                                            Inactive 
                                        </option>
                                    </select>
                                </div>
                                <div class="form-group">
                                    <label class="control-label">Cost</label>
                                    <div class="input-group">
                                        <span class="input-group-addon addon-inside bg-black">
                                            <i class="fa fa-dollar"></i>
                                        </span>
                                        <input type="text" placeholder=""  name="cost" value="" class="form-control" />
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="control-label">Discount Type</label>
                                    <div>
                                        <label class="radio-inline">
                                            <input type="radio" value="1"  name="product_discount_type"  id=""> Percentage
                                        </label>
                                        <label class="radio-inline">
                                            <input type="radio" value="2" name="product_discount_type"  id=""> Amount
                                        </label>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="panel pagination-theme clearfix m-b-0">
                            <div class="panel-body">
                                <div class="form-group">
                                    <label class="control-label">Delivery Timing</label>
                                    <div class="input-group">
                                        <span class="input-group-addon addon-inside bg-black">
                                            <i class="fa fa-clock-o"></i>
                                        </span>
                                        <input type="text" placeholder="" name="delivery_time" value="" class="form-control" />
                                        <span class="input-group-addon">mins</span>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="control-label">Discount</label>
                                    <input type="text" class="form-control" name="product_discount" value="" id="" placeholder="" required />
                                </div>
                                <div class="form-group">
                                    <label class="control-label">Service Tax</label>
                                    <input type="text" class="form-control" name="servicetax" value="" id="" placeholder="" required />
                                </div>
                                <div class="form-group">
                                    <label class="control-label">Product Image</label>
                                    <div class="fileinput fileinput-new" data-provides="fileinput">
                                        <div class="fileinput-new thumbnail" style="width: 200px; height: 150px;">
                                            <img src="http://placehold.it/200x150" alt="">
                                        </div>
                                        <div class="fileinput-preview fileinput-exists thumbnail" style="max-width: 200px; max-height: 150px;"></div>
                                        <div>
                                            <span class="btn btn-default btn-file">
                                                <span class="fileinput-new">Replace</span>
                                                <span class="fileinput-exists">Replace</span>
                                                <input type="file" name="fileToUpload">
                                            </span>
                                            <a href="#" class="btn btn-danger fileinput-exists" data-dismiss="fileinput">Remove</a>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group pull-right">
                                    <button type="submit" class="btn btn-alt btn-hover btn-primary">
                                        <span>SAVE</span> <i class="glyph-icon icon-arrow-right"></i>
                                        <div class="ripple-wrapper"></div>
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

<style>
    .show-cusine, .show-category {
        display: none;
    }
</style>

