      <div class="content-wrapper">
        <!-- Content Header (Page header) -->
<?php if(isset($this->addsport)) { ?>
        
        <div class="opennotificationGreen" style="color:#4cae4c;">
<span class="notification_msgGreen">
    <h3 style="padding-left:299px;">Sport Added Successfully</h3></span>

</div>    
<?php  } ?>
        <!-- Main content -->
        <section class="content">
          <!-- Info boxes -->
          <div class="row">
          	<div class="col-md-12 col-sm-12 no-p-left no-p-right">
            	<div class="panel panel-black no-radius">
                	<div class="panel-heading paddingLR-md paddingTB-sm no-radius">
                    	<h3 class="font-Russo-One no-margin">New Sports</h3>
                    </div>
                </div>
            </div>
          </div>
          
          <div class="row">
          	<div class="col-md-12">
            	<div class="panel panel-gray">
                	<div class="panel-heading paddingLR-md paddingTB-xs">
                    	<h4 class="font-Libre-Baskerville inline-block"><span class="m-right-sm"><i class="fa fa-edit"></i></span>Manage Sports</h4>
                        <a class="btn btn-blue m-top-xs pull-right" href="/admin/sports-details">Sport Details</a>
                    </div>
                    <div class="panel-body padding-md">
                    	<div class="row">
                            <form method="POST" id="sportform">
                            <div class="col-sm-8 col-xs-12 col-sm-offset-2 col-xs-offset-0">
                            	<div class="form-group">
                                    <label for="gameName">Name <span>*</span></label>
                                    <div class="input-group col-xs-12">
                                        <input class="form-control" type="text" id="gameName" name="gameName" value="">
                                    </div>
                                        
                                </div>
                                <div class="form-group">
                                    <label for="status">Status</label>
                                    <div class="input-group col-xs-12">
                                        <select class="form-control" name="status" id="status">
                                            <option value="1">Activate</option>
                                            <option value="0">Deactivate</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group">
                                	<button type="submit" class="btn btn-blue">Save Changes</button>	                               
                                </div>
                          	</div>
                            </form>
                     	</div>
                    </div>
                </div>
                
                
                
            </div>
          </div>
          
          
         
        </section><!-- /.content -->
      </div>

      
      <!----------------------Modals-------------------------->
      <div class="modal fade" id="deleteGame" role="dialog" aria-hidden="true">
                	<div class="modal-dialog">
                    	<div class="modal-content modal-content-bg">
                        	<div class="modal-header model-header-bg no-border-bottom">
                            	<button type="button" data-dismiss="modal" class="close text-white"><span aria-hidden="true" aria-label="Close">&times;</span></button>
                            	
                                <h3 class="font-Titillium-Web no-margin text-center">Do you want to Delete this Game?</h3>
                                
                            </div>
                            <div class="modal-footer light-bg clear-both no-border-top">
                            	
                                <div class="text-center">
                                	<button class="btn btn-warning btn-warning">Delete</button>
                                	<button data-dismiss="modal" class="btn btn-gray font-Russo-One">Cancel</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div><!---------Delete Sport------------>
      
      <div class="modal fade" id="editGame" role="dialog" aria-hidden="true">
                	<div class="modal-dialog">
                    	<div class="modal-content modal-content-bg">
                            <form id="editsportform" name="editsportform">
                        	<div class="modal-header model-header-bg no-border-bottom">
                            	<button type="button" data-dismiss="modal" class="close text-white"><span aria-hidden="true" aria-label="Close">&times;</span></button>
                            	
                                <h3 class="font-Titillium-Web no-margin text-center">New Sports</h3>
                                
                            </div>
                            <div class="modal-body">
                            	<div class="panel panel-black">
                                	<div class="panel-heading paddingLR-md">
                                    	<h4><span class="m-right-sm"><i class="fa fa-edit"></i></span>Manage Sports</h4>
                                    </div>
                                    <div class="panel-body padding-sm">
                                    	<div class="row">
                                        	<div class="col-sm-12">
                                             	<div class="form-group">
                                                	<label for="contestTypeName">Name <span>*</span></label>
                                                    <div class="input-group col-xs-12">
                                                    	<input class="form-control" type="text" id="contestTypeName" value="MLB">
                                                    </div>
                                       
                                                </div>
                                                <div class="form-group">
                                                	<label for="status">Status</label>
                                                    <div class="input-group col-xs-12">
                                                    	<select class="form-control" id="status">
                                                        	<option>Activate</option>
                                                            <option>Deactivate</option>
                                                        </select>
                                                    </div>
                                                </div>
                                                
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="modal-footer light-bg clear-both no-border-top">
                            	
                                <div class="text-center">
                                	<button class="btn btn-blue">Save Changes</button>
                                	<button data-dismiss="modal" class="btn btn-gray font-Russo-One">Cancel</button>
                                </div>
                            </div>
                            </form>
                        </div>
                    </div>
                </div><!---------Edit Sport------------>
      <!----------------------Modals-------------------------->

   
           <script>
        
            setTimeout(function() {
           $('.opennotificationGreen').fadeOut("slow");
            $('div').remove(".notification_msgGreen");
            }, 5000);   
                /*
     * dev:priyankav varanasi
     * date:22/6/2015
     * desc: To validate edit promotion 
     */
         
       $(function() {
   $.validator.addMethod("regex", function(value, element, regexpr) {          
     return regexpr.test(value);
   });
   $('#sportform').validate({
                onkeyup: function(element) {
                    $(element).valid();
                },     
                rules: {
                   gameName: {
                       required:true
                                   }
                 },
                messages: {
               
                    gameName:{
                        required:"Please enter your sport name"
                    }
             
                }
    });
    
    
    });  
        
        </script>