      <div class="content-wrapper">
        <!-- Content Header (Page header) -->
  
    <div class="opennotificationGreen" style="color:#4cae4c;">
<span class="notification_msgGreen">
    <h3 style="padding-left:299px;"><?php if(isset($this->success)){ echo $this->success;}?></h3></span>

</div>
        <!-- Main content -->
        <section class="content">
          <!-- Info boxes -->
          <div class="row">
          	<div class="col-md-12 col-sm-12 no-p-left no-p-right">
            	<div class="panel panel-black no-radius">
                	<div class="panel-heading paddingLR-md paddingTB-sm no-radius">
                    	<h3 class="font-Russo-One no-margin">Game Details</h3>
                    </div>
                </div>
            </div>
          </div>
          
          <div class="row">
          	<div class="col-md-12 col-sm-12">
            	<div class="panel panel-gray">
                	<div class="panel-heading paddingLR-md paddingTB-xs">
                    	<h4 class="font-Libre-Baskerville inline-block">Game Manage</h4>
                        <a class="btn btn-blue m-top-xs btn-sm inline-block pull-right" href="/admin/add-newsport">Add New Sports</a>
                    </div>
                    <div class="panel-body padding-md">
                    	<div class="row">
                        	<div class="col-md-12">
                            	<div class="table-responsive">
                            	<table id="contestTypeDetails" class="display table text-center" data-page-length="10" data-order="[[ 1, &quot;asc&quot; ]]" cellspacing="0" width="100%">
                                	<thead>
                                    	<tr>
                                        	<th>Sr No</th>
                                            <th>Name</th>
                                            <th>Status</th>
                                            <th>Action</th>
                                            <th class="">Delete/Edit</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <?php if(isset($this->sport)){ $i = 0; ?>
 <?php  foreach ($this->sport as $value) { $i++;?>
	<tr>
                                            <td><?php echo $i ;?></td>
                                            <td class="sportname"><?php echo $value['sport_name'];?></td>
                                               <?php if($value['s_status']== 1){ ?>
                                                <td id="activesport_<?php echo $value['sport_id']; ?>" class="center js-sortable-handle sportactive">Active</td>
                                                <td class="center" style="width: 80px;"><a href="#" id="<?php if (isset($value['sport_id'])): echo "sports_" . $value['sport_id'];endif;?>" class="sportsdeactive">
                                                <span id="activesportid_<?php echo $value['sport_id']; ?>" data-sport ="<?php echo $value['sport_id']; ?>" class="label label-danger deactivatesports">Deactivate</span></a></td>
                                               <?php } else { ?>
                                                <td id="activesport_<?php echo $value['sport_id']; ?>" class="center js-sortable-handle sportdeactive">Suspended</td>
                                                <td class="center" style="width: 80px;">
                                                    <a  id="<?php if (isset($value['sport_id'])): echo "sports_" .$value['sport_id']; endif;?>" class="sportsactive">
                                                <span id="activesportid_<?php echo $value['sport_id']; ?>" data-val="<?php echo $value['sport_id']; ?>" class="label label-success  activatesports">Activate</span>
                                                    </a>
                                                </td>
                                               <?php } ?>
                                           <td class="text-center">
                                            	<a class="delete" data-delid= "<?php echo $value['sport_id']; ?>"class="text-black m-right-sm"><span><i  style ="cursor:pointer"class="fa fa-times"></i></span></a>
                                            	
                                            <a class="text-black" data-edit="<?php echo $value['sport_id'];?>"><span><i class="fa fa-edit editsport"></i></span></a>
                                           </td>
                                            
                                        </tr>

                                       <?php } } ?>
                                    
    
                                    </tbody>
                                </table>
                            </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
          </div>
          
          
         
        </section><!-- /.content -->
      </div>
 <!----------------------Modals-------------------------->
      <div class="modal fade" id="deleteGame" role="dialog" aria-hidden="true">
                	<div class="modal-dialog">
                    	<div class="modal-content modal-content-bg">
                        	<div class="modal-header model-header-bg no-border-bottom">
                            	<button type="button" data-dismiss="modal" class="close text-white"><span aria-hidden="true" aria-label="Close">&times;</span></button>
                            	
                                <h3 class="font-Titillium-Web no-margin text-center">Do you want to Delete this Game?</h3>
                                
                            </div>
                            <div class="modal-footer light-bg clear-both no-border-top">
                            	
                                <div class="text-center">
                                	<button class="btn btn-warning btn-warning">Delete</button>
                                	<button data-dismiss="modal" class="btn btn-gray font-Russo-One">Cancel</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div><!---------Delete Sport------------>
      
      <div class="modal fade" id="editGame" role="dialog" aria-hidden="true">
                	<div class="modal-dialog">
                    	<div class="modal-content modal-content-bg">
                           
                        	<div class="modal-header model-header-bg no-border-bottom">
                            	<button type="button" data-dismiss="modal" class="close text-white"><span aria-hidden="true" aria-label="Close">&times;</span></button>
                            	
                                <h3 class="font-Titillium-Web no-margin text-center">New Sports</h3>
                                
                            </div>
                            <div class="modal-body">
                            	<div class="panel panel-black">
                                	<div class="panel-heading paddingLR-md">
                                    	<h4><span class="m-right-sm"><i class="fa fa-edit"></i></span>Manage Sports</h4>
                                    </div>
                                    <div class="panel-body padding-sm">
                                    	<div class="row">
                                             <form id="editsportform" name="editsportform">
                                        	<div class="col-sm-12">
                                            	<div class="form-group">
                                                    <input class="form-control hidden" type="text" id="sportid" value="">
                                                	<label for="sportname">Name <span>*</span></label>
                                                    <div class="input-group col-xs-12">
                                                    	<input class="form-control" type="text" name="sportname" id="sportname" value="">
                                                    </div>
                                                </div>
                                                <div class="form-group">
                                                	<label for="status">Status</label>
                                                    <div class="input-group col-xs-12">
                                                    	<select class="form-control" id="status">
                                                        	<option value="1">Active</option>
                                                            <option value ="0">Deactive</option>
                                                        </select>
                                                    </div>
                                                </div>
                                                
                                            </div>
                                             </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="modal-footer light-bg clear-both no-border-top">
                            	
                                <div class="text-center">
                                	<button class="btn btn-blue saveeditsport">Save Changes</button>
                                	<button data-dismiss="modal" class="btn btn-gray font-Russo-One">Cancel</button>
                                </div>
                            </div>
                        
                        </div>
                    </div>
                </div><!---------Edit Sport------------>
      <!----------------------Modals-------------------------->

      <script>
            /*
   * dev:priyankav varanasi
   * date:19/5/2015
   * desc: to deactivate sport on call
   */
   $(document).on('click','.deactivatesports',function(){
        var sportid = $(this).attr('data-sport');
            $.ajax({
            url: './user-ajax-handler',
            type: 'POST',
            datatype: 'json',
            data: {
                method: 'activedeactivesport',
                sport: sportid
            },
            beforeSend: function() {
                console.log('deactivating sport..')
            },
            success: function(response) {
                if (response) {
                var clnew = response.replace(/(\r\n|\n|\r)/gm,"");
                 var cl = "activesport_" + clnew;
                    var clu = "sports_" + clnew;
                   $("#" + cl).html('Suspended');
                    $("#" + clu).html('<span id="activesportid_'+clnew+'" class="label label-success  activatesports" data-val="'+clnew+'">Activate</span>');
                }
            }
        });
  });
  
    /*
   * dev:priyankav varanasi
   * date:19/5/2015
   * desc: to activate sport on call
   */
   $(document).on('click','.activatesports',function(){
        var sportid = $(this).attr('data-val');
       
            $.ajax({
            url: './user-ajax-handler',
            type: 'POST',
            datatype: 'json',
            data: {
                method: 'activedeactivesport',
                sport: sportid
            },
            beforeSend: function() {
                console.log('activating sport..')
            },
            success: function(response) {
                if (response) {
                var clnew = response.replace(/(\r\n|\n|\r)/gm,"");
                 var cl = "activesport_" + clnew;
                    var clu = "sports_" + clnew;
                   $("#" + cl).html('Active');
                    $("#" + clu).html('<span id="activesportid"'+clnew+'" class="label label-danger deactivatesports" data-sport="'+clnew+'">Deactivate</span>');
                }
            }
        });
  });
  
  
  
  /*
   * dev:priyankav varanasi
   * date:19/5/2015
   * desc: to delete sport on call
   */
    $(document.body).on('click','.delete',function(){ 
    var w = $(this);
           var del_did= $(this).attr('data-delid');
         
          $.ajax({
             url: './user-ajax-handler',
              type: 'POST',
            datatype: 'json',
          data:{
              del_did:del_did,
              method :'sportdelete'
        },
            success: function(response){
               
                 w.parent().parent().hide(); 
            }

            });
           
       });
       
       
       
            /*
   * dev:priyankav varanasi
   * date 19/5/2015
   * desc: to open the edit modal and show the sport
   */ 
  $(document.body).on('click','.editsport',function(){
      var z = $(this);
       var sport = z.parent().parent().attr('data-edit');
      
       var sportname = "";
       var status = "" ;
        sportname = z.parent().parent().parent().siblings('.sportname').html();
        status = z.parent().parent().parent().siblings('.sportactive').html();
        var x;
        if(status==='Active'){
          
           x = 1;  
        }else{
            x = 0;
        }
     
       $('#sportname').val(sportname);
       $('#status').val(x);
       $('#sportid').val(sport);
       
       $('#editGame').modal('show');
        
    });
    
    /*
   * dev:priyankav varanasi
   * date:11/5/2015
   * desc: to update the sport details via ajax
   */ 
    
    $(document.body).on('click','.saveeditsport',function(){
        
        var sportname = $('#sportname').val();
        var status = $('#status').val();
        var sportid = $('#sportid').val();
    
          if($('#sportname').valid()){
          $.ajax({
           url: './user-ajax-handler',
              type: 'POST',
            datatype: 'json',
          data:{
              sportname:sportname,
              status :status,
              sportid:sportid,
             method :'updatesport'
        },
        beforeSend: function(){
            console.log('updating sport..');
        },
            success: function(response){
                window.location = "?message=success";
                  
            }
              
        });
    }
    });
    
      </script>
      
            <script>
                       $(function() {
   $.validator.addMethod("regex", function(value, element, regexpr) {          
     return regexpr.test(value);
   });
 $('#editsportform').validate({
                onkeyup: function(element) {
                    $(element).valid();
                },     
                rules: {
                   sportname: {
                        required:true
                                   }
          
                },
                messages: {
               
                    sportname:{
                        required:"Please enter your sport name"
                    }
        
                }
    });
    });
   </script>
      <?php if(isset($this->success)){ ?>
   <script>
       //dev:priyanka varanasi
       //date:11/7/2015
    setTimeout(function() {
            $('.opennotificationGreen').fadeOut("slow");
            $('div').remove(".notification_msgGreen");
            }, 5000); 
            
            //just remove the url params to unshow the success message everytime after relaoding the page
            window.history.pushState({}, "", "/admin/sports-details" );
            
       </script>
  <?php  } ?>
