<?php
$countryCodeDetails = $this->countryCodeDetails;
?>
<div id="page-title">
    <h2>Add Users Details</h2>
</div>
<div class="row">
    <div class="col-md-12">
        <form class="form-horizontal bordered-row" enctype="multipart/form-data" method="POST" autocomplete="off">
            <div class="row">
                <div class="col-md-6">
                    <div class="panel">
                        <div class="panel-body">
                            <div class="example-box-wrapper">
                                <table class="table table-responsive">
                                    <tbody>
                                        <tr>
                                            <td>
                                                <label class="control-label">User Image</label>
                                            </td>
                                            <td>
                                                <div class="fileinput fileinput-new" data-provides="fileinput">
                                                    <div class="fileinput-new thumbnail" style="width: 200px; height: 150px;">
                                                        <img src="http://placehold.it/200x150" alt="">
                                                    </div>
                                                    <div class="fileinput-preview fileinput-exists thumbnail" style="max-width: 200px; max-height: 150px;"></div>
                                                    <div>
                                                        <span class="btn btn-default btn-file">
                                                            <span class="fileinput-new">Select Image</span>
                                                            <span class="fileinput-exists">Replace</span>
                                                            <input type="file" name="fileToUpload">
                                                        </span>
                                                        <a href="#" class="btn btn-danger fileinput-exists" data-dismiss="fileinput">Remove</a>
                                                    </div>
                                                </div>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <label class="control-label">User Name</label>
                                            </td>
                                            <td>
                                                <input type="text" class="form-control" name="uname" id="uname" value="" placeholder="" required />
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <label class="control-label">Email</label>
                                            </td>
                                            <td>
                                                <input type="text" class="form-control" type="text" name="email"  id="email" value="" placeholder="" required />
                                            </td>
                                        </tr>
                                        <tr>
                                            <!--added by sowmya 17 march 2016-->
                                            <td>
                                                <label class="control-label">Password</label>
                                            </td>
                                            <td>
                                                <input type="password" class="form-control" type="text" name="password"  id="password" value="" placeholder="" required />
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <label class="control-label">First Name</label>
                                            </td>
                                            <td>
                                                <input type="text" class="form-control"  name="first_name" value="" placeholder="" required />
                                            </td>
                                        </tr>

                                        <tr>
                                            <td>
                                                <label class="control-label">Last Name</label>
                                            </td>
                                            <td>
                                                <input type="text" class="form-control" name="last_name"  id="last_name" value="" placeholder="" required />
                                            </td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="panel">
                        <div class="panel-body">
                            <div class="example-box-wrapper">
                                <table class="table table-responsive">
                                    <tbody>
                                        <tr>
                                            <td>
                                                <label class="control-label">Phone</label>
                                            </td>                                         
                                            <td>
                                                <select class="js-example-responsive form-control"  id="category" name="contact_country_code" style="width:100%;">
                                                    <?php foreach ($countryCodeDetails as $value) { ?>
                                                        <option value="<?php echo $value['country_id'] ?>">
                                                            <?php echo $value['name'] ?>  &nbsp; <?php echo $value['phonecode'] ?>
                                                        </option>
                                                    <?php }
                                                    ?>
                                                </select>
                                            </td>
                                            <td>
                                                <input id="phone" type="text" name="phone" value="" class="form-control" />


                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <label class="control-label">City</label>
                                            </td>
                                            <td>
                                                <div class="input-group">
                                                    <input type="text" placeholder="" type="text" name="city"  id="city" value="" class="form-control" />
                                                </div>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <label class="control-label">State</label>
                                            </td>
                                            <td>
                                                <input type="text" class="form-control" name="state"  id="state" value=""  placeholder="" required />
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <label class="control-label">Country</label>
                                            </td>
                                            <td>
                                                <input type="text" class="form-control" name="country"  id="country" value="" placeholder="" required />
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <label class="control-label">Status</label>
                                            </td>
                                            <td>
                                                <select  class="js-example-responsive js-example-basic-hide-search form-control" name="status"> 
                                                    <option value="1">
                                                        Active 
                                                    </option>
                                                    <option value="2">
                                                        Deactivate 
                                                    </option>
                                                </select>
                                            </td>

                                        </tr>
                                    </tbody>
                                </table>
                                <div class="form-group pull-right">
                                    <button type="submit" class="btn btn-alt btn-hover btn-primary">
                                        <span>SAVE</span> <i class="glyph-icon icon-arrow-right"></i>
                                        <div class="ripple-wrapper"></div>
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>


