<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            User Settings
            <small>for your next cool web APP</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-futbol-o"></i> Home</a></li>
            <li>User Settings</li>
            <li class="active">Email Manager</li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">
        <!-- Info boxes -->
        <div class="row">
            <div class="col-md-12 col-sm-12 no-p-left no-p-right">
                <div class="panel panel-black no-radius">
                    <div class="panel-heading paddingLR-md paddingTB-sm no-radius">
                        <h3 class="font-Russo-One no-margin">Manage Emails</h3>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12 col-sm-12">
                <div class="panel panel-gray">
                    <div class="panel-heading paddingLR-md paddingTB-xs">
                        <h4 class="font-Libre-Baskerville inline-block">Registered Users</h4>
                    </div>
                    <div class="panel-body">

                        <div class="m-top-md">
                            <div class="table-responsive">
                                <table id="registeredUsers" class="display table text-center" data-page-length="10" data-order="[[ 1, &quot;asc&quot; ]]" cellspacing="0" width="100%">
                                    <thead>
                                       <tr>
                            <th>Sr. No.</th>
                            <th>UserID</th>
                            <th>User Name</th>                            
                            <th>User Email</th>                           
                            <th>Reg. date</th>
                            <th>Send Mail</th>
                        </tr>
                                    </thead>
                                        <tbody>
                       <?php if(isset($this->userdetails)){ $index=1; foreach ($this->userdetails as $uVal){ ?>
                        <!-- Table row -->
                            <td><?php echo $index; ?></td>
                            <td><?php echo $uVal['user_id']; ?></td>
                            <td><?php if(isset($uVal['user_name'])){ echo $uVal['user_name']; }else{ echo "N/A"; } ?></td>
                            <td><?php if(isset($uVal['email'])){ echo $uVal['email']; }else{ echo "N/A"; } ?></td>
                            <td><?php if(isset($uVal['reg_date'])){  echo date("j F , Y", strtotime($uVal['reg_date'])); }else{ echo "N/A"; } ?></td>
                             <td class="text-center">
                                                <a data-toggle="modal" data-target="#sendMail" class="text-black"  data-uname="<?php echo $uVal['user_name']; ?>" data-uid="<?php echo $uVal['user_id']; ?>"  data-mail="<?php echo $uVal['email']; ?>" ><span><i class="fa fa-edit sendunregmail"></i></span></a>
                                            </td>
                        </tr>
                        <!-- // Table row END -->
                        <?php $index++; }} ?>
                    </tbody>
                                    </tbody>
                                </table>
                            </div>
                        </div>


                    </div>
                </div>

                <div class="panel panel-gray">
                    <div class="panel-heading paddingLR-md paddingTB-xs">
                        <h4 class="font-Libre-Baskerville inline-block">Unregistered Users</h4>
                    </div>
                    <div class="panel-body">

                        <div class="m-top-md">
                            <div class="table-responsive">
                                <table id="unregisteredUsers" class="display table text-center" data-page-length="10" data-order="[[ 1, &quot;asc&quot; ]]" cellspacing="0" width="100%">
                                    <thead>
                                          <tr>
                            <th>Sr. No.</th>                           
                            <th>User Email</th>                           
                            <th>sent. date</th>
                            <th>Message</th>
                            <th>Send Mail</th>
                        </tr>
                                    </thead>
                                       <tbody>
                       <?php if(isset($this->unregister)){ $index=1; foreach ($this->unregister as $uVal){ ?>
                        <!-- Table row -->
                            <td><?php echo $index; ?></td>
                            <td><?php if(isset($uVal['email_id'])){ echo $uVal['email_id']; }else{ echo "N/A"; } ?></td>
                            <td><?php if(isset($uVal['sent_on'])){ echo date("j F , Y", strtotime($uVal['sent_on']));  }else{ echo "N/A"; } ?></td>
                            <td><?php if(isset($uVal['message'])){ echo $uVal['message']; }else{ echo "N/A"; } ?></td>
                              <td class="text-center">
                                                <a data-toggle="modal" data-target="#sendMail" class="text-black" data-uname="<?php echo $uVal['email_id']; ?>" data-uid="<?php echo $uVal['e_log_id']; ?>"  data-mail="<?php echo $uVal['email_id']; ?>"><span><i class="fa fa-edit sendunregmail"></i></span></a>
                                            </td>
                        </tr>
                        <!-- // Table row END -->
                        <?php $index++; }} ?>
                    </tbody>

                                    </tbody>
                                </table>
                            </div>
                        </div>


                    </div>
                </div>

                <div class="panel panel-gray">
                    <div class="panel-heading paddingLR-md paddingTB-xs">
                        <h4 class="font-Libre-Baskerville inline-block">Email Logs</h4>
                    </div>
                    <div class="panel-body">

                        <div class="m-top-md">
                            <div class="table-responsive">
                                <table id="emailLogs" class="display table text-center" data-page-length="10" data-order="[[ 1, &quot;asc&quot; ]]" cellspacing="0" width="100%">
                                    <thead>
                                        <tr>
                                            <th>Sr No</th>
                                            <th>Sent Email</th>
                                            <th>Sent Time</th>
                                            <th>Sent Template</th>
                                            <th>Message</th>
                                        </tr>
                                    </thead>
                                    <!-- Table body -->
                                    <tbody>
                                        <?php if (isset($this->emaillogDetails)): $row = 0;
                                            foreach ($this->emaillogDetails as $emaillogDetails): $row ++; ?>
                                                <tr class="gradeA">
                                                    <td><?php echo $row; ?></td>
                                                    <td><?php echo $emaillogDetails['email_id']; ?></td>
                                                    <td><?php echo date("j F , Y", strtotime($emaillogDetails['sent_on'])); ?></td>
                                                    <td><?php echo $emaillogDetails['subject']; ?></td>
                                                    <td><?php echo $emaillogDetails['message']; ?></td>
                                                </tr>
                                            <?php endforeach;
                                        endif; ?>

                                    </tbody>
                                    <!-- // Table body END -->
                                </table>
                            </div>
                        </div>


                    </div>
                </div>
            </div>
        </div>



    </section><!-- /.content -->
</div>

<!----------------------Modals-------------------------->

<div class="modal fade" id="sendMail" role="dialog" aria-hidden="true">
    <div class="modal-dialog width50p">
        <div class="modal-content modal-content-bg">
            <div class="modal-header model-header-bg no-border-bottom">
                <button type="button" data-dismiss="modal" class="close text-white"><span aria-hidden="true" aria-label="Close">&times;</span></button>

                <h3 class="font-Titillium-Web no-margin text-center">Edit Mail</h3>

            </div>
            <div class="modal-body">
                <div class="panel panel-black">
                    <div class="panel-heading paddingLR-md">
                        <h4><span class="m-right-sm"><i class="fa fa-edit"></i></span>Send Message To <span id="username" style="color:#926cff;"><strong></strong></span></h4>
                    </div>
                    <div class="panel-body padding-sm">
                        <div class="row">
                            <div class="col-md-12">
                                <form id="sendmailform" name="sendmailform">
                                <div class="form-group">
                                    <label>To</label>
                                    <div class="input-group col-xs-12">
                                        <input class="form-control" type="email" id="sendmail" name="sendmail" value="" disabled>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="subject">Subject</label>
                                    <div class="input-group col-xs-12">
                                        <input class="form-control" type="text" name="subject" id="subject">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="message">Message</label>
                                    <div class="input-group col-xs-12">
                                        <textarea class="form-control" name="message" id="message">
                                        </textarea>
                                    </div>
                                </div>
                                </form>
                                <label id="ret-msg" ></label>     
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer light-bg clear-both no-border-top">

                <div class="text-center">
                    <button class="btn btn-blue" id="sendsuccess" data-id="">Send</button>
                    <button data-dismiss="modal" class="btn btn-gray font-Russo-One">Cancel</button>
                </div>
            </div>
        </div>
    </div>
</div><!---------Edit User------------>

<!----------------------Modals-------------------------->

<script type="text/javascript">
    /*
     * dev:priyanka varanasi
     * desc: to fetch data to send mail 
     * date:24/6/2015
     */
    $(document).ready(function(){
        $('.sendunregmail').on('click',function(event){
            
            $('#sendmail').attr('value','');
             var uid = $(this).parent().parent().attr('data-uid');
             var email = $(this).parent().parent().attr('data-mail');
             console.log(email);
             var uname = $(this).parent().parent().attr('data-uname');
             $('#sendmail').val(email);
             $('#username').html(uname);
             $('#sendsuccess').attr('data-id',uid);
             
             $('#ret-msg').css('color','');
             $('#ret-msg').html('');
             $('#subject').val('');
             $('#message').val('');
        });
    });
    
       /*
     * dev:priyanka varanasi
     * desc: To send mail through ajax
     * date:24/6/2015
     */
         
      $(document.body).on('click','#sendsuccess',function(){
            var email = $('#sendmail').val();
            var subject = $('#subject').val();
            var message = $('#message').val();
            var username = $('#username').html();
       if($('#sendmailform').valid()){
                $.ajax({

                        url      : '/admin/email-manager', 
                        type     : 'POST',
                        dataType : 'json',
                        data : {
                            method : 'sendmail',
                            email : email,
                            subject : subject,
                            message : message,
                            username : username
                        },
                        beforeSend : function() {
                                
                        },
                        success : function(response) {
                            if(response.code==200){
                                $('#ret-msg').show();
                                $('#ret-msg').css('color','green');
                                $('#ret-msg').html(response.message);
                                $('#subject').val('');
                                $('#message').val('');
                            }else if(response.code == 198){
                                $('#ret-msg').show();
                                $('#ret-msg').css('color','red');
                                $('#ret-msg').html('<h4>'+response.message+'</h4>');
                            }
                            setTimeout("$('#ret-msg').hide();",5000);
                        }
                });
            }
         
        });

 
                       $(function() {
   $.validator.addMethod("regex", function(value, element, regexpr) {          
     return regexpr.test(value);
   });
 $('#sendmailform').validate({
                onkeyup: function(element) {
                    $(element).valid();
                },     
                rules: {
                   subject: {
                        required:true
                                   },
                      message: {
                        required:true
                                   }
               
          
                },
                messages: {
               
                    subject:{
                        required:"Please enter subject"
                    },
                      message:{
                        required:"Please enter some message "
                    }
              
                }
    });
    });
  
</script>
<script>
    $('#registeredUsers').DataTable({
        "bLengthChange": false,
    });

</script>
<script>
    $('#unregisteredUsers').DataTable({
        "bLengthChange": false,
    });

</script>
<script>
    $('#emailLogs').DataTable({
        "bLengthChange": false,
    });

</script>