                                     
<div id="page-title">
    <h2>User Details</h2>
    <p>The most complete user interface framework that can be used to create stunning admin dashboards and presentation websites.</p>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="panel">
            <div class="panel-body">
                <h3 class="title-hero">View/Edit/Remove Products</h3>
                <div class="example-box-wrapper">
                    <table class="table table-striped table-bordered responsive no-wrap datatable-responsive" cellspacing="0" width="100%">
                        <thead>
                            <tr>
                                <th>S.No. </th>
                                <th> User ID </th>
                                <th> User Name </th>
                                <th> Email</th>
                                <th> First Name</th>
                                <th> Last name </th>
                                <th> Date </th>
                                <th> Status </th>
                                <th> Action </th>
                                <th> View/Edit/Delete</th>

                            </tr>
                        </thead>
                        <tfoot>
                            <tr>
                                <th>S.No. </th>
                                <th> User ID </th>
                                <th> User Name </th>
                                <th> Email</th>
                                <th> First Name</th>
                                <th> Last name </th>
                                <th> Date </th>
                                <th> Status </th>
                                <th> Action </th>
                                <th> View/Edit/Delete</th>

                            </tr>
                        </tfoot>
                        <tbody>

                            <?php
                            if (isset($this->userdetails)) {
                                $i = 1;
                                foreach ($this->userdetails as $value) {
                                    if ($value['role'] != 2) {
                                        ?>

                                        <tr>
                                            <td><?php echo $i; ?></td>
                                            <td><?php echo $value['user_id']; ?></td>
                                            <td><?php echo $value['uname']; ?></td>
                                            <td><?php echo $value['email']; ?></td>
                                            <td><?php echo $value['first_name']; ?></td>
                                            <td><?php echo $value['last_name']; ?></td>
                                            <td><?php echo date("j F , Y h:i:s A", strtotime($value['reg_date'])); ?></td>
                                            <?php if ($value['status'] == 1): ?>
                                                <td id="activeuser_<?php echo $value['user_id']; ?>" class="useractive">Active</td>
                                                <td class="center"><a style="cursor:pointer"  id="<?php
                                                    if (isset($value['user_id'])): echo "user_" . $value['user_id'];
                                                    endif;
                                                    ?>" class="userdeactive">
                                                        <span id="activeclass_<?php echo $value['user_id']; ?>" class="bs-label label-danger">Deactivate</span></a></td>
                                            <?php else: ?>
                                                <td id="activeuser_<?php echo $value['user_id']; ?>" class="userdeactive">Suspended</td>
                                                <td class="center" ><a style="cursor:pointer" id="<?php
                                                    if (isset($value['user_id'])): echo "user_" . $value['user_id'];
                                                    endif;
                                                    ?>" class="useractive">
                                                        <span id="activeclass_<?php echo $value['user_id']; ?>"  class="bs-label label-success">Activate</span></a></td>
                                            <?php endif; ?> 


                                            <td class="text-center">
                                                <a href="/admin/view-user-details/<?php echo $value['user_id']; ?>" class="btn btn-default"><i class="glyph-icon icon-linecons-eye"></i></a>
                                                <a href="/admin/edit-user-details/<?php echo $value['user_id']; ?>" class="btn btn-default"><i class="glyph-icon icon-linecons-pencil"></i></a>
                                                <a href="javascript:;" id="<?php echo "userdelete_" . $value['user_id']; ?>" class="btn btn-default deleteuser"><i class="glyph-icon icon-linecons-trash"></i></a>
                                            </td>
                                        </tr>
                                        <?php
                                        $i++;
                                    }
                                }
                            }
                            ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>


