      <div class="content-wrapper">
        <!-- Content Header (Page header) -->
  <div class="opennotificationGreen" style="color:#4cae4c;">
<span class="notification_msgGreen">
    <h3 style="padding-left:299px;"><?php if(isset($this->success)){ echo $this->success;}?></h3></span>

</div>

        <!-- Main content -->
        <section class="content">
          <!-- Info boxes -->
          <div class="row">
          	<div class="col-md-12 col-sm-12 no-p-left no-p-right">
            	<div class="panel panel-black no-radius">
                	<div class="panel-heading paddingLR-md paddingTB-sm no-radius">
                    	<h3 class="font-Russo-One no-margin">User Account Details</h3>
                    </div>
                </div>
            </div>
          </div>
          
          <div class="row">
          	<div class="col-md-12 col-sm-12">
            	<div class="panel panel-gray">
                	<div class="panel-heading paddingLR-md paddingTB-xs">
                    	<h4 class="font-Libre-Baskerville inline-block">Account Manage</h4>
                    </div>
                    <div class="panel-body">
                    	
                      <div class="m-top-md">
                        	<div class="table-responsive">
                            	<table id="userAccountDetails" class="display table text-center" data-page-length="10" data-order="[[ 1, &quot;asc&quot; ]]" cellspacing="0" width="100%">
                                	<thead>
                                    	<tr>
                                           <th>User Name</th>
                                            <th>Balance Amount</th>
                                            <th>FPP</th>
                                            <th>Bonus Amount</th>
                                            <th>Edit</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <?php if(isset($this->useraccoutinfo)){$i=0;foreach ($this->useraccoutinfo as $value) { $i++; ?>
     	                                        <tr>
                                            <td class="user"><?php echo $value['user_name'];?></td>
                                            <td class="bal"><?php echo $value['balance_amt'];?></td>
                                            <td class="fpp"><?php echo $value['fpp'];?></td>
                                            <td class="bonus"><?php echo $value['bonus_amt'];?></td>
                                            <td class="text-center">
                                            	<a data-toggle="modal" data-edit="<?php echo $value['user_id'];?>"  class="text-black edituser"><span><i class="fa fa-edit"></i></span></a>
                                            </td>
                                            </tr>
                                    <?php    }  } ?>
                                      </tbody>
                                </table>
                          </div>
                        </div>
                        
                        
                    </div>
                </div>
            </div>
          </div>
          
          
         
        </section><!-- /.content -->
      </div>

      <!----------------------Modals-------------------------->
      
      <div class="modal fade" id="editUserAccount" role="dialog" aria-hidden="true">
                	<div class="modal-dialog width50p">
                    	<div class="modal-content modal-content-bg">
                           
                        	<div class="modal-header model-header-bg no-border-bottom">
                            	<button type="button" data-dismiss="modal" class="close text-white"><span aria-hidden="true" aria-label="Close">&times;</span></button>
                            	
                                <h3 class="font-Titillium-Web no-margin text-center">Edit User Account</h3>
                                
                            </div>
                            <div class="modal-body">
                            	<div class="panel panel-black">
                                	<div class="panel-heading paddingLR-md">
                                    	<h4><span class="m-right-sm"><i class="fa fa-edit"></i></span>Manage User Account Details</h4>
                                    </div>
                                    <div class="panel-body padding-sm">
                                    	<div class="row">
                                            <form id ="editusersettingsform">
                                        	<div class="col-md-12">
                                            	<div class="form-group">
                                                    <input class="form-control hidden" type="text" id="userid" value="" >
                                                	<label for="userName">User Name</label>
                                                    <div class="input-group col-xs-12">
                                                    	<input class="form-control" type="text" id="userName" value="abc" disabled>
                                                    </div>
                                                </div>
                                                <div class="form-group">
                                                	<label for="balance">Balance</label>
                                                    <div class="input-group col-xs-12">
                                                    	<input class="form-control" type="text" name="balance" id="balance" value="0">
                                                    </div>
                                                </div>
                                                <div class="form-group">
                                                	<label for="FPP">FPP</label>
                                                    <div class="input-group col-xs-12">
                                                    	<input class="form-control" type="text"  name="FPP" id="FPP" value="0">
                                                    </div>
                                                </div>
                                                <div class="form-group">
                                                	<label for="bonus">Bonus Amount</label>
                                                    <div class="input-group col-xs-12">
                                                    	<input class="form-control" type="text" name="bonus" id="bonus" value="0">
                                                    </div>
                                                </div>
                                                
                                            </div>
                                                </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="modal-footer light-bg clear-both no-border-top">
                            	
                                <div class="text-center">
                                	<button class="btn btn-blue saveuseraccount">Save Changes</button>
                                	<button data-dismiss="modal" class="btn btn-gray font-Russo-One">Cancel</button>
                                </div>
                            </div>
                           
                        </div>
                    </div>
                </div><!---------Edit User------------>
      
      <!----------------------Modals-------------------------->
      
       <script>
		$('#userAccountDetails').DataTable({
			"bLengthChange": false,
			
			});

	</script>
        
        <script>
            
            /*
   * dev:priyankav varanasi
   * date:22/5/2015
   * desc: to open the edit modal and show the user account details
   */ 
  $(document.body).on('click','.edituser',function(){
      var z = $(this);
       var user = z.attr('data-edit');
       
       var username = "";
       var fpp = "" ;
       var bonus =" ";
       var amt = " ";
        username = z.parent().siblings('.user').html();
        amt = z.parent().siblings('.bal').html();
        fpp = z.parent().siblings('.fpp').html();
        bonus = z.parent().siblings('.bonus').html();
       
       $('#userName').val(username);
       $('#balance').val(amt);
       $('#FPP').val(fpp);
        $('#bonus').val(bonus);
        $('#userid').val(user);
       
       $('#editUserAccount').modal('show');
        
    });
    
    
          
    /*
     * dev:priyankav varanasi
     * date:15/6/2015
     * desc: To validate user settings
     */
         
       $(function() {
   $.validator.addMethod("regex", function(value, element, regexpr) {          
     return regexpr.test(value);
   });
   $('#editusersettingsform').validate({
                onkeyup: function(element) {
                    $(element).valid();
                },     
                rules: {
                   balance: {
                       regex: /^\d+$/
                                   },
                    FPP:{
                        regex: /^\d+$/
                        
                    },
                    bonus:{
                        regex: /^\d+$/
                        
                    }
                 },
                messages: {
               
                    balance:{
                        regex:"Please enter only amount"
                    },
                    FPP:{
                        regex:"Please enter only amount"
                     },
                       bonus:{
                        regex:"Please enter only amount"
                        
                    }
              
                }
    });
    
    
    });  
    
    
    
    
       /*
   * dev:priyankav varanasi
   * date:21/5/2015
   * desc: to update the user account details via ajax
   */ 
    
    $(document.body).on('click','.saveuseraccount',function(){
        
        var name = $('#userName').val();
        var bal = $('#balance').val();
        var fpp = $('#FPP').val();
        var bonus = $('#bonus').val();
        var userid = $('#userid').val();
         if( $("#editusersettingsform").valid()){ 
          $.ajax({
           url: './user-ajax-handler',
              type: 'POST',
            datatype: 'json',
          data:{
              name:name,
              bal :bal,
              fpp:fpp,
              bonus :bonus,
              userid:userid,
              method :'updateuseraccount'
        },
        beforeSend: function(){
            console.log('updating the user account..');
        },
            success: function(response){
                 window.location = "?message=success";
                  
            }
              
        });
    }
      
    });
    
  
         

    
    
    
    
            </script>
               <?php if(isset($this->success)){ ?>
   <script>
       //dev:priyanka varanasi
       //date:11/7/2015
    setTimeout(function() {
            $('.opennotificationGreen').fadeOut("slow");
            $('div').remove(".notification_msgGreen");
            }, 5000); 
            
            //just remove the url params to unshow the success message everytime after relaoding the page
            window.history.pushState({}, "", "/admin/user-details" );
            
       </script>
  <?php  } ?>