<div id="page-title">
    <h2>Add Delivery Guy Details</h2>  
</div>
<div class="row">
    <div class="col-md-12">
        <form class="form-horizontal bordered-row" enctype="multipart/form-data" method="POST">
            <div class="row">
                <div class="col-md-6">
                    <div class="panel">
                        <div class="panel-body">
                            <div class="example-box-wrapper">
                                <table class="table table-responsive">
                                    <tbody>
                                        <tr>
                                            <td>
                                                <label class="control-label">Delivery Guy Name</label>
                                            </td>
                                            <td>
                                                <input type="text" class="form-control" name="login_name" id="loginname" value="" placeholder="" required />
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <label class="control-label">Email</label>
                                            </td>
                                            <td>
                                                <input type="text" class="form-control" type="text" name="email"  id="email" value="" placeholder="" required />
                                            </td>
                                        </tr>

                                        <tr>
                                            <td>
                                                <label class="control-label">First Name</label>
                                            </td>
                                            <td>
                                                <input type="text" class="form-control"  name="firstname" value="" placeholder="" required />
                                            </td>
                                        </tr>

                                        <tr>
                                            <td>
                                                <label class="control-label">Last Name</label>
                                            </td>
                                            <td>
                                                <input type="text" class="form-control" name="lastname"  id="last_name" value="" placeholder="" required />
                                            </td>
                                        </tr>

                                        <tr>
                                            <!--added by sowmya 17 march 2016-->
                                            <td>
                                                <label class="control-label">Password</label>
                                            </td>
                                            <td>
                                                <input type="password" class="form-control" type="text" name="password"  id="password" value="" placeholder="" required />
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <label class="control-label">Phone</label>
                                            </td>
                                            <td>
                                                <input type="text" placeholder=""  name="phone"  id="phone" value=""class="form-control" />

                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <label class="control-label">Status</label>
                                            </td>
                                            <td>
                                                <select  class="js-example-responsive js-example-basic-hide-search form-control" name="status"> 
                                                    <option value="1">
                                                        Active 
                                                    </option>
                                                    <option value="2">
                                                        Deactivate 
                                                    </option>
                                                </select>
                                            </td>

                                        </tr>

                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="panel">
                        <div class="panel-body">
                            <div class="example-box-wrapper">
                                <table class="table table-responsive">
                                    <tbody>

                                        <tr>
                                            <td>
                                                <label class="control-label">City</label>
                                            </td>
                                            <td>
                                                <div class="input-group">
                                                    <input type="text" placeholder="" type="text" name="city"  id="city" value="" class="form-control" />
                                                </div>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <label class="control-label">State</label>
                                            </td>
                                            <td>
                                                <input type="text" class="form-control" name="state"  id="state" value=""  placeholder="" required />
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <label class="control-label">Country</label>
                                            </td>
                                            <td>
                                                <input type="text" class="form-control" name="country"  id="country" value="" placeholder="" required />
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <label class="control-label">Address</label>
                                            </td>
                                            <td>
                                                <textarea class="form-control" name="address" id="address" cols="20" rows="2"  ></textarea>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <label class="control-label"> Delivery Guy For Hotel/Store </label>
                                            </td>
                                            <td>
                                                <label class="radio-inline">
                                                    <input type="radio" value="1" name="hotel_store"  id="hotel" /> Hotel 
                                                </label>
                                                <label class="radio-inline">
                                                    <input type="radio" value="2"  name="hotel_store"  id="store" />Store 
                                                </label>
                                            </td>
                                        </tr>
                                        <tr  class="show-hotel">
                                            <td>
                                                <label class="control-label">Select the Location</label>
                                            </td>
                                            <td>
                                                <select class="form-control selectpicker width-full selectlocation" name="location" da selectpicker width-full ta-size="10" data-live-search="true">
                                                    <optgroup label="Select Location">
                                                        <option> Select Location </option>
                                                        <?php
                                                        if (isset($this->locationdetails)) {
                                                            foreach ($this->locationdetails as $value) {
                                                                ?>
                                                                <option value="<?php echo $value['location_id']; ?>"><?php echo $value['name']; ?></option>
                                                                <?php
                                                            }
                                                        }
                                                        ?>
                                                    </optgroup>
                                                </select>
                                            </td>
                                        </tr>
                                        <tr class="show-hotel">
                                            <td>
                                                <label class="control-label">Hotel Name </label>
                                            </td>
                                            <td>
                                                <select class="js-example-responsive form-control" name="hotel_id[]" id="hotel_id" style="width:100%;" multiple="multiple">
                                                    <optgroup label="Select Hotel" id="location">
                                                        <option value=""> Select Hotel </option>
                                                    </optgroup>
                                                </select>
                                            </td>
                                        </tr>
                                         <tr  class="show-store">
                                            <td>
                                                <label class="control-label">Select the Location</label>
                                            </td>
                                            <td>
                                                <select class="form-control selectpicker width-full selectlocation1" name="location1" da selectpicker width-full ta-size="10" data-live-search="true">
                                                    <optgroup label="Select Location">
                                                        <option> Select Location </option>
                                                        <?php
                                                        if (isset($this->locationdetails)) {
                                                            foreach ($this->locationdetails as $value) {
                                                                ?>
                                                                <option value="<?php echo $value['location_id']; ?>"><?php echo $value['name']; ?></option>
                                                                <?php
                                                            }
                                                        }
                                                        ?>
                                                    </optgroup>
                                                </select>
                                            </td>
                                        </tr>
                                        <tr class="show-store">
                                            <td>
                                                <label class="control-label">Store Name </label>
                                            </td>
                                            <td>
                                                <select class="js-example-responsive form-control" name="store_id[]" id="store_id" style="width:100%;" multiple="multiple">
                                                    <optgroup label="Select Store" id="location1">
                                                        <option value=""> Select Store </option>
                                                    </optgroup>
                                                </select>
                                            </td>
                                        </tr>
                                    </tbody>
                                </table>
                                <div class="form-group pull-right">
                                    <button type="submit" class="btn btn-alt btn-hover btn-primary">
                                        <span>SAVE</span> <i class="glyph-icon icon-arrow-right"></i>
                                        <div class="ripple-wrapper"></div>
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>


<style>
    .show-hotel, .show-store {
        display: none;
    }
</style>

<script>
    $(function() {
        $('#hotel').click(function() {
            $('.show-hotel').show();
            $('.show-store').hide();
        });
        $('#store').click(function() {
            $('.show-hotel').hide();
            $('.show-store').show();
        });
    });
</script>
