
<div id="page-title">
    <h2>Add Delivery Guy Details</h2>
    <p>The most complete user interface framework that can be used to create stunning admin dashboards and presentation websites.</p>
</div>
<div class="row">
    <div class="col-md-12">
        <form class="form-horizontal bordered-row" enctype="multipart/form-data" method="POST">
            <div class="row">
                <div class="col-md-6">
                    <div class="panel">
                        <div class="panel-body">
                            <div class="example-box-wrapper">
                                <table class="table table-responsive">
                                    <tbody>
                                        <tr>
                                            <td>
                                                <label class="control-label">User Name</label>
                                            </td>
                                            <td>
                                                <input type="text" class="form-control" name="login_name" id="loginname" value="" placeholder="" required />
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <label class="control-label">Email</label>
                                            </td>
                                            <td>
                                                <input type="text" class="form-control" type="text" name="email"  id="email" value="" placeholder="" required />
                                            </td>
                                        </tr>

                                        <tr>
                                            <td>
                                                <label class="control-label">First Name</label>
                                            </td>
                                            <td>
                                                <input type="text" class="form-control"  name="firstname" value="" placeholder="" required />
                                            </td>
                                        </tr>

                                        <tr>
                                            <td>
                                                <label class="control-label">Last Name</label>
                                            </td>
                                            <td>
                                                <input type="text" class="form-control" name="lastname"  id="last_name" value="" placeholder="" required />
                                            </td>
                                        </tr>
                                        
                                                                 <tr>
                                            <td>
                                                <label class="control-label">Password</label>
                                            </td>
                                            <td>
                                                <input type="password" placeholder=""   name="password"  id="password" value=""class="form-control" />

                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <label class="control-label">Phone</label>
                                            </td>
                                            <td>
                                                <input type="text" placeholder=""  name="phone"  id="phone" value=""class="form-control" />

                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <label class="control-label">Status</label>
                                            </td>
                                            <td>
                                                <select  class="js-example-responsive js-example-basic-hide-search form-control" name="status"> 
                                                    <option value="1">
                                                        Active 
                                                    </option>
                                                    <option value="2">
                                                        Deactive 
                                                    </option>
                                                </select>
                                            </td>

                                        </tr>

                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="panel">
                        <div class="panel-body">
                            <div class="example-box-wrapper">
                                <table class="table table-responsive">
                                    <tbody>
                                        <tr>
                                            <td>
                                                <label class="control-label">City</label>
                                            </td>
                                            <td>
                                                <div class="input-group">
                                                    <input type="text" placeholder="" type="text" name="city"  id="city" value="" class="form-control" />
                                                </div>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <label class="control-label">State</label>
                                            </td>
                                            <td>
                                                <input type="text" class="form-control" name="state"  id="state" value=""  placeholder="" required />
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <label class="control-label">Country</label>
                                            </td>
                                            <td>
                                                <input type="text" class="form-control" name="country"  id="country" value="" placeholder="" required />
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <label class="control-label">Address</label>
                                            </td>
                                            <td>
                                                <textarea class="form-control" name="address" id="address" cols="20" rows="2"  ></textarea>
                                            </td>
                                        </tr>
                                    </tbody>
                                </table>
                                <div class="form-group pull-right">
                                    <button type="submit" class="btn btn-alt btn-hover btn-primary">
                                        <span>SAVE</span> <i class="glyph-icon icon-arrow-right"></i>
                                        <div class="ripple-wrapper"></div>
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>



