                                     
<div id="page-title">
    <h2>Delivery Guy Orders Details</h2>
    <p>The most complete user interface framework that can be used to create stunning admin dashboards and presentation websites.</p>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="panel">
            <div class="panel-body">
                <h3 class="title-hero">View Delivery Guy Order Details</h3>
                <div class="example-box-wrapper">
                    <table id="datatable-responsive" class="table table-striped table-bordered responsive no-wrap" cellspacing="0" width="100%">
                        <thead>
                            <tr>
                                <th> S.No </th>
                                <th>Delivery Status</th>
                                <th>Time</th>
                                <th>Order status</th>
                                <th>Pay Status</th>
                                <th>delivery_status</th>
                                <th>Order Pay Amount </th>
                                
                            </tr>
                        </thead>
                        <tfoot>
                            <tr>
                                <th> S.No </th>
                                <th>Delivery Status</th>
                                <th>Time</th>
                                <th>Order status</th>
                                 <th>Pay Status</th>
                                <th>delivery_status</th>
                                <th>Order Pay Amount </th>
                                

                            </tr>
                        </tfoot>
                        <tbody>

                            <?php
                            if (isset($this->deliveryguysorderdetails)) {
                                $i = 1;
                                foreach ($this->deliveryguysorderdetails as $value) {
                                    ?>

                                    <tr id="<?php echo $value['del_guy_id']; ?>" >
                                        <td><?php if($value['status_type']==1){
                                                echo 'Pick Up Done';
                                        }else if($value['status_type']==2){
                                          echo 'In transit';  
                                        }else if($value['status_type']==3){
                                           echo 'Delivered';  
                                        }else{
                                          echo 'No Acknowledge';     
                                            
                                        }
?></td>
                                        <td><?php if($value['order_status']==1){
                                                echo 'In Process';
                                        }else if($value['order_status']==2){
                                          echo 'Delivered';  
                                        }else if($value['order_status']==3){
                                           echo 'Cancelled';  
                                        }else{
                                          echo 'No Acknowledge';     
                                            
                                        }
?></td>
                                        <td><?php if($value['pay_status']==0){
                                                echo 'Pending';
                                        }else if($value['pay_status']==1){
                                          echo 'completed';  
                                        }else if($value['pay_status']==2){
                                           echo 'Failed';  
                                        }else if($value['pay_status']==3){
                                          echo 'COD';     
                                            
                                        }else{
                                          echo 'No Acknowledgement';    
                                        }
?></td>
                                        <td><?php if($value['delivery_status']==0){
                                                echo 'Pending';
                                        }else if($value['delivery_status']== 1){
                                          echo 'completed';  
                                        }else if($value['delivery_status']==2){
                                           echo 'Return/Cancelled';  
                                        }else if($value['delivery_status']==3){
                                          echo 'Unable to Reach';     
                                            
                                        }else{
                                          echo 'No Acknowledgement';    
                                        }
?></td>
                                        <td><?php echo $value['total_amount']; ?></td>
                                       
                                    </tr>
                                <?php
                                }
                            }
                            ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>


