<div id="page-title">
    <h2>Delivery Guy Orders Details For Stores</h2>    
</div>
<div class="row">
    <div class="col-md-12">
        <div class="panel">
            <div class="panel-body">
                <h3 class="title-hero">View Delivery Guy Order Details  For Stores</h3>
                <div class="example-box-wrapper" id="delivery_status_log">
                    <!-- Nav tabs -->
                    <ul class="nav nav-pills" role="tablist">
                        <li role="presentation" class="active"> 
                            <a href="#processing" aria-controls="processing" role="tab" data-toggle="tab">Processing</a>
                        </li>
                        <li role="presentation" >
                            <a href="#pickup" aria-controls="pickup" role="tab" data-toggle="tab">Pick Up</a>
                        </li>                     
                        <li role="presentation">
                            <a href="#outfordelivery" aria-controls="outfordelivery" role="tab" data-toggle="tab">Out for Delivery</a>
                        </li>     
                        <li role="presentation">
                            <a href="#delivered" aria-controls="delivered" role="tab" data-toggle="tab">Delivered</a>
                        </li>   
                    </ul>
                    <!-- Tab panes -->
                    <div class="tab-content">
                        <div role="tabpanel" class="tab-pane fade in active" id="processing">
                            <h3 class="title-hero">Processing </h3>
                            <table class="table table-striped table-bordered responsive no-wrap datatable-responsive" cellspacing="0" width="100%">
                                <thead>
                                    <tr>
                                        <th> S.No </th>
                                        <th>Store Name</th>
                                        <th> Delivery UserName </th>
                                        <th>Delivery Status</th>
                                        <th>Order ID</th>     
                                        <th>Pay Type</th>
                                        <th>Pay Status</th>
                                    </tr>
                                </thead>
                                <tfoot>
                                    <tr>
                                        <th> S.No </th>
                                        <th>Store Name</th>
                                        <th> Delivery UserName </th>
                                        <th>Delivery Status</th>
                                        <th>Order ID</th>     
                                        <th>Pay Type</th>
                                        <th>Pay Status</th>
                                    </tr>
                                </tfoot>
                                <tbody>
                                    <?php
                                    if (isset($this->processing)) {
                                        $i = 1;
                                        foreach ($this->processing as $value) {
                                            if ($value['hotel_store'] == 2) {
                                                ?>
                                                <tr id="<?php echo $value['del_guy_id']; ?>" >
                                                    <td><?php echo ++$i; ?></td>
                                                    <td><?php echo $value['store_name']; ?></td>
                                                    <td><?php echo $value['login_name']; ?></td>                                               
                                                    <td><?php
                                                        if ($value['order_status'] == 2) {
                                                            echo 'Processing ';
                                                        } else if ($value['order_status'] == 3) {
                                                            echo 'Pick Up';
                                                        } else if ($value['order_status'] == 4) {
                                                            echo 'Out For Delivered';
                                                        } else if ($value['order_status'] == 5) {
                                                            echo 'Delivered';
                                                            ;
                                                        }
                                                        ?></td>

                                                    <td><?php echo $value['order_id']; ?></td>
                                                    <td><?php
                                                        if ($value['tx_type'] == 1) {
                                                            echo 'COD';
                                                        } else {
                                                            echo "PaYpaL";
                                                        }
                                                        ?></td>
                                                    <td><?php
                                                        if ($value['tx_status'] == 1) {
                                                            echo 'Success';
                                                        } else if ($value['tx_status'] == 2) {
                                                            echo 'Pending';
                                                        } else if ($value['tx_status'] == 3) {
                                                            echo 'Failed';
                                                        } else {
                                                            echo 'Canceled';
                                                        }
                                                        ?></td> 
                                                </tr>   

                                                <?php
                                                $i++;
                                            }
                                        }
                                    }
                                    ?>
                                </tbody>
                            </table>
                        </div>
                        <div role="tabpanel" class="tab-pane fade " id="pickup">
                            <h3 class="title-hero">Pick Up</h3>
                            <table class="table table-striped table-bordered responsive no-wrap datatable-responsive" cellspacing="0" width="100%">
                                <thead>
                                    <tr>
                                        <th> S.No </th>
                                        <th>Store Name</th>
                                        <th> Delivery UserName </th>
                                        <th>Delivery Status</th>
                                        <th>Order ID</th>     
                                        <th>Pay Type</th>
                                        <th>Pay Status</th>
                                    </tr>
                                </thead>
                                <tfoot>
                                    <tr>
                                        <th> S.No </th>
                                        <th>Store Name</th>
                                        <th> Delivery UserName </th>
                                        <th>Delivery Status</th>
                                        <th>Order ID</th>     
                                        <th>Pay Type</th>
                                        <th>Pay Status</th>
                                    </tr>
                                </tfoot>
                                <tbody>
                                    <?php
                                    if (isset($this->pickup)) {
                                        $i = 1;
                                        foreach ($this->pickup as $value) {
                                            if ($value['hotel_store'] == 2) {
                                                ?>

                                                <tr id="<?php echo $value['del_guy_id']; ?>" >
                                                    <td><?php echo ++$i; ?></td>
                                                    <td><?php echo $value['store_name']; ?></td>
                                                    <td><?php echo $value['login_name']; ?></td>                                            
                                                    <td><?php
                                                        if ($value['order_status'] == 2) {
                                                            echo 'Processing ';
                                                        } else if ($value['order_status'] == 3) {
                                                            echo 'Pick Up';
                                                        } else if ($value['order_status'] == 4) {
                                                            echo 'Out For Delivered';
                                                        } else if ($value['order_status'] == 5) {
                                                            echo 'Delivered';
                                                            ;
                                                        }
                                                        ?></td>
                                                    <td><?php echo $value['order_id']; ?></td>
                                                    <td><?php
                                                        if ($value['tx_type'] == 1) {
                                                            echo 'COD';
                                                        } else {
                                                            echo "PaYpaL";
                                                        }
                                                        ?></td>
                                                    <td><?php
                                                        if ($value['tx_status'] == 1) {
                                                            echo 'Success';
                                                        } else if ($value['tx_status'] == 2) {
                                                            echo 'Pending';
                                                        } else if ($value['tx_status'] == 3) {
                                                            echo 'Failed';
                                                        } else {
                                                            echo 'Canceled';
                                                        }
                                                        ?></td> 
                                                </tr>   
                                                <?php
                                                $i++;
                                            }
                                        }
                                    }
                                    ?>
                                </tbody>
                            </table>
                        </div>

                        <div role="tabpanel" class="tab-pane fade" id="outfordelivery">
                            <h3 class="title-hero">Out For Delivery </h3>
                            <table class="table table-striped table-bordered responsive no-wrap datatable-responsive" cellspacing="0" width="100%">
                                <thead>
                                    <tr>
                                        <th> S.No </th>
                                        <th>Store Name</th>
                                        <th> Delivery UserName </th>
                                        <th>Delivery Status</th>
                                        <th>Order ID</th>     
                                        <th>Pay Type</th>
                                        <th>Pay Status</th>

                                    </tr>
                                </thead>
                                <tfoot>
                                    <tr>
                                        <th> S.No </th>
                                        <th>Store Name</th>
                                        <th> Delivery UserName </th>
                                        <th>Delivery Status</th>
                                        <th>Order ID</th>     
                                        <th>Pay Type</th>
                                        <th>Pay Status</th>
                                    </tr>
                                </tfoot>
                                <tbody>
                                    <?php
                                    if (isset($this->outfordelivery)) {
                                        $i = 1;
                                        foreach ($this->outfordelivery as $value) {
                                            if ($value['hotel_store'] == 2) {
                                                ?>
                                                <tr id="<?php echo $value['del_guy_id']; ?>" >
                                                    <td><?php echo ++$i; ?></td>
                                                    <td><?php echo $value['store_name']; ?></td>
                                                    <td><?php echo $value['login_name']; ?></td>
                                                    <td><?php
                                                        if ($value['order_status'] == 2) {
                                                            echo 'Processing ';
                                                        } else if ($value['order_status'] == 3) {
                                                            echo 'Pick Up';
                                                        } else if ($value['order_status'] == 4) {
                                                            echo 'Out For Delivered';
                                                        } else if ($value['order_status'] == 5) {
                                                            echo 'Delivered';
                                                            ;
                                                        }
                                                        ?></td>

                                                    <td><?php echo $value['order_id']; ?></td>
                                                    <td><?php
                                                        if ($value['tx_type'] == 1) {
                                                            echo 'COD';
                                                        } else {
                                                            echo "PaYpaL";
                                                        }
                                                        ?></td>
                                                    <td><?php
                                                        if ($value['tx_status'] == 1) {
                                                            echo 'Success';
                                                        } else if ($value['tx_status'] == 2) {
                                                            echo 'Pending';
                                                        } else if ($value['tx_status'] == 3) {
                                                            echo 'Failed';
                                                        } else {
                                                            echo 'Canceled';
                                                        }
                                                        ?></td> 
                                                </tr>   
                                                <?php
                                                $i++;
                                            }
                                        }
                                    }
                                    ?>
                                </tbody>
                            </table>
                        </div>
                        <div role="tabpanel" class="tab-pane fade" id="delivered">
                            <h3 class="title-hero">Delivered </h3>
                            <table class="table table-striped table-bordered responsive no-wrap datatable-responsive" cellspacing="0" width="100%">
                                <thead>
                                    <tr>
                                        <th> S.No </th>
                                        <th>Store Name</th>
                                        <th> Delivery UserName </th>
                                        <th>Delivery Status</th>
                                        <th>Order ID</th>     
                                        <th>Pay Type</th>
                                        <th>Pay Status</th>
                                    </tr>
                                </thead>
                                <tfoot>
                                    <tr>
                                        <th> S.No </th>
                                        <th>Store Name</th>
                                        <th> Delivery UserName </th>
                                        <th>Delivery Status</th>
                                        <th>Order ID</th>     
                                        <th>Pay Type</th>
                                        <th>Pay Status</th>

                                    </tr>
                                </tfoot>
                                <tbody>
                                    <?php
                                    if (isset($this->delivered)) {
                                        $i = 1;
                                        foreach ($this->delivered as $value) {
                                            if ($value['hotel_store'] == 2) {
                                                ?>
                                                <tr id="<?php echo $value['del_guy_id']; ?>" >
                                                    <td><?php echo ++$i; ?></td>
                                                    <td><?php echo $value['store_name']; ?></td>
                                                    <td><?php echo $value['login_name']; ?></td>

                                                    <td><?php
                                                        if ($value['order_status'] == 2) {
                                                            echo 'Processing ';
                                                        } else if ($value['order_status'] == 3) {
                                                            echo 'Pick Up';
                                                        } else if ($value['order_status'] == 4) {
                                                            echo 'Out For Delivered';
                                                        } else if ($value['order_status'] == 5) {
                                                            echo 'Delivered';
                                                            ;
                                                        }
                                                        ?></td>

                                                    <td><?php echo $value['order_id']; ?></td>
                                                    <td><?php
                                                        if ($value['tx_type'] == 1) {
                                                            echo 'COD';
                                                        } else {
                                                            echo "PaYpaL";
                                                        }
                                                        ?></td>
                                                    <td><?php
                                                        if ($value['tx_status'] == 1) {
                                                            echo 'Success';
                                                        } else if ($value['tx_status'] == 2) {
                                                            echo 'Pending';
                                                        } else if ($value['tx_status'] == 3) {
                                                            echo 'Failed';
                                                        } else {
                                                            echo 'Canceled';
                                                        }
                                                        ?></td> 
                                                </tr>   
                                                <?php
                                                $i++;
                                            }
                                        }
                                    }
                                    ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    $('[data-toggle="tab"]').click(function(e) {
        e.preventDefault();
        $(this).parent().siblings().removeClass('active');
        $(this).parent().addClass('active');
        var id = $(this).attr('href');
        $(id).siblings().removeClass('in active');
        $(id).toggleClass('in active');
    });
</script>
