<div id="page-title">
    <h2>view Delivery Guy Details</h2>   
</div>
<div class="row">
    <div class="col-md-12">
        <form class="form-horizontal bordered-row" enctype="multipart/form-data" method="POST">
            <div class="row">
                <div class="col-md-6">
                    <div class="panel">
                        <div class="panel-body">
                            <div class="example-box-wrapper">
                                <table class="table table-responsive">
                                    <tbody>
                                        <tr>
                                            <td>
                                                <label class="control-label">Delivery ID</label>
                                            </td>
                                            <td>
                                                <?php echo $this->deliveryguydetails['del_guy_id']; ?>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <label class="control-label">Hotel Names</label>
                                            </td>
                                            <td>
                                                <?php echo $this->deliveryguydetails['hotel_id']; ?>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <label class="control-label">Delivery Name</label>
                                            </td>
                                            <td>
                                                <?php echo $this->deliveryguydetails['login_name']; ?>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <label class="control-label">Email</label>
                                            </td>
                                            <td>
                                                <?php
                                                if (isset($this->deliveryguydetails['email'])) {
                                                    echo $this->deliveryguydetails['email'];
                                                }
                                                ?>
                                            </td>
                                        </tr>

                                        <tr>
                                            <td>
                                                <label class="control-label">First Name</label>
                                            </td>
                                            <td>
                                                <?php
                                                if (isset($this->deliveryguydetails['firstname'])) {
                                                    echo $this->deliveryguydetails['firstname'];
                                                }
                                                ?>
                                            </td>
                                        </tr>

                                        <tr>
                                            <td>
                                                <label class="control-label">Last Name</label>
                                            </td>
                                            <td>
                                                <?php
                                                if (isset($this->deliveryguydetails['lastname'])) {
                                                    echo $this->deliveryguydetails['lastname'];
                                                }
                                                ?>
                                            </td>
                                        </tr>

                                        <tr>
                                            <td>
                                                <label class="control-label">Password</label>
                                            </td>
                                            <td>
                                                <?php echo $this->deliveryguydetails['password']; ?>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <label class="control-label">Phone</label>
                                            </td>
                                            <td>
                                                <?php
                                                if (isset($this->deliveryguydetails['phone'])) {
                                                    echo $this->deliveryguydetails['phone'];
                                                }
                                                ?>

                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <label class="control-label">Status</label>
                                            </td>
                                            <td><?php
                                                if (isset($this->deliveryguydetails['status']) == 1) {
                                                    echo " Active ";
                                                } else {
                                                    echo "Deactivate";
                                                }
                                                ?>
                                            </td>

                                        </tr>

                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="panel">
                        <div class="panel-body">
                            <div class="example-box-wrapper">
                                <table class="table table-responsive">
                                    <tbody>
                                        <tr>
                                            <td>
                                                <label class="control-label">City</label>
                                            </td>
                                            <td>
                                                <div class="input-group">
                                                    <?php
                                                    if (isset($this->deliveryguydetails['city'])) {
                                                        echo $this->deliveryguydetails['city'];
                                                    }
                                                    ?>
                                                </div>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <label class="control-label">State</label>
                                            </td>
                                            <td>
                                                <?php
                                                if (isset($this->deliveryguydetails['state'])) {
                                                    echo $this->deliveryguydetails['state'];
                                                }
                                                ?>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <label class="control-label">Country</label>
                                            </td>
                                            <td>
                                                <?php
                                                if (isset($this->deliveryguydetails['country'])) {
                                                    echo $this->deliveryguydetails['country'];
                                                }
                                                ?>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <label class="control-label">Address</label>
                                            </td>
                                            <td>
                                                <?php
                                                if (isset($this->deliveryguydetails['address'])) {
                                                    echo $this->deliveryguydetails['address'];
                                                }
                                                ?>
                                            </td>
                                        </tr>
                                    </tbody>
                                </table>                          
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>




