<section id="indexLogin" class="index-bg-1">
	<div class="container ">
    	<div class="row marginTB-md ">
        	<div class="col-lg-12 col-md-6 col-sm-12">
            	<div class="m-top-75">
                	<div class="width40p margin-auto">
                	<div class="panel radius-15 panel-login padding-sm">
                    	<div class="panel-heading">
                        	<img src="<?php echo $this->baseUrl() . $this->appSetting->assestPath."admin/images/fansports-logo.png"; ?>" class="img-responsive center-block">
                        </div>
                        <div class="panel-body">
                        	<form method="post">
                                	<div class="form-group">
                                    	<label for="adminName">Username:</label>
                                        <div class="input-group">
                                        	<span class="input-group-addon"><i class="fa fa-user"></i></span>
                                                <input required type="text" name="username" class="form-control" placeholder="Enter Your Username">
                                        </div>
                                    </div>
                                    <div class="form-group m-top-sm">
                                    	<label for="adminPassword">Password</label>
                                        <div class="input-group">
                                        	<span class="input-group-addon"><i class="fa fa-key"></i></span>
                                            <input required class="form-control" type="password" name="password"  placeholder="Enter Your Password">
                                        </div>
                                    </div>
                                    <div class="form-group">
                                    	<button class="form-control btn btn-blue">Sign In</button>
                                    </div>
                                </form>
                        </div>
                		
                    </div>
                </div>
                    
                    <div class="opennotificationGreen alert alert-dismissable width40p margin-auto radius-15" style="display :none !important; background: rgba(23,188,208,0.5);">
                        <span class="notification_msgGreen error"><h2 class="text-danger no-margin"><center><?php echo $this->errormgs ?></center></h2></span>  
                    </div>
                </div>
                
            </div>
        </div>
    </div>
</section>

<?php if(isset($this->errormgs)){ ?>
<!-- This script Displays the  notification when the user details are submitted on submit  -->
<script>  
       
        $('.opennotificationGreen').fadeIn("slow");             
        $('.opennotificationGreen').css('display','block');
        
        setTimeout(function() {
            $('.opennotificationGreen').fadeOut("slow");
            $('div').remove(".notification_msgGreen");
            }, 3000); 
          
    </script>
    <?php } ?>
