<?php // echo '<pre>';print_r($this->storedetails); die;    ?>
<div id="content" class="content">
    <ol class="breadcrumb pull-right">
        <li><a href="index.html">Home</a></li>
        <li><a href="javascript:;">Store Details</a></li>
        <li class="active">Edit Store Details</li>
    </ol>
    <!-- end breadcrumb -->
    <!-- begin page-header -->
    <h1 class="page-header">Edit Store Details </h1>
    <!-- end page-header -->

    <!-- begin row -->
    <div class="row">
        <!-- begin col-12 -->
        <div class="col-md-12">
            <!-- begin panel -->
            <div class="panel pagination-theme clearfix m-b-0">
                <div class="panel-body">
                    <form class="" role="form" enctype="multipart/form-data" method="POST">
                        <div class="row">
                            <div class="col-md-12">
                                <!--==============================================edited by sreekanth================================================================================                         -->
                                <legend class="heading">Location:</legend>

                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label class="control-label">Select the Country</label>
                                            <select class="form-control selectpicker width-full selectcountry" name="selectcountry"  selectpicker width-full ta-size="10" data-live-search="true">
                                                <optgroup label="Select Country">
                                                    <option value="<?php echo $value['location_id']; ?>"><?php
                                                        if (isset($this->storedetails['countryName'])) {

                                                            echo $this->storedetails['countryName'];
                                                        } else {

                                                            echo "Select Country";
                                                        }
                                                        ?>
                                                    </option>
                                                    <?php
                                                    if (isset($this->countrylist)) {
                                                        foreach ($this->countrylist as $value) {
                                                            ?>
                                                            <option value="<?php echo $value['location_id']; ?>"><?php echo $value['name']; ?></option>
                                                            <?php
                                                        }
                                                    }
                                                    ?>
                                                </optgroup>
                                            </select>
                                        </div>
                                        <div class="form-group">
                                            <label class="control-label">Select the State</label>
                                            <select id="state" class="form-control selectpicker width-full selectstate" name="selectstate" data-size="10" data-live-search="true">
                                                <optgroup label="Select State" id="state">
                                                    <option value="<?php echo $value['location_id']; ?>"><?php
                                                        if (isset($this->storedetails['stateName'])) {

                                                            echo $this->storedetails['stateName'];
                                                        } else {

                                                            echo "Select state";
                                                        }
                                                        ?></option>
                                                </optgroup>
                                            </select>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label class="control-label">Select the City</label>
                                            <select id="city" class="form-control selectpicker width-full selectcity" name="selectcity" data-size="10" data-live-search="true">
                                                <optgroup label="Select City" id="city">
                                                    <option value="<?php echo $value['location_id']; ?>"><?php
                                                        if (isset($this->storedetails['cityName'])) {

                                                            echo $this->storedetails['cityName'];
                                                        } else {

                                                            echo "Select city";
                                                        }
                                                        ?></option>
                                                </optgroup>
                                            </select>
                                        </div>
                                        <div class="form-group">
                                            <label class="control-label">Select the Location</label>
                                            <select id="location" class="form-control selectpicker loc-disable width-full" name="selectlocation" data-size="10" data-live-search="true">
                                                <optgroup label="Select Location" id="location">
                                                    <option value="<?php echo $value['location_id']; ?>"><?php
                                                        if (isset($this->storedetails['areaName'])) {

                                                            echo $this->storedetails['areaName'];
                                                        } else {

                                                            echo "Select Location";
                                                        }
                                                        ?></option>
                                                </optgroup>
                                            </select>
                                            <small><i>if your location is not listed, Click <a href="javascript:;" class="add-loc">here</a></i></small>
                                            <input type="text" class="form-control m-t-20 new-location" name="location_name" placeholder="Enter your Location" />
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <!--===============================================edited by sreekanth=========END========================================================-->

                            <div class="col-md-12">
                                <legend class="heading">Details:</legend>

                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group has-success has-feedback m-b-10">
                                            <label class="control-label">Store Name</label>
                                            <input type="text" value="<?php
                                            if (isset($this->storedetails['store_name'])) {
                                                echo $this->storedetails['store_name'];
                                            }
                                            ?>" name="store_name" class="form-control" />
                                            <span class="fa fa-check form-control-feedback"></span>
                                        </div>


                                        <div class="form-group has-error has-feedback m-b-10">
                                            <label class="control-label">Store Address</label>
                                            <textarea  name="address" class="form-control" rows="3"><?php
                                                if (isset($this->storedetails['store_address'])) {
                                                    echo $this->storedetails['store_address'];
                                                }
                                                ?></textarea>
                                            <span class="fa fa-times form-control-feedback"></span>
                                        </div>
                                        <div class="form-inline m-b-10">
                                            <label class="">Timing</label>
                                            <br/>
                                            <div style="display: inline-flex;">
                                                <div class="form-group" style="width: 53%;">
                                                    <input type="text" placeholder="Opening Time" value="<?php
                                                    if (isset($this->storedetails['Open_time'])) {
                                                        echo $this->storedetails['Open_time'];
                                                    }
                                                    ?>" name="open_time" class="form-control" /> AM &nbsp; &nbsp; &nbsp; &nbsp;
                                                </div>
                                                <div class="form-group">
                                                    <input type="text" placeholder="Closing Time" value="<?php
                                                    if (isset($this->storedetails['Closing_time'])) {
                                                        echo $this->storedetails['Closing_time'];
                                                    }
                                                    ?>" name="closing_time" class="form-control" /> PM
                                                </div>
                                            </div>
                                        </div>

                                        <div class="form-group m-b-10">
                                            <label class="control-label">Primary Phone No.</label>
                                            <input type="text" name="primary_phone" value="<?php
                                            if (isset($this->storedetails['store_contact_number'])) {
                                                echo $this->storedetails['store_contact_number'];
                                            }
                                            ?>"class="form-control" />
                                        </div>

                                        <div class="form-group m-b-10">
                                            <label class="control-label">Secondary Phone No.</label>
                                            <input type="text"  value="<?php
                                            if (isset($this->storedetails['Secondary_phone'])) {
                                                echo $this->storedetails['Secondary_phone'];
                                            }
                                            ?>" name="secondary_phone" class="form-control" />
                                        </div>

                                        <div class="form-group m-b-10">
                                            <label class="control-label">Select the Category Name</label>
                                            <select id="cat_name" class="form-control selectpicker width-full cat_name" name="cat_name[]" data-size="10" data-live-search="true" multiple="multiple">
                                                <optgroup label="Select Category" id="cat_name">
                                                    <option value="<?php echo $this->storedetails['category_id']; ?>"><?php
                                                        if (isset($this->storedetails['cat_name'])) {

                                                            echo $this->storedetails['cat_name'];
                                                        } else {

                                                            echo "Select Category Name";
                                                        }
                                                        ?></option>
                                                </optgroup>
                                                <?php
                                                if (isset($this->categorylist)) {
                                                    foreach ($this->categorylist as $value) {
                                                        ?>
                                                        <option value="<?php echo $value['category_id']; ?>"><?php echo $value['cat_name']; ?></option>
                                                        <?php
                                                    }
                                                }
                                                ?>
                                            </select>
                                        </div>                                   
                                    </div>

                                    <div class="col-md-6">
                                        <div class="form-group m-b-10">
                                            <label class="control-label">Store Image</label>
                                            <div class="form-group">
                                                <div class="fileinput fileinput-new" data-provides="fileinput">
                                                    <div class="fileinput-new thumbnail" style="width: 200px; height: 150px;">
                                                        <img src="<?php
                                                        if (isset($this->storedetails['store_image'])) {
                                                            echo $this->storedetails['store_image'];
                                                        }
                                                        ?>" alt="">
                                                    </div>
                                                    <div class="fileinput-preview fileinput-exists thumbnail" style="max-width: 200px; max-height: 150px;"></div>
                                                    <div>
                                                        <span class="btn btn-default btn-file">
                                                            <span class="fileinput-new">Select Image</span>
                                                            <span class="fileinput-exists">Replace</span>
                                                            <input type="file" name="fileToUpload">
                                                        </span>
                                                        <a href="#" class="btn btn-danger fileinput-exists" data-dismiss="fileinput">Remove</a>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>

                                        <div class="form-group m-b-10">
                                            <label class="control-label">Delivery Charges</label>
                                            <input type="text" value="<?php
                                            if (isset($this->storedetails['Deliverycharge'])) {
                                                echo $this->storedetails['Deliverycharge'];
                                            }
                                            ?>" name="deliverycharge" class="form-control" />
                                        </div>
                                        <div class="form-group m-b-10">
                                            <label class="control-label">Store Notice</label>
                                            <textarea   name="notice" class="form-control"> <?php
                                                if (isset($this->storedetails['Notice'])) {
                                                    echo $this->storedetails['Notice'];
                                                }
                                                ?></textarea>
                                        </div>
                                        <div class="form-group">
                                            <label class="control-label">Status</label>
                                            <select class="form-control selectpicker width-full" name="store_status" data-size="10">
                                                <option value="1" <?php
                                                if (isset($this->storedetails['store_status']) == 1) {
                                                    echo "selected";
                                                }
                                                ?>>Active</option>
                                                <option value="2" <?php
                                                if (isset($this->storedetails['store_status']) == 2) {
                                                    echo "selected";
                                                }
                                                ?>>Inactive</option>
                                            </select>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="text-right m-r-10">
                                <button type="submit" class="btn btn-theme">Edit Store</button>
                            </div>
                        </div>

                    </form>
                </div>
            </div>
            <!-- end panel -->
        </div>
        <!-- end col-12 -->
    </div>
    <!-- end row -->
</div>
