<section class="restaurant-details">
    <div class="parallax-container h-350">
        <div class="parallax"><img src="assets/images/cart-bg.jpg" class="responsive-img"></div>
        <div class="parallax-content p-top-64">
        </div>
    </div>
    <?php
    if (isset($this->cartdata)) {
        foreach ($this->cartdata as $value) {
            ?>

            <div class="red lighten-5 paddingTB-md">
                <div class="container w85">
                    <div class="card-panel">
                        <div class="row">


                            <div class="col s12">
                                <div id="cart" class="row">
                                    <h4 style="margin-left: 1%;">Shopping Cart</h4>
                                    <div class="items col l9 m9 s12">
                                        <h5 class="orderHeading m-top-md"><?php
                                            if (isset($value['hotelname'])) {
                                                echo $value['hotelname'];
                                            }
                                            ?></h5>
                                        <?php foreach ($value['products'] as $val) { ?>
                                            <div class="row grandparent" >
                                                <div class="col l2">
                                                    <img src="<?php
                                                    if (isset($val['imagelink'])) {
                                                        echo $val['imagelink'];
                                                    }
                                                    ?>" class="responsive-img" />
                                                </div>
                                                <div class="col l5">
                                                    <div class="description">
                                                        <h1 style=' font-size: 19px;'><?php
                                                            if (isset($val['product_name'])) {
                                                                echo $val['product_name'];
                                                            }
                                                            ?></h1>
                                                        <h2>In Stock - Ready to Delivery</h2>
                                                    </div>
                                                </div>
                                                <div class="col l2 tquant">
                                                    <div class="product_quantity">
                                                        <div class="quantity_button">
                                                            <div class="how_many"><?php
                                                                if (isset($val['quantity'])) {
                                                                    echo $val['quantity'];
                                                                }
                                                                ?></div>
                                                            <div class="add_sub">
                                                                <div class="add changecookiequantity" product-id="<?php
                                                                if (isset($val['product_id'])) {
                                                                    echo $val['product_id'];
                                                                }
                                                                ?>" hotel-id="<?php
                                                                     if (isset($val['hotel_id'])) {
                                                                         echo $val['hotel_id'];
                                                                     }
                                                                     ?>" value="add" item-cost="<?php
                                                                     if (isset($val['unit_cost'])) {
                                                                         echo $val['unit_cost'];
                                                                     }
                                                                     ?>">+</div>
                                                                <div class="sub changecookiequantity" product-id="<?php
                                                                if (isset($val['product_id'])) {
                                                                    echo $val['product_id'];
                                                                }
                                                                ?>" hotel-id="<?php
                                                                     if (isset($val['hotel_id'])) {
                                                                         echo $val['hotel_id'];
                                                                     }
                                                                     ?>"value="sub" item-cost="<?php
                                                                     if (isset($val['unit_cost'])) {
                                                                         echo $val['unit_cost'];
                                                                     }
                                                                     ?>">-</div>
                                                            </div>
                                                        </div>
                                                    </div>

                                                </div>

                                                <div class="col l1 tcost">
                                                    <div class="price"><i class="fa fa-inr"><?php
                                                            if (isset($val['total_cost'])) {
                                                                echo $val['total_cost'];
                                                            }
                                                            ?></i></div>

                                                </div>
                                                <div class="col l2 tdel">
                                                    <div class="product_quantity">
                                                        <div class="quantity_button" style="background-color: transparent;">
                                                            <a href="javascript:;" data-prod="<?php
                                                            if (isset($val['product_id'])) {
                                                                echo $val['product_id'];
                                                            }
                                                            ?>"data-hid="<?php
                                                               if (isset($val['hotel_id'])) {
                                                                   echo $val['hotel_id'];
                                                               }
                                                               ?>"  class="text-danger deleteitem"   data-unitcost="<?php echo $val['unit_cost']; ?>">
                                                                <i style='font-size: 23px;'class="fa fa-trash"></i>
                                                            </a>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        <?php } ?>	

                                    </div>
                                    <div class="subTotal col l3 m3 s12 p-top-60">
                                        <div class="chk">
                                            <label>TOTAL :</label>
                                            <table class="totalTable">
                                                <tbody>
                                                    <tr>
                                                        <td>Subtotal</td>
                                                        <td><span class="subtotal" data-total="<?php echo $value['totalcost']; ?>" ><i class="fa fa-inr"><?php echo $value['totalcost']; ?></i></span></td>
                                                    </tr>
        <!--                                                    <tr>
                                                        <td>Delivery Fee</td>
                                                        <td><span><i class="fa fa-inr"></i></span> 50</td>
                                                    </tr>
                                                    <tr>
                                                        <td>+ Service Fee(8%)</td>
                                                        <td><span><i class="fa fa-inr"></i></span> 11.50</td>
                                                    </tr>
                                                    <tr>
                                                        <td>+ VAT</td>
                                                        <td><span><i class="fa fa-inr"></i></span> 44.50</td>
                                                    </tr>
                                                    <tr>
                                                        <td>Discount</td>
                                                        <td>- <span><i class="fa fa-inr"></i></span> 100</td>
                                                    </tr>-->
                                                    <tr>
                                                        <td>Grand Total</td>
                                                        <td><span class="grandtotal" grand-total="<?php echo $value['totalcost']; ?>" ><i class="fa fa-inr"><?php echo $value['totalcost']; ?></i></span></td>
                                                    </tr>
                                                </tbody>
                                            </table>
                                        </div>
                                        <div class="center">
                                            <a  href ="/order-confirmation/<?php echo $value['hotel_id']; ?>/-for-the-restaurant-<?php echo $value['hotelname']; ?>" class="btn btn-alt waves-effect waves-teal btn-large green-text">Proceed to Check Out</a>
                                        </div>
                                        <div class="right m-top-md m-bot-lg">
                                            <a href ="/restaurant-details/<?php echo $value['hotel_id']; ?>" class="btn btn-alt text-red waves-effect waves-light ">Order More</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>  

            <?php
        }
    } else {
        ?>

        <div class="red lighten-5 paddingTB-md">
            <div class="container w85">
                <div class="card-panel">
                    <div class="row">
                        <div class="col s12">
                            <h4 style="margin-left: 1%;">Shopping Cart</h4>
                            <img src="assets/images/cart.jpg" class="responsive-img" />
                        </div>
                        <div class="col s12 center">
                            <a href="#changePlaceModal" class="btn btn-alt lime-text waves-effect waves-light top5px modal-trigger" href="">Find Restaurant<span class="m-left-sm"><i class="fa fa-shopping-bag"></i></span></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>   

    <?php }
    ?>
</section>

