<?php $alluserdetailsArray = $this->hoteldetails; ?>
<div id="page-title">
    <h2>Add Hotel Details</h2>
</div>
<form class="form-horizontal bordered-row" enctype="multipart/form-data" method="POST">
    <div class="row">
        <div class="col-md-12" style="padding: 0px;">
            <legend class="heading">Location:</legend>
        </div>
        <div class="col-md-6">
            <div class="panel">
                <div class="panel-body">
                    <div class="example-box-wrapper">
                        <div class="form-group">
                            <label class="control-label">Select the Country</label>
                            <select data-live-search="true" ta-size="10" width-full="" selectpicker="" da="" name="selectcountry" class="form-control js-example-responsive width-full selectcountry">
                             <optgroup label="Select Country">
                                                    <option> Select Country </option>
                                                    <?php
                                                    if (isset($this->countriesdetails)) {
                                                        foreach ($this->countriesdetails as $value) {
                                                            ?>
                                                            <option value="<?php echo $value['location_id']; ?>"><?php echo $value['name']; ?></option>
                                                            <?php
                                                        }
                                                    }
                                                    ?>
                                                </optgroup>
                            </select>
                        </div>
                        <div class="form-group">
                            <label class="control-label">Select the State</label>
                            <select data-live-search="true" data-size="10" name="selectstate" class="form-control js-example-responsive width-full selectstate">
                                <optgroup id="state" label="Select State">                                                    
                                    <option> Select State </option>
                                </optgroup>
                            </select>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="panel">
                <div class="panel-body">
                    <div class="example-box-wrapper">
                        <div class="form-group">
                            <label class="control-label">Select the City</label>
                            <select data-live-search="true" data-size="10" name="selectcity" class="form-control js-example-responsive width-full selectcity">
                                <optgroup id="city" label="Select City">
                                    <option> Select City </option>
                                </optgroup>
                            </select>
                        </div>
                        <div class="form-group">
                            <label class="control-label">Select the Location</label>
                            <select data-live-search="true" data-size="10" name="selectlocation" class="form-control js-example-responsive loc-disable width-full">
                                <optgroup id="location" label="Select Location">
                                    <option value=""> Select Location </option>
                                </optgroup>
                            </select>
                            <small><i>if your location is not listed, Click <a class="add-loc" href="javascript:;">here</a></i></small>
                            <input type="text" placeholder="Enter your Location" name="location_name" class="form-control m-t-20 new-location">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12" style="padding: 0px;">
            <legend class="heading">Details:</legend>
        </div>
        <div class="col-md-6" style="padding: 0px;">
            <div class="panel">
                <div class="panel-body">
                    <div class="example-box-wrapper">
                        <table class="table table-responsive">
                            <tbody>
                                <tr>
                                    <td>
                                        <label class="control-label">Agent ID</label>
                                    </td>
                                    <td>
                                        <input type="text" class="form-control" name="agent_id" id="agent_id" disabled value="<?php echo $alluserdetailsArray['agent_id'] ?>" placeholder=""  />
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <label class="control-label">Agent Name</label>
                                    </td>
                                    <td>
                                        <input type="text" class="form-control" disabled type="text" name="loginname"  id="loginname" value="<?php echo $alluserdetailsArray['loginname'] ?>" placeholder="" />
                                    </td>
                                </tr>

                                <tr>
                                    <td>
                                        <label class="control-label">Hotel Name</label>
                                    </td>
                                    <td>
                                        <input type="text" class="form-control"  name="hotel_name" value="" placeholder="" required />
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <label class="control-label">Select Cuisine</label>
                                    </td>
                                    <td>
                                        <select class="form-control js-example-responsive width-full" value="<?php echo $this->cuisine123; ?>" multiple="" name="selectcuisine[]" data-size="10" data-live-search="true">
                                            <optgroup label="Select Cuisine">
                                                <?php
//                                                                                        echo $this->cuisine123 ;die;
                                                if (isset($this->cuisine123)) {
//                                                    foreach ($this->cuisine123 as $value) {
                                                    ?>
                                                    <option value="<?php echo $this->cuisine123; ?>"><?php echo $this->cuisine123; ?></option>
                                                    <?php
                                                }
//                                                }
                                                ?>
                                            </optgroup>
                                        </select>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <label class="control-label">Hotel Address</label>
                                    </td>
                                    <td>
                                        <textarea class="form-control" name="address" id="address" cols="20" rows="2"  ><?php echo $alluserdetailsArray['address'] ?></textarea>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <label class="control-label">Timing</label>
                                    </td>
                                    <td>
                                        <div class="" style="display: inline-flex;">
                                            <input type="text" class="form-control" name="open_time"  id="open_time" value="<?php echo $alluserdetailsArray['open_time'] ?>" placeholder="" required style="width: 39%;" /> &nbsp; AM

                                            <input type="text" class="form-control" name="closing_time"  id="closing_time" value="<?php echo $alluserdetailsArray['closing_time'] ?>" placeholder="" required style="width: 39%; margin-left: 5%;" /> &nbsp; PM
                                        </div>
                                    </td>
                                </tr>                                  
                                <tr>
                                    <td>
                                        <label class="control-label">Status</label>
                                    </td>
                                    <td>
                                        <select  class="js-example-responsive js-example-basic-hide-search form-control" name="hotel_status"> 
                                            <option value="1" <?php
                                            if ($alluserdetailsArray['hotel_status'] == 1) {
                                                echo"selected";
                                            }
                                            ?>>
                                                Active 
                                            </option>
                                            <option value="2"
                                            ?>>
                                                Inactive 
                                            </option>
                                        </select>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <label class="control-label">Primary Phone No.</label>
                                    </td>
                                    <td>
                                        <input type="text" class="form-control" name="primary_phone"  id="primary_phone" value="<?php echo $alluserdetailsArray['primary_phone'] ?>" placeholder="" required />
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-6" style="padding: 0px;">
            <div class="panel">
                <div class="panel-body">
                    <div class="example-box-wrapper">
                        <table class="table table-responsive">
                            <tbody>
                                <tr>
                                    <td>
                                        <label class="control-label">Secondary Phone No.</label>
                                    </td>
                                    <td>
                                        <input type="text" class="form-control" name="secondary_phone"  id="last_name" value="" placeholder=""  />
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <label class="control-label">Hotel Image</label>
                                    </td>
                                    <td>
                                        <div class="fileinput fileinput-new" data-provides="fileinput">
                                            <div class="fileinput-new thumbnail" style="width: 200px; height: 150px;">
                                                <img data-src="" alt="">
                                            </div>
                                            <div class="fileinput-preview fileinput-exists thumbnail" style="max-width: 200px; max-height: 150px;"></div>
                                            <div>
                                                <span class="btn btn-sucess btn-file"><span class="fileinput-new">Select image</span><span class="fileinput-exists">Change</span><input type="file" name="..."></span>
                                                <a href="#" class="btn btn-danger fileinput-exists" data-dismiss="fileinput">Remove</a>
                                            </div>
                                        </div>

                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <label class="control-label">Min. Order</label>
                                    </td>
                                    <td>
                                        <input type="text" class="form-control" name="minorder"  id="minorder" value="" placeholder="" required />
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <label class="control-label">Delivery Charges</label>
                                    </td>
                                    <td>
                                        <input type="text" class="form-control" name="deliverycharge"  id="last_name" value="" placeholder="" required />
                                    </td>
                                </tr>                                   
                                <tr>
                                    <td>
                                        <label class="control-label">Hotel Notice</label>
                                    </td>
                                    <td>
                                        <textarea class="form-control" name="address" id="address" cols="20" rows="2"  ></textarea>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                        <div class="form-group pull-right">
                            <button type="submit" class="btn btn-alt btn-hover btn-primary">
                                <span>SAVE</span> <i class="glyph-icon icon-arrow-right"></i>
                                <div class="ripple-wrapper"></div>
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
<style>
    .select2.select2-container {
        width: 100% !important;
    }
    legend.heading::after {
        background: #dfdfdf none repeat scroll 0 0;
        content: "";
        height: 1px;
        margin-left: 0.5rem;
        position: absolute;
        top: 1.1rem;
        width: 100%;
    }
    legend.heading {
        border: medium none;
        color: #fb0007;
        display: block;
        font-size: 1.5rem;
        font-weight: bold;
        letter-spacing: 0.06rem;
        margin-bottom: 1.5rem;
        margin-top: 3%;
        overflow: hidden;
        position: relative;
        text-transform: uppercase;
        width: 100%;
    }
</style>