
<div id="page-title">
    <h2>Hotel Details</h2>
    <p>The most complete user interface framework that can be used to create stunning admin dashboards and presentation websites.</p>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="panel">
            <div class="panel-body">
                <h3 class="title-hero">View/Edit/Remove Hotels</h3>
                <div class="example-box-wrapper">
                    <table class="table table-striped table-bordered responsive no-wrap datatable-responsive" cellspacing="0" width="100%">
                        <thead>
                            <tr>
                                <th>S.No.</th>
                                <th>Hotel ID</th>
                                <th>Hotel Name</th>
                                <th> Agent ID</th>
                                <th> Agent Name </th>                            
                                <th> Timing </th>
                                <th> Status </th>
                                <th> Action </th>
                                <th> View/Delete</th>

                            </tr>
                        </thead>
                        <tfoot>
                            <tr>
                                <th>S.No.</th>
                                <th>Hotel ID</th>
                                <th>Hotel Name</th>
                                <th> Agent ID</th>
                                <th> Agent Name </th>
                                <th> Timing </th>
                                <th> Status </th>
                                <th> Action </th>
                                <th> View/Delete</th>

                            </tr>
                        </tfoot>
                        <tbody>

                            <?php
                            $i = 0;
                            if (isset($this->hoteldetails)) {
                                foreach ($this->hoteldetails as $value) {
                                    ?>

                                    <tr>
                                        <td><?php echo ++$i; ?></td>
                                        <td><?php echo $value['id']; ?></td>
                                        <td><?php echo $value['hotel_name']; ?></td>
                                        <td><?php echo $value['agent_id']; ?></td>
                                        <td><?php echo $value['loginname']; ?></td> 
                                        <td>
                                            <span><?php echo $value['open_time']; ?>AM</span> - <span><?php echo $value['closing_time']; ?>PM</span>
                                        </td>
                                        <?php if ($value['hotel_status'] == 1): ?>
                                            <td id="activehotel_<?php echo $value['id']; ?>" class="hotelactive">Active</td>
                                            <td class="center"><a style="cursor:pointer"  id="<?php
                                                if (isset($value['id'])): echo "hotel_" . $value['id'];
                                                endif;
                                                ?>" class="hoteldeactive">
                                                    <span id="activeclass_<?php echo $value['id']; ?>" class="bs-label label-danger">Deactivate</span></a></td>
                                        <?php else: ?>
                                            <td id="activehotel_<?php echo $value['id']; ?>" class="hoteldeactive">Suspended</td>
                                            <td class="center" ><a style="cursor:pointer" id="<?php
                                                if (isset($value['id'])): echo "hotel_" . $value['id'];
                                                endif;
                                                ?>" class="hotelactive">
                                                    <span id="activeclass_<?php echo $value['id']; ?>"  class="bs-label label-success">Activate</span></a></td>
                                        <?php endif; ?> 
                                        <td class="text-center">
                                            <a href="/admin/view-hotel-details/<?php echo $value['id']; ?>" class="btn btn-default"><i class="glyph-icon icon-linecons-eye"></i></a>
        <!--                                            <a href="/admin/edit-hotel-details/<?php echo $value['id']; ?>" class="btn btn-default"><i class="glyph-icon icon-linecons-penci"></i></a>-->
                                            <a href="javascript:;" id="<?php echo "hoteldelete_" . $value['id']; ?>" class="btn btn-default deletehotel"><i class="glyph-icon icon-linecons-trash"></i></a>
                                        </td>
                                    </tr>
                                    <?php
                                }
                            }
                            ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

