<?php
$allhoteldetailsArray = $this->allhoteldetails;
?>
<div id="page-title">
    <h2>View Hotel Details</h2>
</div>
<div class="row">
    <div class="col-md-12">
        <form class="form-horizontal bordered-row" enctype="multipart/form-data" method="POST">
            <div class="row">
                <div class="col-md-6">
                    <div class="panel">
                        <div class="panel-body">
                            <div class="example-box-wrapper">
                                <table class="table table-responsive">
                                    <tbody>
                                        <tr>
                                            <td>
                                                <label class="control-label">Agent ID</label>
                                            </td>
                                            <td>
                                                <?php echo $allhoteldetailsArray['agent_id'] ?>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <label class="control-label">Agent Name</label>
                                            </td>
                                            <td>
                                                <?php echo $allhoteldetailsArray['loginname'] ?>
                                            </td>
                                        </tr>

                                        <tr>
                                            <td>
                                                <label class="control-label">Hotel Name</label>
                                            </td>
                                            <td>
                                                <?php echo $allhoteldetailsArray['hotel_name'] ?>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <label class="control-label">Hotel Rating</label>
                                            </td>
                                            <td>
                                                <?php echo $allhoteldetailsArray['hotel_rating'] ?>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <label class="control-label">Cuisine</label>
                                            </td>
                                            <td>

                                                <?php
                                                $i = 0;
                                                if (isset($this->cuisinesdDetails)) {

                                                    foreach ($this->cuisinesdDetails as $value) {


                                                        echo $value['Cuisine_name'];
                                                        ?>    
                                                    <?php
                                                    }
                                                } else {
                                                    ?>
                                                    No Cuisine found !!
                                                <?php
                                                }
                                                $i++;
                                                ?>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <label class="control-label">Hotel Address</label>
                                            </td>
                                            <td>
<?php echo $allhoteldetailsArray['address'] ?>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <label class="control-label">Timing</label>
                                            </td>
                                            <td>
                                                <div class="" style="display: inline-flex;">
<?php echo $allhoteldetailsArray['open_time'] ?>&nbsp; AM&nbsp; &nbsp;- &nbsp;<?php echo $allhoteldetailsArray['closing_time'] ?>&nbsp; PM
                                                </div>
                                            </td>
                                        </tr>                                  
                                        <tr>
                                            <td>
                                                <label class="control-label">Status</label>
                                            </td>
                                            <td>
                                                <?php
                                                if ($allhoteldetailsArray['hotel_status'] == 1) {
                                                    echo"Active";
                                                } else {
                                                    echo"Deactivate";
                                                }
                                                ?>            
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <label class="control-label">Primary Phone No.</label>
                                            </td>
                                            <td>
<?php echo $allhoteldetailsArray['hotel_contact_number'] ?>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <label class="control-label">Secondary Phone No.</label>
                                            </td>
                                            <td>
<?php echo $allhoteldetailsArray['secondary_phone'] ?>
                                            </td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="panel">
                        <div class="panel-body">
                            <div class="example-box-wrapper">
                                <table class="table table-responsive">
                                    <tbody>

                                        <tr>
                                            <td>
                                                <label class="control-label">Hotel Image</label>
                                            </td>
                                            <td>
                                                <div class="fileinput fileinput-new" data-provides="fileinput">
                                                    <div class="fileinput-new thumbnail" style="width: 200px; height: 150px;">
                                                        <img src="<?php
                                                        if (isset($this->allhoteldetails['hotel_image'])) {
                                                            echo $this->allhoteldetails['hotel_image'];
                                                        }
                                                        ?>" alt="">
                                                    </div>
                                                    <div class="fileinput-preview fileinput-exists thumbnail" style="max-width: 200px; max-height: 150px;"></div>                                
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <label class="control-label">Min. Order</label>
                                            </td>
                                            <td>
<?php echo $allhoteldetailsArray['minorder'] ?>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <label class="control-label">Delivery Charges</label>
                                            </td>
                                            <td>
<?php echo $allhoteldetailsArray['deliverycharge'] ?>
                                            </td>
                                        </tr>                                   
                                        <tr>
                                            <td>
                                                <label class="control-label">Hotel Notice</label>
                                            </td>
                                            <td>
<?php echo $allhoteldetailsArray['notice'] ?>                                   
                                            </td>
                                        </tr>
                                    </tbody>
                                </table>                             
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

<style>
    .select2.select2-container {
        width: 100% !important;
    }
</style>