<div id="page-title">
    <h2>Dashboard</h2>
    
</div>
<div class="row">
    <div class="col-md-12">
        <div class="row">
            <div class="col-md-3"><a href="#" title="Example tile shortcut" class="tile-box tile-box-shortcut btn-danger"><span class="bs-badge badge-absolute">1</span><div class="tile-header">Users</div><div class="tile-content-wrapper"><i class="glyph-icon icon-file-photo-o"></i></div></a></div>
            <div class="col-md-3">
                <a href="#" title="Example tile shortcut" class="tile-box tile-box-shortcut btn-success">
                    <div class="tile-header">Products</div>
                    <div class="tile-content-wrapper"><i class="glyph-icon icon-desktop"></i></div>
                </a>
            </div>
            <div class="col-md-3"><a href="#" title="Example tile shortcut" class="tile-box tile-box-shortcut btn-info"><span class="bs-badge badge-absolute">2</span><div class="tile-header">Orders</div><div class="tile-content-wrapper"><i class="glyph-icon icon-download"></i></div></a></div>
            <div class="col-md-3">
                <a href="#" title="Example tile shortcut" class="tile-box tile-box-shortcut btn-warning">
                    <div class="tile-header">Agents</div>
                    <div class="tile-content-wrapper"><i class="glyph-icon icon-code-fork"></i></div>
                </a>
            </div>
        </div>
    </div>
</div>