<!-- Content Wrapper. Contains page content -->
      <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
          <h1>
            Dashboard
            <small>for your next cool web APP</small>
          </h1>
          <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li class="active">Dashboard</li>
          </ol>
        </section>
        
        <!-- Main content -->
        
        <section class="content">
           Info boxes 
          <div class="row">
            <div class="col-lg-2 col-md-4 col-xs-6">
               small box 
              <div class="small-box bg-aqua">
                <div class="inner">
                  <h3><?php // if(!empty($this->usercount)){ echo $this->usercount;}else{ echo 0; }?></h3>
                </div>
                <div class="icon">
                  <i class="fa fa-user"></i>
                </div>
                <a href="/admin/user-details" class="small-box-footer">Users<i class="fa fa-arrow-circle-right"></i></a>
              </div>
            </div>  
            <div class="col-lg-2 col-md-4 col-xs-6">
               small box 
              <div class="small-box bg-green">
                <div class="inner">
                  <h3><?php // if(!empty($this->allcontest)){ echo $this->allcontest;}else{ echo 0; }?></h3>
                </div>
                <div class="icon">
                  <i class="fa fa-futbol-o"></i>
                </div>
                <a href="/admin/contest-details" class="small-box-footer">Contest <i class="fa fa-arrow-circle-right"></i></a>
              </div>
            </div>
            <div class="col-lg-2 col-md-4 col-xs-6">
               small box 
              <div class="small-box bg-yellow">
                <div class="inner">
                  <h3>0</h3>
                </div>
                <div class="icon">
                  <i class="fa fa-bar-chart"></i>
                </div>
                <a href="/admin/promotion-details" class="small-box-footer">Promotion <i class="fa fa-arrow-circle-right"></i></a>
              </div>
            </div>
            <div class="col-lg-2 col-md-4 col-xs-6">
               small box 
              <div class="small-box bg-red">
                <div class="inner">
                  <h3><?php // if(!empty($this->alltickets)){ echo $this->alltickets;}else{ echo 0; }?></h3>
                </div>
                <div class="icon">
                  <i class="fa fa-ticket"></i>
                </div>
                <a href="/admin/ticket-details" class="small-box-footer">Ticket <i class="fa fa-arrow-circle-right"></i></a>
              </div>
            </div> 
            <div class="col-lg-2 col-md-4 col-xs-6">
               small box 
              <div class="small-box bg-teal">
                <div class="inner">
                  <h3><?php // if(!empty($this->allsports)){ echo $this->allsports;}else{ echo 0; }?></h3>
                </div>
                <div class="icon">
                  <i class="fa fa-gamepad"></i>
                </div>
                <a href="/admin/sports-details" class="small-box-footer">Sports <i class="fa fa-arrow-circle-right"></i></a>
              </div>
            </div> 
            <div class="col-lg-2 col-md-4 col-xs-6">
               small box 
              <div class="small-box bg-maroon">
                <div class="inner">
                  <h3><?php // if(!empty($this->alloffers)){ echo $this->alloffers;}else{ echo 0; }?></h3>
                </div>
                <div class="icon">
                  <i class="fa fa-bolt"></i>
                </div>
                <a href="/admin/offers" class="small-box-footer">Offers <i class="fa fa-arrow-circle-right"></i></a>
              </div>
            </div> 
          </div>
          
          <div class="row">
          	<div class="col-md-12">
            	<div class="box box-black box-solid">
                <div class="box-header with-border">
                  <h3 class="box-title font-Libre-Baskerville"><span class="m-right-sm"><i class="fa fa-bar-chart"></i></span>Join User Statics</h3>
                  <div class="pull-right m-left-md">
                    <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                  </div>
                  <div class="pull-right">
                    	<select class="form-control input-sm" onchange="location = this.options[this.selectedIndex].value;" style="width:150px">
                                            <?php
//                                            $select = "";
//                                            $year = date("Y");
//                                            for ($i = 1; $i <= 5; $i++) {
//                                                if ($year == $this->year)
//                                                    $select = "selected"
//                                                    ?>
                                                <!--<option //<?php echo $select; ?> value="/admin/dashboard?year=<?php echo $year; ?>"><?php echo $year; ?></option>-->						
                                                <?php
//                                                $year--;
//                                                $select = "";
//                                            }
                                            ?>
		        </select>
                  </div>
                </div>
                <div class="box-body">
                  <div class="chart">
                    <div id="barChartUserStatics"  style="width:100%;height:300px;margin: 0 auto"></div>
                  </div>
                </div> /.box-body 
              </div> 
            </div>
          </div>
          
          <div class="row">
          	<div class="col-md-12">
            	<div class="box box-black box-solid">
                <div class="box-header with-border">
                  <h3 class="box-title font-Libre-Baskerville"><span class="m-right-sm"><i class="fa fa-bar-chart"></i></span>Profit Statics</h3>
                  <div class="pull-right m-left-md">
                    <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                  </div>
                  <div class="pull-right">
                      <select class="form-control input-sm" onchange="location = this.options[this.selectedIndex].value;" style="width:150px">
                                            <?php
//                                            $select = "";
//                                            $year = date("Y");
//                                            for ($i = 1; $i <= 5; $i++) {
//                                                if ($year == $this->profityear)
//                                                    $select = "selected"
//                                                    ?>
                                                <!--<option <?php echo $select; ?> value="/admin/dashboard?profityear=<?php echo $year; ?>"><?php echo $year; ?></option>-->						
                                                <?php
//                                                $year--;
//                                                $select = "";
//                                            }
                                            ?>
		    </select>
                  </div>
                </div>
                <div class="box-body">
                  <div class="chart">
                    <div id="barChartProfitStatics" style="width:100%;height:300px;margin: 0 auto"></div>
                  </div>
                </div> /.box-body 
              </div> 
            </div>
          </div>
          <div style="display:none;" id="total-months"><?php echo json_encode($this->usermonths); ?></div>
          <div style="display:none;" id="total-user"><?php echo json_encode($this->usertotal); ?></div>
          <div style="display:none;" id="total-profit"><?php echo json_encode($this->profittotal); ?></div>
         
        </section>
        
        
        <!-- /.content -->
      </div><!-- /.content-wrapper -->