
<?php
$alladmindetailsArray = $this->admindetails;?>
<style>
    html,
    body {
        height: 100%;
        background: #fff
    }
</style>   
<!-- Start LOGIN -->
<div class="center-vertical login-bg">
    <div class="center-content">
        <form  id="login-validation" class="col-md-4 col-sm-5 col-xs-11 col-lg-3 center-margin" method="POST">
            <div id="header-logo" class="logo-bg">
                <a href="/admin" class="logo-content-big logo-left" title="Ziingo">Ziingo <i>UI</i> <span>Dashboard</span></a>
                <a href="/admin" class="logo-content-small" title="Ziingo">Ziingo <i>UI</i> <span>Dashboard</span></a>
            </div>
            <div id="login-form" class="content-box bg-default">
                <div class="content-box-wrapper pad20A">
                    <img class="mrg25B center-margin radius-all-100 display-block login-user-pic" src="<?php echo $alladmindetailsArray[0]['profilepic_url']; ?>" alt="assets/admin/images/pic.jpg" />
                    <div class="form-group">
                        <div class="input-group">
                            <span class="input-group-addon addon-inside bg-gray"><i class="glyph-icon icon-envelope-o"></i></span>
                            <input id="adminUN"  type="text" placeholder="Username" name="username" class="form-control" />
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="input-group">
                            <span class="input-group-addon addon-inside bg-gray"><i class="glyph-icon icon-unlock-alt"></i></span>
                            <input type="password" id="adminPW" placeholder="Password" name="password" class="form-control"/>
                        </div>
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn btn-block btn-primary">Login</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
<!-- End LOGIN -->