<!-- begin #content -->
<div id="content" class="content">
    <!-- begin breadcrumb -->
    <ol class="breadcrumb pull-right">
        <li><a href="javascript:;">Home</a></li>
        <li class="active">Dashboard</li>
    </ol>
    <!-- end breadcrumb -->
    <!-- begin page-header -->
    <h1 class="page-header">Dashboard</h1>
    <!-- end page-header -->

    <!-- begin row -->
    <div class="row">
        <!-- begin col-3 -->
        <div class="col-md-3">
            <!-- begin widget -->
            <div class="widget widget-stat bg-inverse text-white">
                <div class="widget-stat-btn"><a href="#" data-click="widget-reload"><i class="fa fa-repeat"></i></a></div>
                <div class="widget-stat-icon"><i class="fa fa-cutlery"></i></div>
                <div class="widget-stat-info">
                    <div class="widget-stat-shop">Hotels</div>
                    <div class="widget-stat-number">839</div>

                </div>
            </div>
            <!-- end widget -->
        </div>
        <!-- end col-3 -->
        <!-- begin col-3 -->
<!--        <div class="col-md-3">
             begin widget 
            <div class="widget widget-stat bg-success text-white">
                <div class="widget-stat-btn"><a href="#" data-click="widget-reload"><i class="fa fa-repeat"></i></a></div>
                <div class="widget-stat-icon"><i class="fa fa-file-text-o"></i></div>
                <div class="widget-stat-info">
                    <div class="widget-stat-title">Order Details</div>
                    <div class="widget-stat-number">91</div>

                </div>
            </div>
             end widget 
        </div>-->
        <!-- end col-3 -->
        <!-- begin col-3 -->
        <div class="col-md-3">
            <!-- begin widget -->
            <div class="widget widget-stat bg-primary text-white">
                <div class="widget-stat-btn"><a href="#" data-click="widget-reload"><i class="fa fa-repeat"></i></a></div>
                <div class="widget-stat-icon"><i class="fa fa-forumbee"></i></div>
                <div class="widget-stat-info">
                    <div class="widget-stat-title">Product Details</div>
                    <div class="widget-stat-number">98</div>

                </div>
            </div>
            <!-- end widget -->
        </div>
        <!-- end col-3 -->
        <!-- begin col-3 -->
        <div class="col-md-3">
            <!-- begin widget -->
            <div class="widget widget-stat bg-purple text-white">
                <div class="widget-stat-btn"><a href="#" data-click="widget-reload"><i class="fa fa-repeat"></i></a></div>
                <div class="widget-stat-icon"><i class="fa fa-money"></i></div>
                <div class="widget-stat-info">
                    <div class="widget-stat-title">Payment Details</div>
                    <div class="widget-stat-number">29</div>

                </div>
            </div>
            <!-- end widget -->
        </div>


        <!-- end col-3 -->
    </div>
    <!-- end row -->

</div>