	<!-- begin #content -->
		<div id="content" class="content">
			<!-- begin breadcrumb -->
			<ol class="breadcrumb pull-right">
				<li><a href="javascript:;">Home</a></li>
				<li class="active">Dashboard</li>
			</ol>
			<!-- end breadcrumb -->
			<!-- begin page-header -->
			<h1 class="page-header">Dashboard <small>header small text goes here...</small></h1>
			<!-- end page-header -->

			<!-- begin row -->
			<div class="row">
				<!-- begin col-3 -->
				<div class="col-md-3">
					<!-- begin widget -->
					<div class="widget widget-stat bg-inverse text-white">
						<div class="widget-stat-btn"><a href="#" data-click="widget-reload"><i class="fa fa-repeat"></i></a></div>
						<div class="widget-stat-icon"><i class="fa fa-users"></i></div>
						<div class="widget-stat-info">
							<div class="widget-stat-title">New Visitors</div>
							<div class="widget-stat-number">839</div>
							<div class="widget-stat-text">(3.10% better than last week)</div>
						</div>
					</div>
					<!-- end widget -->
				</div>
				<!-- end col-3 -->
				<!-- begin col-3 -->
				<div class="col-md-3">
					<!-- begin widget -->
					<div class="widget widget-stat bg-success text-white">
						<div class="widget-stat-btn"><a href="#" data-click="widget-reload"><i class="fa fa-repeat"></i></a></div>
						<div class="widget-stat-icon"><i class="fa fa-diamond"></i></div>
						<div class="widget-stat-info">
							<div class="widget-stat-title">New Registered VIP</div>
							<div class="widget-stat-number">2,291</div>
							<div class="widget-stat-text">(10.2% better than last week)</div>
						</div>
					</div>
					<!-- end widget -->
				</div>
				<!-- end col-3 -->
				<!-- begin col-3 -->
				<div class="col-md-3">
					<!-- begin widget -->
					<div class="widget widget-stat bg-primary text-white">
						<div class="widget-stat-btn"><a href="#" data-click="widget-reload"><i class="fa fa-repeat"></i></a></div>
						<div class="widget-stat-icon"><i class="fa fa-hdd-o"></i></div>
						<div class="widget-stat-info">
							<div class="widget-stat-title">Total Bandwidth Used</div>
							<div class="widget-stat-number">982GB</div>
							<div class="widget-stat-text">(1,239GB Left)</div>
						</div>
					</div>
					<!-- end widget -->
				</div>
				<!-- end col-3 -->
				<!-- begin col-3 -->
				<div class="col-md-3">
					<!-- begin widget -->
					<div class="widget widget-stat bg-purple text-white">
						<div class="widget-stat-btn"><a href="#" data-click="widget-reload"><i class="fa fa-repeat"></i></a></div>
						<div class="widget-stat-icon"><i class="fa fa-file"></i></div>
						<div class="widget-stat-info">
							<div class="widget-stat-title">Pending Invoice</div>
							<div class="widget-stat-number">29</div>
							<div class="widget-stat-text">(3 new transaction)</div>
						</div>
					</div>
					<!-- end widget -->
				</div>
				<!-- end col-3 -->
			</div>
			<!-- end row -->

		</div>