
<style>
    #page-container {
        background-image: url("/themes/agent/skin/images/signin-bg.jpg");
        background-size: cover;
    }

    .forget, .register {
        display: none;
    }
</style>
<div class="login">
    <!-- begin login-brand -->
    <div class="login-brand bg-theme login-border text-white">
        <img src="<?php echo $this->baseUrl() . $this->theme_base_path ?>/images/icon.png" height="36" class="pull-right" alt="" /> Login Panel
    </div>
    <!-- end login-brand -->

    <!-- begin login-content -->
    <div class="login-content">
        <h4 class="text-center m-t-0 m-b-20">Great to have you back!</h4>
        <form  method="POST" name="login_form" class="form-input-flat">
            <div class="form-group">
                <input type="text" id="loginname" name="loginname" class="form-control input-lg" placeholder="Email Address" required />
            </div>
            <div class="form-group">
                <input type="password" id="pwd" name="pwd" class="form-control input-lg" placeholder="Password" required />
            </div>
            <div class="text-right m-b-10">
                <a href="javascript:;" id="forget">Forgot Password ?</a>
            </div>
            <div class="row m-b-20">
                <div class="col-md-12">
                    <button type="submit" name="agentform" value="agentlogin" class="btn btn-theme btn-lg btn-block">Sign in to your account</button>
                </div>
            </div>
            <div class="text-center">
                New here? <a href="javascript:;" class="text-muted" id="register">Create a new account</a>
            </div>
        </form>
    </div>
    <!-- end login-content -->
</div>
<!-- end login -->

<!-- begin forget Password -->
<div class="forget">
    <!-- begin login-brand -->
    <div class="login-brand bg-theme login-border text-white">
        <img src="<?php echo $this->baseUrl() . $this->theme_base_path ?>/images/icon.png" height="36" class="pull-right" alt="" /> Forgot Password ?
    </div>
    <!-- end login-brand -->
    <!-- begin login-content -->
    <div class="login-content">
        <h4 class="text-center m-t-0 m-b-20">Reset link will be sent to you.</h4>
        <form action="index.html" method="POST" name="login_form" class="form-input-flat">
            <div class="form-group">
                <input type="email" class="form-control input-lg" placeholder="Email Address" required />
            </div>
            <div class="row m-b-20">
                <div class="col-md-12">
                    <button type="submit" class="btn btn-theme btn-lg btn-block">Send Link</button>
                </div>
            </div>
            <div class="text-right">
                Back to <a href="javascript:;" class="text-muted" id="blogin">Login</a>
            </div>
        </form>
    </div>
    <!-- end login-content -->
</div>
<!-- end forget Password -->

<!-- begin register -->
<div class="register" style="top:35px;">
    <!-- begin register-brand -->
    <div class="register-brand bg-theme login-border text-white">
        <img src="<?php echo $this->baseUrl() . $this->theme_base_path ?>/images/icon.png" height="36" class="pull-right" alt="" /> Registration Form
    </div>
    <!-- end register-brand -->
    <!-- begin register-content -->
    <div class="register-content">
        <h4 class="m-t-0 m-b-5">Great to see you here!</h4>
        <p class="m-b-20">Create your Ziingo AGENT Account in less than 2 mins.</p>

        <form  method="POST" name="register_form" class="form-input-flat">
            <div class="row row-space-14">
                <div class="col-md-6 m-b-15">
                    <input type="text" class="form-control input-lg" id="fname" name="first_name" placeholder="First Name" required />
                </div>
                <div class="col-md-6 m-b-15">
                    <input type="text" class="form-control input-lg" id="lname" name="last_name" placeholder="Last Name" required />
                </div>
            </div>
              <div class="form-group">
                <input type="text" id="uname" name="name" value =""  class="form-control input-lg" placeholder="Username" required/>
            </div>
            <div class="form-group">
                <input type="email" id="email" name="email" value =""  class="form-control input-lg" placeholder="Email Address" required/>
            </div>
            <div class="form-group">
                <input type="password" id="password" name="password" value ="" class="form-control input-lg" placeholder="Password" required />
            </div>
            <div class="form-group">
                <input id="city" name="city" value ="" class="form-control input-lg" placeholder="City" required />
            </div>
            <div class="row m-b-15">
                <div class="col-md-12">
                    <button type="submit" name="agentform" value="agentsignup" class="btn btn-theme btn-lg btn-block">Register</button>
                </div>
            </div>
            <div class="text-center">
                Already a member? <a href="javascript:;" class="text-muted" id="login">Login with your account</a>
            </div>
        </form>
    </div>

</div>