     <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
          <h1>
            Site Management
            <small>for your next cool web APP</small>
          </h1>
          <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-futbol-o"></i> Home</a></li>
            <li>Site Mangement</li>
            <li class="active">Manage Countries</li>
          </ol>
        </section>

        <!-- Main content -->
        <section class="content">
          <!-- Info boxes -->
          <div class="row">
          	<div class="col-md-12 col-sm-12 no-p-left no-p-right">
            	<div class="panel panel-black no-radius">
                	<div class="panel-heading paddingLR-md paddingTB-sm no-radius">
                    	<h3 class="font-Russo-One no-margin">Manage Countries</h3>
                    </div>
                </div>
            </div>
          </div>
          
          <div class="row">
          	<div class="col-md-12 col-sm-12">
            	<div class="panel panel-gray">
                	<div class="panel-heading paddingLR-md paddingTB-xs">
                    	<h4 class="font-Libre-Baskerville inline-block">Country Details</h4>
                    </div>
                    <div class="panel-body">
                    	
                      <div class="m-top-md">
                        	<div class="table-responsive">
                            	<table id="countryDetails" class="display table text-center" data-page-length="20" data-order="[[ 1, &quot;asc&quot; ]]" cellspacing="0" width="100%">
                                	<!-- Table heading -->
                    <thead>
                        <tr>
                            <th>Sr No</th>
                            <th>Country Code</th>
                            <th>Country Name</th>
                            <th class="center">Status</th>
                            <th class="center">Action</th>
                        </tr>
                    </thead>
                    <!-- // Table heading END -->

                    <!-- Table body -->
                    <tbody>

                        <?php if(isset($this->countries)): $row = 0; foreach($this->countries as $countriesDetails): $row ++; ?>
                        <!-- Table row -->
                        <tr class="gradeA">
                            <td><?php echo $row; ?></td>
                            <td><?php echo $countriesDetails['country_code']; ?></td>
                            <td><?php echo $countriesDetails['country_name']; ?></td>
                            <?php if($countriesDetails['status']==='1'): ?>
                            <td id="activecountry_<?php echo $countriesDetails['country_id']; ?>" class="center js-sortable-handle useractive">Active</td>
                            <td class="center" style="width: 80px;"><a href="#" id="<?php if (isset($countriesDetails['country_id'])): echo "country_" . $countriesDetails['country_id'];endif;?>" class="countrydeactive">
                            <span id="activeclass_<?php echo $countriesDetails['country_id']; ?>" class="label label-danger">Deactivate</span></a></td>
                              <?php  else: ?>
                            <td id="activecountry_<?php echo $countriesDetails['country_id']; ?>" class="center js-sortable-handle userdeactive">Suspended</td>
                            <td class="center" style="width: 80px;"><a href="#" id="<?php if (isset($countriesDetails['country_id'])): echo "country_" . $countriesDetails['country_id']; endif;?>" class="countryactive">
                            <span id="activeclass_<?php echo $countriesDetails['country_id']; ?>"  class="label label-success">Activate</span></a></td>
                            <?php endif;?>
                        </tr>                        
                        <!-- // Table row END -->
                        <?php endforeach;  endif; ?>
                    </tbody>
                    <!-- // Table body END -->
                                </table>
                          </div>
                        </div>
                        
                        
                    </div>
                </div>
                
                
            </div>
          </div>
          
          
         
        </section><!-- /.content -->
      </div>
<script>
    $('#countryDetails').DataTable({
        "bLengthChange": false,
    });
</script> 
<script>
 $(document).ready(function(){
   $(document.body).on('click','.countrydeactive',function(){
     var country = $(this).attr('id');
        var country_id = country.replace("country_","");        
        var w = $(this);        
        $.ajax({
        
            url: '/admin/jshandler',
            type: 'POST',
            datatype: 'HTML',
            data:{
                method : 'countryactive',
                country_id : country_id
            },
            beforeSend : function() {

            },
            success : function(response) {                  
                $('#'+"activeclass_"+response).removeClass('label label-danger');
                $('#'+"activeclass_"+response).addClass('label label-success');
                $('#'+"activeclass_"+response).html("Activate");
                $('#country_'+response).removeClass('countrydeactive');
                $('#country_'+response).addClass('countryactive');
                $('#'+"activecountry_"+response).html("Suspended");
            }
            
        
        });  
   }); 
   
   $(document.body).on('click','.countryactive',function(){
        var country = $(this).attr('id');
        var country_id = country.replace("country_","");                
        var w = $(this);        
        $.ajax({
        
            url: '/admin/jshandler',
            type: 'POST',
            datatype: 'HTML',
            data:{
                method : 'countryactive',
                country_id : country_id
            },
            beforeSend : function() {

            },
            success : function(response) {               
                $('#'+"activeclass_"+response).removeClass('label label-success');
                $('#'+"activeclass_"+response).addClass('label label-danger');
                $('#'+"activeclass_"+response).html("Deactivate");
                $('#country_'+response).removeClass('countryactive');
                $('#country_'+response).addClass('countrydeactive');
                $('#'+"activecountry_"+response).html("Active");
            }
            
        
        });   
   });
 });
 </script>

 <!----------------------Modals-------------------------->
      
<!--      <div class="modal fade" id="sendMail" role="dialog" aria-hidden="true">
                	<div class="modal-dialog width50p">
                    	<div class="modal-content modal-content-bg">
                        	<div class="modal-header model-header-bg no-border-bottom">
                            	<button type="button" data-dismiss="modal" class="close text-white"><span aria-hidden="true" aria-label="Close">&times;</span></button>
                            	
                                <h3 class="font-Titillium-Web no-margin text-center">Edit Mail</h3>
                                
                            </div>
                            <div class="modal-body">
                            	<div class="panel panel-black">
                                	<div class="panel-heading paddingLR-md">
                                    	<h4><span class="m-right-sm"><i class="fa fa-edit"></i></span>Send Message To <span><strong>Manoj</strong></span></h4>
                                    </div>
                                    <div class="panel-body padding-sm">
                                    	<div class="row">
                                        	<div class="col-md-12">
                                            	<div class="form-group">
                                                	<label>To</label>
                                                    <div class="input-group col-xs-12">
                                                    	<input class="form-control" type="email" value="manoj.kosare@globussoft.com" disabled>
                                                    </div>
                                                </div>
                                                <div class="form-group">
                                                	<label for="subject">Subject</label>
                                                    <div class="input-group col-xs-12">
                                                    	<input class="form-control" type="text" id="subject">
                                                    </div>
                                                </div>
                                                <div class="form-group">
                                                	<label for="message">Message</label>
                                                    <div class="input-group col-xs-12">
                                                    	<textarea class="form-control" id="message">
                                                        </textarea>
                                                    </div>
                                                </div>
                                                
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="modal-footer light-bg clear-both no-border-top">
                            	
                                <div class="text-center">
                                	<button class="btn btn-blue">Send</button>
                                	<button data-dismiss="modal" class="btn btn-gray font-Russo-One">Cancel</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>-------Edit User------------>
      
      <!----------------------Modals-------------------------->