<div id="page-title">
    <h2>Country Details</h2>
    <p>The most complete user interface framework that can be used to create stunning admin dashboards and presentation websites.</p>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="panel addContent">
            <div class="panel-body">
                <h3 class="title-hero">Add Country</h3>
                <div class="example-box-wrapper">
                    <div class="row">
                        <div class="col-md-10 col-md-offset-1">
                            <form class="form-horizontal bordered-row" method="POST">
                                <div class="form-group">
                                    <label class="col-sm-2 control-label">Enter the Country</label>
                                    <div class="col-sm-10">
                                        <input type="text" name="name" class="form-control" id="" placeholder="" required />
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-sm-2 control-label">Status</label>
                                    <div class="col-sm-5">
                                        <select  class="js-example-responsive js-example-basic-hide-search form-control" name="location_status"> 
                                            <option value="1">
                                                Active 
                                            </option>
                                            <option value="2">
                                                Deactive 
                                            </option>
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group pull-right">
                                    <button type="submit" class="btn btn-alt btn-hover btn-primary">
                                        <span>SAVE</span> <i class="glyph-icon icon-arrow-right"></i>
                                        <div class="ripple-wrapper"></div>
                                    </button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>

        </div>
        <div class="panel editContent">
            <div class="panel-body">
                <h3 class="title-hero">Edit Country</h3>
                <div class="example-box-wrapper">
                    <div class="row">
                        <div class="col-md-10 col-md-offset-1">
                            <form class="form-horizontal bordered-row" method="POST" action="/admin/edit-location">
                                <div class="form-group">
                                    <label class="col-sm-2 control-label">Country Name</label>
                                    <div class="col-sm-10">
                                        <input type="text" class="form-control" id="editlocation" name="location"placeholder="" value="" required />
                                    </div>
                                      <div class="col-sm-10 hidden">
                                        <input type="text" class="form-control" id="locationid" name="location_id" placeholder="" value="" required />
                                    </div>
                                </div>
                                <div class="form-group pull-right">
                                    <button type="submit" name="locationbtn"  value="country" class="btn btn-alt btn-hover btn-primary">
                                        <span>UPDATE</span> <i class="glyph-icon icon-refresh"></i>
                                        <div class="ripple-wrapper"></div>
                                    </button>
                                    <button class="btn btn-alt btn-hover btn-info">
                                        <span>CANCEL</span> <i class="glyph-icon icon-trash"></i>
                                        <div class="ripple-wrapper"></div>
                                    </button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<div class="row">
    <div class="col-md-12">
        <div class="panel">
            <div class="panel-body">
                <h3 class="title-hero">Country details</h3>
                <div class="example-box-wrapper">
                    <table id="datatable-responsive" class="table table-striped table-bordered responsive no-wrap" cellspacing="0" width="100%">
                        <thead>
                            <tr>
                                <th>Sl. No.</th>
                                <th >Country Name</th>
                                <th >Status</th>
                                <th >Action</th>
                                <th >Edit</th>
                            </tr>
                        </thead>
                        <tfoot>
                            <tr>
                                <th> Country Name </th>
                                <th> Status </th>
                                <th> Action </th>
                                <th> View </th>
                            </tr>
                        </tfoot>
                        <tbody>

                            <?php
                            $i = 1;
                            foreach ($this->countriesdetails as $value) {
                                ?>

                                <tr id="<?php echo $value['location_id']; ?>">
                                    <td><strong><?php echo $i; ?></strong></td>
                                    <td><strong><?php echo $value['name']; ?></strong></td>
                                    <?php if ($value['location_status'] == 1): ?>
                                        <td id="activelocation_<?php echo $value['location_id']; ?>" class="locationactive">Active</td>
                                        <td class="center"><a style="cursor:pointer"  id="<?php if (isset($value['location_id'])): echo "location_" . $value['location_id'];
                                endif;
                                        ?>" class="locationdeactive">
                                                <span id="activeclass_<?php echo $value['location_id']; ?>" class="bs-label label-danger">Deactivate</span></a></td>
    <?php else: ?>
                                        <td id="activelocation_<?php echo $value['location_id']; ?>" class="locationdeactive">Suspended</td>
                                        <td class="center" ><a style="cursor:pointer" id="<?php if (isset($value['location_id'])): echo "location_" . $value['location_id'];
        endif;
        ?>" class="locationactive">
                                                <span id="activeclass_<?php echo $value['location_id']; ?>"  class="bs-label label-success">Activate</span></a></td>
    <?php endif; ?> 
                                    <td class="center">
                                        <a  href="javascript:;" class="btn btn-default locationedit" id="showEdit_<?php echo $value['location_id']; ?>"><i class="glyph-icon icon-linecons-eye"></i></a>
                                        <!--<span  id="<?php// echo "coutrydelete_" . $value['location_id']; ?>" class="btn btn-default countrydelete" ><i class="glyph-icon icon-linecons-trash"></i></span>-->
                                    </td>
                                </tr>



                                <?php
                                $i++;
                            }
                            ?>


                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

