<div id="page-title">
    <h2>Hotel Cuisine Details</h2>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="panel addContent">
            <div class="panel-body">
                <h3 class="title-hero">Add Cuisine</h3>
                <div class="example-box-wrapper">
                    <div class="row">
                        <div class="col-md-10 col-md-offset-1">
                            <form class="form-horizontal bordered-row" method="POST">
                                <div class="form-group">
                                    <label class="col-sm-2 control-label">Choose the Hotel</label>
                                    <div class="col-sm-10">
                                        <select class="js-example-responsive form-control" name="hotels" style="width:100%;" id="test">
                                            <option disabled selected>Select Hotel</option>
                                            <?php foreach ($this->hotellist as $value) { ?>
                                                <option value="<?php echo $value['id'] ?>">
                                                    <?php echo $value['hotel_name'] ?>
                                                </option>
                                            <?php } ?>
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-sm-2 control-label">Enter the Cuisine</label>
                                    <div class="col-sm-10">
                                        <input type="text" class="form-control" name="cuisinename"  disabled id="demo" placeholder="" required />
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-sm-2 control-label">Status</label>
                                    <div class="col-sm-5">
                                        <select  class="js-example-responsive js-example-basic-hide-search form-control" name="cuisine_status"> 
                                            <option value="1">
                                                Active 
                                            </option>
                                            <option value="2">
                                                Inactive 
                                            </option>
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group pull-right">
                                    <button  type="submit" class="btn btn-alt btn-hover btn-primary">
                                        <span>SAVE</span> <i class="glyph-icon icon-arrow-right"></i>
                                        <div class="ripple-wrapper"></div>
                                    </button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>

        </div>
        <div class="panel editContent">
            <div class="panel-body">
                <h3 class="title-hero">Edit Cuisine</h3>
                <div class="example-box-wrapper">
                    <div class="row">
                        <div class="col-md-10 col-md-offset-1">
                            <form class="form-horizontal bordered-row" method="POST" action="/admin/edit-cuisines">
                                <div class="form-group">
                                    <label class="col-sm-2 control-label">Cuisine Name</label>
                                    <div class="col-sm-10">
                                        <input type="text" class="form-control" id="editcuisine"  name="cuisine" placeholder="" value="" required />
                                    </div>
                                    <div class="col-sm-10 hidden">
                                        <input type="text" class="form-control" id="cuisineid"  name="cuisine_id" placeholder="" value="" required />
                                    </div>
                                </div>
                                <div class="form-group pull-right">
                                    <button   type="submit" name="cuisinebtn"  value="cuisine" class="btn btn-alt btn-hover btn-primary">
                                        <span>UPDATE</span> <i class="glyph-icon icon-refresh"></i>
                                        <div class="ripple-wrapper"></div>
                                    </button>
                                    <button class="btn btn-alt btn-hover btn-info">
                                        <span>CANCEL</span> <i class="glyph-icon icon-trash"></i>
                                        <div class="ripple-wrapper"></div>
                                    </button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<div class="row">
    <div class="col-md-12">
        <div class="panel">
            <div class="panel-body">
                <h3 class="title-hero">Hotel Cuisine Details</h3>
                <div class="example-box-wrapper">
                    <table class="table table-striped table-bordered responsive no-wrap datatable-responsive" cellspacing="0" width="100%">
                        <thead>
                            <tr>
                                <th>S. No.</th>
                                <th>Hotel Name</th>
                                <th>Cuisine Name</th>
                                <th>Status</th>
                                <th>Action</th>
                                <th>Edit</th>
                            </tr>
                        </thead>
                        <tfoot>
                            <tr>
                                <th>S. No.</th>
                                <th>Hotel Name</th>
                                <th>Cuisine Name</th>
                                <th>Status</th>
                                <th>Action</th>
                                <th>Edit</th>
                            </tr>
                        </tfoot>
                        <tbody>
                            <?php if (empty($this->cuisinesdetails)) { ?>
                            <br><br><br><br><br><br><br><br>
                            <center>
                                <h3> No Result Found For Cuisine Details</h3> </center>
                            <br><br><br><br><br><br><br><br>
                            <?php
                        } else {
                            $i = 1;
                            foreach ($this->cuisinesdetails as $value) {
                                ?>

                                <tr id="<?php echo $value['cuisine_id']; ?>">
                                    <td><strong><?php echo $i; ?></strong></td>
                                    <td><strong><?php echo $value['hotel_name']; ?></strong></td>

                                    <td><strong><?php echo $value['Cuisine_name']; ?></strong></td>

                                    <?php if ($value['cuisine_status'] == 1): ?>
                                        <td id="activecuisine_<?php echo $value['cuisine_id']; ?>" class="cuisineactive">Active</td>
                                        <td class="center"><a style="cursor:pointer" id="<?php
                                            if (isset($value['cuisine_id'])): echo "cuisine_" . $value['cuisine_id'];
                                            endif;
                                            ?>" class="cuisinedeactive">
                                                <span id="activeclass_<?php echo $value['cuisine_id']; ?>" class="bs-label label-danger">Inactive </span></a></td>
                                    <?php else: ?>
                                        <td id="activecuisine_<?php echo $value['cuisine_id']; ?>" class="cuisinedeactive">Suspended</td>
                                        <td class="center" ><a  style="cursor:pointer" id="<?php
                                            if (isset($value['cuisine_id'])): echo "cuisine_" . $value['cuisine_id'];
                                            endif;
                                            ?>" class="cuisineactive">
                                                <span id="activeclass_<?php echo $value['cuisine_id']; ?>"  class="bs-label label-success">Activate</span></a></td>
                                    <?php endif; ?> 
                                    <td class="center">
                                        <a  href="javascript:;" class="btn btn-default cuisineedit" id="showEdit_<?php echo $value['cuisine_id']; ?>"><i class="glyph-icon icon-linecons-pencil"></i></a>
                                        <span  id="<?php echo "cuisinedelete_" . $value['cuisine_id']; ?>"  class="btn btn-default cuisinedelete"><i class="glyph-icon icon-linecons-trash"></i></span>
                                    </td>
                                </tr>



                                <?php
                                $i++;
                            }
                        }
                        ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>


<style>
    #test .select2-search.select2-search--dropdown {
        display: none;
    }
</style>
