
<div class="content-wrapper" style="min-height: 689px;">
    <?php if(isset($this->off)){ ?>
 <div class="opennotificationGreen" style="color:#4cae4c;">
<span class="notification_msgGreen">
    <h3 style="padding-left:299px;">Offer Details Edited successfully</h3></span>

</div>
    <?php } ?>
    <section class="content">
        <div class="row">
            <form method="POST" id="offerseditform" enctype="multipart/form-data">
            <div class="col-md-12">
                
                            	<div class="panel panel-black">
                                	<div class="panel-heading paddingLR-md">
                                    	<h4><span class="m-right-sm"><i class="fa fa-edit"></i></span>Offer Details</h4>
                                    </div>
                                    <div class="panel-body padding-sm">
                                    	<div class="row">
                                        	<div class="col-sm-6">
                                             
                                                <div class="form-group">
                                                    <input class="form-control hidden" type="text" name="offerid" id="offerid" value="<?php if(isset($this->editofferdetails)){ echo $this->editofferdetails['offer_id'];}?>">
                                                	<label for="offercontest">Offer contest</label>
                                                    <div class="input-group col-xs-12">
                                                        <input class="form-control" type="text" id="offercontest" value="<?php if(isset($this->editofferdetails)){ echo $this->editofferdetails['contest_name'];}?>" disabled="">
                                                    </div>
                                                </div>
                                            	<div class="form-group">
                                                    <label for="offerName">Offer Name</label>
                                                    <div class="input-group col-xs-12">
                                                    	<input class="form-control" type="text" name="offeridentity" id="offerName" value="<?php if(isset($this->editofferdetails)){ echo $this->editofferdetails['o_name'];}?>">
                                                    </div>
                                                </div>
                                                <div class="form-group">
                                                        <label>Status</label>
                                                           <div class="input-group col-xs-12">
                                                               <select id="status" name = "status" class="form-control">
                                                                    <option value="1" <?php if (isset($this->editofferdetails['o_status']) && $this->editofferdetails['o_status'] === '1'){ echo 'selected'; } ?>>active</option>
                                                                     <option value="0" <?php if (isset($this->editofferdetails['o_status']) && $this->editofferdetails['o_status'] === '0'){ echo 'selected'; } ?>>deactive</option>
                                                         </select>
                                                        </div>
                                                          </div>
                                                <div class="form-group">
                                                	<label>Valid From</label>
                                                    <div class="input-group col-xs-12">
                                                    	<span class="input-group-addon">
                                                        	<i class="fa fa-calendar"></i>
                                                        </span>
                                                        <input id="validFrom" name="validFrom" data-provide="datepicker" value="<?php if(isset($this->editofferdetails)){ echo $this->editofferdetails['valid_from'];}?>" class="date">
                                                    </div>
                                                </div>
                                                <div class="form-group">
                                                	<label>Valid Upto</label>
                                                    <div class="input-group col-xs-12">
                                                    	<span class="input-group-addon">
                                                        	<i class="fa fa-calendar"></i>
                                                        </span>
                                                        <input id="validUpto" name="validUpto" data-provide="datepicker" value="<?php if(isset($this->editofferdetails)){ echo $this->editofferdetails['valid_upto'];}?>" class="date" >
                                                    </div>
                                                </div>
                                                <div class="form-group">
                                                	<label for="amount">Amount</label>
                                                    <div class="input-group col-xs-12">
                                                    	<input id="amountoffer" type="text" name="amountoffer" class="form-control" value = "<?php if(isset($this->editofferdetails)){ echo $this->editofferdetails['amount'];}?>">
                                                    </div>
                                                </div>
                                                <div class="form-group">
                                                	<label for="fppval">FPP</label>
                                                    <div class="input-group col-xs-12">
                                                    	<input id="fppval" type="text" name= "fppval" class="form-control" value = "<?php if(isset($this->editofferdetails)){ echo $this->editofferdetails['fpp_value'];}?>">
                                                    </div>
                                                </div>
                                                    </div>
                                             <div class="col-sm-6">
                                          <div class="form-group">
                                                	<div class="offer-img-container">
                                                    	<img src="<?php if(isset($this->editofferdetails)){ echo $this->editofferdetails['img_url'];}?>" name="imageurl" type ="image" class="img-responsive offersimage">
                                                    </div>
                                                    <div class="input-group">
                                                    	<input type="file" id="imageuplaod" name="myfile">
                                                    </div>
                                               <?php if(isset($this->error)){ ?>
                                              <span id="errmsg" style="color:#D40000;"><?php echo $this->error ;?></span>
                                              <?php } ?>
                                                      </div>     
                                                <div class="form-group">
                                                	<label for="oDescription">Offer Description</label>
                                                    <div class="input-group col-xs-12">
                                                    	<textarea id="oDescription"name="oDescription" class="form-control"><?php if(isset($this->editofferdetails)){ echo $this->editofferdetails['o_description'];}?></textarea>
                                                    </div>
                                                </div>   
                                            </div>    
                                            </div>
                                        </div>
                                    </div>
                                </div>
                      <div class="text-center">
                    <button class="btn btn-blue " type="submit" id="saveeditoffer">Save Changes</button>
                    <button data-dismiss="modal" class="btn btn-gray font-Russo-One">Cancel</button>
                </div>
                   </form>
            </div>
        </div>
<script>
    
        setTimeout(function() {
           $('.opennotificationGreen').fadeOut("slow");
            $('div').remove(".notification_msgGreen");
            }, 10000); 
        /*
   * dev:priyankav varanasi
   * date:27/5/2015
   * desc: to save the edited offers details
   */ 
                   $(function() {
   $.validator.addMethod("regex", function(value, element, regexpr) {          
     return regexpr.test(value);
   });
 
   $('#offerseditform').validate({
                onkeyup: function(element) {
                    $(element).valid();
                },     
                rules: {
                   offeridentity: {
                        required:true
                                   },
                    status: {
                        required:true
                                   },
                    validFrom:{
                        //required:true
                        
                    },
                    validUpto:{
                        //required:true
                        
                    },
                   amountoffer: {
                        required: true,
                        number :true
                     
                    },
                    fppval: {
                        required: true,
                        number:true
                       
                    },
                    oDescription: {
                        required: true
                    }
                   
                },
                messages: {
               
                    offeridentity:{
                        required:"Please enter your offer name"
                    },
                     status:{
                        required:"Please enter offer status"
                    },
                    validFrom:{
                        required:"Please enter offer start date"
                     },
                    validUpto: {
                        required: "please enter offer end date"
                    },
                    amountoffer: {
                        required: "please enter amount"
                        
                     },
                    fppval: {
                        required: "please enter fpp value"
                        
                    },
                    oDescription: {
                        required: "please enter offer description"
                       
                    }
                   
                }

    });
    });
    </script>
                    <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
          <script>
              
  $(function() {
    $( ".date" ).datepicker();
  });

  </script>
