<div class="content-wrapper" style="min-height: 689px;">
    <?php if(isset($this->succ)){ ?>
 <div class="opennotificationGreen" style="color:#4cae4c;">
<span class="notification_msgGreen">
    <h3 style="padding-left:299px;">ticket Details Edited successfully</h3></span>

</div>
    <?php } ?>
    <section class="content">
        <div class="row">
            <div class="col-md-12">
                <form method="POST" id="ticketeditform" name="ticketeditingform">
                <div class="panel panel-black">
                    <div class="panel-heading paddingLR-md">
                        <h4><span class="m-right-sm"><i class="fa fa-edit"></i></span>Manage Ticket</h4>
                    </div>
                    <div class="panel-body padding-sm">
                        <div class="row">
                            
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <input class="form-control hidden" type="text" name="ticketid" id="ticketid" value="<?php if(isset($this->ticketdetails)){ echo $this->ticketdetails['ticket_id'];}?>" >
                                        <label for="tContest">Ticket Contest</label>
                                        <div class="input-group col-xs-12">
                                            <input class="form-control" type="text" name="tContest" id="tContest" value="<?php if(isset($this->ticketdetails)){ echo $this->ticketdetails['contest_name'];}?>" disabled>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label>Code</label>
                                        <div class="input-group col-xs-12">
                                            <input type="text" class="form-control" name="tcode" id="tcode" value="<?php if(isset($this->ticketdetails)){ echo $this->ticketdetails['ticket_code'];}?>" disabled>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label>ticket Name</label>
                                        <div class="input-group col-xs-12">
                                            <input type="text" class="form-control" name="ticketname" id="ticketname" value="<?php if(isset($this->ticketdetails)){ echo $this->ticketdetails['ticket_name'];}?>" >
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label>Selling</label>
                                        <div class="input-group col-xs-12">
                                            <select id="selling" name="selling" value="<?php if(isset($this->ticketdetails)){ echo $this->ticketdetails['selling_status'];}?>" class="form-control">
                                                <option value="1" <?php if (isset($this->ticketdetails['selling_status']) && $this->ticketdetails['selling_status'] === '1'){ echo 'selected'; } ?>>Yes</option>
                                                <option value="0" <?php if (isset($this->ticketdetails['selling_status']) && $this->ticketdetails['selling_status'] === '0'){ echo 'selected'; } ?> >No</option>
                                            </select>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label for="status">Status</label>
                                        <div class="input-group col-xs-12">
                                            <select id="status"  class="form-control" name="status">
                                                <option value="1" <?php if (isset($this->ticketdetails['t_status']) && $this->ticketdetails['t_status'] === '1'){ echo 'selected'; } ?> >Active</option>
                                                <option value ="0" <?php if (isset($this->ticketdetails['t_status']) && $this->ticketdetails['t_status'] ==='0'){echo 'selected'; }?> >Deactive</option>
                                            </select>
                                        </div>
                                    </div>

                                </div>
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <label>Valid From</label>
                                        <div class="input-group col-xs-12">
                                            <span class="input-group-addon">
                                                <i class="fa fa-calendar"></i>
                                            </span>
                                            <input id="validfrom" name="validFrom" data-provide="datepicker" value="<?php if(isset($this->ticketdetails)){ echo $this->ticketdetails['valid_from'];}?>" class="date">
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label>Valid Upto</label>
                                        <div class="input-group col-xs-12">
                                            <span class="input-group-addon">
                                                <i class="fa fa-calendar"></i>
                                            </span>
                                            <input id="validupto" name="validUpto" value="<?php if(isset($this->ticketdetails)){ echo $this->ticketdetails['valid_upto'];}?>" data-provide="datepicker" class="date" >
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label>FPP Amount</label>
                                        <div class="input-group col-xs-12">
                                            <input  id="fppamount" name="fppamount" class="form-control" type="text" value="<?php if(isset($this->ticketdetails)){ echo $this->ticketdetails['fpp_value'];}?>">
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label for="tDescription">Ticket Description</label>
                                        <div class="input-group col-xs-12">
                                            <textarea id="tDescription" name="tDescription"  class="form-control"  ><?php if(isset($this->ticketdetails)){ echo $this->ticketdetails['description'];}?></textarea>
                                        </div>
                                    </div>
                                </div>
                           
                        </div>
                    </div>
                </div>

                <div class="text-center">
                    <button class="btn btn-blue " type="submit" id="saveeditedticket">Save Changes</button>
                    <a href="<?php $this->baseUrl(); ?>/admin/ticket-details" data-dismiss="modal" class="btn btn-gray font-Russo-One">Cancel</button></a>
                </div>
                 </form>
            </div>
        </div>
    </section>
</div>
    

         
   <script>
       //dev:priyanka varanasi
       //date:11/7/2015
    setTimeout(function() {
           $('.opennotificationGreen').fadeOut("slow");
            $('div').remove(".notification_msgGreen");
            }, 10000); 

            
            /*
             * dev:priyankav varanasi
             * date:25/5/2015
             * desc: tosave the edited ticket detailsg
             */
            
               $(function() {
   $.validator.addMethod("regex", function(value, element, regexpr) {          
     return regexpr.test(value);
   });
            $('#ticketeditingform').validate({
                onkeyup: function(element) {
                    $(element).valid();
                },
                rules: {
                    ticketname: {
                        required: true
                    },

                    fppamount: {
                        required: true,
                        number: true

                    },
                    tDescription: {
                        required: true
                    }

                },
                messages: {
                    ticketname: {
                        required: "Please enter your ticket name"
                    },

                    fppamount: {
                        required: "please enter amount"
                        

                    },
                    tDescription: {
                        required: "please enter ticket description"
                    }


                }
            });
               });
               
   </script>
              <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
   <script>
  $(function() {
    $( ".date" ).datepicker();
  });

  </script> 
