<div id="page-title">
    <h2>Grocery Category Details</h2>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="panel addContent">
            <div class="panel-body">
                <h3 class="title-hero">Add Category</h3>
                <div class="example-box-wrapper">
                    <div class="row">
                        <div class="col-md-10 col-md-offset-1">
                            <form class="form-horizontal bordered-row" method="POST">                        
                                <div class="form-group">
                                    <label class="col-sm-2 control-label">Enter the Category</label>
                                    <div class="col-sm-10">
                                        <input type="text" class="form-control" name="categoryname"  placeholder="" required />
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-sm-2 control-label">Enter the Description</label>
                                    <div class="col-sm-10">
                                        <input type="text" class="form-control" name="cat_desc"  id="cat_desc" placeholder=""  />
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-sm-2 control-label">Status</label>
                                    <div class="col-sm-5">
                                        <select  class="js-example-responsive js-example-basic-hide-search form-control" name="cat_status"> 
                                            <option value="1">
                                                Active 
                                            </option>
                                            <option value="2">
                                                Inactive 
                                            </option>
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group pull-right">
                                    <button  type="submit" class="btn btn-alt btn-hover btn-primary">
                                        <span>SAVE</span> <i class="glyph-icon icon-arrow-right"></i>
                                        <div class="ripple-wrapper"></div>
                                    </button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="panel editContent">
            <div class="panel-body">
                <h3 class="title-hero">Edit Category</h3>
                <div class="example-box-wrapper">
                    <div class="row">
                        <div class="col-md-10 col-md-offset-1">
                            <form class="form-horizontal bordered-row" method="POST" action="/admin/edit-grocery-category">
                                <div class="form-group">
                                    <label class="col-sm-2 control-label">Category Name</label>
                                    <div class="col-sm-10">
                                        <input type="text" class="form-control" id="editcategory"  name="category" placeholder="" value="" required />
                                    </div>
                                    <div class="col-sm-10 hidden">
                                        <input type="text" class="form-control" id="categoryid"  name="category_id" placeholder="" value="" required />
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-sm-2 control-label">Category Description</label>
                                    <div class="col-sm-10">
                                        <input type="text" class="form-control" id="editcategorydesc"  name="catdesc" placeholder="" value=""  />
                                    </div>
                                    <div class="col-sm-10 hidden">
                                        <input type="text" class="form-control" id="categorydesc"  name="cat_desc" placeholder="" value=""  />
                                    </div>
                                </div>
                                <div class="form-group pull-right">
                                    <button  type="submit" name="categorybtn"  value="category" class="btn btn-alt btn-hover btn-primary">
                                        <span>UPDATE</span> <i class="glyph-icon icon-refresh"></i>
                                        <div class="ripple-wrapper"></div>
                                    </button>
                                    <button class="btn btn-alt btn-hover btn-info">
                                        <span>CANCEL</span> <i class="glyph-icon icon-trash"></i>
                                        <div class="ripple-wrapper"></div>
                                    </button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>



<div class="row">
    <div class="col-md-12">
        <div class="panel">
            <div class="panel-body">
                <h3 class="title-hero">Grocery Category Details</h3>
                <div class="example-box-wrapper">
                    <table class="table table-striped table-bordered responsive no-wrap datatable-responsive" cellspacing="0" width="100%">
                        <thead>
                            <tr>
                                <th>S. No.</th>                            
                                <th>Category Name</th>
                                <th>Category Description</th>
                                <th>Status</th>
                                <th>Action</th>
                                <th>Edit/Delete</th>
                            </tr>
                        </thead>
                        <tfoot>
                            <tr>
                                <th>S. No.</th>                            
                                <th>Category Name</th>
                                <th>Category Description</th>
                                <th>Status</th>
                                <th>Action</th>
                                <th>Edit/Delete</th>
                            </tr>
                        </tfoot>
                        <tbody>

                            <?php if (empty($this->categorydetails)) { ?>
                            <br><br><br><br><br><br><br><br>
                            <center>
                                <h3> No Result Found For Grocery Category Details</h3> </center>
                            <br><br><br><br><br><br><br><br>
                            <?php
                        } else {
                            $i = 1;
                            foreach ($this->categorydetails as $value) {
                                ?>

                                <tr id="<?php echo $value['category_id']; ?>">
                                    <td><strong><?php echo $i; ?></strong></td>                                 
                                    <td><strong><?php echo $value['cat_name']; ?></strong></td>
                                    <td><strong><?php echo $value['cat_desc']; ?></strong></td>

                                    <?php if ($value['cat_status'] == 1): ?>
                                        <td id="activecategory_<?php echo $value['category_id']; ?>" class="grocerycategoryactive">Active</td>
                                        <td class="center"><a style="cursor:pointer" id="<?php
                                            if (isset($value['category_id'])): echo "category_" . $value['category_id'];
                                            endif;
                                            ?>" class="grocerycategorydeactive">
                                                <span id="activeclass_<?php echo $value['category_id']; ?>" class="bs-label label-danger">Deactivate</span></a></td>
                                    <?php else: ?>
                                        <td id="activecategory_<?php echo $value['category_id']; ?>" class="grocerycategorydeactive">Suspended</td>
                                        <td class="center" ><a  style="cursor:pointer" id="<?php
                                            if (isset($value['category_id'])): echo "category_" . $value['category_id'];
                                            endif;
                                            ?>" class="grocerycategoryactive">
                                                <span id="activeclass_<?php echo $value['category_id']; ?>"  class="bs-label label-success">Activate</span></a></td>
                                    <?php endif; ?> 
                                    <td class="center">
                                        <a  href="javascript:;" class="btn btn-default grocerycategoryedit" id="showEdit_<?php echo $value['category_id']; ?>"><i class="glyph-icon icon-linecons-pencil"></i></a>
                                        <span  id="<?php echo "categorydelete_" . $value['category_id']; ?>"  class="btn btn-default grocerycategorydelete"><i class="glyph-icon icon-linecons-trash"></i></span>
                                    </td>
                                </tr>
                                <?php
                                $i++;
                            }
                        }
                        ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>


<style>
    #test .select2-search.select2-search--dropdown {
        display: none;
    }
</style>
