<div id="page-title">
    <h2>Location Details</h2>   
</div>
<div class="row">
    <div class="col-md-12">
        <div class="panel addContent">
            <div class="panel-body">
                <h3 class="title-hero">Add City</h3>
                <div class="example-box-wrapper">
                    <div class="row">
                        <div class="col-md-10 col-md-offset-1">
                            <form class="form-horizontal bordered-row" method="POST">
                                <div class="form-group">
                                    <label class="col-sm-2 control-label">Choose the Country</label>
                                    <div class="col-sm-10">
                                        <select class="js-example-responsive form-control"  name="country" id="selectcountry"style="width:100%;">
                                            <option disabled selected>Select Country</option>
                                            <?php foreach ($this->countrieslist as $value) { ?>
                                                <option value="<?php echo $value['location_id'] ?>">
                                                    <?php echo $value['name'] ?>
                                                </option>
                                            <?php } ?>
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group ">
                                    <label class="col-sm-2 control-label">Choose the State</label>
                                    <div class="col-sm-10">
                                        <select class="js-example-responsive form-control"  name="state" id="selectstate" disabled="" style="width:100%;">
                                            <option disabled selected>Select State</option>

                                        </select>
                                    </div>
                                </div>

                                <div class="form-group ">
                                    <label class="col-sm-2 control-label">Choose the city</label>
                                    <div class="col-sm-10">
                                        <select class="js-example-responsive form-control"  name="city" id="selectcity" disabled="" style="width:100%;">
                                            <option disabled selected>Select city</option>

                                        </select>
                                    </div>
                                </div>
                                <div class="form-group " >
                                    <label class="col-sm-2 control-label">Enter the Location</label>
                                    <div class="col-sm-10">
                                        <input type="text" class="form-control" id="demo" name="locationname" disabled=""  placeholder="" required />
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-sm-2 control-label">Status</label>
                                    <div class="col-sm-5">
                                        <select  class="js-example-responsive js-example-basic-hide-search form-control" name="location_status"> 
                                            <option value="1">
                                                Active 
                                            </option>
                                            <option value="2">
                                                Deactivate 
                                            </option>
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group pull-right">
                                    <button class="btn btn-alt btn-hover btn-primary">
                                        <span>SAVE</span> <i class="glyph-icon icon-arrow-right"></i>
                                        <div class="ripple-wrapper"></div>
                                    </button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>

        </div>
        <div class="panel editContent">
            <div class="panel-body">
                <h3 class="title-hero">Edit Location</h3>
                <div class="example-box-wrapper">
                    <div class="row">
                        <div class="col-md-10 col-md-offset-1">
                            <form class="form-horizontal bordered-row" method="POST" action="/admin/edit-location">
                                <div class="form-group">
                                    <label class="col-sm-2 control-label">Location Name</label>
                                    <div class="col-sm-10">
                                        <input type="text" class="form-control" id="editlocation"  name="location" placeholder="" value="" required />
                                    </div>
                                    <div class="col-sm-10 hidden">
                                        <input type="text" class="form-control" id="locationid"  name="location_id" placeholder="" value="" required />
                                    </div>
                                </div>
                                <div class="form-group pull-right">
                                    <button  type="submit" name="locationbtn"  value="location" class="btn btn-alt btn-hover btn-primary">
                                        <span>UPDATE</span> <i class="glyph-icon icon-refresh"></i>
                                        <div class="ripple-wrapper"></div>
                                    </button>
                                    <button class="btn btn-alt btn-hover btn-info">
                                        <span>CANCEL</span> <i class="glyph-icon icon-trash"></i>
                                        <div class="ripple-wrapper"></div>
                                    </button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>



<div class="row">
    <div class="col-md-12">
        <div class="panel">
            <div class="panel-body">
                <h3 class="title-hero">Location Details</h3>
                <div class="example-box-wrapper">
                    <table class="table table-striped table-bordered responsive no-wrap datatable-responsive" cellspacing="0" width="100%">
                        <thead>
                            <tr>
                                <th>S.No.</th>
                                <th >Location Name</th>
                                <th >Status</th>
                                <th >Action</th>
                                <th >Edit</th>
                            </tr>
                        </thead>
                        <tfoot>
                            <tr>
                                <th>S.No.</th>
                                <th> Location Name </th>
                                <th> Status </th>
                                <th> Action </th>
                                <th> Edit </th>
                            </tr>
                        </tfoot>
                        <tbody>
                            <?php if (empty($this->locationdetails)) { ?>
                            <br><br><br><br><br><br><br><br>
                            <center>
                                <h3> No Result Found For Location Details</h3> </center>
                            <br><br><br><br><br><br><br><br>
                            <?php
                        } else {
                            $i = 1;
                            foreach ($this->locationdetails as $value) {
                                ?>

                                <tr  id="<?php echo $value['location_id']; ?>">
                                    <td><strong><?php echo $i; ?></strong></td>
                                    <td><strong><?php echo $value['name']; ?></strong></td>

                                    <?php if ($value['location_status'] == 1): ?>
                                        <td id="activelocation_<?php echo $value['location_id']; ?>" class="locationactive">Active</td>
                                        <td class="center"><a  style="cursor:pointer" id="<?php
                                            if (isset($value['location_id'])): echo "location_" . $value['location_id'];
                                            endif;
                                            ?>" class="locationdeactive">
                                                <span id="activeclass_<?php echo $value['location_id']; ?>" class="bs-label label-danger">Deactivate</span></a></td>
        <?php else: ?>
                                        <td id="activelocation_<?php echo $value['location_id']; ?>" class="locationdeactive">Suspended</td>
                                        <td class="center" ><a style="cursor:pointer" id="<?php
                                                               if (isset($value['location_id'])): echo "location_" . $value['location_id'];
                                                               endif;
                                                               ?>" class="locationactive">
                                                <span id="activeclass_<?php echo $value['location_id']; ?>"  class="bs-label label-success">Activate</span></a></td>
        <?php endif; ?> 
                                    <td class="center">
                                        <a  href="javascript:;" class="btn btn-default locationedit" id="showEdit_<?php echo $value['location_id']; ?>"><i class="glyph-icon icon-linecons-pencil"></i></a>
                                        <span  id="<?php echo "locationdelete_" . $value['location_id']; ?>" class="btn btn-default locationdelete" ><i class="glyph-icon icon-linecons-trash"></i></span>
                                    </td>
                                </tr>


                                <?php
                                $i++;
                            }
                        }
                        ?>


                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>








