      <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
          <h1>
            Store
            <small>for your next cool web APP</small>
          </h1>
          <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-futbol-o"></i> Home</a></li>
            <li>Store</li>
            <li class="active">New Ticket</li>
          </ol>
        </section>

        <!-- Main content -->
        <section class="content">
          <!-- Info boxes -->
          <div class="row">
          	<div class="col-md-12 col-sm-12 no-p-left no-p-right">
            	<div class="panel panel-black no-radius">
                	<div class="panel-heading paddingLR-md paddingTB-sm no-radius">
                    	<h3 class="font-Russo-One no-margin">New Ticket</h3>
                    </div>
                </div>
            </div>
          </div>
          
          <div class="row">
          	<div class="col-md-12">
            	<div class="panel panel-gray">
                	<div class="panel-heading paddingLR-md paddingTB-xs">
                    	<h4 class="font-Libre-Baskerville inline-block">Manage Ticket</h4>
                    </div>
                    <div class="panel-body padding-md">
                    	<div class="row">
                        	<div class="col-md-8 col-sm-8 col-sm-offset-2 col-xs-offset-0">
                                    <form method="POST" id="ticketsformpost" name="ticketsformpost">
                            	<div class="form-group">
                                                	<label for="tContest">Ticket Contest</label>
                                                    <div class="input-group col-xs-12">
                                                    	  <select name="contest" class="form-control m-b">
                                                              <option value="">select</option>
                                                                                <?php if(isset($this->contests)){ foreach ($this->contests as $contest){ ?>
                                                                                 <option value="<?php echo $contest['contest_id'].'@'.$contest['contest_name']; ?>"><?php echo $contest['contest_name']; ?></option>
                                                                                 <?php }} ?>
                                                                             </select>  
                                                    </div>
                                                </div>
                                          <div class="form-group">
                                                	<label>Ticket Name</label>
                                                    <div class="input-group col-xs-12">
                                                    	<input class="form-control" type="text" name="ticketname" value="">
                                                    </div>
                                                </div>
                                                <div class="form-group">
                                                	<label>Code</label>
                                                    <div class="input-group col-xs-12">
                                                    	<input type="text" id="ticket_code" name="ticket_code" class="form-control">
                                                        <span class="input-group-btn">
                                                        	<a class="btn btn-blue"  onclick = "generatesecuritycode(this)">Generate Code</a>
                                                        </span>
                                                    </div>
                                                </div>
                                                <div class="form-group">
                                                	<label>Valid From</label>
                                                    <div class="input-group col-xs-12">
                                                    	<span class="input-group-addon">
                                                        	<i class="fa fa-calendar"></i>
                                                        </span>
                                                        <input id="validFrom"name="validFrom" data-provide="datepicker" class="date">
                                                    </div>
                                                </div>
                                                <div class="form-group">
                                                	<label>Valid Upto</label>
                                                    <div class="input-group col-xs-12">
                                                    	<span class="input-group-addon">
                                                        	<i class="fa fa-calendar"></i>
                                                        </span>
                                                        <input id="validUpto" name="validUpto" data-provide="datepicker" class="date" >
                                                    </div>
                                                </div>
                                                <div class="form-group">
                                                	<label>FPP Amount</label>
                                                    <div class="input-group col-xs-12">
                                                    	<input class="form-control" type="text" name="fpp" value="">
                                                    </div>
                                                </div>
                                                <div class="form-group">
                                                	<label>Selling</label>
                                                    <div class="input-group col-xs-12">
                                                    	<select name="selling" class="form-control">
                                                        	<option value="1">Yes</option>
                                                            <option vlaue="0">No</option>
                                                        </select>
                                                    </div>
                                                </div>
                                        <div class="form-group">
                                                	<button class="btn btn-blue paddingLR-md">Save Changes</button>
                                                </div>
                                    </form>
                            </div>
                        </div>
                    </div>
                </div>
                
                
                
            </div>
          </div>
          
          
         
        </section><!-- /.content -->
      </div>

     
      <script>
            /*
     * dev: priyanka varanasi
     * desc: generate random code for ticket code
     * date:25/5/2015
     */
  function generatesecuritycode()
{
    var text = "";
    var possible = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";

    for( var i=0; i < 5; i++ )
        text += possible.charAt(Math.floor(Math.random() * possible.length));

    document.getElementById("ticket_code").value = text;
}
          
          </script>
           <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
          <script>
              
  $(function() {
    $( ".date" ).datepicker();
  });


    
     $(document).ready(function(){
  $('#ticketsformpost').validate({
                onkeyup: function(element) {
                    $(element).valid();
                },     
                rules: {
                   ticketname: {
                        required:true
                                   },
                    validFrom:{
                        required:true
                        
                    },
                    validUpto:{
                        required:true
                        
                    },
                   fpp: {
                        required: true,
                        number :true
                     
                    },
                    contest: {
                        required: true
                       
                    },
                    ticket_code: {
                        required: true
                    }
                   
                },
                messages: {
               
                    ticketname:{
                        required:"Please enter your ticket name"
                    },
                    validFrom:{
                        required:"Please enter ticket start date"
                     },
                    validUpto: {
                        required: "please enter ticket end date"
                    },
                    fpp: {
                        required: "please enter amount"
                        
                     },
                    contest: {
                        required: "please enter desired contest"
                       
                    },
                     ticket_code: {
                         required: "please enter ticket code"
                    }
                
                  
                }
    });
   });




  </script>    