      <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
          <h1>
            Manage Offers
            <small>for your next cool web APP</small>
          </h1>
          <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-futbol-o"></i> Home</a></li>
            <li>Manage Offers</li>
            <li class="active">Offers</li>
          </ol>
        </section>

        <!-- Main content -->
        <section class="content">
          <!-- Info boxes -->
          <div class="row">
          	<div class="col-md-12 col-sm-12 no-p-left no-p-right">
            	<div class="panel panel-black no-radius">
                	<div class="panel-heading paddingLR-md paddingTB-sm no-radius">
                    	<h3 class="font-Russo-One no-margin">Offers Details</h3>
                    </div>
                </div>
            </div>
          </div>
          
          <div class="row">
          	<div class="col-md-12 col-sm-12">
            	<div class="panel panel-gray">
                	<div class="panel-heading paddingLR-md paddingTB-xs">
                    	<h4 class="font-Libre-Baskerville">Upload New Offer</h4>
                    </div>
                    <div class="panel-body padding-md">
                    	<div class="row">
                        	<div class="col-md-8 col-sm-8 col-sm-offset-2 col-xs-12">
                                    <form method="POST" name="offersform" id="offersform" enctype="multipart/form-data">
                            		<div class="form-group">
                                    	<div class="input-group">
                                        	<input type="file" id="myimagefile" name="myimagefile">
                                        </div>
                                            <span id="errormsg" style="color:#D40000;"><?php if(isset( $this->error)){ echo $this->error;}?></span>
                                    </div>
                              		<div class="form-group">
                               			<label>Offer Name</label>
                                        <div class="input-group col-xs-12">
                                        	<input type="text" name="offername" class="form-control" placeholder="Offer Name">
                                        </div>
                                	</div>
                                          <div class="form-group">
                               			<label>Offer start Date</label>
                                        <div class="input-group col-xs-12">
                                            <span class="input-group-addon">
                                                        	<i class="fa fa-calendar"></i>
                                                        </span>
                                        	<input type="text"  class="date" name="offerstart" placeholder="Offer start Date">
                                        </div>
                                	</div>
                                    <div class="form-group">
                               			<label>Offer End Date</label>
                                        <div class="input-group col-xs-12">
                                            <span class="input-group-addon">
                                                        	<i class="fa fa-calendar"></i>
                                                        </span>
                                        	<input type="text" class="date" name="offerend" placeholder="Offer End Date">
                                        </div>
                                	</div>
                                          <div class="form-group">
                                                	<label for="amount">Amount</label>
                                                    <div class="input-group col-xs-12">
                                                    	<input id="amount" name="amount" class="form-control" value=''>
                                                    </div>
                                                </div>
                                         <div class="form-group">
                                                	<label for="fpp">FPP</label>
                                                    <div class="input-group col-xs-12">
                                                    	<input id="fpp" name="fppval" class="form-control" value=''>
                                                    </div>
                                                </div>
                                    <div class="form-group">
                               			<label>Offer Description</label>
                                        <div class="input-group col-xs-12">
                                        	<textarea class="form-control" name="offerdescription" placeholder="Offer Description"></textarea>
                                        </div>
                                	</div>
                                    
                            		<div class="form-group">
                                    	<label>Offer for Contest</label>
                                        <div class="input-group col-xs-12">
                                        	
                                            	<option>select</option>
                                               	  <select name="contest" class="form-control m-b">
                                                              <option value="">select</option>
                                                                                <?php if(isset($this->offercontests)){ foreach ($this->offercontests as $contest){ ?>
                                                                                 <option value="<?php echo $contest['contest_id'].'@'.$contest['contest_name']; ?>"><?php echo $contest['contest_name']; ?></option>
                                                                                 <?php }} ?>
                                                                             </select>  
                                          
                                        </div>
                                    </div>
                                    <div class="text-center">
                                    	<button class="btn btn-blue paddingLR-lg">Upload Offer</button>
                                        
                                    </div>
                                    </form>
                             </div>
                        </div>
                        
                    </div>
                </div>
                
                <div class="panel panel-gray">
                	<div class="panel-heading paddingLR-md paddingTB-xs">
                    	<h4 class="font-Libre-Baskerville inline-block">Offer Manage</h4>
                    </div>
                    <div class="panel-body">
                    	<div class="">
                        	<div class="table-responsive">
                            	<table id="offerManage" class="display table text-center" data-page-length="10" data-order="[[ 1, &quot;asc&quot; ]]" cellspacing="0" width="100%">
                                	<thead>
                                    	<tr>
                                        	<th>Sr No</th>
                                            <th>Name</th>
                                            <th>Contest ID</th>
                                            <th>contest name</th>
                                            <th>Offer start Date</th>
                                            <th>Offer End Date</th>
                                            <th>Description</th>
                                            <th>Amount</th>
                                            <th>fpp</th>
                                            <th>Status</th>
                                            <th>Action</th>
                                            <th class="">Delete/Edit</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <?php if(isset($this->offers)){ $i=0;foreach($this->offers as $value){ $i++;?>                                   	<tr>
                                           <td><?php echo $i;?></td>
                                            <td><?php echo $value['o_name'];?></td>
                                            <td><?php echo $value['contest_id'];?></td>
                                            <td><?php echo $value['contest_name'];?></td>
                                            <td><?php echo date("j F , Y", strtotime($value['valid_from']));  ?></td>
                                            <td><?php echo date("j F , Y", strtotime($value['valid_upto']));  ?></td>
                                            <td><?php echo $value['o_description'];?></td>
                                            <td><?php echo $value['amount'];?></td>
                                             <td><?php echo $value['fpp_value'];?></td>
                                               <?php if($value['o_status']==1){ ?>
                                                <td id="activeoffer_<?php echo $value['offer_id']; ?>" class="center js-sortable-handle offeractive">Active</td>
                                                <td class="center" style="width: 80px;"><a id="<?php if (isset( $value['offer_id'])): echo "offers_" .  $value['offer_id'];endif;?>" class="offersdeactive">
                                                <span id="activeoffers_<?php echo  $value['offer_id']; ?>" data-offers ="<?php echo  $value['offer_id']; ?>"  style="cursor:pointer"  class="label label-danger deactivateoffers">Deactivate</span></a></td>
                                               <?php } else { ?>
                                                <td id="activeoffers_<?php echo $value['offer_id']; ?>" class="center js-sortable-handle offersdeactive">Suspended</td>
                                                <td class="center" style="width: 80px;">
                                                    <a  id="<?php if (isset($value['offer_id'])): echo "offers_" . $value['offer_id']; endif;?>" class="offersactive">
                                                <span id="activeoffers_<?php echo $value['offer_id']; ?>" data-val="<?php echo $value['offer_id']; ?>" style="cursor:pointer" class="label label-success activateoffers">Activate</span>
                                                    </a>
                                                </td>
                                               <?php }?>
                                            
                                            <td class="text-center">
                                            	<a data-toggle="modal" data-del="<?php echo $value['offer_id']; ?>" class="text-black m-right-sm delete" ><span><i class="fa fa-times"></i></span></a>
                                            	<a href="edit-offers-details/<?php echo $value['offer_id']; ?>" class="text-black editoffers" ><span><i class="fa fa-edit"></i></span></a>
                                            </td>
                                            
                                        </tr>
                                        <?php } } ?>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                        
                        
                    </div>
                </div>
            </div>
          </div>
          
          
         
        </section><!-- /.content -->
      </div>

   <!----------------------Modals-------------------------->
      <div class="modal fade" id="deleteOffer" role="dialog" aria-hidden="true">
                	<div class="modal-dialog">
                    	<div class="modal-content modal-content-bg">
                        	<div class="modal-header model-header-bg no-border-bottom">
                            	<button type="button" data-dismiss="modal" class="close text-white"><span aria-hidden="true" aria-label="Close">&times;</span></button>
                            	
                                <h3 class="font-Titillium-Web no-margin text-center">Do you want to Delete this Offer?</h3>
                                
                            </div>
                            <div class="modal-footer light-bg clear-both no-border-top">
                            	
                                <div class="text-center">
                                	<button class="btn btn-warning btn-warning">Delete</button>
                                	<button data-dismiss="modal" class="btn btn-gray font-Russo-One">Cancel</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div><!---------Delete Offer------------>
  <!---------EditOffer ------------>
      
<!--                
          <script>
              
  $(function() {
    $( ".date" ).datepicker(){
        $( ".date" ).datepicker{
     format: "mm-dd-yyyy";
 }
  });
  });


  </script>  -->
 <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
<script>
    
  $(document).ready(function() {
    $(".date").datepicker();
  });
</script>

  <script>
              /*
   * dev:priyankav varanasi
   * date:27/5/2015
   * desc: to deactivate offers on call
   */
   $(document).on('click','.deactivateoffers',function(){
        var offerid = $(this).attr('data-offers');
            $.ajax({
            url: './user-ajax-handler',
            type: 'POST',
            datatype: 'json',
            data: {
                method: 'activedeactiveoffers',
                offerid: offerid
            },
            beforeSend: function() {
                console.log('deactivating offers..');
            },
            success: function(response) {
                if (response) {
                var clnew = response.replace(/(\r\n|\n|\r)/gm,"");
                 var cl = "activeoffers_"+clnew;
                    var clu = "offers_"+ clnew;
                   $("#" + cl).html('Suspended');
                    $("#" + clu).html('<span id="activeoffers_'+clnew+'" class="label label-success activateoffers"   style="cursor:pointer" data-val="'+clnew+'">Activate</span>');
                }
            }
        });
  });
  
    /*
   * dev:priyankav varanasi
   * date:27/5/2015
   * desc: to activate offers on call
   */
   $(document).on('click','.activateoffers',function(){
        var offerid = $(this).attr('data-val');
            $.ajax({
            url: './user-ajax-handler',
            type: 'POST',
            datatype: 'json',
            data: {
                method: 'activedeactiveoffers',
                offerid: offerid
            },
            beforeSend: function() {
                console.log('activating offers..');
            },
            success: function(response) {
                if (response) {
                var clnew = response.replace(/(\r\n|\n|\r)/gm,"");
                 var cl = "activeoffers_"+clnew;
                    var clu = "offers_"+clnew;
                   $("#" + cl).html('Active');
                    $("#" + clu).html('<span id="activeoffers_'+clnew+'" class="label label-danger deactivateoffers"  style="cursor:pointer"  data-offers="'+clnew+'">Deactivate</span>');
                }
            }
        });
  });
       /*
   * dev:priyankav varanasi
   * date:27/5/2015
   * desc: to delete offers on call
   */
    $(document.body).on('click','.delete',function(){ 
    var w = $(this);
           var del_did= $(this).attr('data-del');
          
          $.ajax({
             url: './player-details',
              type: 'POST',
            datatype: 'json',
          data:{
              offersid: del_did,
              method :'offersdelete'
        },
            success: function(response){
            
                 w.parent().parent().hide(); 
            }

            });
           
       });
    


$(document.body).on('click','#saveeditoffers',function(){
     $("#offerseditform").valid();
     if( $("#offerseditform").valid()){
         $('#offerseditform').submit(); 
      }      
    });
$('#offerseditform').on('submit', function(e) {
        e.preventDefault();
    var form_data = new FormData(this);  
   var file_data = $('#imageuplaod').prop('files')[0];
  
var offerid =         $('#offerid').val();
var offerName =       $('#offerName').val();
var  oDescription =   $('#oDescription').val();
var status =          $('#status').val();
var offercontest =    $('#offercontest').val();
var validFrom =       $('#validFrom').val();
var validUpto =       $('#validUpto').val();
var fppamount =       $('#amountoffer').val();
var fpp =       $('#fppval').val();
var imageurl =       $('.offersimage').attr('src');

            form_data.append('file', file_data);
            form_data.append("offerid", offerid);
            form_data.append("oDescription", oDescription);
            form_data.append("status", status); 
            form_data.append("offercontest", offercontest); 
            form_data.append("validFrom", validFrom); 
            form_data.append("validUpto", validUpto); 
            form_data.append("amount", fppamount);
            form_data.append("imageurl", imageurl);
            form_data.append("offerName", offerName);
            form_data.append("fpp", fpp);
            
          $.ajax({
              
            url: './edit-offers-details',
            type: 'POST',
            datatype: 'Json',
            data: form_data,
            processData: false,
            contentType: false,
             beforeSend: function() {
                console.log('updating offers..');
            },
    
            success: function(response) {
             if(response){
                  window.location.reload(true);   
            }
        }        
        
            });   
         
    });
    
    
     $(document).ready(function(){
         
   
   $('#offersform').validate({
                onkeyup: function(element) {
                    $(element).valid();
                },     
                rules: {
                  
                    
                   offername: {
                        required:true
                                   },
                    offerstart:{
                        required:true
                        
                    },
                    offerend:{
                        required:true
                        
                   },
                   amount: {
                        required: true,
                        number :true
                     
                    },
                    fppval: {
                        required: true,
                        number:true
                       
                    },
                    offerdescription: {
                        required: true
                    },
                    contest: {
                        required: true
                       
                    },
                    file: {
                        required: true
                    }
                },
                messages: {
                  
                offername:{
                        required:"Please enter your offer name"
                    },
                    offerstart:{
                        required:"Please enter offer start date"
                     },
                    offerend: {
                        required: "please enter offer end date"
                    },
                    amount: {
                        required: "please enter amount"
                        
                     },
                    fppval: {
                        required: "please enter fpp value"
                        
                    },
                    offerdescription: {
                        required: "please enter offer description"
                       
                    },
                    contest: {
                        required: "please enter desired contest"
                       
                    },
                    file: {
                        required: "please uplaod image for your offer"
                     }
                }
    });
   });
   
   
   $(document).ready(function () {
    $('body').on('change','#myimagefile',function(){
        
        var value = $(this).val(),
        file = value.toLowerCase(),
        extension = file.substring(file.lastIndexOf('.') + 1);
        if((extension==='jpg')||(extension==='png')||(extension==='jpeg')){
            $('#errormsg').html('');
        }else{
            $('#errormsg').html('Please select valid file extension *.jpg or *.png or *.jpeg only');
        }
                    
    }); 
});
  </script>