      <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
          <h1>
            Store
            <small>for your next cool web APP</small>
          </h1>
          <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-futbol-o"></i> Home</a></li>
            <li>Store</li>
            <li class="active">Store Details</li>
          </ol>
        </section>

        <!-- Main content -->
        <section class="content">
          <!-- Info boxes -->
          <div class="row">
          	<div class="col-md-12 col-sm-12 no-p-left no-p-right">
            	<div class="panel panel-black no-radius">
                	<div class="panel-heading paddingLR-md paddingTB-sm no-radius">
                    	<h3 class="font-Russo-One no-margin">Store Details</h3>
                    </div>
                </div>
            </div>
          </div>
          
          <div class="row">
          	<div class="col-md-12">
            	<div class="panel panel-gray">
                	<div class="panel-heading paddingLR-md paddingTB-xs">
                    	<h4 class="font-Libre-Baskerville inline-block">Upload New Product</h4>
                    </div>
                    <div class="panel-body padding-md">
                    	<div class="row">
                        	<div class="col-md-8 col-sm-8 col-sm-offset-2 col-xs-offset-0">
                            	<div class="form-group">
                                                	<label>Product Name</label>
                                                    <div class="input-group col-xs-12">
                                                    	<input class="form-control" type="text">
                                                    </div>
                                                </div>
                                                <div class="form-group">
                                                	<label>Url</label>
                                                    <div class="input-group col-xs-12">
                                                    	<input type="text" class="form-control">
                                                    </div>
                                                </div>
                                                <div class="form-group">
                                                	<label>FPP Points</label>
                                                    <div class="input-group col-xs-12">
                                                    	<input class="form-control" type="text">
                                                    </div>
                                                </div>
                                                <div class="form-group">
                                                	<label>Real Cash</label>
                                                    <div class="input-group col-xs-12">
                                                    	<input class="form-control" type="text">
                                                    </div>
                                                </div>
                                                <div class="form-group">
                                                	<label>Quantity</label>
                                                    <div class="input-group col-xs-12">
                                                    	<input class="form-control" type="text">
                                                    </div>
                                                </div>
                                                <div class="form-group">
                                                	<button class="btn btn-blue paddingLR-md">Upload Product</button>
                                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                
                <div class="panel panel-gray">
                	<div class="panel-heading paddingLR-md paddingTB-xs">
                    	<h4 class="font-Libre-Baskerville inline-block">Available Products</h4>
                    </div>
                    <div class="panel-body padding-md">
                    	<div class="row">
                        	<div class="col-md-12">
                              <div class="table-responsive">
                                <table id="availableProduct" class="display table" data-page-length="10" data-order="[[ 1, &quot;asc&quot; ]]" cellspacing="0" width="100%">
                                  <thead>
                                    <tr>
                                      <th>No.</th>
                                      <th>Product Name</th>
                                      <th>Fpp</th>
                                      <th>Points</th>
                                      <th>Real Cash</th>
                                      <th>Quantity</th>
                                      <th>Status</th>
                                      <th>Action</th>
                                      <th>Edit/Delete</th>
                                      </tr>
                                    </thead>
                                  <tbody>
                                    </tbody>
                                  </table>
                              </div>
                            </div>
                        </div>
                    </div>
                </div>
                
                
                
            </div>
          </div>
          
          
         
        </section><!-- /.content -->
      </div>

 
      <!----------------------Modals-------------------------->
      <div class="modal fade" id="deleteTicket" role="dialog" aria-hidden="true">
                	<div class="modal-dialog">
                    	<div class="modal-content modal-content-bg">
                        	<div class="modal-header model-header-bg no-border-bottom">
                            	<button type="button" data-dismiss="modal" class="close text-white"><span aria-hidden="true" aria-label="Close">&times;</span></button>
                            	
                                <h3 class="font-Titillium-Web no-margin text-center">Do you want to Delete this Ticket?</h3>
                                
                            </div>
                            <div class="modal-footer light-bg clear-both no-border-top">
                            	
                                <div class="text-center">
                                	<button class="btn btn-warning btn-warning">Delete</button>
                                	<button data-dismiss="modal" class="btn btn-gray font-Russo-One">Cancel</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
      
      <div class="modal fade" id="editTicket" role="dialog" aria-hidden="true">
                	<div class="modal-dialog width70p">
                    	<div class="modal-content modal-content-bg">
                        	<div class="modal-header model-header-bg no-border-bottom">
                            	<button type="button" data-dismiss="modal" class="close text-white"><span aria-hidden="true" aria-label="Close">&times;</span></button>
                            	
                                <h3 class="font-Titillium-Web no-margin text-center">Edit Ticket</h3>
                                
                            </div>
                            <div class="modal-body">
                            	<div class="panel panel-black">
                                	<div class="panel-heading paddingLR-md">
                                    	<h4><span class="m-right-sm"><i class="fa fa-edit"></i></span>Manage Ticket</h4>
                                    </div>
                                    <div class="panel-body padding-sm">
                                    	<div class="row">
                                        	<div class="col-sm-6">
                                            	<div class="form-group">
                                                	<label for="tContest">Ticket Contest</label>
                                                    <div class="input-group col-xs-12">
                                                    	<input class="form-control" type="text" id="tContest" value="Ticket valid for NHL $5 Head-to-Head (Hosting) Contest!" disabled>
                                                    </div>
                                                </div>
                                                <div class="form-group">
                                                	<label>Code</label>
                                                    <div class="input-group col-xs-12">
                                                    	<input type="text" class="form-control" value="IgaRDXZ" disabled>
                                                    </div>
                                                </div>
                                                <div class="form-group">
                                                	<label>Selling</label>
                                                    <div class="input-group col-xs-12">
                                                    	<select class="form-control">
                                                        	<option>Yes</option>
                                                            <option>No</option>
                                                        </select>
                                                    </div>
                                                </div>
                                                <div class="form-group">
                                                	<label for="status">Status</label>
                                                    <div class="input-group col-xs-12">
                                                    	<select class="form-control" id="status">
                                                        	<option>Activate</option>
                                                            <option>Deactivate</option>
                                                        </select>
                                                    </div>
                                                </div>
                                                
                                            </div>
                                            <div class="col-sm-6">
                                            	<div class="form-group">
                                                	<label>Valid From</label>
                                                    <div class="input-group col-xs-12">
                                                    	<span class="input-group-addon">
                                                        	<i class="fa fa-calendar"></i>
                                                        </span>
                                                        <input id="validFrom" data-provide="datepicker"  class="form-control">
                                                    </div>
                                                </div>
                                                <div class="form-group">
                                                	<label>Valid Upto</label>
                                                    <div class="input-group col-xs-12">
                                                    	<span class="input-group-addon">
                                                        	<i class="fa fa-calendar"></i>
                                                        </span>
                                                        <input id="validUpto" data-provide="datepicker"  class="form-control">
                                                    </div>
                                                </div>
                                                <div class="form-group">
                                                	<label>FPP Amount</label>
                                                    <div class="input-group col-xs-12">
                                                    	<input class="form-control" type="text" value="250">
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="modal-footer light-bg clear-both no-border-top">
                            	
                                <div class="text-center">
                                	<button class="btn btn-blue">Save Changes</button>
                                	<button data-dismiss="modal" class="btn btn-gray font-Russo-One">Cancel</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
      <!----------------------Modals-------------------------->