      <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
          <h1>
            Store
            <small>for your next cool web APP</small>
          </h1>
          <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-futbol-o"></i> Home</a></li>
            <li>Store</li>
            <li class="active">Ticket Details</li>
          </ol>
        </section>

        <!-- Main content -->
        <section class="content">
          <!-- Info boxes -->
          <div class="row">
          	<div class="col-md-12 col-sm-12 no-p-left no-p-right">
            	<div class="panel panel-black no-radius">
                	<div class="panel-heading paddingLR-md paddingTB-sm no-radius">
                    	<h3 class="font-Russo-One no-margin">Ticket Details</h3>
                    </div>
                </div>
            </div>
          </div>
          
          <div class="row">
          	<div class="col-md-12">
            	<div class="panel panel-gray">
                	<div class="panel-heading paddingLR-md paddingTB-xs">
                    	<h4 class="font-Libre-Baskerville inline-block">Ticket Manage</h4>
                    </div>
                    <div class="panel-body padding-md">
                    	<div class="table-responsive">
                            	<table id="ticketDetails" class="display table text-center" data-page-length="10" data-order="[[ 1, &quot;asc&quot; ]]" cellspacing="0" width="100%">
                                	<thead>
                                    	<tr>
                                        	<th>Sr No</th>
                                            <th>ticket name</th>
                                            <th>Description</th>
                                            <th>Ticket Code</th>
                                            <th>Ticket Valid From</th>
                                            <th>Ticket Valid Upto</th>
                                            <th>Status</th>
                                            <th>Action</th>
                                            <th class="">Delete/Edit</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <?php if(isset($this->tickets)){ $i=0; foreach ($this->tickets as $value) { $i++; ?>
   	<tr>
                                            <td class=""><?php echo $i;?></td>
                                            <td class="ticketname" ><?php echo $value['ticket_name'];?></td>
                                            <td class="description" ><?php echo $value['description'];?></td>
                                            <td class="ticketcode" ><?php echo $value['ticket_code'];?></td>
                                            <td class="validityfrom" ><?php echo date("j F , Y", strtotime($value['valid_from']));  ?></td>
                                            <td class="vladityto" ><?php echo date("j F , Y", strtotime($value['valid_upto']));  ?></td>
                                            <?php if($value['t_status']==1){ ?>
                                                <td id="activeticket_<?php echo $value['ticket_id']; ?>" class="center js-sortable-handle ticketactive">Active</td>
                                                <td class="center" style="width: 80px;"><a href="#" id="<?php if (isset( $value['ticket_id'])): echo "tickets_" .  $value['ticket_id'];endif;?>" class="ticketsdeactive">
                                                <span id="activetickets_<?php echo  $value['ticket_id']; ?>" data-tickets ="<?php echo  $value['ticket_id']; ?>" class="label label-danger deactivatetickets">Deactivate</span></a></td>
                                               <?php } else { ?>
                                                <td id="activeticket_<?php echo $value['ticket_id']; ?>" class="center js-sortable-handle ticketdeactive">Suspended</td>
                                                <td class="center" style="width: 80px;">
                                                    <a  id="<?php if (isset($value['ticket_id'])): echo "tickets_" . $value['ticket_id']; endif;?>" class="ticketsactive">
                                                <span id="activetickets_<?php echo $value['ticket_id']; ?>" data-val="<?php echo $value['ticket_id']; ?>" class="label label-success activatetickets">Activate</span>
                                                    </a>
                                                </td>
                                               <?php }?> 
                                            <td class="text-center">
                                            	<a data-toggle="modal" data-del="<?php echo $value['ticket_id']; ?>" class="text-black m-right-sm delete" span><i class="fa fa-times"></i></span></a>
                                            	<a href="edit-ticketdetails/<?php echo $value['ticket_id']; ?>"   class="text-black editticket" ><span><i class="fa fa-edit"></i></span></a>
                                            </td>
                                            
                                        </tr>

                                        <?php } }  ?>
                                 

                                    </tbody>
                                </table>
                            </div>
                    </div>
                </div>
                
                
                
            </div>
          </div>
          
          
         
        </section><!-- /.content -->
      </div>

 <!----------------------Modals-------------------------->
      <div class="modal fade" id="deleteTicket" role="dialog" aria-hidden="true">
                	<div class="modal-dialog">
                    	<div class="modal-content modal-content-bg">
                        	<div class="modal-header model-header-bg no-border-bottom">
                            	<button type="button" data-dismiss="modal" class="close text-white"><span aria-hidden="true" aria-label="Close">&times;</span></button>
                            	
                                <h3 class="font-Titillium-Web no-margin text-center">Do you want to Delete this Ticket?</h3>
                                
                            </div>
                            <div class="modal-footer light-bg clear-both no-border-top">
                            	
                                <div class="text-center">
                                	<button class="btn btn-warning btn-warning">Delete</button>
                                	<button data-dismiss="modal" class="btn btn-gray font-Russo-One">Cancel</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div><!---------Delete Sport------------>
<!---------Edit Sport------------>
      <!----------------------Modals-------------------------->
      <script>
          
            /*
   * dev:priyankav varanasi
   * date:25/5/2015
   * desc: to deactivate tickets on call
   */
   $(document).on('click','.deactivatetickets',function(){
        var ticketid = $(this).attr('data-tickets');
            $.ajax({
            url: './user-ajax-handler',
            type: 'POST',
            datatype: 'json',
            data: {
                method: 'activedeactivetickets',
                ticketid: ticketid
            },
            beforeSend: function() {
                console.log('deactivating tickets..');
            },
            success: function(response) {
                if (response) {
                var clnew = response.replace(/(\r\n|\n|\r)/gm,"");
                 var cl = "activeticket_"+clnew;
                    var clu = "tickets_"+ clnew;
                   $("#" + cl).html('Suspended');
                    $("#" + clu).html('<span id="activetickets_'+clnew+'" class="label label-success activatetickets" data-val="'+clnew+'">Activate</span>');
                }
            }
        });
  });
  
    /*
   * dev:priyankav varanasi
   * date:25/5/2015
   * desc: to activate tickets on call
   */
   $(document).on('click','.activatetickets',function(){
        var ticketid = $(this).attr('data-val');
            $.ajax({
            url: './user-ajax-handler',
            type: 'POST',
            datatype: 'json',
            data: {
                method: 'activedeactivetickets',
                ticketid: ticketid
            },
            beforeSend: function() {
                console.log('activating ticket..');
            },
            success: function(response) {
                if (response) {
                var clnew = response.replace(/(\r\n|\n|\r)/gm,"");
                 var cl = "activeticket_"+clnew;
                    var clu = "tickets_"+clnew;
                   $("#" + cl).html('Active');
                    $("#" + clu).html('<span id="activetickets_'+clnew+'" class="label label-danger deactivatetickets" data-tickets="'+clnew+'">Deactivate</span>');
                }
            }
        });
  });
  

    
    
     /*
   * dev:priyankav varanasi
   * date:25/5/2015
   * desc: to delete ticket on call
   */
    $(document.body).on('click','.delete',function(){ 
    var w = $(this);
           var del_did= $(this).attr('data-del');
          
          $.ajax({
             url: './player-details',
              type: 'POST',
            datatype: 'json',
          data:{
              ticketid: del_did,
              method :'ticketdelete'
        },
            success: function(response){
            
                 w.parent().parent().hide(); 
            }

            });
           
       });
    
       
          </script>
              <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
                  
                          
<script>
  $(function() {
    $( ".date" ).datepicker();
  });

  </script>    