
<div id="content" class="content">
    <!-- begin breadcrumb -->
    <ol class="breadcrumb pull-right">
        <li><a href="javascript:;">Home</a></li>
        <li><a href="javascript:;"> Reviews</a></li>
        <li class="active">Hotel Reviews</li>
    </ol>
    <!-- end breadcrumb -->
    <!-- begin page-header -->
    <h1 class="page-header">Hotel Reviews </h1>
    <!-- end page-header -->

    <!-- begin row -->
    <div class="row">
        <!-- begin col-12 -->
        <div class="col-md-12">           
            <!-- begin panel -->
            <div class="panel pagination-theme clearfix m-b-0">
                <table id="data-table" data-order='[[1,"asc"]]' class="table table-bordered table-hover">
                    <thead>
                        <tr class="default">
                            <th>S.No. </th>                                                          
                                <th> Hotel Name</th>
                                <th> User Name </th>
                                <th> Email</th>
                                <th> Rating </th>
                                <th> Details</th>
                                <th> Review Date </th>
                                <th> Status </th>
                                <th> Action </th>
                                <th>Delete</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php
                        if (isset($this->reviewdetails)) {
                            $i = 0;
                            foreach ($this->reviewdetails as $value) {
                                ?>
                                <tr id="<?php echo $value['review_id']; ?>">
                                        <td><?php echo ++$i; ?></td>
                                   <td><?php echo $value['hotel_name']; ?></td>
                                        <td><?php echo $value['uname']; ?></td>
                                        <td><?php echo $value['email']; ?></td>                                     
                                        <td><?php echo $value['review_rating']; ?></td>
                                        <td><?php echo $value['review_description']; ?></td>
                                        <td><?php echo date("j F , Y h:i:s A", strtotime($value['review_date'])); ?></td>
                                    <?php if ($value['review_status'] == 1) { ?>
                                        <td>
                                            <label id="activeclass_<?php echo $value['review_id']; ?>" class="label label-success js-check-change-field">ACTIVE</label>
                                        </td>

                                        <td class="text-center">
                                            <input type="checkbox" data-render="switchery" id="<?php
                                            if (isset($value['review_id'])): echo "review_" . $value['review_id'];
                                            endif;
                                            ?>"  class="js-switch js-check-change reviewdeactive" data-theme="lime" checked /> 
                                        </td>
                                    <?php }else { ?>
                                        <td >
                                            <label id="activeclass_<?php echo $value['review_id']; ?>" class="label label-danger js-check-change-field">SUSPENDED</label>
                                        </td>
                                        <td class="text-center">
                                            <input type="checkbox" data-render="switchery" id="<?php
                                            if (isset($value['review_id'])): echo "review_" . $value['review_id'];
                                            endif;
                                            ?>"  class="js-switch js-check-change reviewactive" data-theme="lime" /> 
                                        </td>
                                    <?php } ?>

                                    <td class="text-center">                                     
                                        <a href="javascript:;" id="<?php echo "reviewdelete_" . $value['review_id']; ?>" class="btn btn-primary btn-icon btn-circle btn-sm deletereview">
                                            <i class="fa fa-trash"></i>
                                        </a>
                                    </td>
                                </tr>
                                <?php
                            }
                        }
                        ?>

                    </tbody>
                </table>
            </div>

        </div>

    </div>

</div>



