<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Payment Settings
            <small>for your next cool web APP</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-futbol-o"></i> Home</a></li>
            <li>Payment Settings</li>
            <li class="active">Withdrawal Details</li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">
   
        <!-- Info boxes -->
        <div class="row">
            <div class="col-md-12 col-sm-12 no-p-left no-p-right">
                <div class="panel panel-black no-radius">
                    <div class="panel-heading paddingLR-md paddingTB-sm no-radius">
                        <h3 class="font-Russo-One no-margin">Withdrawal Details</h3>
                    </div>
                </div>
            </div>
        </div>
    
        <div class="row">
            <div class="col-md-12 col-sm-12">
                  <div>
                    <div class="panel panel-gray">
                        <div class="panel-heading paddingLR-md paddingTB-xs">
                            <h4 class="font-Libre-Baskerville inline-block">Withdrawal Paypal Details</h4><br>
                            <h5 class="font-Libre-Baskerville inline-block">Completed Requests</h5>
                          </div>
                        <div class="panel-body">
                            <div class="">
                                <div class="table-responsive">
                                    <div id="baseDateControl">

                                   <table id="withdrawalcompleted" class="display table text-center" data-page-length="10" data-order="[[ 1, &quot;asc&quot; ]]" cellspacing="0" width="100%">
                                        <thead>
                                            <tr>
                                                <th>Sr No</th>
                                                <th>User</th>
                                                <th>Amount($)</th>
                                                <th>Pay Method</th>
                                                <th>Request Date</th>
                                                <th>Pay Date</th>
                                                <th>Transaction ID</th>
                                                <th>Status</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <?php if (isset($this->completedrequests)) {
                                                $j = 0;
                                                foreach ($this->completedrequests as $value) {
                                                    $j++; ?>
                                                    <tr class="withdraw"> 

                                                        <td><?php echo $j; ?></td>
                                                        <td><?php echo $value['user_name']; ?></td>
                                                        <td><?php echo $value['requested_amt']; ?></td>
                                                        <td><?php if($value['pay_method']==1){echo"Paypal";}else{ echo"Check" ;}?></td>
                                                        <td><?php echo $value['request_date']; ?></td>
                                                        <td><?php echo $value['pay_date']; ?></td>
                                                        <td><?php if(!empty($value['transaction_id'])){  echo $value['transaction_id'] ;}else{ echo"Delivered through check" ;}?></td>
                                                        <td>completed</td>
                                                    </tr>
    <?php }
} ?>  
                                        </tbody>
                                    </table>
                                 
                                </div>
                            </div>


                        </div>
                    </div>
                    <br>

                </div>       
          </div>
        </div>



    </section><!-- /.content -->
</div>
        <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
        <script src="//cdn.datatables.net/1.10.7/js/jquery.dataTables.min.js"></script>
       
<script>
    $('#withdrawalcompleted').DataTable({
        "bLengthChange": false,
    });
</script>