      <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
          <h1>
            Payment Settings
            <small>for your next cool web APP</small>
          </h1>
          <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-futbol-o"></i> Home</a></li>
            <li>Payment Settings</li>
            <li class="active">Depositer Details</li>
          </ol>
        </section>

        <!-- Main content -->
        <section class="content">
          <!-- Info boxes -->
          <div class="row">
          	<div class="col-md-12 col-sm-12 no-p-left no-p-right">
            	<div class="panel panel-black no-radius">
                	<div class="panel-heading paddingLR-md paddingTB-sm no-radius">
                    	<h3 class="font-Russo-One no-margin">Depositor Details</h3>
                    </div>
                </div>
            </div>
          </div>
          
          <div class="row">
          	<div class="col-md-12 col-sm-12">
            	<div class="panel panel-gray">
                	<div class="panel-heading paddingLR-md paddingTB-xs">
                    	<h4 class="font-Libre-Baskerville inline-block">Depositor Manage</h4>
                    </div>
                    <div class="panel-body">
                    	<div class="">
                        	<div class="table-responsive">
                            	<table id="depositerDetails" class="display table text-center" data-page-length="10" data-order="[[ 1, &quot;asc&quot; ]]" cellspacing="0" width="100%">
                                	<thead>
                                    	<tr>
                                        	<th>Sr No</th>
                                            <th>User Name</th>
                                            <th>Pay Method</th>
                                            <th>Amount($)</th>
                                            <th>Confirmation Code</th>
                                            <th>Transaction Date</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <?php if(isset($this->depositors)){ $row = 0;
          foreach ($this->depositors as $value) { $row++;?>
       	<tr>
                                        <td><?php echo $row;?></td>
                                            <td><?php echo $value['user_name'];?></td>
                                            <td>paypal</td>
                                            <td><?php echo $value['t_amount'];?></td>
                                            <td><?php echo $value['confirmation_code'];?></td>
                                            <td><?php echo $value['transaction_date'];?></td>
                                            
                                        </tr>  
                                        <?php  }  } ?>
                                    
                                 
                                        
                                    </tbody>
                                </table>
                            </div>
                        </div>
                        
                        
                    </div>
                </div>
            </div>
          </div>
          
          
         
        </section><!-- /.content -->
      </div>
  <script>
		$('#depositerDetails').DataTable({
			"bLengthChange": false,
			
			});

	</script>