      <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
          <h1>
            Payment Settings
            <small>for your next cool web APP</small>
          </h1>
          <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-futbol-o"></i> Home</a></li>
            <li>Payment Settings</li>
            <li class="active">Profit Status</li>
          </ol>
        </section>

        <!-- Main content -->
        <section class="content">
          <!-- Info boxes -->
          <div class="row">
          	<div class="col-md-12 col-sm-12 no-p-left no-p-right">
            	<div class="panel panel-black no-radius">
                	<div class="panel-heading paddingLR-md paddingTB-sm no-radius">
                    	<h3 class="font-Russo-One no-margin">Profit Status</h3>
                    </div>
                </div>
            </div>
          </div>
          
          
          
          <div class="row">
          	<div class="col-md-12">
            	<div class="box box-black box-solid">
                <div class="box-header with-border">
                  <h3 class="box-title font-Libre-Baskerville"><span class="m-right-sm"><i class="fa fa-bar-chart"></i></span>Profit Statics</h3>                                    
                </div>
                <div class="box-body">
                  <div class="tab-content">
                                <div role="tabpanel" class="tab-pane active" id="allUsers">
                                    <div class="m-top-md">
                                        <div class="table-responsive">
                                            <table id="contestProfitDetails" class="display table" data-page-length="10" data-order="[[ 1, &quot;asc&quot; ]]" cellspacing="0" width="100%">
                                                <thead>
                                                    <tr>
                                                        <th>Sr No</th>
                                                        <th>Contest Name</th>
                                                        <th>Total UserEntry</th>
                                                        <th>Start Time</th>
                                                        <th>End Time</th>
                                                        <th>Profit Amount</th>
                                                        <th>Profit Date</th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    <?php if (isset($this->profitStatics)) {
                                                        $row = 0;
                                                        foreach ($this->profitStatics as $val) {
                                                            $row ++; ?>
                                                            <tr>
                                                                <td><?php echo $row; ?></td>
                                                                <td class =contestsname"><?php echo $val['contest_name']; ?></td>
                                                                <td class = "user-entry text-center" ><?php echo $val['user_entry']; ?></td>
                                                                <td class="contest_type"><?php echo $val['start_time']; ?></td>
                                                                <td class="entryfee"><?php echo $val['end_time']; ?></td>
                                                                <td class="starttime text-center"><?php echo $val['amount']; ?></td>
                                                                <td class ="endtime"><?php echo date_format(date_create($val['date']), 'jS F Y');; ?></td>

                                                            </tr>
                                                    <?php } } ?>  
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                  </div>
                </div><!-- /.box-body -->
              </div> 
            </div>
          </div>
          </section><!-- /.content -->
      </div>

<script>
    $('#contestProfitDetails').DataTable({
        "bLengthChange": false,
    });
</script>    