<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Payment Settings
            <small>for your next cool web APP</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-futbol-o"></i> Home</a></li>
            <li>Payment Settings</li>
            <li class="active">Withdrawal Details</li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">
   
        <!-- Info boxes -->
        <div class="row">
            <div class="col-md-12 col-sm-12 no-p-left no-p-right">
                <div class="panel panel-black no-radius">
                    <div class="panel-heading paddingLR-md paddingTB-sm no-radius">
                        <h3 class="font-Russo-One no-margin">Withdrawal Details</h3>
                    </div>
                </div>
            </div>
        </div>
    
        <div class="row">
            <div class="col-md-12 col-sm-12">

                <div>
                    <div class="panel panel-gray">
                        <div class="panel-heading paddingLR-md paddingTB-xs">
                            <h4 class="font-Libre-Baskerville inline-block">Withdrawal Paypal Details</h4><br>
                            <h5 class="font-Libre-Baskerville inline-block">Pending Paypal Requests</h5>
                             
                            <a id="paycompleted" href="/admin/completed-requests" class="btn btn-blue pull-right">Completed Requests</a>

                        </div>
                        <div class="panel-body">
                            <div class="">
                                <div class="table-responsive">
                                    <table id="withdrawalpending" class="display table text-center" data-page-length="10" data-order="[[ 1, &quot;asc&quot; ]]" cellspacing="0" width="100%">
                                        <thead>
                                            <tr>
                                                <th>Sr No</th>
                                                <th>click to pay</th>
                                                <th>User</th>
                                                <th>Amount($)</th>
                                                <th>Pay Method</th>
                                                <th>Request Date
                                                <th>Status</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <?php if (isset($this->pendingpaypalrequests)) {
                                                $j = 0;
                                                foreach ($this->pendingpaypalrequests as $value) {
                                                    $j++; ?>
                                                    <tr class="withdraw"> 

                                                        <td><?php echo $j; ?></td>
                                                        <td class="processthisrequest" id="completerequest_<?php echo $value['withdrawal_id']; ?>"><input value="<?php echo $value['withdrawal_id']; ?>" type ="checkbox" name ="processrequest" > </td>
                                                        <td><?php echo $value['user_name']; ?></td>
                                                        <td><?php echo $value['requested_amt']; ?></td>
                                                        <td>Paypal</td>
                                                        <td><?php echo $value['request_date']; ?></td>
                                                        <td>Pending</td>
                                                    </tr>
    <?php }
} ?>  
                                        </tbody>
                                    </table>
                                    <div class="m-top-md pull-right">
                                        <button class="btn btn-blue paddingLR-md" id="payrequest">Pay</button>
                                    </div>
                                </div>
                            </div>


                        </div>
                    </div>
                    <br>


                </div>       
                <div class="panel panel-gray">
                    <div class="panel-heading paddingLR-md paddingTB-xs">
                        <h4 class="font-Libre-Baskerville inline-block">Withdrawal Details</h4><br>
                        <h5 class="font-Libre-Baskerville inline-block">Pending Check Requests</h5>
                    </div>
                    <div class="panel-body">
                        <div class="">
                            <div class="table-responsive">
                                <table id="withdrawalcompleted" class="display table text-center" data-page-length="10" data-order="[[ 1, &quot;asc&quot; ]]" cellspacing="0" width="100%">
                                    <thead>
                                        <tr>
                                            <th>Sr No</th>
                                            <th>User</th>
                                            <th>Amount($)</th>
                                            <th>Pay Method</th>
                                            <th>Request Date
                                            <th>Status</th>
                                            <th>Process request</th>
                                        </tr>
                                    </thead>

                                    <tbody>
<?php if (isset($this->pendingcheckrequests)) {
    $k = 0;
    foreach ($this->pendingcheckrequests as $val) {
        $k++; ?>
                                                <tr>
                                                    <td><?php echo $k; ?></td>
                                                    <td><?php echo $val['user_name']; ?></td>
                                                    <td><?php echo $val['requested_amt']; ?></td>
                                                    <td>Check</td>
                                                    <td><?php echo $val['request_date']; ?></td>
                                                    <td>Pending</td>
                                                    <td class="center" style="width: 80px;">
                                                        <a class="requestprocess">
                                                            <span id="request_<?php echo $val['withdrawal_id']; ?>" data-val="<?php echo $val['withdrawal_id']; ?>" class="label label-success ">Process Request</span>
                                                        </a>
                                                    </td>
                                                </tr>
    <?php }
} ?>  


                                    </tbody>
                                </table>
                            </div>
                        </div>


                    </div>
                </div>      


            </div>
        </div>



    </section><!-- /.content -->
</div>
<script>
    $('#withdrawalcompleted').DataTable({
        "bLengthChange": false,
    });

    $('#withdrawalpending').DataTable({
        "bLengthChange": false,
    });

</script>

<script>
    /*
     * dev:priyanka varanasi
     * desc: to process the pending request for with draw money from user
     * date: 15/5/2015
     */
    $(document.body).on('click', '#payrequest', function() {
        var withdrawalids = new Array();
        $('.processthisrequest').each(function(index, value) {
            if ($(this).children().is(':checked')) {
                withdrawalids.push($(this).children().attr('value'));
            }
        });
        $.ajax({
            url: './withdraw-ajax-handler',
            type: 'POST',
            datatype: 'json',
            data: {
                method: 'processthroughPaypal',
                data: withdrawalids
            },
            beforeSend: function() {
                console.log('request is processing...');
            },
            success: function(response) {
            if(response){
          //window.location.reload(true);
            }
        }
        });
  });
  
     /*
     * dev:priyanka varanasi
     * desc: to process the pending request for with draw using  money from user
     * date: 15/5/2015
     */
    $(document.body).on('click', '.requestprocess', function() {
  var checkrequest  =  $(this).children().attr('data-val');
       $.ajax({
            url: './withdraw-ajax-handler',
            type: 'POST',
            datatype: 'json',
            data: {
                method: 'processthroughcheck',
                data: checkrequest
            },
            beforeSend: function() {
                console.log('request is processing...');
            },
            success: function(response) {
              var clnew = response.replace(/(\r\n|\n|\r)/gm,"");
               var c = clnew.replace(/\"/g, ""); 
                 var cl = "request_" + c;
                 $("#" + cl).parent().parent().parent().hide();
            }

        });
  });
  
  
</script>




