<div id="content" class="content">
    <ol class="breadcrumb pull-right">
        <li><a href="/agent/dashboard">Dashboard</a></li>
        <li><a href="javascript:;">Hotel Details</a></li>
        <li class="active">View Hotel Details</li>
    </ol>
    <!-- end breadcrumb -->
    <!-- begin page-header -->
    <h1 class="page-header">View Hotel Details </h1>
    <!-- end page-header -->

    <!-- begin row -->
    <div class="row">
        <!-- begin col-12 -->
        <div class="col-md-12">
            <!-- begin panel -->
            <div class="panel pagination-theme clearfix m-b-0">
                <div class="panel-body">
                    <form class="" role="form" enctype="multipart/form-data" method="POST">
                        <div class="row">
                            <div class="col-md-12">
                                <legend class="heading">Location:</legend>

                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label class="control-label">Country</label>

                                            <?php
                                            if (isset($this->hoteldetails['countryName'])) {
                                                echo $this->hoteldetails['countryName'];
                                            }
                                            ?>

                                        </div>
                                        <div class="form-group">
                                            <label class="control-label"> State</label>

                                            <?php
                                            if (isset($this->hoteldetails['stateName'])) {
                                                echo $this->hoteldetails['stateName'];
                                            }
                                            ?>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label class="control-label"> City</label>

                                                <?php
                                                if (isset($this->hoteldetails['cityName'])) {
                                                    echo $this->hoteldetails['cityName'];
                                                }
                                                ?>
                                            </div>
                                            <div class="form-group">
                                                <label class="control-label"> Location</label>

                                                <?php
                                                if (isset($this->hoteldetails['areaName'])) {
                                                    echo $this->hoteldetails['areaName'];
                                                }
                                                ?>                                        
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <legend class="heading">Details:</legend>

                                    <div class="row">
                                        <div class="col-md-6">
                                            <div class="form-group has-success has-feedback m-b-10">
                                                <label class="control-label">Hotel Name</label>
                                                <?php
                                                if (isset($this->hoteldetails['hotel_name'])) {
                                                    echo $this->hoteldetails['hotel_name'];
                                                }
                                                ?>
                                                <span class="fa fa-check form-control-feedback"></span>
                                            </div>

                                            <div class="form-group">
                                                <label class="control-label"> Cuisine</label>

                                                <?php
                                                if (isset($this->cuisine123)) {
                                                    echo $this->cuisine123;
                                                    ?>
                                                    <?php
                                                }
                                                ?>        
                                            </div>

                                            <div class="form-group has-error has-feedback m-b-10">
                                                <label class="control-label">Hotel Address</label>
                                                <?php
                                                if (isset($this->hoteldetails['address'])) {
                                                    echo $this->hoteldetails['address'];
                                                }
                                                ?>
                                                <span class="fa fa-times form-control-feedback"></span>
                                            </div>
                                            <div class="form-inline m-b-10">
                                                <label class="">Timing</label>
                                                <br/>
                                                <div style="display: inline-flex;">
                                                    <div class="form-group" style="width: 53%;">
                                                        <?php
                                                        if (isset($this->hoteldetails['open_time'])) {
                                                            echo $this->hoteldetails['open_time'];
                                                        }
                                                        ?> AM &nbsp; &nbsp; &nbsp; &nbsp;
                                                    </div>
                                                    <div class="form-group">
                                                        <?php
                                                        if (isset($this->hoteldetails['closing_time'])) {
                                                            echo $this->hoteldetails['closing_time'];
                                                        }
                                                        ?>PM
                                                    </div>
                                                </div>
                                            </div>

                                            <div class="form-group m-b-10">
                                                <label class="control-label">Primary Phone No.</label>
                                                <?php
                                                if (isset($this->hoteldetails['primary_phone'])) {
                                                    echo $this->hoteldetails['primary_phone'];
                                                }
                                                ?>
                                            </div>

                                            <div class="form-group m-b-10">
                                                <label class="control-label">Secondary Phone No.</label>
                                                <?php
                                                if (isset($this->hoteldetails['secondary_phone'])) {
                                                    echo $this->hoteldetails['secondary_phone'];
                                                }
                                                ?>
                                            </div>

                                            <div class="form-group">
                                                <label class="control-label">Status</label>
                                                <?php
                                                if (isset($this->hoteldetails['hotel_status']) == 1) {
                                                    echo "Active";
                                                } else {
                                                    echo "Inactive";
                                                }
                                                ?>
                                            </div>
                                        </div>

                                        <div class="col-md-6">
                                            <div class="form-group m-b-10">
                                                <label class="control-label">Hotel Image</label>
                                                <div class="form-group">
                                                    <div class="fileinput fileinput-new" data-provides="fileinput">
                                                        <div class="fileinput-new thumbnail" style="width: 200px; height: 150px;">
                                                            <img src="<?php
                                                            if (isset($this->hoteldetails['hotel_image'])) {
                                                                echo $this->hoteldetails['hotel_image'];
                                                            }
                                                            ?>" alt="">
                                                        </div>
                                                        <div class="fileinput-preview fileinput-exists thumbnail" style="max-width: 200px; max-height: 150px;"></div>

                                                    </div>
                                                </div>
                                            </div>
                                            <div class="form-group m-b-10">
                                                <label class="control-label">Min. Order</label>
                                                <?php
                                                if (isset($this->hoteldetails['minorder'])) {
                                                    echo $this->hoteldetails['minorder'];
                                                }
                                                ?>
                                            </div>
                                            <div class="form-group m-b-10">
                                                <label class="control-label">Delivery Charges</label>
                                                <?php
                                                if (isset($this->hoteldetails['deliverycharge'])) {
                                                    echo $this->hoteldetails['deliverycharge'];
                                                }
                                                ?>
                                            </div>
                                            <div class="form-group m-b-10">
                                                <label class="control-label">Hotel Notice</label>
                                                <?php
                                                if (isset($this->hoteldetails['notice'])) {
                                                    echo $this->hoteldetails['notice'];
                                                }
                                                ?>
                                            </div>
                                        </div>
                                    </div>                                   

                                </div>
                            </div>
                    </form>
                </div>
                <!-- end panel -->
            </div>
            <!-- end col-12 -->
        </div>
        <!-- end row -->
    </div>
</div>
</div>