
<script type="text/javascript" language="javascript" class="init">


$(document).ready(function() {
	$('#promotionpage').dataTable( {
		columnDefs: [ {
			targets: [ 0 ],
			orderData: [ 0, 1 ]
		}, {
			targets: [ 1 ],
			orderData: [ 1, 0 ]
		}, {
			targets: [ 4 ],
			orderData: [ 4, 0 ]
		} ]
	} );
} );

</script>
<div id="content">
	<h4>Contest Promotion Details</h4>
<div class="innerLR">

	<!-- Widget -->
	<div class="widget">
		
		<!-- Widget heading -->
		<div class="widget-head">
			<h4 class="heading">Contest Promotions</h4>
		</div>
                <div>
                     <a class="btn btn-icon btn-primary glyphicons circle_ok" href="/admin/add-contest-promotion" type="button" style="margin-left:870px">
                            <i></i>Add Promotion Details</a>
                             
                    </div>
		<!-- // Widget heading END -->
		
		<div class="widget-body">
		
			<!-- Table -->
			<table  id="promotionpage"class="dynamicTable table table-striped table-bordered table-condensed">			
				<!-- Table heading -->
                                <thead>
                                    <tr>
                                        <th>Sno.</th>
                                        <th>Display Name</th>
                                        <th>URL</th>
                                        <th>Status</th>
                                        <th>Action</th>
                                        <th class="center">Delete / Edit</th>
                                    </tr>
                                </thead>
				<!-- // Table heading END -->
				
				<!-- Table body -->
				<tbody>			
                                    <?php if(isset($this->promotion)): $row = 0; foreach ($this->promotion as $promotionDetails): $row++; ?>
					<!-- Table row -->
					<tr>
						<td><?php echo $row; ?></td>
						<td><?php echo  $promotionDetails['promotion_display_name']; ?></td>
                                                <td><?php echo  $promotionDetails['promotion_url']; ?></td>
						<?php if($promotionDetails['status']==1): ?>
                                                <td id="activepromotion_<?php echo $promotionDetails['promotion_id']; ?>" class="center js-sortable-handle useractive">Active</td>
                                                <td class="center" style="width: 80px;"><a href="#" id="<?php if (isset($promotionDetails['promotion_id'])): echo "promotion_" . $promotionDetails['promotion_id'];endif;?>" class="promotiondeactive">
                                                <span id="activeclass_<?php echo $promotionDetails['promotion_id']; ?>" class="label label-block label-inverse">Deactivate</span></a></td>
                                                  <?php  else: ?>
                                                <td id="activepromotion_<?php echo $promotionDetails['promotion_id']; ?>" class="center js-sortable-handle userdeactive">Suspended</td>
                                                <td class="center" style="width: 80px;"><a href="#" id="<?php if (isset($promotionDetails['promotion_id'])): echo "promotion_" . $promotionDetails['promotion_id']; endif;?>" class="promotionactive">
                                                <span id="activeclass_<?php echo $promotionDetails['promotion_id']; ?>"  class="label label-block label-primary">Activate</span></a></td>
                                                <?php endif;?> 
                                                
                                                <td class="center" style="width: 80px;">
                                                <a id="promotiondelete_<?php echo $promotionDetails['promotion_id']; ?>" href="#" class="btn-action glyphicons remove_2 btn-danger promotion-delete"><i></i></a>
                                                <a href="/admin/edit-contest-promotion/<?php echo $promotionDetails['promotion_id']; ?>" class="btn-action glyphicons pencil btn-success"><i></i></a>
                                                </td>
					</tr>
					<!-- // Table row END -->					           
                                        <?php endforeach; endif; ?>
				</tbody>
				<!-- // Table body END -->
				
			</table>
			<!-- // Table END -->
			
		</div>
	</div>	
</div>			
</div>
<script>
    $('#menu_components3').removeClass('collapse').addClass('in collapse');
    $('#promotion_setting_menu').removeClass('hasSubmenu glyphicons cogwheels').addClass('hasSubmenu glyphicons charts active');
    $('#contest_promotion_menu').addClass('active');    
</script>


