<div class="content-wrapper" style="min-height: 659px;">
<?php if(isset($this->success)) { ?>
            <div class="opennotificationGreen" style="color:#4cae4c;">
<span class="notification_msgGreen">
    <h3 style="padding-left:299px;">Promotion Details Edited  Successfully</h3></span>

</div>
<?php  }  ?>
        <section class="content">
          <!-- Info boxes -->
          <div class="row">
          	<div class="col-md-12 col-sm-12 no-p-left no-p-right">
            	<div class="panel panel-black no-radius">
                	<div class="panel-heading paddingLR-md paddingTB-sm no-radius">
                    	<h3 class="font-Russo-One no-margin">New Contest Promotion</h3>
                    </div>
                </div>
            </div>
          </div>
          
          <div class="row">
          	<div class="col-md-12 col-sm-12">
            	<div class="panel panel-gray">
                	<div class="panel-heading paddingLR-md paddingTB-xs">
                    	<h4 class="font-Libre-Baskerville inline-block">Edit Contest Promotion</h4>
                        <a href="<?php // echo $this->getHost();?>../../admin/promotion-details"><button class="btn btn-blue m-top-xs btn-sm inline-block pull-right">Promotion Details</button></a>
                    </div>
                    <div class="panel-body padding-md">
                    	<div class="row">
                          <div class="com-md-8 col-sm-8 col-xs-12 col-sm-offset-2">
                              <form method="post" id="editpromotiondetails" name="editpromotiondetails">
                          		<div class="form-group">
                                	<label for="pDN">Promotion Display Name</label>
                                    <div class="input-group col-xs-12">
                                        <input type="text" class="form-control" name="pDN" id="pDN" value="<?php  echo $this->editpromotion['promotion_display_name']?>">
                                    </div>
                                </div>
                              <div class="form-group">
                                	<label for="pURL">Promotion URL</label>
                                    <div class="input-group col-xs-12">
                                        <input type="text" class="form-control" name="pURL" id="pURL" value="<?php  echo $this->editpromotion['promotion_url'];?>">
                                    </div>
                                </div>
                                
                                <div class="form-group">
                                	<label>Promotion Content</label>
                                	<div class="input-group col-xs-12">
                                    	<div class="summernote"></div>
                                    </div>
                                </div>
                                
                                <div class="form-group">
                                	<label>Status</label>
                                	<div class="input-group col-xs-12">
                                            <select class="form-control" name="status">
                                                <option value="1">Active</option>
                                                <option value="0">Deactive</option>
                                        </select>
                                    </div>
                                </div>
                                  <input name="promotion_content" id="promotion_content" style="display: none">
                                <div class="form-group">
                                    <button id="submitbutton" class="btn btn-blue paddingLR-md m-right-sm" type="submit">Save Changes</button>
                                    <a href="<?php $this->baseUrl(); ?>/admin/promotion-details" class="btn btn-gray font-Russo-One paddingLR-md">Cancel</a>
                                </div>
                              </form>
                          </div>
                        </div>
                    </div>
                </div>
            </div>
          </div>
          <?php $content = htmlentities($this->editpromotion['promotion_content']);
//                 print_r($content);
//                 die();
                 ?>              
          <?php // echo trim(preg_replace('/\s+/', ' ', $this->editpromotion['promotion_content']));
//                 die();?>
         
        </section><!-- /.content -->
      </div>
<script>
          setTimeout(function() {
           $('.opennotificationGreen').fadeOut("slow");
            $('div').remove(".notification_msgGreen");
            }, 5000);   
	
		$('.summernote').summernote({
					height: 150,                 // set editor height
				  	minHeight: null,             // set minimum height of editor
				  	maxHeight: null,             // set maximum height of editor
				  	focus: true,  
					});
                                        
                 
                $('.note-editable').html('<?php echo addslashes(trim(preg_replace("/\s+/", " ", $this->editpromotion['promotion_content'])));?>');
               
//                alert($('.note-editable').html());
                
                
                
	</script>
        <script>
//        var contents = $('.note-editable').text();
//                function copyContents{
//                    alert(contents);
//                    $('.contents').text(contents);
//                }
                
                $('#submitbutton').click(function (){
//                var contents = $('.note-editable').text();
                    $('#promotion_content').attr("value", $('.note-editable').html());
                });
        </script>
        <script>
        
        
                /*
     * dev:priyankav varanasi
     * date:22/6/2015
     * desc: To validate edit promotion 
     */
         
       $(function() {
   $.validator.addMethod("regex", function(value, element, regexpr) {          
     return regexpr.test(value);
   });
   $('#editpromotiondetails').validate({
                onkeyup: function(element) {
                    $(element).valid();
                },     
                rules: {
                   pDN: {
                       required:true
                                   },
                    pURL:{
                       required:true
                        
                    }
                
                 },
                messages: {
               
                    pDN:{
                        required:"Please enter promotion dislay name"
                    },
                    pURL:{
                        required:"Please promotion url"
                     }
                     
              
                }
    });
    
    
    });  
        
        </script>