<div class="content-wrapper" style="min-height: 659px;">
        <!-- Content Header (Page header) -->
        <section class="content-header">
          <h1>
            Promotion Setting
            <small>for your next cool web APP</small>
          </h1>
          <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-futbol-o"></i> Home</a></li>
            <li>Promotion Setting</li>
            <li class="active">Player Salary</li>
          </ol>
        </section>

        <!-- Main content -->
        <section class="content">
          <!-- Info boxes -->
          <div class="row">
          	<div class="col-md-12 col-sm-12 no-p-left no-p-right">
            	<div class="panel panel-black no-radius">
                	<div class="panel-heading paddingLR-md paddingTB-sm no-radius">
                    	<h3 class="font-Russo-One no-margin">Promotion Details</h3>
                    </div>
                </div>
            </div>
          </div>
          
          <div class="row">
          	<div class="col-md-12 col-sm-12">
            	<div class="panel panel-gray">
                	<div class="panel-heading paddingLR-md paddingTB-xs">
                    	<h4 class="font-Libre-Baskerville inline-block">Contest Promotions</h4>
                        <a href="/admin/add-promotion-details"><button class="btn btn-blue m-top-xs btn-sm inline-block pull-right"><span class="m-right-sm"><i class="fa fa-plus"></i></span> Add Promotion Details</button></a>
                    </div>
                    <div class="panel-body padding-md">
                    	<div class="row">
                          <div class="com-md-12">
                            <div class="table-responsive">
                              <div id="promotionDetails_wrapper" class="dataTables_wrapper no-footer">
                                  <table width="100%" cellspacing="0" data-order="[[ 1, &quot;asc&quot; ]]" data-page-length="10" class="display table text-center dataTable no-footer" id="promotionDetails" role="grid" aria-describedby="promotionDetails_info" style="width: 100%;">
                                <thead>
                                  <tr role="row">
                                      <th class="sorting" tabindex="0" aria-controls="promotionDetails" rowspan="1" colspan="1" style="width: 108px;" aria-label="Sr No: activate to sort column ascending">Sr No</th>
                                      <th class="sorting_asc" tabindex="0" aria-controls="promotionDetails" rowspan="1" colspan="1" style="width: 215px;" aria-sort="ascending" aria-label="Display Name: activate to sort column descending">Display Name</th>
                                      <th class="sorting" tabindex="0" aria-controls="promotionDetails" rowspan="1" colspan="1" style="width: 91px;" aria-label="URL: activate to sort column ascending">URL</th>
                                      <th class="sorting" tabindex="0" aria-controls="promotionDetails" rowspan="1" colspan="1" style="width: 122px;" aria-label="Status: activate to sort column ascending">Status</th>
                                      <th class="sorting" tabindex="0" aria-controls="promotionDetails" rowspan="1" colspan="1" style="width: 121px;" aria-label="Action: activate to sort column ascending">Action</th>
                                      <th class="sorting" tabindex="0" aria-controls="promotionDetails" rowspan="1" colspan="1" style="width: 183px;" aria-label="Delete/Edit: activate to sort column ascending">Delete/Edit</th>
                                  </tr>
                                  </thead>
                                <tbody>
                                    <?php 
                                    
                                    $count = 1;
                                    if(isset($this->promotion)){
                                        foreach($this->promotion as $value){
                                            
                                        ?>
                                    <tr>
                                        <td><?php echo $count; $count++;?></td>
                                        <td><?php echo $value['promotion_display_name']?></td>
                                        <td><?php echo $value['promotion_url']?></td>
                                        <td class="pstatus"><?php if($value['status']==1){echo "Active";}else{echo "Deactive";}?></td>
                                        <td class="updatestatus" data-pid="<?php echo $value['promotion_id']?>" data-status="<?php echo $value['status'];?>"><?php if($value['status']==1){ ?> <span class= "label label-danger">Deactivate</span><?php } else{?><span class= "label label-success">Activate</span><?php }?></td>
                                        <td>
                                            <a class="pdelete" data-pid="<?php echo $value['promotion_id']?>"  class="text-black m-right-sm remove" ><span><i class="fa fa-times"></i></span></a>
                                            <a  class="text-black editcontestdet" href="/admin/edit-promotion/<?php echo $value['promotion_id']?>" ><span><i class="fa fa-edit"></i></span></a>
                                        </td>
                                        
                                    </tr>
                                    <?php }}?>
                                </tbody>
                                </table>
                              </div>
                          </div>
                        </div>
                    </div>
                </div>
            </div>
          </div>
        </section><!-- /.content -->
      </div>
<script>
    $('#promotionDetails').DataTable({
        "bLengthChange": false,
    });
    
    
    
</script>
<script>
    $(".updatestatus").click(function (){
        var pid = $(this).attr("data-pid");
        var status = $(this).attr("data-status");
        var w = $(this);
        
           $.ajax({            
                url      : '/admin/updatestatus',
                type     : 'POST',
                dataType : 'JSON',
                data : {
                    pid   : pid,
                    status : status,
                    method : "update"
                },
                beforeSend : function() {
                
                },
                success : function(response) {              
//                    w.('.modal-body').html(response);
//                    $('.playerdetails').html(response);
                    if(response==1){
                        
                        if(status == 1){
                            w.attr("data-status", 0);
                            w.html('<span class= "label label-success">Activate</span>');
                           w.siblings(".pstatus").html("Deactive");
                        } else if(status == 0){
                         w.attr("data-status", 1);
                            w.html('<span class="label label-danger">Deactivate</span>');
                            w.siblings(".pstatus").html("Active");
                        }
                    }

                }
            
            });
        
    });
    
    
    
    $(".pdelete").click(function (){
        var pid = $(this).attr("data-pid");
        var w = $(this);
        $.ajax({
            url      : '/admin/updatestatus',
                type     : 'POST',
                dataType : 'JSON',
                data : {
                    pid   : pid,
                    method : "delete"
                },
                beforeSend : function() {
                
                },
                success : function(response) {              
//                    w.('.modal-body').html(response);
//                    $('.playerdetails').html(response);
                    if(response==1){
                        w.parent().parent().remove();
                    }

                }
            
        });
        
    });
</script>