    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
          <h1>
            Contest Settings
            <small>for your next cool web APP</small>
          </h1>
          <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-futbol-o"></i> Home</a></li>
            <li>Contest Settings</li>
            <li class="active">Add New Contest Type</li>
          </ol>
        </section>

        <!-- Main content -->
        <section class="content">
          <!-- Info boxes -->
          <div class="row">
          	<div class="col-md-12 col-sm-12 no-p-left no-p-right">
            	<div class="panel panel-black no-radius">
                	<div class="panel-heading paddingLR-md paddingTB-sm no-radius">
                    	<h3 class="font-Russo-One no-margin">New Contest Type</h3>
                    </div>
                </div>
            </div>
          </div>
          
          <div class="row">
          	<div class="col-md-12 col-sm-12">
            	<div class="panel panel-gray">
                	<div class="panel-heading paddingLR-md paddingTB-xs">
                    	<h4 class="font-Libre-Baskerville inline-block"><span class="m-right-sm"><i class="fa fa-edit"></i></span>Manage Contest Type</h4>
                        <a class="btn btn-blue m-top-xs pull-right" href="/admin/contesttype-details">Contest Type Details</a>
                    </div>
                    <div class="panel-body padding-md">
                    	<div class="row">
                            <form method ="POST" id="addnewcontesttype" name="addnewcontesttype">
                            <div class="col-sm-8 col-xs-12 col-sm-offset-2 col-xs-offset-0">
                            	<div class="form-group">
                                	<label for="contestTypeName">Name <span>*</span></label>
                                    <div class="input-group col-xs-12">
                                    	<input class="form-control" type="text"  name ="contestTypeName" id="contestTypeName" value="">
                                    </div>
                                </div>
                                <div class="form-group">
                                	<label for="status">Status</label>
                                    <div class="input-group col-xs-12">
                                    	<select class="form-control" name="status" id="status">
                                        	<option value ="1">Activate</option>
                                            <option value="0">Deactivate</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group">
                                	<label for="Description">Description <span>*</span></label>
                                    <div class="input-group col-xs-12">
                                    	<input class="form-control" type="text"  name ="Description" id="Description" value="">
                                    </div>
                                </div>
                                <div class="form-group">
                                	<button type="submit" class="btn btn-blue">Save Changes</button>	                               
                                </div>
                          	</div>
                            </form>
                     	</div>
                    </div>
                </div>
            </div>
          </div>
          
          
         
        </section><!-- /.content -->
      </div>
<script>
        /*
   * dev:priyankav varanasi
   * date:22/6/2015
   * desc: to validate add new contest type
   */ 
                   $(function() {
   $.validator.addMethod("regex", function(value, element, regexpr) {          
     return regexpr.test(value);
   });
 
   $('#addnewcontesttype').validate({
                onkeyup: function(element) {
                    $(element).valid();
                },     
                rules: {
                   contestTypeName: {
                        required:true
                                   },
                                   Description:{
                                      required:true     
                                   }
                 },
                messages: {
                  contestTypeName: {
                         required:"Please enter contest type name"
                                   },
                    Description:{
                        required:"Please enter contest description"
                    
                               }
                 
                }

    });
    });
    </script>