      <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
          <h1>
            Contest Settings
            <small>for your next cool web APP</small>
          </h1>
          <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-futbol-o"></i> Home</a></li>
            <li>Contest Settings</li>
            <li class="active">Contest Type Details</li>
          </ol>
        </section>

        <!-- Main content -->
        <section class="content">
          <!-- Info boxes -->
          <div class="row">
          	<div class="col-md-12 col-sm-12 no-p-left no-p-right">
            	<div class="panel panel-black no-radius">
                	<div class="panel-heading paddingLR-md paddingTB-sm no-radius">
                    	<h3 class="font-Russo-One no-margin">Contest Type Details</h3>
                    </div>
                </div>
            </div>
          </div>
          
          <div class="row">
          	<div class="col-md-12 col-sm-12">
            	<div class="panel panel-gray">
                	<div class="panel-heading paddingLR-md paddingTB-xs">
                    	<h4 class="font-Libre-Baskerville inline-block">Contest Type Manage</h4>
                        <a class="btn btn-blue m-top-xs pull-right" href="/admin/add-newcontesttype"><i class="fa fa-plus-circle" >Add New Contest Type</i></a>
                    </div>
                    <div class="panel-body">
                    	<div class="">
                        	<div class="table-responsive">
                            	<table id="contestTypeDetails" class="display table text-center" data-page-length="10" data-order="[[ 1, &quot;asc&quot; ]]" cellspacing="0" width="100%">
                                	<thead>
                                    	<tr>
                                        	<th>Sr No</th>
                                            <th>Name</th>
                                            <th>Status</th>
                                            <th>Action</th>
                                            <th class="">Delete/Edit</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <?php if(isset($this->contesttypeinfo)){ $i =0; foreach($this->contesttypeinfo as $contesttype) { $i++ ; ?>
                                            
                                    	<tr>
                                            <td><?php echo $i;?></td>
                                            <td class="typename"><?php echo $contesttype['name'];?></td>
                                            <?php if($contesttype['status']==1){ ?>
                                                <td  id="activecontesttype_<?php echo $contesttype['con_type_id']; ?>" class="center js-sortable-handle contesttypeactive">Active</td>
                                                <td class="center" style="width: 80px;"><a href="#" id="<?php if (isset($contesttype['con_type_id'])): echo "contesttype_" . $contesttype['con_type_id'];endif;?>" class="contesttypedeactive">
                                                <span id="activetype_<?php echo $contesttype['con_type_id']; ?>" data-contesttype ="<?php echo $contesttype['con_type_id']; ?>" class="label label-danger deactivatecontesttype">Deactivate</span></a></td>
                                               <?php } else { ?>
                                                <td id="activecontesttype_<?php echo $contesttype['con_type_id']; ?>" class="center js-sortable-handle contesttypeactive">Suspended</td>
                                                <td class="center" style="width: 80px;">
                                                    <a  id="<?php if (isset($contesttype['con_type_id'])): echo "contesttype_" . $contesttype['con_type_id']; endif;?>" class="contesttypeactive">
                                                <span id="activetype_<?php echo $contesttype['con_type_id']; ?>" data-contesttype= "<?php echo $contesttype['con_type_id']; ?>" class="label label-success activatecontesttype">Activate</span>
                                                    </a>
                                                </td>
                                               <?php }?> 
                                            <td class="text-center">
                                            	<a data-toggle="modal" data-target="#deleteContest" class="text-black m-right-sm deletecontesttype" contest-typedel="<?php echo $contesttype['con_type_id']; ?>" href="#"><span><i class="fa fa-times"></i></span></a>
                                            	<a  class="text-black editcontesttype" data-editid="<?php echo $contesttype['con_type_id']; ?>"><span><i class="fa fa-edit"></i></span></a>
                                            </td>
                                            
                                        </tr>
                                        <?php } }?>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                        
                        
                    </div>
                </div>
            </div>
          </div>
          
          
         
        </section><!-- /.content -->
      </div>

      <div class="modal fade" id="editContestType" role="dialog" aria-hidden="true">
                	<div class="modal-dialog">
                    	<div class="modal-content modal-content-bg">
                        	<div class="modal-header model-header-bg no-border-bottom">
                            	<button type="button" data-dismiss="modal" class="close text-white"><span aria-hidden="true" aria-label="Close">&times;</span></button>
                            	
                                <h3 class="font-Titillium-Web no-margin text-center">Edit Contest Type</h3>
                                
                            </div>
                            <div class="modal-body">
                            	<div class="panel panel-black">
                                	<div class="panel-heading paddingLR-md">
                                    	<h4><span class="m-right-sm"><i class="fa fa-edit"></i></span>Manage Contest Type</h4>
                                    </div>
                                    <div class="panel-body padding-sm">
                                    	<div class="row">
                                        	<div class="col-sm-12">
                                                    <form id="admineditcontest" name  ="admineditcontest"> 
                                            	<div class="form-group">
                                                    <input class="form-control hidden" type="number" name="conedit" id="contTpedit" value="">
                                                	<label for="contestTypeName">Name <span>*</span></label>
                                                    <div class="input-group col-xs-12">
                                                    	<input class="form-control" type="text"  name = "contestTypeName" id="contestTypeName" value="">
                                                    </div>
                                                </div>
                                                <div class="form-group">
                                                	<label for="status">Status</label>
                                                    <div class="input-group col-xs-12">
                                                    	<select class="form-control" name="status" id="status">
                                                        	<option value="1">Active</option>
                                                            <option value="0">Deactive</option>
                                                        </select>
                                                    </div>
                                                </div>
                                                    </form>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="modal-footer light-bg clear-both no-border-top">
                            	
                                <div class="text-center">
                                	<button class="btn btn-blue savecontesttype">Save Changes</button>
                                	<button data-dismiss="modal" class="btn btn-gray font-Russo-One">Cancel</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
<script>
          
  /*
   * dev:priyankav varanasi
   * date:5/5/2015
   * desc: To deactivate contest type 
   */
   $(document).on('click','.deactivatecontesttype',function(){
        var contypeid = $(this).attr('data-contesttype');
            $.ajax({
            url: './user-ajax-handler',
            type: 'POST',
            datatype: 'json',
            data: {
                method: 'activedeactivecontesttype',
                con_type_id: contypeid
            },
            beforeSend: function() {
                console.log('deactivating contesttype..')
            },
            success: function(response) {
                if (response) {
                 var clnew = response.replace(/(\r\n|\n|\r)/gm,"");
                  var v = clnew.replace(/\"/g, ""); 
                  var cl = "activecontesttype_"+v;
                      var clu = "contesttype_" +v;
                   $("#" +cl).html('Suspended');
                    $("#" + clu).html('<span id="activetype_'+v+'" class="label label-success activatecontesttype" data-contesttype="'+v+'">Activate</span>');
                }
            }
        });
  });
  
    /*
   * dev:priyankav varanasi
   * date:11/5/2015
   * desc: to activate contest type on call
   */
   $(document).on('click','.activatecontesttype',function(){
        var contypeid = $(this).attr('data-contesttype');
            $.ajax({
            url: './user-ajax-handler',
            type: 'POST',
            datatype: 'json',
            data: {
                method: 'activedeactivecontesttype',
                con_type_id: contypeid
            },
            beforeSend: function() {
                console.log('activating contesttype..')
            },
            success: function(response) {
                if (response) {
                var clnew = response.replace(/(\r\n|\n|\r)/gm,"");
                var c = clnew.replace(/\"/g, ""); 
              
                 var cl = "activecontesttype_"+c;
                    var clu = "contesttype_"+c;
                   $("#"+cl).html('Active');
                    $("#"+ clu).html('<span id="activetype_'+c+'" class="label label-danger deactivatecontesttype" data-contesttype="'+c+'">Deactivate</span>');
                }
            }
        });
  });
    /*
   * dev:priyankav varanasi
   * date:11/5/2015
   * desc: to delete contest type
   */
    $(document.body).on('click','.deletecontesttype',function(){ 
    var w = $(this);
           var del_contesttype = $(this).attr('contest-typedel');
          
          $.ajax({
             url: './user-ajax-handler',
              type: 'POST',
            datatype: 'json',
          data:{
              contesttypedel: del_contesttype,
              method :'contesttypedelete'
        },
            success: function(response){
                console.log($(this));
                 w.parent().parent().hide(); 
            }

            });
           
       });
       
       
            /*
   * dev:priyankav varanasi
   * date:11/5/2015
   * desc: to edit contest type details
   */ 
  $(document.body).on('click','.editcontesttype',function(){
      var z = $(this);
      var statusval;
       var edittypename = z.attr('data-editid');
      
       var contesttypename = "";
       var status = "" ;
        contesttypename = z.parent().siblings('.typename').html();
        status = z.parent().siblings('.contesttypeactive').html();
      if(status==='Active'){
         statusval = '1';
     }else{
         statusval = '0';
     }
       $('#contestTypeName').val(contesttypename);
       $('#contTpedit').val(edittypename);
       $('#status').val(statusval);
       
       $('#editContestType').modal('show');
        
    });
    
    
           /*
   * dev:priyankav varanasi
   * date:6/5/2015
   * desc: to update the contest type details via ajax
   */ 
    
    $(document.body).on('click','.savecontesttype',function(e){
        e.preventDefault();
        var contypenmae = $('#contestTypeName').val();
        var coneditval = $('#contTpedit').val();
//        alert(coneditval);
        var status = $('#status').val();
        if($('#admineditcontest').valid()){
      $.ajax({
               url: './user-ajax-handler',
              type: 'POST',
              datatype: 'json',
          data:{
              conname:contypenmae,
              conedit :coneditval,
              status:status,
              method :'updatecontesttype'
        },
        beforeSend: function(){
            console.log('updating the contest type details..');
        },
            success: function(response){
                window.location.reload(true);
                  
            }
              
        });
    }
      
    });
    
     
        /*
   * dev:priyankav varanasi
   * date:22/6/2015
   * desc: to validate edit contest type
   */ 
                   $(function() {
   $.validator.addMethod("regex", function(value, element, regexpr) {          
     return regexpr.test(value);
   });
 
   $('#admineditcontest').validate({
                onkeyup: function(element) {
                    $(element).valid();
                },     
                rules: {
                   contestTypeName: {
                        required:true
                                   }
                 },
                messages: {
               
                    offeridentity:{
                        required:"Please enter contest type name"
                    
        }
              
                   
                }

    });
    });
    </script>