<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Contest Settings
            <small>for your next cool web APP</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-futbol-o"></i> Home</a></li>
            <li>Contest Settings</li>
            <li class="active">Contest Details</li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">
        <!-- Info boxes -->
        <div class="row">
            <div class="col-md-12 col-sm-12 no-p-left no-p-right">
                <div class="panel panel-black no-radius">
                    <div class="panel-heading paddingLR-md paddingTB-sm no-radius">
                        <h3 class="font-Russo-One no-margin">Contest Details</h3>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12 col-sm-12">
                <div class="panel panel-gray">
                    <div class="panel-heading paddingLR-md paddingTB-xs">
                        <h4 class="font-Libre-Baskerville inline-block">Contest Manage</h4>
                        <a class="btn btn-blue m-top-xs pull-right" href="/admin/addnewcontest"><span class="m-right-sm"><i class="fa fa-plus-circle"></i></span>Add New Contest</a>
                    </div>
                    <div class="panel-body">
                        <div role="tabpanel">
                            <ul class="nav nav-tabs" role="tablist">
                                <li role="presentation" class="active"><a href="#allUsers" aria-controls="allUsers" role="tab" data-toggle="tab"> All Users </a></li>
                                <li role="presentation" class=""><a href="#Upcoming" aria-controls="Upcoming" role="tab" data-toggle="tab"> Upcoming </a></li>
                                <li role="presentation" class=""><a href="#Completed" aria-controls="Completed" role="tab" data-toggle="tab"> Completed </a></li>
                                <li role="presentation" class=""><a href="#Canceled" aria-controls="Canceled" role="tab" data-toggle="tab"> Canceled </a></li>
                                <li role="presentation" class=""><a href="#Live" aria-controls="Live" role="tab" data-toggle="tab"> Live </a></li>
<!--                            <button class="btn btn-light-gray paddingLR-md active"><a href="#allUsers" aria-controls="allUsers" role="tab" data-toggle="tab">All</a></button>
                                <button class="btn btn-light-gray"><a href="#Upcoming" aria-controls="allUsers" role="tab" data-toggle="tab">Upcoming</a></button>
                                <button class="btn btn-light-gray"><a href="#Completed" aria-controls="allUsers" role="tab" data-toggle="tab">Completed</a></button>
                                <button class="btn btn-light-gray"><a href="#Canceled" aria-controls="allUsers" role="tab" data-toggle="tab">Canceled</a></button>
                                <button class="btn btn-light-gray"><a href="#Live" aria-controls="allUsers" role="tab" data-toggle="tab">Live</a></button>-->
                            </ul>
                            <div class="tab-content">
                                <div role="tabpanel" class="tab-pane active" id="allUsers">
                                    <div class="m-top-md">
                                        <div class="table-responsive">
                                            <table id="contestDetails" class="display table" data-page-length="10" data-order="[[ 1, &quot;asc&quot; ]]" cellspacing="0" width="100%">
                                                <thead>
                                                    <tr>
                                                        <th>Sr No</th>
                                                        <th>Name</th>
                                                        <th>Sport</th>
                                                        <th>Type</th>
                                                        <th>Fee</th>
                                                        <th>Start Time</th>
                                                        <th>End Time</th>
                                                        <th>Prize Pool</th>
                                                        <th>FPP</th>
                                                        <th>Status</th>
                                                        <th>Delete/Edit</th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    <?php if (isset($this->contests)) {
                                                        $row = 0;
                                                        foreach ($this->contests as $val) {
                                                            $row ++; ?>
                                                            <tr>
                                                                <td><?php echo $row; ?></td>
                                                                <td class =contestsname"><?php echo $val['contest_name']; ?></td>
                                                                <td class = "sportname" >PGA</td>
                                                                <td class="contest_type"> <?php
                                                                    switch ($val['contest_type']):
                                                                        case 1 : echo "Gauranteed";
                                                                            break;
                                                                        case 2 : echo "Qualifier";
                                                                            break;
                                                                        case 3 : echo "Head-to-Head";
                                                                            break;
                                                                        case 4 : echo "50/50";
                                                                            break;
                                                                        case 5 : echo "Leagues";
                                                                            break;
                                                                        case 6 : echo "Multipliers";
                                                                            break;
                                                                        case 7: echo "Steps";
                                                                            break;
                                                                    endswitch;
                                                                    ?></td>
                                                                <td class="entryfee"><?php echo $val['entry_fee']; ?></td>
                                                                <td class="starttime"><?php echo date("j F , Y", strtotime($val['start_time']));  ?></td>
                                                                <td class ="endtime"><?php echo date("j F , Y", strtotime($val['end_time']));  ?></td>
                                                                <td class = "prizepool"><?php echo $val['prize_pool']; ?></td>
                                                                <td class ="fpp"><?php echo $val['fpp']; ?></td>
                                                                <td class ="status"><?php if($val['status']==1){ echo 'Active';} else{ echo 'Inactive';}?></td>
                                                                <td class="text-center">
                                                                    <a data-toggle="modal"  data-id="<?php echo $val['contest_id'];?>" data-target="#deleteContest" class="text-black m-right-sm remove" href="#"><span><i class="fa fa-times"></i></span></a>
                                                                    <a class="text-black editcontestdet" data-edit ="<?php echo $val['contest_id'];?>"><span><i class="fa fa-edit"></i></span></a>
                                                                </td>

                                                            </tr>
    <?php }
} ?>  
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                                <div role="tabpanel" class="tab-pane" id="Upcoming">
                                    <div class="m-top-md">
                                        <div class="table-responsive">
                                            <table id="UpcomingDetails" class="display table" data-page-length="10" data-order="[[ 1, &quot;asc&quot; ]]" cellspacing="0" width="100%">
                                                <thead>
                                                    <tr>
                                                        <th>Sr No</th>
                                                        <th>Name</th>
                                                        <th>Sport</th>
                                                        <th>Type</th>
                                                        <th>Fee</th>
                                                        <th>Start Time</th>
                                                        <th>End Time</th>
                                                        <th>Prize Pool</th>
                                                        <th>FPP</th>
                                                        <th>Status</th>
                                                        <th>Delete/Edit</th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    <?php if (isset($this->upcoming)) {
                                                        $row = 0;
                                                        foreach ($this->upcoming as $val) {
                                                            $row ++; ?>
                                                            <tr>
                                                                <td><?php echo $row; ?></td>
                                                                <td class =contestsname"><?php echo $val['contest_name']; ?></td>
                                                                <td class = "sportname" >PGA</td>
                                                                <td class="contest_type"> <?php
                                                                    switch ($val['contest_type']):
                                                                        case 1 : echo "Gauranteed";
                                                                            break;
                                                                        case 2 : echo "Qualifier";
                                                                            break;
                                                                        case 3 : echo "Head-to-Head";
                                                                            break;
                                                                        case 4 : echo "50/50";
                                                                            break;
                                                                        case 5 : echo "Leagues";
                                                                            break;
                                                                        case 6 : echo "Multipliers";
                                                                            break;
                                                                        case 7: echo "Steps";
                                                                            break;
                                                                    endswitch;
                                                                    ?></td>
                                                                <td class="entryfee"><?php echo $val['entry_fee']; ?></td>
                                                                <td class="starttime"><?php echo date("j F , Y", strtotime($val['start_time']));  ?></td>
                                                                <td class ="endtime"><?php echo date("j F , Y", strtotime($val['end_time']));  ?></td>
                                                                <td class = "prizepool"><?php echo $val['prize_pool']; ?></td>
                                                                <td class ="fpp"><?php echo $val['fpp']; ?></td>
                                                                <td class ="status"><?php if($val['status']==1){ echo 'Active';} else{ echo 'Inactive';}?></td>
                                                                <td class="text-center">
                                                                    <a data-toggle="modal"  data-id="<?php echo $val['contest_id'];?>" data-target="#deleteContest" class="text-black m-right-sm remove" href="#"><span><i class="fa fa-times"></i></span></a>
                                                                    <a  class="text-black editcontestdet" data-edit ="<?php echo $val['contest_id'];?>"><span><i class="fa fa-edit"></i></span></a>
                                                                </td>

                                                            </tr>
    <?php }
} ?>  
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                                  <div role="tabpanel" class="tab-pane" id="Completed">
                                    <div class="m-top-md">
                                        <div class="table-responsive">
                                            <table id="CompletedDetails" class="display table" data-page-length="10" data-order="[[ 1, &quot;asc&quot; ]]" cellspacing="0" width="100%">
                                                <thead>
                                                    <tr>
                                                        <th>Sr No</th>
                                                        <th>Name</th>
                                                        <th>Sport</th>
                                                        <th>Type</th>
                                                        <th>Fee</th>
                                                        <th>Start Time</th>
                                                        <th>End Time</th>
                                                        <th>Prize Pool</th>
                                                        <th>FPP</th>
                                                        <th>Status</th>
                                                        <th>Delete/Edit</th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    <?php if (isset($this->completed)) {
                                                        $row = 0;
                                                        foreach ($this->completed as $val) {
                                                            $row ++; ?>
                                                            <tr>
                                                                <td><?php echo $row; ?></td>
                                                                <td class =contestsname"><?php echo $val['contest_name']; ?></td>
                                                                <td class = "sportname" >PGA</td>
                                                                <td class="contest_type"> <?php
                                                                    switch ($val['contest_type']):
                                                                        case 1 : echo "Gauranteed";
                                                                            break;
                                                                        case 2 : echo "Qualifier";
                                                                            break;
                                                                        case 3 : echo "Head-to-Head";
                                                                            break;
                                                                        case 4 : echo "50/50";
                                                                            break;
                                                                        case 5 : echo "Leagues";
                                                                            break;
                                                                        case 6 : echo "Multipliers";
                                                                            break;
                                                                        case 7: echo "Steps";
                                                                            break;
                                                                    endswitch;
                                                                    ?></td>
                                                                <td class="entryfee"><?php echo $val['entry_fee']; ?></td>
                                                                <td class="starttime"><?php echo date("j F , Y", strtotime($val['start_time']));  ?></td>
                                                                <td class ="endtime"><?php echo date("j F , Y", strtotime($val['end_time']));  ?></td>
                                                                <td class = "prizepool"><?php echo $val['prize_pool']; ?></td>
                                                                <td class ="fpp"><?php echo $val['fpp']; ?></td>
                                                                <td class ="status"><?php if($val['status']==1){ echo 'Active';} else{ echo 'Inactive';}?></td>
                                                                <td class="text-center">
                                                                    <a data-toggle="modal"  data-id="<?php echo $val['contest_id'];?>" data-target="#deleteContest" class="text-black m-right-sm remove" href="#"><span><i class="fa fa-times"></i></span></a>
                                                                    <a  class="text-black editcontestdet" data-edit ="<?php echo $val['contest_id'];?>"><span><i class="fa fa-edit"></i></span></a>
                                                                </td>

                                                            </tr>
    <?php }
} ?>  
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                             <div role="tabpanel" class="tab-pane" id="Canceled">
                                    <div class="m-top-md">
                                        <div class="table-responsive">
                                            <table id="Canceleddetails" class="display table" data-page-length="10" data-order="[[ 1, &quot;asc&quot; ]]" cellspacing="0" width="100%">
                                                <thead>
                                                    <tr>
                                                        <th>Sr No</th>
                                                        <th>Name</th>
                                                        <th>Sport</th>
                                                        <th>Type</th>
                                                        <th>Fee</th>
                                                        <th>Start Time</th>
                                                        <th>End Time</th>
                                                        <th>Prize Pool</th>
                                                        <th>FPP</th>
                                                        <th>Status</th>
                                                        <th>Delete/Edit</th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    <?php if (isset($this->canceled)) {
                                                        $row = 0;
                                                        foreach ($this->canceled as $val) {
                                                            $row ++; ?>
                                                            <tr>
                                                                <td><?php echo $row; ?></td>
                                                                <td class =contestsname"><?php echo $val['contest_name']; ?></td>
                                                                <td class = "sportname" >PGA</td>
                                                                <td class="contest_type"> <?php
                                                                    switch ($val['contest_type']):
                                                                        case 1 : echo "Gauranteed";
                                                                            break;
                                                                        case 2 : echo "Qualifier";
                                                                            break;
                                                                        case 3 : echo "Head-to-Head";
                                                                            break;
                                                                        case 4 : echo "50/50";
                                                                            break;
                                                                        case 5 : echo "Leagues";
                                                                            break;
                                                                        case 6 : echo "Multipliers";
                                                                            break;
                                                                        case 7: echo "Steps";
                                                                            break;
                                                                    endswitch;
                                                                    ?></td>
                                                                <td class="entryfee"><?php echo $val['entry_fee']; ?></td>
                                                                <td class="starttime"><?php echo date("j F , Y", strtotime($val['start_time']));  ?></td>
                                                                <td class ="endtime"><?php echo date("j F , Y", strtotime($val['end_time']));  ?></td>
                                                                <td class = "prizepool"><?php echo $val['prize_pool']; ?></td>
                                                                <td class ="fpp"><?php echo $val['fpp']; ?></td>
                                                                <td class ="status"><?php if($val['status']==1){ echo 'Active';} else{ echo 'Inactive';}?></td>
                                                                <td class="text-center">
                                                                    <a data-toggle="modal"  data-id="<?php echo $val['contest_id'];?>" data-target="#deleteContest" class="text-black m-right-sm remove" href="#"><span><i class="fa fa-times"></i></span></a>
                                                                    <a  class="text-black editcontestdet"  data-edit ="<?php echo $val['contest_id'];?>" ><span><i class="fa fa-edit"></i></span></a>
                                                                </td>

                                                            </tr>
    <?php }
} ?>  
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                                    <div role="tabpanel" class="tab-pane" id="Live">
                                    <div class="m-top-md">
                                        <div class="table-responsive">
                                            <table id="LiveDetails" class="display table" data-page-length="10" data-order="[[ 1, &quot;asc&quot; ]]" cellspacing="0" width="100%">
                                                <thead>
                                                    <tr>
                                                        <th>Sr No</th>
                                                        <th>Name</th>
                                                        <th>Sport</th>
                                                        <th>Type</th>
                                                        <th>Fee</th>
                                                        <th>Start Time</th>
                                                        <th>End Time</th>
                                                        <th>Prize Pool</th>
                                                        <th>FPP</th>
                                                        <th>Status</th>
                                                        <th>Delete/Edit</th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    <?php if (isset($this->livecontests)) {
                                                        $row = 0;
                                                        foreach ($this->livecontests as $val) {
                                                            $row ++; ?>
                                                            <tr>
                                                                <td><?php echo $row; ?></td>
                                                                <td class =contestsname ><?php echo $val['contest_name']; ?></td>
                                                                <td class = "sportname" >PGA</td>
                                                                <td class="contest_type"> <?php
                                                                    switch ($val['contest_type']):
                                                                        case 1 : echo "Gauranteed";
                                                                            break;
                                                                        case 2 : echo "Qualifier";
                                                                            break;
                                                                        case 3 : echo "Head-to-Head";
                                                                            break;
                                                                        case 4 : echo "50/50";
                                                                            break;
                                                                        case 5 : echo "Leagues";
                                                                            break;
                                                                        case 6 : echo "Multipliers";
                                                                            break;
                                                                        case 7: echo "Steps";
                                                                            break;
                                                                    endswitch;
                                                                    ?></td>
                                                                <td class="entryfee"><?php echo $val['entry_fee']; ?></td>
                                                                <td class="starttime"><?php echo date("j F , Y", strtotime($val['start_time']));  ?></td>
                                                                <td class ="endtime"><?php echo date("j F , Y", strtotime($val['end_time']));  ?></td>
                                                                <td class = "prizepool"><?php echo $val['prize_pool']; ?></td>
                                                                <td class ="fpp"><?php echo $val['fpp']; ?></td>
                                                                <td class ="status"><?php if($val['status']==1){ echo 'Active';} else{ echo 'Inactive';}?></td>
                                                                <td class="text-center">
                                                                    <a data-toggle="modal"  data-id="<?php echo $val['contest_id'];?>" data-target="#deleteContest" class="text-black m-right-sm remove" href="#"><span><i class="fa fa-times"></i></span></a>
                                                                    <a  class="text-black editcontestdet" data-edit ="<?php echo $val['contest_id'];?>" ><span><i class="fa fa-edit"></i></span></a>
                                                                </td>

                                                            </tr>
    <?php }
} ?>  
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                                
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>



    </section><!-- /.content -->
</div>

      <div class="modal fade" id="editContest" role="dialog" aria-hidden="true">
                	<div class="modal-dialog width70p">
                    	<div class="modal-content modal-content-bg">
                        	<div class="modal-header model-header-bg no-border-bottom">
                            	<button type="button" data-dismiss="modal" class="close text-white"><span aria-hidden="true" aria-label="Close">&times;</span></button>
                            	
                                <h3 class="font-Titillium-Web no-margin text-center">Edit Contest</h3>
                                
                            </div>
                            <div class="modal-body">
                            	<div class="panel panel-black">
                                	<div class="panel-heading paddingLR-md">
                                    	<h4><span class="m-right-sm"><i class="fa fa-edit"></i></span>Manage Contest Details</h4>
                                    </div>
                                    <input class="form-control hidden" type="text" id="contestID" value="">
                                    <div class="panel-body padding-sm">
                                    	<div class="row">
                                            <form id="editcontestform" name="editcontestform">
                                        	<div class="col-md-6 col-sm-6">
                                            	<div class="form-group">
                                                	<label for="contestName">Contest Name <span>*</span></label>
                                                    <div class="input-group col-xs-12">
                                                    	<input class="form-control" type="text" name ="contestName" id="contestName" value="">
                                                    </div>
                                                </div>
                                                <div class="form-group">
                                                	<label for="sportsID">Sports ID</label>
                                                    <div class="input-group col-xs-12">
                                                    	<input class="form-control" type="text" name="sportsID" id="sportsID" value="">
                                                    </div>
                                                </div>
                                                <div class="form-group">
                                                	<label for="pEntryLimit">Player (Entry Limit)</label>
                                                    <div class="input-group col-xs-12">
                                                    	<input class="form-control" type="text"  name="pEntryLimit" id="pEntryLimit" value="">
                                                    </div>
                                                </div>
                                                <div class="form-group">
                                                	<label for="cLimit">Challange Limit</label>
                                                    <div class="input-group col-xs-12">
                                                    	<input class="form-control" type="text" name="cLimit" id="cLimit" value="">
                                                    </div>
                                                </div>
                                                <div class="form-group">
                                                	<label for="entryFee">Entry Fee</label>
                                                    <div class="input-group col-xs-12">
                                                    	<input class="form-control" type="text" name="entryFee" id="entryFee" value="">
                                                    </div>
                                                </div>
                                                <div class="form-group">
                                                	<label for="matchID">Match ID</label>
                                                    <div class="input-group col-xs-12">
                                                    	<input class="form-control" type="text" name="matchID" id="matchID" value="" disabled>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="col-md-6 col-sm-6">
                                            	<div class="form-group">
                                                	<label for="prizePool">Prize Pool</label>
                                                    <div class="input-group col-xs-12">
                                                    	<input class="form-control" type="text" name="prizePool" id="prizePool" value="">
                                                    </div>
                                                </div>
                                                <div class="form-group">
                                                	<label for="fppReward">FPP Reward</label>
                                                    <div class="input-group col-xs-12">
                                                    	<input class="form-control" type="text" name="fppReward" id="fppReward" value="">
                                                    </div>
                                                </div>
                                                <div class="form-group">
                                                	<label for="msTime">Match Start Time</label>
                                                    <div class="input-group col-xs-12">
                                                    	<input class="form-control" type="text" name="msTime" id="msTime" value="" disabled>                                           </div>
                                                </div>
                                                <div class="form-group">
                                                	<label for="cType">Contest Type</label>
                                                    <div class="input-group col-xs-12">
                                                    	<select class="form-control"name="cType" id="cType">
                                                            <option value="1" selected="">Guaranteed</option>
                                                            <option value="2" selected="">qualifier</option>
                                                            <option value="3" selected="">head-to-head</option>
                                                            <option value="4" selected="">50/50</option>
                                                            <option value="5">Leagues</option>
                                                            <option value="6">multipliers</option>                                                             			                                                			<option value="5">Multipliers</option>
                                                            <option value="7">steps </option>  
                                                        </select>
                                                    </div>
                                                </div>
                                                <div class="form-group">
                                                	<label for="pType">Play Type</label>
                                                    <div class="input-group col-xs-12">
                                                    	<select class="form-control" name="pType" id="pType">
                                                        	<option value="1" selected="">Anyone</option>
                                                            <option value="2">Friend</option>
                                                        </select>
                                                    </div>
                                                </div>
                                                <div class="form-group">
                                                	<label for="prizes">Prizes</label>
                                                    <div class="input-group col-xs-12">
                                                    	<select class="form-control" name="prizes" id="prizes">
                                                        	<option value="0" selected="">No Prize</option>
                                                            <option value="1">Winner Takes All</option>
                                                            <option value="2">Top 2 Win</option>
                                                            <option value="3">Top 5 Win</option>
                                                            <option value="4">50/50</option>
                                                            <option value="5">custom payout</option>
                                                            
                                                        </select>
                                                    </div>
                                                </div>
                                                <div class="form-group">
                                                	<label for="description">Description</label>
                                                    <div class="input-group col-xs-12">
                                                    	<textarea class="form-control" name="description" id="description">
                                                        </textarea>
                                                        <span class="font-10 block">(Maximum characters: 650)</span>
                                                        <span class="font-10 block">You Have <span class="font-14">650</span> Characters Left</span>
                                                    </div>
                                                </div>
                                            </div>
                                        </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="modal-footer light-bg clear-both no-border-top">
                            	
                                <div class="text-center">
                                	<button class="btn btn-blue updatecontestdetails">Save Changes</button>
                                	<button data-dismiss="modal" class="btn btn-gray font-Russo-One">Cancel</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div><!---------Edit Contest------------>

<script>
    
    /*
   * dev:priyankav varanasi
   * date:11/05/2015
   * desc: to open the edit modal and show the contest details
   */ 
 
 
       $(document).on('click','.editcontestdet',function(){
           $('#editcontestform').validate().resetForm();
         
        var z = $(this);
                $('#contestID').val('');
                $('#contestName').val('');
                $('#sportsID').val('');
                $('#pEntryLimit').val('')
                $('#msTime').val('');
                $('#fppReward').val('');
                $('#description').val('');
                $('#entryFee').val('');
                $('#matchID').val('');
                $('#cType').val('');
                $('#prizes').val('')
                $('#prizePool').val('');
        var contests = z.attr('data-edit');
         $.ajax({
          url:"./user-ajax-handler",
          type: 'POST',
            datatype: 'json',
          data:{
            method :'editcontest',
            contestid : contests
          },
          beforeSend:function(){
              console.log('fetching contest details...');
                  
          },
          success: function(response){
              if(response){
                   response = JSON.parse(response);
               $(response).each(function (key,val) {
                 
                $('#contestID').val(val.contest_id);
                $('#contestName').val(val.contest_name);
                $('#sportsID').val(val.sport_id);
                $('#pEntryLimit').val(val.play_limit)
                $('#msTime').val(val.start_time);
                $('#fppReward').val(val.fpp);
                $('#description').val(val.description);
                $('#entryFee').val(val.entry_fee);
                $('#matchID').val(val.match_id);
                $('#cType').val(val.contest_type);
                $('#prizes').val(val.prize_type);
                $('#prizePool').val(val.prize_pool);
                    
               });
      $('#editContest').modal('show');

              }
   
            
       }
         
      });

        
    });
  
    /*
     * dev: priyanka varanasi
     * date : 11/5/2015
     * desc: to delete the contest from db
     */
  $(document.body).on('click','.remove',function(){
      var x = $(this);
      var con_id = $(this).attr('data-id');
      $.ajax({
          url:"./user-ajax-handler",
          type: 'POST',
            datatype: 'json',
          data:{
            method :'contestdelete',
            contestid : con_id
          },
          beforeSend:function(){
              console.log('deleting contest...');
                  
          },
          success: function(response){
            x.parent().parent().hide();
          }
         
      });
      
     
  }); 
  
  
   
           /*
   * dev:priyankav varanasi
   * date:12/5/2015
   * desc: to update the contest details via ajax
   */ 
    
    $(document.body).on('click','.updatecontestdetails',function(e){
        e.preventDefault();
        var coninfo  = new Array;
        var data = new Array();
          var conID  =  $('#contestID').val();
          data[1] =     $('#contestName').val();
          data[2] =   $('#sportsID').val();
          data[3] =  $('#pEntryLimit').val()
          data[4] =  $('#msTime').val();
          data[5] = $('#fppReward').val();
          data[6] = $('#description').val();
          data[7] =  $('#entryFee').val();
          data[8] =   $('#matchID').val();
          data[9] =  $('#cType').val();
          data[10]=  $('#prizes').val();
          data[11] =  $('#prizePool').val();
     
     coninfo.push({contest_name:data[1],sport_id:data[2],play_limit:data[3],start_time:data[4],fpp:data[5],description:data[6],entry_fee:data[7],match_id :data[8],contest_type:data[9],prize_type:data[10],prize_pool:data[11]});
    
 if($('#editcontestform').valid()){
       $.ajax({
              url: './user-ajax-handler',
              type: 'POST',
              datatype: 'json',
          data:{
              data : coninfo,
              method :'updatecontestdet',
              contestid :conID
        },
        beforeSend: function(){
            console.log('updating the contest details..');
        },
            success: function(response){
                window.location.reload(true);
                  
            }
              
        });
    }
      
    });
     
  </script>
    <script>
    $('#contestDetails').DataTable({
        "bLengthChange": false,
    });
  $('#LiveDetails').DataTable({
        "bLengthChange": false,
    });
    $('#Canceleddetails').DataTable({
        "bLengthChange": false,
    });
    $('#CompletedDetails').DataTable({
        "bLengthChange": false,
    });
    $('#UpcomingDetails').DataTable({
        "bLengthChange": false,
    });
    
                  $(function() {
   $.validator.addMethod("regex", function(value, element, regexpr) {          
     return regexpr.test(value);
   });
    $("#editcontestform").validate({
        onkeyup: function(element) {
                    $(element).valid();
                },
        rules: {
            contestName: {
                required: true,
                maxlength: 650
            },
            sportsID: {
                required: true,
                maxlength: 3,
                regex: /^\d+$/
            },
            pEntryLimit: {
                required: true,
                maxlength: 3,
                regex: /^\d+$/
            },
            cLimit: {
                required: true,
                regex: /^(?:\d*\.\d{1,2}|\d+)$/
            },
            entryFee: {
                required: true
            },
            prizePool: {
                required: true,
                regex: /^(?:\d*\.\d{1,2}|\d+)$/
            },
            fppReward: {
                required: true,
                maxlength: 8,
                regex: /^\d+$/
            },
            cType: {
                required: true
            },
            pType: {
                required: true
            },
            prizes: {
                required: true
            },
            description: {
                required: true,
                maxlength: 650
            }            
            
        },
        messages: {
            contestName: {
                required: "Contest name is required",
                maxlength: "Maximum number of characters allowed is 650"
            },
            pEntryLimit: {
                required: "Entry limit is required",
                maxlength: "Maximum 3 digits are allowed",
                regex: "Please enter only digits"
            },
            cLimit: {
                required: "Challenge limit is required",
                maxlength: "Maximum 3 digits are allowed",
                regex: "Please enter only digits"
            },
            entryFee: {
                required: "Entry fee is required",
                regex: "Please enter numbers only(decimals also allowed)"
            },
            prizePool: {
                required: "Prize pool is required",
                regex: "Please enter numbers only(decimals also allowed)"
            },
            fppReward: {
                required: "FPP Reward is required",
                maxlength: "Maximum 8 digits are allowed",
                regex: "Please enter digits only"
            },
            cType: {
                required: "Contest Type is required"
            },
         
            pType: {
                required: "Play Type is required"
            },
            prizes: {
                required: "Prize is required"
            },
            description: {
                required: "Description is required",
                maxlength: "Maximum number of characters allowed is 650"
            }
            
        }

    });
    });
 </script>   