
<div id="content">
	<h4>New Featured Contest</h4>
<div class="innerLR">

	<!-- Widget -->
	<div class="widget">
		
		<!-- Widget heading -->
		<div class="widget-head">
			<h4 class="heading">Manage Featured Contest</h4>
                        </div>
                <div>
<!--                    <a class="btn btn-icon btn-primary glyphicons circle_ok" href="/admin/new-contest" type="button" style="margin-left:900px">
                            <i></i> Add New Contest
                             </a>-->
	 </div>
		<!-- // Widget heading END -->
		
		<div class="widget-body">
		
			<!-- Table -->
			<table  cellpadding="0" cellspacing="0" border="0" class="datatable table table-striped table-bordered">
			
				<!-- Table heading -->
				<thead>
					<tr>
						<th>Name</th>
						<th>Sports ID</th>
						<th>Type</th>
						<th>Fee</th>						
                                                <th>Start Time</th>
                                                <th>Prizes</th>
                                                <th>Prize Pool</th>
                                                <th>Match ID</th>
                                                <th>FPP</th>
                                                <th>Action</th>
                                                
					</tr>
				</thead>
				<!-- // Table heading END -->
				
				<!-- Table body -->
				<tbody>
				
					
					<?php if(isset($this->contest)): foreach ($this->contest as $contest): ?>
					<!-- Table row -->
					<tr class="gradeA">
						<td><?php echo $contest['contest_name']; ?></td>
                                                <td><?php echo $contest['sports_id']; ?></td>
                                                <td><?php echo $contest['con_type_id']; ?></td>
                                                <td><?php echo $contest['entry_fee']; ?></td>
                                                <td><?php echo date("j F Y, h:i:s A", strtotime($contest['start_time'])); // echo $contest['start_time']; ?></td>
                                                <td><?php echo $contest['prizes']; ?></td>
                                                <td><?php echo $contest['prize_pool']; ?></td>
                                                <td><?php echo $contest['match_id']; ?></td>
                                                <td><?php echo $contest['fpp']; ?></td>						 
                                                <td>
                                                    <a id="contestupdate_<?php echo $contest['contest_id']; ?>" href="#" class="btn-action glyphicons ok_2 btn-success featuredcontest"><i></i></a>
                                                    <!--<a href="/admin/edit-contest/<?php // echo $contest['contest_id']; ?>" class="btn-action glyphicons pencil btn-success"><i></i></a>-->
                                                </td>

					</tr>
					<!-- // Table row END -->
					<?php endforeach; endif; ?>
					
				</tbody>
				<!-- // Table body END -->
				
			</table>
			<!-- // Table END -->
			
		
	</div>	
</div>			
</div>
<script>
    $('#menu_components2').removeClass('collapse').addClass('in collapse');
    $('#contest_setting_menu').removeClass('hasSubmenu glyphicons cogwheels').addClass('hasSubmenu glyphicons cogwheels active');
    $('#featured_contest_menu').addClass('active');    
</script>


