<div id="content">
	<h4>Match Details</h4>
</div>
<div class="innerLR">

	<!-- Widget -->
	<div class="widget">
		
		<!-- Widget heading -->
		<div class="widget-head">
			<h4 class="heading">Match Manage</h4>
		</div>
		<!-- // Widget heading END -->
		
    <div class="widget-body">
        <form class="form-horizontal margin-none"  method="post">
                    <div class="tab-content pad0">

                            <!-- Tab content -->
                            <div class="tab-pane active" id="account-details">

                                    <!-- Row -->
                                    <div class="row-fluid">

                                            <!-- Column -->
                                            <div class="span6">

                                                    <!-- Group -->
                                                    <div class="control-group">
                                                            <label class="control-label">Sports</label>
                                                            <div class="controls">
                                                                <select class="span4" name="sports">                                                                    
                                                                    <option value="">Select</option>    
                                                                    <?php if(isset($this->sports)): foreach ($this->sports as $sportsDetails): ?>
                                                                    <option value="<?php echo $sportsDetails['sports_id']; ?>"><?php echo $sportsDetails['display_name']; ?></option>  
                                                                    <?php endforeach; endif; ?>
                                                                </select>        
                                                            </div>
                                                    </div>
                                                    <!-- // Group END -->
                                            </div>
                                            <!-- // Column END -->

                                            <!-- Column -->
                                            <div class="span6">							

                                                    <!-- Group -->
                                                    <div class="control-group">
                                                            <label class="control-label">Date</label>
                                                            <div class="controls">
                                                               <select class="span4" name="status">
                                                                   <option value="">Select</option>                                                                          
                                                                </select> 
                                                            </div>
                                                    </div>
                                                    <!-- // Group END -->                                                  
                                            </div>
                                            <!-- // Column END -->

                                    </div>
                                    <!-- // Row END -->

                                    <div class="separator line bottom"></div>
                                    
                                    <!-- Table -->
			<table  cellpadding="0" cellspacing="0" border="0" class="datatable table table-striped table-bordered">
			
				<!-- Table heading -->
				<thead>
					<tr>
						<th class="center">Sno.</th>
						<th class="center">Match ID</th>
						<th class="center">Time</th>
						<th class="center">Date</th>
						<th class="center">Status</th>
                                                <th class="center">Action</th>
					</tr>
				</thead>
				<!-- // Table heading END -->
				
				<!-- Table body -->
				<tbody>				
					<!-- Table row -->
					<tr class="gradeA">
						<td class="center">2</td>
						<td class="center">123545</td>
						<td class="center">4:00 AM</td>
						<td class="center">20.03.2014</td>
						<td class="center">Not Started</td>
                                                <td class="center" style="width: 80px;">
                                                <a href="/admin/contest/new-contest"class="usersactive">
                                                <span id="activeclass_"  class="label label-block label-inverse">Create Contest</span>
                                                </a>
                                                </td>
					</tr>
					<!-- // Table row END -->
					<!-- Table row -->
					<tr class="gradeA">
						<td class="center">1</td>
						<td class="center">123545</td>
						<td class="center">4:00 AM</td>
						<td class="center">20.03.2014</td>
						<td class="center">Not Started</td>
                                                <td class="center" style="width: 80px;">
                                                <a href="/admin/new-contest"class="usersactive">
                                                <span id="activeclass_"  class="label label-block label-inverse">Create Contest</span>
                                                </a>
                                                </td>
					</tr>
					<!-- // Table row END -->                                        
				</tbody>
				<!-- // Table body END -->
				
			</table>
			<!-- // Table END -->

                            </div>
                            <!-- // Tab content END -->

                            <!-- Tab content -->                    

                            <div class="tab-pane" id="account-settings">
                               

                                    <div class="separator line bottom"></div>

                                    <!-- Form actions -->
                                    <div class="form-actions" class="margin-none">
                                            <button type="submit" class="btn btn-icon btn-primary glyphicons circle_ok"><i></i>Save changes</button>
                                    </div>
                                    <!-- // Form actions END -->

                            </div>
                            <!-- // Tab content END -->
                    </div>
            </form>
    </div>	
</div>			
</div>
<script>
    $('#menu_components2').removeClass('collapse').addClass('in collapse');
    $('#contest_setting_menu').removeClass('hasSubmenu glyphicons cogwheels').addClass('hasSubmenu glyphicons cogwheels active');
    $('#match_detail_menu').addClass('active');    
</script>
