      <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
          <h1>
            Contest Info
            <small>for your next cool web APP</small>
          </h1>
          <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-futbol-o"></i> Home</a></li>
            <li>User Settings</li>
            <li class="active">User Contest Info</li>
          </ol>
        </section>

        <!-- Main content -->
        <section class="content">
          <!-- Info boxes -->
          <div class="row">
          	<div class="col-md-12 col-sm-12 no-p-left no-p-right">
            	<div class="panel panel-black no-radius">
                	<div class="panel-heading paddingLR-md paddingTB-sm no-radius">
                    	<h3 class="font-Russo-One no-margin">User Contests</h3>
                    </div>
                </div>
            </div>
          </div>
          
          <div class="row">
          	<div class="col-md-12 col-sm-12">
            	<div class="panel panel-gray">
                	<div class="panel-heading paddingLR-md paddingTB-xs">
                            <h4 class="font-Libre-Baskerville inline-block"><?php if(isset($this->usercontestinfo)){ echo $this->usercontestinfo[0]['contest_name'];}?></h4>
                        <h4 class="font-Libre-Baskerville inline-block" style="margin-left:172px;"><?php if($this->usercontestinfo[0]['sport_id']==1){ echo "PGA";}?></h4>
                        <h4 class="font-Libre-Baskerville inline-block" style="margin-left:320px;"><?php if(isset($this->usercontestinfo)){ echo date("j F ,Y", strtotime($this->usercontestinfo[0]['end_time'])); } ?></h4>
                    </div>
                    <div class="panel-body">
                    	
                      <div class="m-top-md">
                        	<div class="table-responsive">
                            	<table id="userDetails" class="display table text-center" data-page-length="10" data-order="[[ 1, &quot;asc&quot; ]]" cellspacing="0" width="100%">
                                	<thead>
                                    	<tr>
                                            <th>Sr No</th>
                                            <th>User Name</th>
                                            <th>Email</th>
                                            <th>Lineup id</th>
                                            <th>Contest Name</th>
                                            <th>Prize</th>
                                            <th>User Rank</th>
                                            <th>Completed On</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                          <?php if (isset($this->usercontestinfo)) {
                                            $row = 0;
                                            foreach ($this->usercontestinfo as $usercontestinfo) {
                                                $row ++; ?>
                                    	<tr>
                                            <td><?php echo $row ;?></td>
                                            <td><?php echo $usercontestinfo['user_name'] ;?></td>
                                            <td><?php echo $usercontestinfo['email'] ;?></td>
                                            <td><?php echo $usercontestinfo['lineup_id'] ;?></td>
                                            <td><?php echo $usercontestinfo['contest_name'];?></td>
                                            <td><?php echo $usercontestinfo['prize'] ;?></td>
                                            <td><?php echo $usercontestinfo['rank'] ;?></td>
                                            <td><?php echo date("j F , Y", strtotime($usercontestinfo['end_time']));?></td>
                                          
                                        </tr>
                                            <?php }  } ?>
                                    </tbody>
                                </table>
                          </div>
                        </div>
                        
                        
                    </div>
                </div>
            </div>
          </div>
          
          
         
        </section><!-- /.content -->
      </div>