<script>


    $(document).ready(function() {
        eval(mod_pagespeed_YJn5ujga1x);
        eval(mod_pagespeed_ao7FkmdxcI);
        eval(mod_pagespeed_mIkonhgi7n);

//        $('.datatable-responsive').DataTable({
//            serverSide: true,
//            ordering: false,
//            searching: false,
//            ajax: function(data, callback, settings) {
//                var out = [];
//
//                for (var i = data.start, ien = data.start + data.length; i < ien; i++) {
//                    out.push([i + '-1', i + '-2', i + '-3', i + '-4', i + '-5']);
//                }
//
//                setTimeout(function() {
//                    callback({
//                        draw: data.draw,
//                        data: out,
//                        recordsTotal: 5000000,
//                        recordsFiltered: 5000000
//                    });
//                }, 50);
//            },
//            scrollY: 200,
//            scroller: {
//                loadingIndicator: true
//            }
//        });
//    });
        $('.datatable-responsive').DataTable({
            responsive: true,
            "aoColumnDefs": [
                {'bSortable': false, 'aTargets': [0],
                    "targets": [0],
                    "orderable": false}
            ]

        });
    });
    $(document).ready(function() {
        $('.dataTables_filter input').attr("placeholder", "Search...");
    });


    $('#selectcity').change(function() {
        $("#demo").prop("disabled", false);
    });
    /*
     * DEV :sowmya
     * Desc : to add new location
     * Date : 7/4/2016
     */

    $(".add-loc").click(function() {
        $(".new-location").show();
        $(".loc-disable").prop("disabled", true);
    });
    /*
     * DEV :priyanka varanasi
     * Desc : Deactivate user
     * Date : 16/12/2015
     */
    $(document.body).on('change', '#selectcountry', function() {
        var countryid = $(this).val();

        $.ajax({
            url: './locationsettings-handler',
            type: 'POST',
            datatype: 'json',
            data: {
                method: 'FetchSatesByCountryId',
                countryid: countryid
            },
            beforeSend: function() {

            },
            success: function(response) {
                var res = jQuery.parseJSON(response);
                if (res['code'] === 200) {
                    $('#selectstate').html('');
                    $('#selectstate').append('<option>Select state</option>');
                    $(res.data).each(function(ind, val) {
                        $('#selectstate').append('<option value=' + val.location_id + '>' + val.name + '</option>');
                        $('#selectstate').select2();
                    });
                    $('#selectstate').prop('disabled', false);
                    $("#demo").prop("disabled", true);
                } else {
                    $('#selectstate').html('');
                    $('#selectstate').append('<option>No state available for this city</option>');
                    $('#selectstate').select2();
                    $('#selectstate').prop('disabled', false);
                    $("#demo").prop("disabled", true);
                    $("#selectcity").prop("disabled", true);

                }
            }
        });

    });

    $(window).load(function() {
        setTimeout(function() {
            $('#loading').fadeOut(400, "linear");
        }, 300);
    });
    $(".js-example-responsive").select2();

    $(".js-example-basic-hide-search").select2({
        minimumResultsForSearch: Infinity
    });
    $('#selectstate').change(function() {
        $("#demo").prop("disabled", false);
    });
    $('#test').change(function() {
        $("#demo").prop("disabled", false);
    });

    /*
     * DEV :priyanka varanasi
     * Desc : Deactivate user
     * Date : 16/12/2015
     */
    $(document.body).on('change', '#selectstate', function() {
        var stateid = $(this).val();

        $.ajax({
            url: './locationsettings-handler',
            type: 'POST',
            datatype: 'json',
            data: {
                method: 'FetchCityByStateId',
                stateid: stateid
            },
            beforeSend: function() {

            },
            success: function(response) {
                var res = jQuery.parseJSON(response);
                if (res['code'] === 200) {
                    $('#selectcity').html('');
                    $('#selectcity').append('<option>Select state</option>');
                    $(res.data).each(function(ind, val) {
                        $('#selectcity').append('<option value=' + val.location_id + '>' + val.name + '</option>');
                        $('#selectcity').select2();
                    });
                    $('#selectcity').prop('disabled', false);
                    $("#demo").prop("disabled", false);
                } else {
                    $('#selectcity').html('');
                    $('#selectcity').append('<option>No city available for this state</option>');
                    $('#selectcity').select2();
                    $('#selectcity').prop('disabled', false);
                    $("#demo").prop("disabled", true);
                }
            }
        });

    });
    /*
     * DEV :priyanka varanasi
     * Desc : Deactivate location status
     * Date : 16/12/2015
     */
    $(document.body).on('click', '.locationdeactive', function() {
        var locationid = $(this).attr('id');
        var locationid = locationid.replace("location_", "");

        console.log('deactivate called');
        $.ajax({
            url: './locationsettings-handler',
            type: 'POST',
            datatype: 'HTML',
            data: {
                method: 'locationactive',
                locationid: locationid
            },
            beforeSend: function() {

            },
            success: function(response) {
                console.log(response);
                var uid = response.replace(/ /g, '');

                $('#' + "activeclass_" + uid).removeClass('bs-label label-danger');
                $('#' + "activeclass_" + uid).addClass('bs-label label-success');
                $('#' + "activeclass_" + uid).html("Activate");
                $('#location_' + uid).removeClass('locationdeactive');
                $('#location_' + uid).addClass('locationactive');
                $('#' + "activelocation_" + uid).html("Suspended");

            }
        });

    });
    /*
     * DEV :priyanka varanasi
     * Desc : Activate location
     * Date : 16/12/2015
     */
    $(document.body).on('click', '.locationactive', function() {
        var locationid = $(this).attr('id');
        var locationid = locationid.replace("location_", "");
        console.log('activate called');
        $.ajax({
            url: './locationsettings-handler',
            type: 'POST',
            datatype: 'HTML',
            data: {
                method: 'locationactive',
                locationid: locationid
            },
            beforeSend: function() {

            },
            success: function(response) {
                var uid = response.replace(/ /g, '');
                $('#' + "activeclass_" + uid).removeClass('bs-label label-success');
                $('#' + "activeclass_" + uid).addClass('bs-label label-danger');
                $('#' + "activeclass_" + uid).html("Dectivate");
                $('#location_' + uid).removeClass('locationactive');
                $('#location_' + uid).addClass('locationdeactive');
                $('#' + "activelocation_" + uid).html("Active");

            }


        });

    });

    /*
     * DEV :priyanka varanasi
     * Desc : edit country
     * Date : 16/12/2015
     */
    $(document.body).on('click', '.locationedit', function() {
        var locationid = $(this).attr('id');
        var locationid = locationid.replace("showEdit_", "");
        $.ajax({
            url: './locationsettings-handler',
            type: 'POST',
            datatype: 'HTML',
            data: {
                method: 'getlocation',
                locationid: locationid
            },
            beforeSend: function() {

            },
            success: function(response) {
                var res = jQuery.parseJSON(response);
                if (res.code === 200) {

                    $('.editContent').find('#editlocation').val('');
                    $('.editContent').find('#locationid').val(res.data['location_id']);
                    $('.editContent').find('#editlocation').val(res.data['name']);
                    $('.editContent').show();
                    $('.addContent').hide();

                } else {

                    window.location.reload(true);
                }

            }


        });

    });

    /*
     * DEV :priyanka varanasi
     * Desc : Deactivate product status
     * Date : 29/1/2016
     */
    $(document.body).on('click', '.productdeactive', function() {
        var productid = $(this).attr('id');
        var productid = productid.replace("product_", "");

        console.log('deactivate called');
        $.ajax({
            url: './product-ajax-handler',
            type: 'POST',
            datatype: 'HTML',
            data: {
                method: 'productstatuschange',
                productid: productid
            },
            beforeSend: function() {

            },
            success: function(response) {
                console.log(response);
                var uid = response.replace(/ /g, '');

                $('#' + "activeclass_" + uid).removeClass('bs-label label-danger');
                $('#' + "activeclass_" + uid).addClass('bs-label label-success');
                $('#' + "activeclass_" + uid).html("Activate");
                $('#product_' + uid).removeClass('productdeactive');
                $('#product_' + uid).addClass('productactive');
                $('#' + "activeproduct_" + uid).html("Suspended");

            }
        });

    });


    /*
     * DEV :priyanka varanasi
     * Desc : Deactivate product status
     * Date : 29/1/2016
     */
    $(document.body).on('click', '.productactive', function() {
        var productid = $(this).attr('id');
        var productid = productid.replace("product_", "");

        console.log('deactivate called');
        $.ajax({
            url: './product-ajax-handler',
            type: 'POST',
            datatype: 'HTML',
            data: {
                method: 'productstatuschange',
                productid: productid
            },
            beforeSend: function() {

            },
            success: function(response) {
                console.log(response);
                var uid = response.replace(/ /g, '');

                $('#' + "activeclass_" + uid).removeClass('bs-label label-success');
                $('#' + "activeclass_" + uid).addClass('bs-label label-danger');
                $('#' + "activeclass_" + uid).html("Deactivate");
                $('#product_' + uid).removeClass('productactive');
                $('#product_' + uid).addClass('productdeactive');
                $('#' + "activeproduct_" + uid).html("Active");

            }
        });

    });
    /*
     * DEV :priyanka varanasi
     * Desc : Delete product
     * Date : 29/1/2016
     */

    $(document.body).on('click', '.deleteproduct', function() {
        var productid = $(this).attr('id');
        productid = productid.replace("productdelete_", "");
        if (productid) {
            $.ajax({
                url: './product-ajax-handler',
                type: 'POST',
                datatype: 'json',
                data: {
                    method: 'productdelete',
                    productid: productid
                },
                beforeSend: function() {

                },
                success: function(response) {
                    if (response) {
                        var uid = response.replace(/ /g, '');
                        $('#' + "productdelete_" + uid).parent().parent().remove();

                    }
                }


            });
        }
    });

    /*
     * DEV :priyanka varanasi
     * Desc : Deactivate user
     * Date : 16/12/2015
     */
    $(document.body).on('click', '.userdeactive', function() {
        var userid = $(this).attr('id');
        var userid = userid.replace("user_", "");

        console.log('deactivate called');
        $.ajax({
            url: './user-ajax-handler',
            type: 'POST',
            datatype: 'HTML',
            data: {
                method: 'useractive',
                userid: userid
            },
            beforeSend: function() {

            },
            success: function(response) {
                console.log(response);
                var uid = response.replace(/ /g, '');

                $('#' + "activeclass_" + uid).removeClass('bs-label label-danger');
                $('#' + "activeclass_" + uid).addClass('bs-label label-success');
                $('#' + "activeclass_" + uid).html("Activate");
                $('#user_' + uid).removeClass('userdeactive');
                $('#user_' + uid).addClass('useractive');
                $('#' + "activeuser_" + uid).html("Suspended");

            }
        });

    });
    /*
     * DEV :priyanka varanasi
     * Desc : Activate user
     * Date : 16/12/2015
     */
    $(document.body).on('click', '.useractive', function() {
        var userid = $(this).attr('id');
        var userid = userid.replace("user_", "");
        console.log('activate called');
        $.ajax({
            url: './user-ajax-handler',
            type: 'POST',
            datatype: 'HTML',
            data: {
                method: 'useractive',
                userid: userid
            },
            beforeSend: function() {

            },
            success: function(response) {
                var uid = response.replace(/ /g, '');
                $('#' + "activeclass_" + uid).removeClass('bs-label label-success');
                $('#' + "activeclass_" + uid).addClass('bs-label label-danger');
                $('#' + "activeclass_" + uid).html("Dectivate");
                $('#user_' + uid).removeClass('useractive');
                $('#user_' + uid).addClass('userdeactive');
                $('#' + "activeuser_" + uid).html("Active");

            }


        });

    });

    /*
     * DEV :priyanka varanasi
     * Desc : Delete user
     * Date : 16/12/2015
     */

    $(document.body).on('click', '.deleteuser', function() {
        
        var obj=$(this);
        var userid = $(this).attr('id');
        var deleteid = userid.replace("userdelete_", "");
        if (deleteid) {
            $.ajax({
                url: './user-ajax-handler',
                type: 'POST',
                datatype: 'json',
                data: {
                    method: 'userdelete',
                    userid: deleteid
                },
                beforeSend: function() {

                },
                success: function(response) {
                    if (response) {
                        var uid = response.replace(/ /g, '');

//                        $('#' + "userdelete_" + uid).parent().parent().remove();
                        obj.parents("tr").remove();

                    }
                }


            });
        }

    });




    /*
     * DEV :priyanka varanasi
     * Desc : Activate agent
     * Date : 16/12/2015
     */
    $(document.body).on('click', '.agentactive', function() {
        var agentid = $(this).attr('id');
        var agentid = agentid.replace("agent_", "");
        console.log('activate called');
        $.ajax({
            url: './user-ajax-handler',
            type: 'POST',
            datatype: 'HTML',
            data: {
                method: 'agentactive',
                agentid: agentid
            },
            beforeSend: function() {

            },
            success: function(response) {
                var uid = response.replace(/ /g, '');
                $('#' + "activeclass_" + uid).removeClass('bs-label label-success');
                $('#' + "activeclass_" + uid).addClass('bs-label label-danger');
                $('#' + "activeclass_" + uid).html("Dectivate");
                $('#agent_' + uid).removeClass('agentactive');
                $('#agent_' + uid).addClass('agentdeactive');
                $('#' + "activeagent_" + uid).html("Active");

            }


        });

    });

    /*
     * DEV :priyanka varanasi
     * Desc : Delete user 
     * Date : 16/12/2015
     */

    $(document.body).on('click', '.deleteagent', function() {
        var agentid = $(this).attr('id');
        var deleteid = agentid.replace("agentdelete_", "");
        if (deleteid) {
            $.ajax({
                url: './user-ajax-handler',
                type: 'POST',
                datatype: 'json',
                data: {
                    method: 'agentdelete',
                    agentid: deleteid
                },
                beforeSend: function() {

                },
                success: function(response) {
                    if (response) {
                        var uid = response.replace(/ /g, '');

                        $('#' + "agentdelete_" + uid).parent().parent().remove();

                    }
                }


            });
        }
    });

    /*
     * DEV :priyanka varanasi
     * Desc : Deactivate agent
     * Date : 16/12/2015
     */
    $(document.body).on('click', '.agentdeactive', function() {

        var agentid = $(this).attr('id');
        var agentid = agentid.replace("agent_", "");

        console.log('deactivate called');
        $.ajax({
            url: './user-ajax-handler',
            type: 'POST',
            datatype: 'HTML',
            data: {
                method: 'agentactive',
                agentid: agentid
            },
            beforeSend: function() {

            },
            success: function(response) {
                console.log(response);
                var uid = response.replace(/ /g, '');
                $('#' + "activeclass_" + uid).removeClass('bs-label label-danger');
                $('#' + "activeclass_" + uid).addClass('bs-label label-success');
                $('#' + "activeclass_" + uid).html("Activate");
                $('#agent_' + uid).removeClass('agentdeactive');
                $('#agent_' + uid).addClass('agentactive');
                $('#' + "activeagent_" + uid).html("Suspended");

            }
        });

    });

    $('#type_cusine').change(function() {
        var typevalue = $(this).val();
        $.ajax({
            url: './product-ajax-handler',
            type: 'POST',
            datatype: 'HTML',
            data: {
                method: 'getcuisines',
                typevalue: typevalue
            },
            beforeSend: function() {

            },
            success: function(response) {
                var res = jQuery.parseJSON(response);
                if (res.code === 200) {

                    $('#cuisine').html('');
                    $('#cuisine').append('<option disabled selected>Select Cuisine</option>');
                    $.each(res.data, function(i, a) {
                        $('#cuisine').append('<option value="' + a.cuisine_id + '">' + a.Cuisine_name + '</option>');
                    });
                    $('.show-cusine').show();
                    $('.show-category').hide();
                }


            }
        });
    });
    $('#type_category').change(function() {
        var typevalue = $(this).val();
        $.ajax({
            url: './product-ajax-handler',
            type: 'POST',
            datatype: 'HTML',
            data: {
                method: 'getcategories',
                typevalue: typevalue
            },
            beforeSend: function() {

            },
            success: function(response) {
                var res = jQuery.parseJSON(response);
                if (res.code === 200) {

                    $('#category').html('');
                    $('#category').append('<option disabled selected>Select category</option>');
                    $.each(res.data, function(i, a) {
                        $('#category').append('<option value="' + a.category_id + '">' + a.cat_name + '</option>');
                    });
                    $('.show-category').show();
                    $('.show-cusine').hide();
                }


            }
        });
    });

    /*
     * DEV :priyanka varanasi
     * Desc : Deactivate delivery guy
     * Date : 9/2/2016
     */
    $(document.body).on('click', '.delguydeactive', function() {

        var delguyid = $(this).attr('id');
        var delguyid = delguyid.replace("delguy_", "");

        console.log('deactivate called');
        $.ajax({
            url: './user-ajax-handler',
            type: 'POST',
            datatype: 'HTML',
            data: {
                method: 'delguystatus',
                delguyid: delguyid
            },
            beforeSend: function() {

            },
            success: function(response) {
                console.log(response);
                var uid = response.replace(/ /g, '');
                $('#' + "activeclass_" + uid).removeClass('bs-label label-danger');
                $('#' + "activeclass_" + uid).addClass('bs-label label-success');
                $('#' + "activeclass_" + uid).html("Activate");
                $('#delguy_' + uid).removeClass('delguydeactive');
                $('#delguy_' + uid).addClass('delguyactive');
                $('#' + "activedelguy_" + uid).html("Suspended");

            }
        });

    });

    /*
     * DEV :priyanka varanasi
     * Desc : Deactivate delivery guy
     * Date : 9/2/2016
     */
    $(document.body).on('click', '.delguyactive', function() {

        var delguyid = $(this).attr('id');
        var delguyid = delguyid.replace("delguy_", "");

        console.log('activate called');
        $.ajax({
            url: './user-ajax-handler',
            type: 'POST',
            datatype: 'HTML',
            data: {
                method: 'delguystatus',
                delguyid: delguyid
            },
            beforeSend: function() {

            },
            success: function(response) {
                console.log(response);
                var uid = response.replace(/ /g, '');
                $('#' + "activeclass_" + uid).removeClass('bs-label label-success');
                $('#' + "activeclass_" + uid).addClass('bs-label label-danger');
                $('#' + "activeclass_" + uid).html("Deactivate");
                $('#delguy_' + uid).removeClass('delguyactive');
                $('#delguy_' + uid).addClass('delguydeactive');
                $('#' + "activedelguy_" + uid).html("Active");

            }
        });

    });



    /*
     * DEV :priyanka varanasi
     * Desc : Delete delivery guy
     * Date : 9/2/2016
     */

    $(document.body).on('click', '.deletedelguy', function() {
        var delguyid = $(this).attr('id');
        var deleteid = delguyid.replace("delguydelete_", "");
        if (deleteid) {
            $.ajax({
                url: './user-ajax-handler',
                type: 'POST',
                datatype: 'json',
                data: {
                    method: 'delguydelete',
                    delguyid: deleteid
                },
                beforeSend: function() {

                },
                success: function(response) {
                    if (response) {
                        var uid = response.replace(/ /g, '');

                        $('#' + "delguydelete_" + uid).parent().parent().remove();

                    }
                }


            });
        }
    });


    /*
     * DEV :Sowmya
     * Desc : add hotel name in add new products
     * Date : 18/3/2016
     */

    $(document.body).on('change', '#agent_id', function() {
        var hotel_id = $(this).val();

        $.ajax({
            url: './product-ajax-handler',
            type: 'POST',
            datatype: 'json',
            data: {
                method: 'hotelsbasedonagent',
                hotel_id: hotel_id
            },
            beforeSend: function() {

            },
            success: function(response) {
                $('#hotel_id').empty();
                var res = jQuery.parseJSON(response);
                console.log(res);
                if (res['code'] === 200) {
                    $('#hotel_id').append('<option disabled selected>Select Hotel</option>');
                    var toAppend = '';
                    $.each(res['data'], function(i, a) {
                        toAppend += '<option value="' + a['id'] + '">' + a['hotel_name'] + '</option>';
                    });
                    $('#hotel_id').append(toAppend);
                    $('.show-hotel').show();
                    $('.show-agent').show();
                } else {
                    $('#hotel_id').append('<option disabled selected>No hotel details found</option>');
                }


            }
        });
    });

    /*
     * DEV :sowmya
     * Desc : Delete user transaction
     * Date : 30/3/2016
     */

    $(document.body).on('click', '.deletetrans', function() {
        var transid = $(this).attr('id');
        var deleteid = transid.replace("transdelete_", "");
        if (deleteid) {
            $.ajax({
                url: './user-ajax-handler',
                type: 'POST',
                datatype: 'json',
                data: {
                    method: 'transdelete',
                    transid: deleteid
                },
                beforeSend: function() {

                },
                success: function(response) {
                    if (response) {
                        var tid = response.replace(/ /g, '');

                        $('#' + "transdelete_" + tid).parent().parent().remove();

                    }
                }


            });
        }

    });
    /*
     * DEV :sowmya
     * Desc : Delete  agenttransaction
     * Date : 4/4/2016
     */

    $(document.body).on('click', '.deleteagenttrans', function() {
        var transid = $(this).attr('id');
        var deleteid = transid.replace("transdelete_", "");
        if (deleteid) {
            $.ajax({
                url: './user-ajax-handler',
                type: 'POST',
                datatype: 'json',
                data: {
                    method: 'agenttransdelete',
                    transid: deleteid
                },
                beforeSend: function() {

                },
                success: function(response) {
                    if (response) {
                        var tid = response.replace(/ /g, '');

                        $('#' + "transdelete_" + tid).parent().parent().remove();

                    }
                }


            });
        }

    });
    /*
     * DEV :sowmya
     * Desc : Delete  product transaction
     * Date : 4/4/2016
     */

    $(document.body).on('click', '.deleteproducttrans', function() {
        var transid = $(this).attr('id');
        var deleteid = transid.replace("transdelete_", "");
        if (deleteid) {
            $.ajax({
                url: './user-ajax-handler',
                type: 'POST',
                datatype: 'json',
                data: {
                    method: 'producttransdelete',
                    transid: deleteid
                },
                beforeSend: function() {

                },
                success: function(response) {
                    if (response) {
                        var tid = response.replace(/ /g, '');

                        $('#' + "transdelete_" + tid).parent().parent().remove();

                    }
                }


            });
        }

    });
    /*
     * DEV :sowmya
     * Desc : Delete orders
     * Date : 30/3/2016
     */

    $(document.body).on('click', '.deleteorder', function() {
        var orderid = $(this).attr('id');
        var deleteid = orderid.replace("orderdelete_", "");
        if (deleteid) {
            $.ajax({
                url: './user-ajax-handler',
                type: 'POST',
                datatype: 'json',
                data: {
                    method: 'orderdelete',
                    orderid: deleteid
                },
                beforeSend: function() {

                },
                success: function(response) {
                    if (response) {
                        var oid = response.replace(/ /g, '');

                        $('#' + "orderdelete_" + oid).parent().parent().remove();

                    }
                }


            });
        }

    });
    /*
     * DEV :sowmya
     * Desc : Deactivate Cuisine status
     * Date : 2/4/2016
     */
    $(document.body).on('click', '.cuisinedeactive', function() {
        var cuisineid = $(this).attr('id');
        var cuisineid = cuisineid.replace("cuisine_", "");

        console.log('deactivate called');
        $.ajax({
            url: './locationsettings-handler',
            type: 'POST',
            datatype: 'HTML',
            data: {
                method: 'cuisineactive',
                cuisineid: cuisineid
            },
            beforeSend: function() {

            },
            success: function(response) {
                console.log(response);
                var uid = response.replace(/ /g, '');

                $('#' + "activeclass_" + uid).removeClass('bs-label label-danger');
                $('#' + "activeclass_" + uid).addClass('bs-label label-success');
                $('#' + "activeclass_" + uid).html("Activate");
                $('#cuisine_' + uid).removeClass('cuisinedeactive');
                $('#cuisine_' + uid).addClass('cuisineactive');
                $('#' + "activecuisine_" + uid).html("Suspended");

            }
        });

    });
    /*
     * DEV :sowmya
     * Desc : Activate cuisine
     * Date : 2/4/2016
     */
    $(document.body).on('click', '.cuisineactive', function() {
        var cuisineid = $(this).attr('id');
        var cuisineid = cuisineid.replace("cuisine_", "");
        console.log('activate called');
        $.ajax({
            url: './locationsettings-handler',
            type: 'POST',
            datatype: 'HTML',
            data: {
                method: 'cuisineactive',
                cuisineid: cuisineid
            },
            beforeSend: function() {

            },
            success: function(response) {
                var uid = response.replace(/ /g, '');
                $('#' + "activeclass_" + uid).removeClass('bs-label label-success');
                $('#' + "activeclass_" + uid).addClass('bs-label label-danger');
                $('#' + "activeclass_" + uid).html("Dectivate");
                $('#cuisine_' + uid).removeClass('cuisineactive');
                $('#cuisine_' + uid).addClass('cuisinedeactive');
                $('#' + "activecuisine_" + uid).html("Active");

            }


        });

    });
    /*
     * DEV :sowmya
     * Desc : Deactivate category status
     * Date : 2/4/2016
     */
    $(document.body).on('click', '.categorydeactive', function() {
        var categoryid = $(this).attr('id');
        var categoryid = categoryid.replace("category_", "");

        console.log('deactivate called');
        $.ajax({
            url: './locationsettings-handler',
            type: 'POST',
            datatype: 'HTML',
            data: {
                method: 'categoryactive',
                categoryid: categoryid
            },
            beforeSend: function() {

            },
            success: function(response) {
                console.log(response);
                var uid = response.replace(/ /g, '');

                $('#' + "activeclass_" + uid).removeClass('bs-label label-danger');
                $('#' + "activeclass_" + uid).addClass('bs-label label-success');
                $('#' + "activeclass_" + uid).html("Activate");
                $('#category_' + uid).removeClass('categorydeactive');
                $('#category_' + uid).addClass('categoryactive');
                $('#' + "activecategory_" + uid).html("Suspended");

            }
        });

    });
    /*
     * DEV :sowmya
     * Desc : Activate category
     * Date : 2/4/2016
     */
    $(document.body).on('click', '.categoryactive', function() {
        var categoryid = $(this).attr('id');
        var categoryid = categoryid.replace("category_", "");
        console.log('activate called');
        $.ajax({
            url: './locationsettings-handler',
            type: 'POST',
            datatype: 'HTML',
            data: {
                method: 'categoryactive',
                categoryid: categoryid
            },
            beforeSend: function() {

            },
            success: function(response) {
                var uid = response.replace(/ /g, '');
                $('#' + "activeclass_" + uid).removeClass('bs-label label-success');
                $('#' + "activeclass_" + uid).addClass('bs-label label-danger');
                $('#' + "activeclass_" + uid).html("Dectivate");
                $('#category_' + uid).removeClass('categoryactive');
                $('#category_' + uid).addClass('categorydeactive');
                $('#' + "activecategory_" + uid).html("Active");

            }


        });

    });

    $(document.body).on("change", ".order_status", function(e) {
        e.preventDefault();
        var obj = $(this);
        var orderId = $(this).attr('data-id');
        var orderStatus = obj.val();
        $.ajax({
            url: './user-ajax-handler',
            type: 'POST',
            datatype: 'json',
            data: {
                method: 'OrderStatusChange',
                orderId: orderId,
                orderStatus: orderStatus
            },
            success: function(response) {
                if (response ===1) {
                    obj.parents("tr").remove();
                    location.reload();
                }
            }
        });
    });
    /*
     * DEV :sowmya
     * Desc : Delete hotel
     * Date : 5/4/2016
     */

    $(document.body).on('click', '.deletehotel', function() {
        var id = $(this).attr('id');
        var deleteid = id.replace("hoteldelete_", "");
        if (deleteid) {
            $.ajax({
                url: './hotel-details-ajax-handler',
                type: 'POST',
                datatype: 'json',
                data: {
                    method: 'hoteldelete',
                    id: deleteid
                },
                beforeSend: function() {

                },
                success: function(response) {
                    if (response) {
                        var uid = response.replace(/ /g, '');

                        $('#' + "hoteldelete_" + uid).parent().parent().remove();

                    }
                }


            });
        }

    });
    /*
     * DEV :sowmya
     * Desc : Deactivate hotel status
     * Date : 5/4/2016
     */
    $(document.body).on('click', '.hoteldeactive', function() {
        var id = $(this).attr('id');
        var id = id.replace("hotel_", "");

        console.log('deactivate called');
        $.ajax({
            url: './hotel-details-ajax-handler',
            type: 'POST',
            datatype: 'HTML',
            data: {
                method: 'hotelactive',
                id: id
            },
            beforeSend: function() {

            },
            success: function(response) {
                console.log(response);
                var uid = response.replace(/ /g, '');

                $('#' + "activeclass_" + uid).removeClass('bs-label label-danger');
                $('#' + "activeclass_" + uid).addClass('bs-label label-success');
                $('#' + "activeclass_" + uid).html("Activate");
                $('#hotel_' + uid).removeClass('hoteldeactive');
                $('#hotel_' + uid).addClass('hotelactive');
                $('#' + "activehotel_" + uid).html("Suspended");

            }
        });

    });
    /*
     * DEV :sowmya
     * Desc : Activate location
     * Date : 5/4/2016
     */
    $(document.body).on('click', '.hotelactive', function() {
        var id = $(this).attr('id');
        var id = id.replace("hotel_", "");
        console.log('activate called');
        $.ajax({
            url: './hotel-details-ajax-handler',
            type: 'POST',
            datatype: 'HTML',
            data: {
                method: 'hotelactive',
                id: id
            },
            beforeSend: function() {

            },
            success: function(response) {
                var uid = response.replace(/ /g, '');
                $('#' + "activeclass_" + uid).removeClass('bs-label label-success');
                $('#' + "activeclass_" + uid).addClass('bs-label label-danger');
                $('#' + "activeclass_" + uid).html("Dectivate");
                $('#hotel_' + uid).removeClass('hotelactive');
                $('#hotel_' + uid).addClass('hoteldeactive');
                $('#' + "activehotel_" + uid).html("Active");

            }


        });

    });
    /*
     * DEV :sowmya
     * Desc : Delete category
     * Date : 5/4/2016
     */

    $(document.body).on('click', '.categorydelete', function() {
        var id = $(this).attr('id');
        var deleteid = id.replace("categorydelete_", "");
        if (deleteid) {
            $.ajax({
                url: './locationsettings-handler',
                type: 'POST',
                datatype: 'json',
                data: {
                    method: 'categorydelete',
                    categoryid: deleteid
                },
                beforeSend: function() {

                },
                success: function(response) {
                    if (response) {
                        var uid = response.replace(/ /g, '');

                        $('#' + "categorydelete_" + uid).parent().parent().remove();

                    }
                }


            });
        }

    });

    /*
     * DEV :sowmya
     * Desc : edit category
     * Date : 5/4/2016
     */
    $(document.body).on('click', '.categoryedit', function() {
        var categoryid = $(this).attr('id');
        var categoryid = categoryid.replace("showEdit_", "");
        $.ajax({
            url: './locationsettings-handler',
            type: 'POST',
            datatype: 'HTML',
            data: {
                method: 'getcategory',
                categoryid: categoryid
            },
            beforeSend: function() {

            },
            success: function(response) {
                var res = jQuery.parseJSON(response);
                if (res.code === 200) {

                    $('.editContent').find('#editcategory').val('');
                    $('.editContent').find('#categoryid').val(res.data['category_id']);
                    $('.editContent').find('#editcategory').val(res.data['cat_name']);
                    $('.editContent').find('#categorydesc').val(res.data['cat_desc']);
                    $('.editContent').find('#editcategorydesc').val(res.data['cat_desc']);
                    $('.editContent').show();
                    $('.addContent').hide();

                } else {

                    window.location.reload(true);
                }

            }


        });

    });
    /*
     * DEV :sowmya
     * Desc : Delete cuisines
     * Date : 5/4/2016
     */

    $(document.body).on('click', '.cuisinedelete', function() {
        var id = $(this).attr('id');
        var deleteid = id.replace("cuisinedelete_", "");
        if (deleteid) {
            $.ajax({
                url: './locationsettings-handler',
                type: 'POST',
                datatype: 'json',
                data: {
                    method: 'cuisinedelete',
                    cuisineid: deleteid
                },
                beforeSend: function() {

                },
                success: function(response) {
                    if (response) {
                        var uid = response.replace(/ /g, '');

                        $('#' + "cuisinedelete_" + uid).parent().parent().remove();

                    }
                }


            });
        }

    });

    /*
     * DEV :sowmya
     * Desc : edit cuisine
     * Date : 5/4/2016
     */
    $(document.body).on('click', '.cuisineedit', function() {
        var cuisineid = $(this).attr('id');
        var cuisineid = cuisineid.replace("showEdit_", "");
        $.ajax({
            url: './locationsettings-handler',
            type: 'POST',
            datatype: 'HTML',
            data: {
                method: 'getcuisine',
                cuisineid: cuisineid
            },
            beforeSend: function() {

            },
            success: function(response) {
                var res = jQuery.parseJSON(response);
                if (res.code === 200) {

                    $('.editContent').find('#editcuisine').val('');
                    $('.editContent').find('#cuisineid').val(res.data['cuisine_id']);
                    $('.editContent').find('#editcuisine').val(res.data['Cuisine_name']);
                    $('.editContent').show();
                    $('.addContent').hide();

                } else {

                    window.location.reload(true);
                }

            }


        });

    });
    /*
     * DEV :sowmya
     * Desc : Deactivate notifiction
     * Date : 9/4/2016
     */
    $(document.body).on('click', '.notificationdeactive', function() {
        var notificationid = $(this).attr('id');
        var notificationid = notificationid.replace("notification_", "");

        console.log('deactivate called');
        $.ajax({
            url: './notification-ajax-handler',
            type: 'POST',
            datatype: 'HTML',
            data: {
                method: 'notificationactive',
                notificationid: notificationid
            },
            beforeSend: function() {

            },
            success: function(response) {
                console.log(response);
                var uid = response.replace(/ /g, '');

                $('#' + "activeclass_" + uid).removeClass('bs-label label-danger');
                $('#' + "activeclass_" + uid).addClass('bs-label label-success');
                $('#' + "activeclass_" + uid).html("Activate");
                $('#notification_' + uid).removeClass('notificationdeactive');
                $('#notification_' + uid).addClass('notificationactive');
                $('#' + "activenotification_" + uid).html("Suspended");

            }
        });

    });
    /*
     * DEV :sowmya
     * Desc : Activate notification
     * Date : 9/4/2016
     */
    $(document.body).on('click', '.notificationactive', function() {
        var notificationid = $(this).attr('id');
        var notificationid = notificationid.replace("notification_", "");
        console.log('activate called');
        $.ajax({
            url: './notification-ajax-handler',
            type: 'POST',
            datatype: 'HTML',
            data: {
                method: 'notificationactive',
                notificationid: notificationid
            },
            beforeSend: function() {

            },
            success: function(response) {
                var uid = response.replace(/ /g, '');
                $('#' + "activeclass_" + uid).removeClass('bs-label label-success');
                $('#' + "activeclass_" + uid).addClass('bs-label label-danger');
                $('#' + "activeclass_" + uid).html("Dectivate");
                $('#notification_' + uid).removeClass('notificationactive');
                $('#notification_' + uid).addClass('notificationdeactive');
                $('#' + "activenotification_" + uid).html("Active");

            }


        });

    });

    /*
     * DEV :sowmya
     * Desc : Delete notification
     * Date : 9/4/2016
     */

    $(document.body).on('click', '.deletenotification', function() {
        var notificationid = $(this).attr('id');
        var deleteid = notificationid.replace("notificationdelete_", "");
        if (deleteid) {
            $.ajax({
                url: './notification-ajax-handler',
                type: 'POST',
                datatype: 'json',
                data: {
                    method: 'deletenotification',
                    notificationId: deleteid
                },
                beforeSend: function() {

                },
                success: function(response) {
                    if (response) {
                        var uid = response.replace(/ /g, '');
                        $('#' + "notificationdelete_" + uid).parent().parent().remove();

                    }
                }


            });
        }

    });
    /*
     * DEV :sowmya
     * Desc : Delete grocery
     * Date : 20/4/2016
     */

    $(document.body).on('click', '.deletegrocery', function() {
        var id = $(this).attr('id');
        var deleteid = id.replace("grocerydelete_", "");
        if (deleteid) {
            $.ajax({
                url: './grocery-details-ajax-handler',
                type: 'POST',
                datatype: 'json',
                data: {
                    method: 'grocerydelete',
                    groceryid: deleteid
                },
                beforeSend: function() {

                },
                success: function(response) {
                    if (response) {
                        var uid = response.replace(/ /g, '');

                        $('#' + "grocerydelete_" + uid).parent().parent().remove();

                    }
                }


            });
        }

    });
    /*
     * DEV :sowmya
     * Desc : Deactivate grocery status
     * Date : 20/4/2016
     */
    $(document.body).on('click', '.grocerydeactive', function() {
        var id = $(this).attr('id');
        var id = id.replace("grocery_", "");

        console.log('deactivate called');
        $.ajax({
            url: './grocery-details-ajax-handler',
            type: 'POST',
            datatype: 'HTML',
            data: {
                method: 'groceryactive',
                groceryid: id
            },
            beforeSend: function() {

            },
            success: function(response) {
                console.log(response);
                var uid = response.replace(/ /g, '');

                $('#' + "activeclass_" + uid).removeClass('bs-label label-danger');
                $('#' + "activeclass_" + uid).addClass('bs-label label-success');
                $('#' + "activeclass_" + uid).html("Activate");
                $('#grocery_' + uid).removeClass('grocerydeactive');
                $('#grocery_' + uid).addClass('groceryactive');
                $('#' + "activegrocery_" + uid).html("Suspended");

            }
        });

    });
    /*
     * DEV :sowmya
     * Desc : Activate grocery
     * Date : 20/4/2016
     */
    $(document.body).on('click', '.groceryactive', function() {
        var id = $(this).attr('id');
        var id = id.replace("grocery_", "");
        console.log('activate called');
        $.ajax({
            url: './grocery-details-ajax-handler',
            type: 'POST',
            datatype: 'HTML',
            data: {
                method: 'groceryactive',
                groceryid: id
            },
            beforeSend: function() {

            },
            success: function(response) {
                var uid = response.replace(/ /g, '');
                $('#' + "activeclass_" + uid).removeClass('bs-label label-success');
                $('#' + "activeclass_" + uid).addClass('bs-label label-danger');
                $('#' + "activeclass_" + uid).html("Dectivate");
                $('#grocery_' + uid).removeClass('groceryactive');
                $('#grocery_' + uid).addClass('grocerydeactive');
                $('#' + "activegrocery_" + uid).html("Active");

            }


        });

    });


    /*
     * DEV :sowmya
     * Desc : Delete grocery
     * Date : 21/4/2016
     */

    $(document.body).on('click', '.deletereview', function() {
        var id = $(this).attr('id');
        var deleteid = id.replace("reviewdelete_", "");
        if (deleteid) {
            $.ajax({
                url: './reviews-ajax-handler',
                type: 'POST',
                datatype: 'json',
                data: {
                    method: 'reviewsdelete',
                    reviewid: deleteid
                },
                beforeSend: function() {

                },
                success: function(response) {
                    if (response) {
                        var uid = response.replace(/ /g, '');

                        $('#' + "reviewdelete_" + uid).parent().parent().remove();

                    }
                }


            });
        }

    });
    /*
     * DEV :sowmya
     * Desc : Deactivate review status
     * Date : 21/4/2016
     */
    $(document.body).on('click', '.reviewdeactive', function() {
        var id = $(this).attr('id');
        var id = id.replace("review_", "");

        console.log('deactivate called');
        $.ajax({
            url: './reviews-ajax-handler',
            type: 'POST',
            datatype: 'HTML',
            data: {
                method: 'reviewsactive',
                reviewid: id
            },
            beforeSend: function() {

            },
            success: function(response) {
                console.log(response);
                var uid = response.replace(/ /g, '');

                $('#' + "activeclass_" + uid).removeClass('bs-label label-danger');
                $('#' + "activeclass_" + uid).addClass('bs-label label-success');
                $('#' + "activeclass_" + uid).html("Activate");
                $('#review_' + uid).removeClass('reviewdeactive');
                $('#review_' + uid).addClass('reviewactive');
                $('#' + "activereview_" + uid).html("Suspended");

            }
        });

    });
    /*
     * DEV :sowmya
     * Desc : Activate grocery
     * Date : 20/4/2016
     */
    $(document.body).on('click', '.reviewactive', function() {
        var id = $(this).attr('id');
        var id = id.replace("review_", "");
        console.log('activate called');
        $.ajax({
            url: './reviews-ajax-handler',
            type: 'POST',
            datatype: 'HTML',
            data: {
                method: 'reviewsactive',
                reviewid: id
            },
            beforeSend: function() {

            },
            success: function(response) {
                var uid = response.replace(/ /g, '');
                $('#' + "activeclass_" + uid).removeClass('bs-label label-success');
                $('#' + "activeclass_" + uid).addClass('bs-label label-danger');
                $('#' + "activeclass_" + uid).html("Dectivate");
                $('#review_' + uid).removeClass('reviewactive');
                $('#review_' + uid).addClass('reviewdeactive');
                $('#' + "activereview_" + uid).html("Active");

            }


        });

    });
    /*
     * DEV :sowmya
     * Desc : Deactivate grocerycategory status
     * Date : 23/4/2016
     */
    $(document.body).on('click', '.grocerycategorydeactive', function() {
        var categoryid = $(this).attr('id');
        var categoryid = categoryid.replace("category_", "");

        console.log('deactivate called');
        $.ajax({
            url: './locationsettings-handler',
            type: 'POST',
            datatype: 'HTML',
            data: {
                method: 'grocerycategoryactive',
                categoryid: categoryid
            },
            beforeSend: function() {

            },
            success: function(response) {
                console.log(response);
                var uid = response.replace(/ /g, '');

                $('#' + "activeclass_" + uid).removeClass('bs-label label-danger');
                $('#' + "activeclass_" + uid).addClass('bs-label label-success');
                $('#' + "activeclass_" + uid).html("Activate");
                $('#category_' + uid).removeClass('grocerycategorydeactive');
                $('#category_' + uid).addClass('grocerycategoryactive');
                $('#' + "activecategory_" + uid).html("Suspended");

            }
        });

    });
    /*
     * DEV :sowmya
     * Desc : Activate grocerycategory
     * Date : 23/4/2016
     */
    $(document.body).on('click', '.grocerycategoryactive', function() {
        var categoryid = $(this).attr('id');
        var categoryid = categoryid.replace("category_", "");
        console.log('activate called');
        $.ajax({
            url: './locationsettings-handler',
            type: 'POST',
            datatype: 'HTML',
            data: {
                method: 'grocerycategoryactive',
                categoryid: categoryid
            },
            beforeSend: function() {

            },
            success: function(response) {
                var uid = response.replace(/ /g, '');
                $('#' + "activeclass_" + uid).removeClass('bs-label label-success');
                $('#' + "activeclass_" + uid).addClass('bs-label label-danger');
                $('#' + "activeclass_" + uid).html("Dectivate");
                $('#category_' + uid).removeClass('grocerycategoryactive');
                $('#category_' + uid).addClass('grocerycategorydeactive');
                $('#' + "activecategory_" + uid).html("Active");

            }


        });
    });
    /*
     * DEV :sowmya
     * Desc : Delete grocerycategory
     * Date :23/4/2016
     */

    $(document.body).on('click', '.grocerycategorydelete', function() {
        var id = $(this).attr('id');
        var deleteid = id.replace("categorydelete_", "");
        if (deleteid) {
            $.ajax({
                url: './locationsettings-handler',
                type: 'POST',
                datatype: 'json',
                data: {
                    method: 'grocerycategorydelete',
                    categoryid: deleteid
                },
                beforeSend: function() {

                },
                success: function(response) {
                    if (response) {
                        var uid = response.replace(/ /g, '');

                        $('#' + "categorydelete_" + uid).parent().parent().remove();

                    }
                }


            });
        }

    });
     /*
     * DEV :sowmya
     * Desc : edit grocerycategory
     * Date :23/4/2016
     */
    $(document.body).on('click', '.grocerycategoryedit', function() {
        var categoryid = $(this).attr('id');
        var categoryid = categoryid.replace("showEdit_", "");
        $.ajax({
            url: './locationsettings-handler',
            type: 'POST',
            datatype: 'HTML',
            data: {
                method: 'getgrocerycategory',
                categoryid: categoryid
            },
            beforeSend: function() {

            },
            success: function(response) {
                var res = jQuery.parseJSON(response);
                if (res.code === 200) {

                    $('.editContent').find('#editcategory').val('');
                    $('.editContent').find('#categoryid').val(res.data['category_id']);
                    $('.editContent').find('#editcategory').val(res.data['cat_name']);
                    $('.editContent').find('#categorydesc').val(res.data['cat_desc']);
                    $('.editContent').find('#editcategorydesc').val(res.data['cat_desc']);
                    $('.editContent').show();
                    $('.addContent').hide();

                } else {

                    window.location.reload(true);
                }

            }


        });

    });
    
      /*
     * DEV :sowmya
     * Desc : Delete cities
     * Date :25/4/2016
     */

    $(document.body).on('click', '.citydelete', function() {
        var id = $(this).attr('id');
        var deleteid = id.replace("citydelete_", "");
        if (deleteid) {
            $.ajax({
                url: './locationsettings-handler',
                type: 'POST',
                datatype: 'json',
                data: {
                    method: 'citydelete',
                    locationid: deleteid
                },
                beforeSend: function() {

                },
                success: function(response) {
                    if (response) {
                        var uid = response.replace(/ /g, '');

                        $('#' + "citydelete_" + uid).parent().parent().remove();

                    }
                }


            });
        }

    });
     
      /*
     * DEV :sowmya
     * Desc : Delete state
     * Date :25/4/2016
     */

    $(document.body).on('click', '.statedelete', function() {
        var id = $(this).attr('id');
        var deleteid = id.replace("statedelete_", "");
        if (deleteid) {
            $.ajax({
                url: './locationsettings-handler',
                type: 'POST',
                datatype: 'json',
                data: {
                    method: 'statedelete',
                    locationid: deleteid
                },
                beforeSend: function() {

                },
                success: function(response) {
                    if (response) {
                        var uid = response.replace(/ /g, '');

                        $('#' + "statedelete_" + uid).parent().parent().remove();

                    }
                }


            });
        }

    });
     
      /*
     * DEV :sowmya
     * Desc : Delete country
     * Date :25/4/2016
     */

    $(document.body).on('click', '.countrydelete', function() {
        var id = $(this).attr('id');
        var deleteid = id.replace("countrydelete_", "");
        if (deleteid) {
            $.ajax({
                url: './locationsettings-handler',
                type: 'POST',
                datatype: 'json',
                data: {
                    method: 'countrydelete',
                    locationid: deleteid
                },
                beforeSend: function() {

                },
                success: function(response) {
                    if (response) {
                        var uid = response.replace(/ /g, '');

                        $('#' + "countrydelete_" + uid).parent().parent().remove();

                    }
                }


            });
        }

    });
     
      /*
     * DEV :sowmya
     * Desc : Delete location
     * Date :25/4/2016
     */

    $(document.body).on('click', '.locationdelete', function() {
        var id = $(this).attr('id');
        var deleteid = id.replace("locationdelete_", "");
        if (deleteid) {
            $.ajax({
                url: './locationsettings-handler',
                type: 'POST',
                datatype: 'json',
                data: {
                    method: 'locationdelete',
                    locationid: deleteid
                },
                beforeSend: function() {

                },
                success: function(response) {
                    if (response) {
                        var uid = response.replace(/ /g, '');

                        $('#' + "locationdelete_" + uid).parent().parent().remove();

                    }
                }


            });
        }

    });
    
     /*
     * DEV :sowmya
     * Desc : Delete coupons
     * Date : 5/3/2016
     */

    $(document.body).on('click', '.deletecoupon', function() {
        var couponId = $(this).attr('id');
        var deleteid = couponId.replace("coupondelete_", "");
        if (deleteid) {
            $.ajax({
                url: './coupons-ajax-handler',
                type: 'POST',
                datatype: 'json',
                data: {
                    method: 'deleteCoupon',
                    couponId: deleteid
                },
                beforeSend: function() {

                },
                success: function(response) {
                    if (response) {
                        var uid = response.replace(/ /g, '');
                        $('#' + "coupondelete_" + uid).parent().parent().remove();

                    }
                }


            });
        }
    });
/*
     * DEV :sowmya
     * Desc : Deactivate coupons status
     * Date : 3/5/2016
     */
    $(document.body).on('click', '.coupondeactive', function() {
        var couponId = $(this).attr('id');
        console.log(couponId);
        var couponId = couponId.replace("coupon_", "");

        console.log('deactivate called');
        $.ajax({
            url: './coupons-ajax-handler',
            type: 'POST',
            datatype: 'HTML',
            data: {
                method: 'changeCouponStatus',
                couponId: couponId
            },
            beforeSend: function() {

            },
            success: function(response) {
                console.log(response);
                var uid = response.replace(/ /g, '');

                $('#' + "activeclass_" + uid).removeClass('bs-label label-danger');
                $('#' + "activeclass_" + uid).addClass('bs-label label-success');
                $('#' + "activeclass_" + uid).html("Activate");
                $('#coupon_' + uid).removeClass('coupondeactive');
                $('#coupon_' + uid).addClass('couponactive');
                $('#' + "activecoupon_" + uid).html("Suspended");

            }
        });

    });
    /*
     * DEV :sowmya
     * Desc : Activate coupons status
     * Date : 4/5/2016
     */
    $(document.body).on('click', '.couponactive', function() {
        var id = $(this).attr('id');
        var id = id.replace("coupon_", "");
        console.log('activate called');
        $.ajax({
            url: './coupons-ajax-handler',
            type: 'POST',
            datatype: 'HTML',
            data: {
                method: 'changeCouponStatus',
                couponId: id
            },
            beforeSend: function() {

            },
            success: function(response) {
                var uid = response.replace(/ /g, '');
                $('#' + "activeclass_" + uid).removeClass('bs-label label-success');
                $('#' + "activeclass_" + uid).addClass('bs-label label-danger');
                $('#' + "activeclass_" + uid).html("Dectivate");
                $('#coupon_' + uid).removeClass('couponactive');
                $('#coupon_' + uid).addClass('coupondeactive');
                $('#' + "activecoupon_" + uid).html("Active");

            }


        });

    });
    
    /*
     * DEV :sowmya
     * Desc : Delete coupons user
     * Date : 5/3/2016
     */

    $(document.body).on('click', '.deletecouponuser', function() {
        var couponId = $(this).attr('id');
        var deleteid = couponId.replace("couponuserdelete_", "");
        if (deleteid) {
            $.ajax({
                url: './coupons-ajax-handler',
                type: 'POST',
                datatype: 'json',
                data: {
                    method: 'deleteCouponUser',
                    couponuserId: deleteid
                },
                beforeSend: function() {

                },
                success: function(response) {
                    if (response) {
                        var uid = response.replace(/ /g, '');
                        $('#' + "couponuserdelete_" + uid).parent().parent().remove();

                    }
                }


            });
        }
    });
</script>
