<script>
    eval(mod_pagespeed_YJn5ujga1x);
    eval(mod_pagespeed_ao7FkmdxcI);
    eval(mod_pagespeed_mIkonhgi7n);
    $(document).ready(function() {


        $('.datatable-responsive').DataTable({
            responsive: true
        });
    });
    $(document).ready(function() {
        $('.dataTables_filter input').attr("placeholder", "Search...");
    });


    $('#selectcity').change(function() {
        $("#demo").prop("disabled", false);
    });
    /*
     * DEV :priyanka varanasi
     * Desc : Deactivate user
     * Date : 16/12/2015
     */
    $(document.body).on('change', '#selectcountry', function() {
        var countryid = $(this).val();

        $.ajax({
            url: './locationsettings-handler',
            type: 'POST',
            datatype: 'json',
            data: {
                method: 'FetchSatesByCountryId',
                countryid: countryid
            },
            beforeSend: function() {

            },
            success: function(response) {
                var res = jQuery.parseJSON(response);
                if (res['code'] === 200) {
                    $('#selectstate').html('');
                    $('#selectstate').append('<option>Select state</option>');
                    $(res.data).each(function(ind, val) {
                        $('#selectstate').append('<option value=' + val.location_id + '>' + val.name + '</option>');
                        $('#selectstate').select2();
                    });
                    $('#selectstate').prop('disabled', false);
                    $("#demo").prop("disabled", true);
                } else {
                    $('#selectstate').html('');
                    $('#selectstate').append('<option>No state available for this city</option>');
                    $('#selectstate').select2();
                    $('#selectstate').prop('disabled', false);
                    $("#demo").prop("disabled", true);
                    $("#selectcity").prop("disabled", true);

                }
            }
        });

    });

    $(window).load(function() {
        setTimeout(function() {
            $('#loading').fadeOut(400, "linear");
        }, 300);
    });
    $(".js-example-responsive").select2();

    $(".js-example-basic-hide-search").select2({
        minimumResultsForSearch: Infinity
    });
    $('#selectstate').change(function() {
        $("#demo").prop("disabled", false);
    });
    $('#test').change(function() {
        $("#demo").prop("disabled", false);
    });

    /*
     * DEV :priyanka varanasi
     * Desc : Deactivate user
     * Date : 16/12/2015
     */
    $(document.body).on('change', '#selectstate', function() {
        var stateid = $(this).val();

        $.ajax({
            url: './locationsettings-handler',
            type: 'POST',
            datatype: 'json',
            data: {
                method: 'FetchCityByStateId',
                stateid: stateid
            },
            beforeSend: function() {

            },
            success: function(response) {
                var res = jQuery.parseJSON(response);
                if (res['code'] === 200) {
                    $('#selectcity').html('');
                    $('#selectcity').append('<option>Select state</option>');
                    $(res.data).each(function(ind, val) {
                        $('#selectcity').append('<option value=' + val.location_id + '>' + val.name + '</option>');
                        $('#selectcity').select2();
                    });
                    $('#selectcity').prop('disabled', false);
                    $("#demo").prop("disabled", false);
                } else {
                    $('#selectcity').html('');
                    $('#selectcity').append('<option>No city available for this state</option>');
                    $('#selectcity').select2();
                    $('#selectcity').prop('disabled', false);
                    $("#demo").prop("disabled", true);
                }
            }
        });

    });
    /*
     * DEV :priyanka varanasi
     * Desc : Deactivate location status
     * Date : 16/12/2015
     */
    $(document.body).on('click', '.locationdeactive', function() {
        var locationid = $(this).attr('id');
        var locationid = locationid.replace("location_", "");

        console.log('deactivate called');
        $.ajax({
            url: './locationsettings-handler',
            type: 'POST',
            datatype: 'HTML',
            data: {
                method: 'locationactive',
                locationid: locationid
            },
            beforeSend: function() {

            },
            success: function(response) {
                console.log(response);
                var uid = response.replace(/ /g, '');

                $('#' + "activeclass_" + uid).removeClass('bs-label label-danger');
                $('#' + "activeclass_" + uid).addClass('bs-label label-success');
                $('#' + "activeclass_" + uid).html("Activate");
                $('#location_' + uid).removeClass('locationdeactive');
                $('#location_' + uid).addClass('locationactive');
                $('#' + "activelocation_" + uid).html("Suspended");

            }
        });

    });
    /*
     * DEV :priyanka varanasi
     * Desc : Activate location
     * Date : 16/12/2015
     */
    $(document.body).on('click', '.locationactive', function() {
        var locationid = $(this).attr('id');
        var locationid = locationid.replace("location_", "");
        console.log('activate called');
        $.ajax({
            url: './locationsettings-handler',
            type: 'POST',
            datatype: 'HTML',
            data: {
                method: 'locationactive',
                locationid: locationid
            },
            beforeSend: function() {

            },
            success: function(response) {
                var uid = response.replace(/ /g, '');
                $('#' + "activeclass_" + uid).removeClass('bs-label label-success');
                $('#' + "activeclass_" + uid).addClass('bs-label label-danger');
                $('#' + "activeclass_" + uid).html("Dectivate");
                $('#location_' + uid).removeClass('locationactive');
                $('#location_' + uid).addClass('locationdeactive');
                $('#' + "activelocation_" + uid).html("Active");

            }


        });

    });

    /*
     * DEV :priyanka varanasi
     * Desc : edit country
     * Date : 16/12/2015
     */
    $(document.body).on('click', '.locationedit', function() {
        var locationid = $(this).attr('id');
        var locationid = locationid.replace("showEdit_", "");
        $.ajax({
            url: './locationsettings-handler',
            type: 'POST',
            datatype: 'HTML',
            data: {
                method: 'getlocation',
                locationid: locationid
            },
            beforeSend: function() {

            },
            success: function(response) {
                var res = jQuery.parseJSON(response);
                if (res.code === 200) {

                    $('.editContent').find('#editlocation').val('');
                    $('.editContent').find('#locationid').val(res.data['location_id']);
                    $('.editContent').find('#editlocation').val(res.data['name']);
                    $('.editContent').show();
                    $('.addContent').hide();

                } else {

                    window.location.reload(true);
                }

            }


        });

    });

    /*
     * DEV :priyanka varanasi
     * Desc : Deactivate product status
     * Date : 29/1/2016
     */
    $(document.body).on('click', '.productdeactive', function() {
        var productid = $(this).attr('id');
        var productid = productid.replace("product_", "");

        console.log('deactivate called');
        $.ajax({
            url: './product-ajax-handler',
            type: 'POST',
            datatype: 'HTML',
            data: {
                method: 'productstatuschange',
                productid: productid
            },
            beforeSend: function() {

            },
            success: function(response) {
                console.log(response);
                var uid = response.replace(/ /g, '');

                $('#' + "activeclass_" + uid).removeClass('bs-label label-danger');
                $('#' + "activeclass_" + uid).addClass('bs-label label-success');
                $('#' + "activeclass_" + uid).html("Activate");
                $('#product_' + uid).removeClass('productdeactive');
                $('#product_' + uid).addClass('productactive');
                $('#' + "activeproduct_" + uid).html("Suspended");

            }
        });

    });


    /*
     * DEV :priyanka varanasi
     * Desc : Deactivate product status
     * Date : 29/1/2016
     */
    $(document.body).on('click', '.productactive', function() {
        var productid = $(this).attr('id');
        var productid = productid.replace("product_", "");

        console.log('deactivate called');
        $.ajax({
            url: './product-ajax-handler',
            type: 'POST',
            datatype: 'HTML',
            data: {
                method: 'productstatuschange',
                productid: productid
            },
            beforeSend: function() {

            },
            success: function(response) {
                console.log(response);
                var uid = response.replace(/ /g, '');

                $('#' + "activeclass_" + uid).removeClass('bs-label label-success');
                $('#' + "activeclass_" + uid).addClass('bs-label label-danger');
                $('#' + "activeclass_" + uid).html("Deactivate");
                $('#product_' + uid).removeClass('productactive');
                $('#product_' + uid).addClass('productdeactive');
                $('#' + "activeproduct_" + uid).html("Active");

            }
        });

    });
    /*
     * DEV :priyanka varanasi
     * Desc : Delete product
     * Date : 29/1/2016
     */

    $(document.body).on('click', '.deleteproduct', function() {
        var productid = $(this).attr('id');
        productid = productid.replace("productdelete_", "");
        if (productid) {
            $.ajax({
                url: './product-ajax-handler',
                type: 'POST',
                datatype: 'json',
                data: {
                    method: 'productdelete',
                    productid: productid
                },
                beforeSend: function() {

                },
                success: function(response) {
                    if (response) {
                        var uid = response.replace(/ /g, '');
                        $('#' + "productdelete_" + uid).parent().parent().remove();

                    }
                }


            });
        }
    });

    /*
     * DEV :priyanka varanasi
     * Desc : Deactivate user
     * Date : 16/12/2015
     */
    $(document.body).on('click', '.userdeactive', function() {
        var userid = $(this).attr('id');
        var userid = userid.replace("user_", "");

        console.log('deactivate called');
        $.ajax({
            url: './user-ajax-handler',
            type: 'POST',
            datatype: 'HTML',
            data: {
                method: 'useractive',
                userid: userid
            },
            beforeSend: function() {

            },
            success: function(response) {
                console.log(response);
                var uid = response.replace(/ /g, '');

                $('#' + "activeclass_" + uid).removeClass('bs-label label-danger');
                $('#' + "activeclass_" + uid).addClass('bs-label label-success');
                $('#' + "activeclass_" + uid).html("Activate");
                $('#user_' + uid).removeClass('userdeactive');
                $('#user_' + uid).addClass('useractive');
                $('#' + "activeuser_" + uid).html("Suspended");

            }
        });

    });
    /*
     * DEV :priyanka varanasi
     * Desc : Activate user
     * Date : 16/12/2015
     */
    $(document.body).on('click', '.useractive', function() {
        var userid = $(this).attr('id');
        var userid = userid.replace("user_", "");
        console.log('activate called');
        $.ajax({
            url: './user-ajax-handler',
            type: 'POST',
            datatype: 'HTML',
            data: {
                method: 'useractive',
                userid: userid
            },
            beforeSend: function() {

            },
            success: function(response) {
                var uid = response.replace(/ /g, '');
                $('#' + "activeclass_" + uid).removeClass('bs-label label-success');
                $('#' + "activeclass_" + uid).addClass('bs-label label-danger');
                $('#' + "activeclass_" + uid).html("Dectivate");
                $('#user_' + uid).removeClass('useractive');
                $('#user_' + uid).addClass('userdeactive');
                $('#' + "activeuser_" + uid).html("Active");

            }


        });

    });

    /*
     * DEV :priyanka varanasi
     * Desc : Delete user
     * Date : 16/12/2015
     */

    $(document.body).on('click', '.deleteuser', function() {
        var userid = $(this).attr('id');
        var deleteid = userid.replace("userdelete_", "");
        if (deleteid) {
            $.ajax({
                url: './user-ajax-handler',
                type: 'POST',
                datatype: 'json',
                data: {
                    method: 'userdelete',
                    userid: deleteid
                },
                beforeSend: function() {

                },
                success: function(response) {
                    if (response) {
                        var uid = response.replace(/ /g, '');

                        $('#' + "userdelete_" + uid).parent().parent().remove();

                    }
                }


            });
        }

    });




    /*
     * DEV :priyanka varanasi
     * Desc : Activate agent
     * Date : 16/12/2015
     */
    $(document.body).on('click', '.agentactive', function() {
        var agentid = $(this).attr('id');
        var agentid = agentid.replace("agent_", "");
        console.log('activate called');
        $.ajax({
            url: './user-ajax-handler',
            type: 'POST',
            datatype: 'HTML',
            data: {
                method: 'agentactive',
                agentid: agentid
            },
            beforeSend: function() {

            },
            success: function(response) {
                var uid = response.replace(/ /g, '');
                $('#' + "activeclass_" + uid).removeClass('bs-label label-success');
                $('#' + "activeclass_" + uid).addClass('bs-label label-danger');
                $('#' + "activeclass_" + uid).html("Dectivate");
                $('#agent_' + uid).removeClass('agentactive');
                $('#agent_' + uid).addClass('agentdeactive');
                $('#' + "activeagent_" + uid).html("Active");

            }


        });

    });

    /*
     * DEV :priyanka varanasi
     * Desc : Delete user
     * Date : 16/12/2015
     */

    $(document.body).on('click', '.deleteagent', function() {
        var agentid = $(this).attr('id');
        var deleteid = agentid.replace("agentdelete_", "");
        if (deleteid) {
            $.ajax({
                url: './user-ajax-handler',
                type: 'POST',
                datatype: 'json',
                data: {
                    method: 'agentdelete',
                    agentid: deleteid
                },
                beforeSend: function() {

                },
                success: function(response) {
                    if (response) {
                        var uid = response.replace(/ /g, '');

                        $('#' + "agentdelete_" + uid).parent().parent().remove();

                    }
                }


            });
        }
    });

    /*
     * DEV :priyanka varanasi
     * Desc : Deactivate agent
     * Date : 16/12/2015
     */
    $(document.body).on('click', '.agentdeactive', function() {

        var agentid = $(this).attr('id');
        var agentid = agentid.replace("agent_", "");

        console.log('deactivate called');
        $.ajax({
            url: './user-ajax-handler',
            type: 'POST',
            datatype: 'HTML',
            data: {
                method: 'agentactive',
                agentid: agentid
            },
            beforeSend: function() {

            },
            success: function(response) {
                console.log(response);
                var uid = response.replace(/ /g, '');
                $('#' + "activeclass_" + uid).removeClass('bs-label label-danger');
                $('#' + "activeclass_" + uid).addClass('bs-label label-success');
                $('#' + "activeclass_" + uid).html("Activate");
                $('#agent_' + uid).removeClass('agentdeactive');
                $('#agent_' + uid).addClass('agentactive');
                $('#' + "activeagent_" + uid).html("Suspended");

            }
        });

    });

    $('#type_cusine').change(function() {
        var typevalue = $(this).val();
        $.ajax({
            url: './product-ajax-handler',
            type: 'POST',
            datatype: 'HTML',
            data: {
                method: 'getcuisines',
                typevalue: typevalue
            },
            beforeSend: function() {

            },
            success: function(response) {
                var res = jQuery.parseJSON(response);
                if (res.code === 200) {

                    $('#cuisine').html('');
                    $('#cuisine').append('<option disabled selected>Select Cusine</option>');
                    $.each(res.data, function(i, a) {
                        $('#cuisine').append('<option value="' + a.cuisine_id + '">' + a.Cuisine_name + '</option>');
                    });
                    $('.show-cusine').show();
                    $('.show-category').hide();
                }


            }
        });
    });
    $('#type_category').change(function() {
        var typevalue = $(this).val();
        $.ajax({
            url: './product-ajax-handler',
            type: 'POST',
            datatype: 'HTML',
            data: {
                method: 'getcategories',
                typevalue: typevalue
            },
            beforeSend: function() {

            },
            success: function(response) {
                var res = jQuery.parseJSON(response);
                if (res.code === 200) {

                    $('#category').html('');
                    $('#category').append('<option disabled selected>Select category</option>');
                    $.each(res.data, function(i, a) {
                        $('#category').append('<option value="' + a.category_id + '">' + a.cat_name + '</option>');
                    });
                    $('.show-category').show();
                    $('.show-cusine').hide();
                }


            }
        });
    });

    /*
     * DEV :priyanka varanasi
     * Desc : Deactivate delivery guy
     * Date : 9/2/2016
     */
    $(document.body).on('click', '.delguydeactive', function() {

        var delguyid = $(this).attr('id');
        var delguyid = delguyid.replace("delguy_", "");

        console.log('deactivate called');
        $.ajax({
            url: './user-ajax-handler',
            type: 'POST',
            datatype: 'HTML',
            data: {
                method: 'delguystatus',
                delguyid: delguyid
            },
            beforeSend: function() {

            },
            success: function(response) {
                console.log(response);
                var uid = response.replace(/ /g, '');
                $('#' + "activeclass_" + uid).removeClass('bs-label label-danger');
                $('#' + "activeclass_" + uid).addClass('bs-label label-success');
                $('#' + "activeclass_" + uid).html("Activate");
                $('#delguy_' + uid).removeClass('delguydeactive');
                $('#delguy_' + uid).addClass('delguyactive');
                $('#' + "activedelguy_" + uid).html("Suspended");

            }
        });

    });

    /*
     * DEV :priyanka varanasi
     * Desc : Deactivate delivery guy
     * Date : 9/2/2016
     */
    $(document.body).on('click', '.delguyactive', function() {

        var delguyid = $(this).attr('id');
        var delguyid = delguyid.replace("delguy_", "");

        console.log('activate called');
        $.ajax({
            url: './user-ajax-handler',
            type: 'POST',
            datatype: 'HTML',
            data: {
                method: 'delguystatus',
                delguyid: delguyid
            },
            beforeSend: function() {

            },
            success: function(response) {
                console.log(response);
                var uid = response.replace(/ /g, '');
                $('#' + "activeclass_" + uid).removeClass('bs-label label-success');
                $('#' + "activeclass_" + uid).addClass('bs-label label-danger');
                $('#' + "activeclass_" + uid).html("Deactivate");
                $('#delguy_' + uid).removeClass('delguyactive');
                $('#delguy_' + uid).addClass('delguydeactive');
                $('#' + "activedelguy_" + uid).html("Active");

            }
        });

    });



    /*
     * DEV :priyanka varanasi
     * Desc : Delete delivery guy
     * Date : 9/2/2016
     */

    $(document.body).on('click', '.deletedelguy', function() {
        var delguyid = $(this).attr('id');
        var deleteid = delguyid.replace("delguydelete_", "");
        if (deleteid) {
            $.ajax({
                url: './user-ajax-handler',
                type: 'POST',
                datatype: 'json',
                data: {
                    method: 'delguydelete',
                    delguyid: deleteid
                },
                beforeSend: function() {

                },
                success: function(response) {
                    if (response) {
                        var uid = response.replace(/ /g, '');

                        $('#' + "delguydelete_" + uid).parent().parent().remove();

                    }
                }


            });
        }
    });


    /*
     * DEV :Sowmya
     * Desc : add hotel name in add new products
     * Date : 18/3/2016
     */

    $(document.body).on('change', '#agent_id', function() {
        var hotel_id = $(this).val();

        $.ajax({
            url: './product-ajax-handler',
            type: 'POST',
            datatype: 'json',
            data: {
                method: 'hotelsbasedonagent',
                hotel_id: hotel_id
            },
            beforeSend: function() {

            },
            success: function(response) {
                $('#hotel_id').empty();
                var res = jQuery.parseJSON(response);
                console.log(res);
                if (res['code'] === 200) {
                    $('#hotel_id').append('<option disabled selected>Select Hotel</option>');
                    var toAppend = '';
                    $.each(res['data'], function(i, a) {
                        toAppend += '<option value="' + a['id'] + '">' + a['hotel_name'] + '</option>';
                    });
                    $('#hotel_id').append(toAppend);
                    $('.show-hotel').show();
                    $('.show-agent').show();
                } else {
                    $('#hotel_id').append('<option disabled selected>No hotel details found</option>');
                }


            }
        });
    });
    
     /*
     * DEV :sowmya
     * Desc : Delete transaction
     * Date : 30/3/2016
     */

    $(document.body).on('click', '.deletetrans', function() {
        var transid = $(this).attr('id');
        var deleteid = transid.replace("transdelete_", "");
        if (deleteid) {
            $.ajax({
                url: './user-ajax-handler',
                type: 'POST',
                datatype: 'json',
                data: {
                    method: 'transdelete',
                    transid: deleteid
                },
                beforeSend: function() {

                },
                success: function(response) {
                    if (response) {
                        var tid = response.replace(/ /g, '');

                        $('#' + "transdelete_" + tid).parent().parent().remove();

                    }
                }


            });
        }

    });
    /*
     * DEV :sowmya
     * Desc : Delete orders
     * Date : 30/3/2016
     */

    $(document.body).on('click', '.deleteorder', function() {
        var orderid = $(this).attr('id');
        var deleteid = orderid.replace("orderdelete_", "");
        if (deleteid) {
            $.ajax({
                url: './user-ajax-handler',
                type: 'POST',
                datatype: 'json',
                data: {
                    method: 'orderdelete',
                    orderid: deleteid
                },
                beforeSend: function() {

                },
                success: function(response) {
                    if (response) {
                        var oid = response.replace(/ /g, '');

                        $('#' + "orderdelete_" + oid).parent().parent().remove();

                    }
                }


            });
        }

    });
</script>
<script>
$('.trigger').change(function(){
   
});
</script>