<?php echo $this->doctype(); ?>
<html lang="en-US">  
    <head>
        <?php
        # Title
        echo $this->headTitle();

        # Meta data
        echo $this->headMeta();

        # CSS
        echo $this->headLink()
                ->appendStylesheet($this->baseUrl() . $this->appSetting->assestPath . 'admin/css/bootstrap.min.css')
                ->appendStylesheet($this->baseUrl() . 'http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css')
                ->appendStylesheet($this->baseUrl() . 'http://code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css')
                ->appendStylesheet($this->baseUrl() . $this->appSetting->assestPath . 'admin/css/jquery-jvectormap-1.2.2.css')
                ->appendStylesheet($this->baseUrl() . $this->appSetting->assestPath . 'admin/css/daterangepicker-bs3.css')
                ->appendStylesheet($this->baseUrl() . $this->appSetting->assestPath . 'admin/css/_all-skins.css')
                ->appendStylesheet($this->baseUrl() . $this->appSetting->assestPath . 'admin/css/jquery.dataTables.css')
                ->appendStylesheet($this->baseUrl() . $this->appSetting->assestPath . 'admin/css/AdminLTE.css')
                ->appendStylesheet($this->baseUrl() . $this->appSetting->assestPath . 'admin/css/fansports-admin.css')
                ->appendStylesheet($this->baseUrl() . $this->appSetting->assestPath . 'admin/css/morris.css')
                ->appendStylesheet($this->baseUrl() . $this->appSetting->assestPath . 'admin/css/summernote.css')
        ?>

        <link rel="stylesheet" href="/assets/admin/js/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="/assets/admin/js/jquery.gritter/css/jquery.gritter.css" />
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
        <link rel="stylesheet" href="https://cdn.datatables.net/1.10.9/css/jquery.dataTables.min.css" />
        <link rel="stylesheet" href="http://code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css" />	
        <link rel="stylesheet" href="/assets/admin/js/jquery.nanoscroller/nanoscroller.css" />
        <link rel="stylesheet" href="https://cdn.datatables.net/plug-ins/1.10.10/filtering/row-based/range_dates.js" />
        <link rel="stylesheet" href="https://cdn.datatables.net/1.10.10/css/jquery.dataTables.min.css" />
        <link rel="stylesheet" href="/assets/admin/js/jasny.bootstrap/extend/css/jasny-bootstrap.min.css" />

        <link rel="stylesheet" href="/assets/admin/js/jquery.niftymodals/css/component.css" />
        <link rel="stylesheet" href="/assets/admin/css/summernote.css" />
        <link rel="stylesheet" href="/assets/admin/css/style.css" />

        <?php
        ;
        #JS        
        echo $this->headScript()
                ->appendFile($this->baseUrl() . $this->appSetting->assestPath . 'admin/js/jQuery-2.1.3.min.js', 'text/javascript')
                ->appendFile($this->baseUrl() . $this->appSetting->assestPath . 'admin/js/jquery-1.11.2.min.js', 'text/javascript')
                ->appendFile($this->baseUrl() . $this->appSetting->assestPath . 'admin/js/jquery.validate.min.js', 'text/javascript')
                ->appendFile($this->baseUrl() . $this->appSetting->assestPath . 'admin/js/jquery.settings.js', 'text/javascript')
                ->appendFile($this->baseUrl() . $this->appSetting->assestPath . 'admin/js/bootstrap.min.js', 'text/javascript')
                ->appendFile($this->baseUrl() . $this->appSetting->assestPath . 'admin/js/Chart.min.js', 'text/javascript')
                ->appendFile($this->baseUrl() . $this->appSetting->assestPath . 'admin/js/fastclick.js', 'text/javascript')
                ->appendFile($this->baseUrl() . $this->appSetting->assestPath . 'admin/js/app.min.js', 'text/javascript')
                ->appendFile($this->baseUrl() . $this->appSetting->assestPath . 'admin/js/jquery.dataTables.min.js', 'text/javascript')
                ->appendFile($this->baseUrl() . $this->appSetting->assestPath . 'admin/js/bootstrap-datepicker.js', 'text/javascript')
                ->appendFile($this->baseUrl() . $this->appSetting->assestPath . 'admin/js/jquery.mCustomScrollbar.js', 'text/javascript')
                ->appendFile($this->baseUrl() . $this->appSetting->assestPath . 'admin/js/jquery.mCustomScrollbar.concat.min.js', 'text/javascript')
                ->appendFile($this->baseUrl() . $this->appSetting->assestPath . 'js/bootstrap-datepicker.js', 'text/javascript')
                ->appendFile($this->baseUrl() . $this->appSetting->assestPath . 'admin/js/fansports-admin.js', 'text/javascript')
                ->appendFile($this->baseUrl() . $this->appSetting->assestPath . 'admin/js/highcharts.js', 'text/javascript')
                ->appendFile($this->baseUrl() . $this->appSetting->assestPath . 'admin/js/exporting.js', 'text/javascript')
                ->appendFile($this->baseUrl() . $this->appSetting->assestPath . 'admin/js/summernote.js', 'text/javascript');
        ?>   

        <script src="/assets/admin/js/jquery.datatables/jquery.datatables.min.js"></script>
        <script src="/assets/admin/js/jquery.datatables/bootstrap-adapter/js/datatables.js"></script>
        <script src="/assets/admin/js/jquery.datatables/jquery.dataTables.columnFilter.js"></script>

        <link href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css" rel="stylesheet" type="text/css" />
        <script src="//cdn.ckeditor.com/4.5.3/full/ckeditor.js"></script>
    </head>    
    <body class="skin-black sidebar-mini">
        <div class="wrapper">
            <?php
            if ($this->auth->hasIdentity()) {
                if ($this->session->storage->role == 2) {
                    ?>
                    <header class="main-header">

                        <a href="/admin" class="logo">
                            <span class="logo-lg">
                                <span class="font-Titillium-Web">
                                    <span class="text-gray">Ziingo</span>
                                </span>
                            </span>
                        </a>

                        <nav class="navbar navbar-static-top" role="navigation">
                            <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
                                <span class="sr-only">Toggle navigation</span>
                            </a>
                            <div class="navbar-custom-menu">
                                <ul class="nav navbar-nav">
                                    <li class="dropdown user user-menu">
                                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                            <span class="hidden-xs"><?php echo $this->session->storage->uname; ?></span>
                                        </a>
                                        <ul class="dropdown-menu">
                                            <li class="user-header">
                                                <p>
                                                    <?php echo $this->session->storage->uname; ?>
                                                </p>
                                            </li>
                                            <li class="user-footer">
                                                <div class="pull-left">
                                                    <a href="#" class="btn btn-default btn-flat">Profile</a>
                                                </div>
                                                <div class="pull-right">
                                                    <a href="/admin/logout" class="btn btn-default btn-flat">Sign out</a>
                                                </div>
                                            </li>
                                        </ul>
                                    </li>
                                </ul>
                            </div>

                        </nav>
                    </header>
                    <aside class="main-sidebar">
                        <section class="sidebar">
                            <div class="user-panel">
                                <div class="pull-left info">
                                    <p><?php echo $this->session->storage->uname; ?></p>
                                    <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
                                </div>
                            </div>
                            <ul class="sidebar-menu">
                                <li class="active treeview">
                                    <a href="/admin/dashboard">
                                        <i class="fa fa-dashboard" ></i> <span>Dashboard</span>
                                    </a>
                                </li>

                                <li>
                                    <a href="#">
                                        <i class="fa fa-user"></i> 
                                        <span>User</span>
                                        <i class="fa fa-angle-left pull-right"></i>
                                    </a>
                                    <ul class="treeview-menu">
                                        <li>
                                            <a href="/admin/userdetails">
                                                <i class="fa fa-circle-o"></i> 
                                                User Details
                                            </a>
                                        </li>
                                        <li>
                                            <a href="/add-user-details">
                                                <i class="fa fa-circle-o"></i> 
                                                Add User Details
                                            </a>
                                        </li>
                                    </ul>
                                </li>

                                <li>
                                    <a href="/admin/transaction">
                                        <i class="fa fa-usd"></i>
                                        <span>Transaction Details</span>
                                    </a>
                                </li>

                                <li>
                                    <a href="/admin/orderdetails">
                                        <i class="fa fa-usd"></i>
                                        <span>Order Details</span>
                                    </a>
                                </li>                                
                                
                                   <li>
                                    <a href="#">
                                        <i class="fa fa-user"></i> 
                                        <span>Product</span>
                                        <i class="fa fa-angle-left pull-right"></i>
                                    </a>
                                    <ul class="treeview-menu">
                                        <li>
                                            <a href="/admin/product-details">
                                                <i class="fa fa-circle-o"></i> 
                                                Product Details
                                            </a>
                                        </li>
                                        <li>
<!--                                            <a href="/add-product-details">
                                                <i class="fa fa-circle-o"></i> 
                                                Add Product Details
                                            </a>-->
                                        </li>
                                    </ul>
                                </li>
                                
                                 <li>
                                    <a href="#">
                                        <i class="fa fa-user"></i> 
                                        <span>Delivery Guy</span>
                                        <i class="fa fa-angle-left pull-right"></i>
                                    </a>
                                    <ul class="treeview-menu">
                                        <li>
                                            <a href="/admin/delivery-guy-details">
                                                <i class="fa fa-circle-o"></i> 
                                                Delivery Guy Details
                                            </a>
                                        </li>
                                        <li>
                                            <a href="/add-delivery-guy-details">
                                                <i class="fa fa-circle-o"></i> 
                                                Add Delivery Guy Details
                                            </a>
                                        </li>
                                    </ul>
                                </li>
                                
                                   <li>
                                    <a href="#">
                                        <i class="fa fa-user"></i> 
                                        <span>Agents</span>
                                        <i class="fa fa-angle-left pull-right"></i>
                                    </a>
                                    <ul class="treeview-menu">
                                        <li>
                                            <a href="/admin/agent-details">
                                                <i class="fa fa-circle-o"></i> 
                                                Agent Details
                                            </a>
                                        </li>
                                        <li>
                                            <a href="/admin/add-agents">
                                                <i class="fa fa-circle-o"></i> 
                                                Add Agents
                                            </a>
                                        </li>
                                    </ul>
                                </li>
                                         <li>
                                    <a href="#">
                                        <i class="fa fa-user"></i> 
                                        <span>Settings</span>
                                        <i class="fa fa-angle-left pull-right"></i>
                                    </a>
                                    <ul class="treeview-menu">
                                        <li>
                                            <a href="/admin/countries-details">
                                                <i class="fa fa-circle-o"></i> 
                                                countries settings
                                            </a>
                                        </li>
                                           <li>
                                            <a href="/admin/states-details">
                                                <i class="fa fa-circle-o"></i> 
                                                states settings
                                            </a>
                                        </li>
                                           <li>
                                            <a href="/admin/city-details">
                                                <i class="fa fa-circle-o"></i> 
                                                cities settings
                                            </a>
                                        </li>
                                            <li>
                                            <a href="/admin/location-details">
                                                <i class="fa fa-circle-o"></i> 
                                                location settings
                                            </a>
                                        </li>
                                     
                                    </ul>
                                </li>

                            </ul>
                        </section>
                    </aside>

                    <div class="container-fluid" id="pcont">

                        <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                            <div class="modal-dialog" role="document">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                        <h4 class="modal-title" id="myModalLabel">Delete Confirmation</h4>
                                    </div>

                                    <div class="modal-body">
                                        Are you sure ?
                                    </div>

                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-primary" id="confirmDelete">Yes</button>
                                        <button type="button" class="btn btn-default" data-dismiss="modal">No</button>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="modal fade" id="addModal" tabindex="-1" role="dialog" aria-labelledby="ModalLabel">
                            <div class="modal-dialog" role="document">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                        <h4 class="modal-title" id="ModalLabel">Modal title</h4>
                                    </div>
                                    <div class="modal-body" id="ModalBody">

                                        <div id="ModalBody" class="modal-body">
                                        </div>

                                    </div>
                                    <div class="modal-footer form-actions">
                                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                                        <button type="button" class="btn btn-primary" id="add">Add</button>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="modal fade" id="editModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                            <div class="modal-dialog" role="document">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                        <h4 class="modal-title" id="myModalLabel">EDIT</h4>
                                    </div>
                                    <div class="modal-body" id="myModalBody">
                                        ...
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                                        <button type="button" class="btn btn-primary" id="saveChanges">Save changes</button>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>

                    <?php
                }
            }
            ?>


