<?php echo $this->doctype(); ?>
<html lang="en-US">  
    <head>
        <?php
        # Title
        echo $this->headTitle();

        # Meta data
        echo $this->headMeta();

        # CSS
        echo $this->headLink()
                ->appendStylesheet($this->baseUrl() . $this->appSetting->assestPath . 'admin/css/bootstrap.min.css')
                ->appendStylesheet($this->baseUrl() .  'http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css')
                ->appendStylesheet($this->baseUrl() .  'http://code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css')
                ->appendStylesheet($this->baseUrl() . $this->appSetting->assestPath . 'admin/css/jquery-jvectormap-1.2.2.css')
                ->appendStylesheet($this->baseUrl() . $this->appSetting->assestPath . 'admin/css/daterangepicker-bs3.css')
                ->appendStylesheet($this->baseUrl() . $this->appSetting->assestPath . 'admin/css/_all-skins.css')
                ->appendStylesheet($this->baseUrl() . $this->appSetting->assestPath . 'admin/css/jquery.dataTables.css')
                ->appendStylesheet($this->baseUrl() . $this->appSetting->assestPath . 'admin/css/AdminLTE.css')
                ->appendStylesheet($this->baseUrl() . $this->appSetting->assestPath . 'admin/css/fansports-admin.css')
                ->appendStylesheet($this->baseUrl() . $this->appSetting->assestPath . 'admin/css/morris.css')
                ->appendStylesheet($this->baseUrl() . $this->appSetting->assestPath . 'admin/css/summernote.css')
                
                ;
        #JS        
        echo $this->headScript()
                
                ->appendFile($this->baseUrl() . $this->appSetting->assestPath . 'admin/js/jQuery-2.1.3.min.js', 'text/javascript')
                ->appendFile($this->baseUrl() . $this->appSetting->assestPath . 'admin/js/jquery-1.11.2.min.js', 'text/javascript')
                ->appendFile($this->baseUrl() . $this->appSetting->assestPath . 'admin/js/jquery.validate.min.js', 'text/javascript')
                 ->appendFile($this->baseUrl() . $this->appSetting->assestPath . 'admin/js/jquery.settings.js', 'text/javascript')
                ->appendFile($this->baseUrl() . $this->appSetting->assestPath . 'admin/js/bootstrap.min.js', 'text/javascript')
                ->appendFile($this->baseUrl() . $this->appSetting->assestPath . 'admin/js/Chart.min.js', 'text/javascript')
                ->appendFile($this->baseUrl() . $this->appSetting->assestPath . 'admin/js/fastclick.js', 'text/javascript')
                ->appendFile($this->baseUrl() . $this->appSetting->assestPath . 'admin/js/app.min.js', 'text/javascript')
                ->appendFile($this->baseUrl() . $this->appSetting->assestPath . 'admin/js/jquery.dataTables.min.js', 'text/javascript')
                ->appendFile($this->baseUrl() . $this->appSetting->assestPath . 'admin/js/bootstrap-datepicker.js', 'text/javascript')
                ->appendFile($this->baseUrl() . $this->appSetting->assestPath . 'admin/js/jquery.mCustomScrollbar.js', 'text/javascript')
                ->appendFile($this->baseUrl() . $this->appSetting->assestPath . 'admin/js/jquery.mCustomScrollbar.concat.min.js', 'text/javascript')
                ->appendFile($this->baseUrl() . $this->appSetting->assestPath . 'js/bootstrap-datepicker.js', 'text/javascript')
                ->appendFile($this->baseUrl() . $this->appSetting->assestPath . 'admin/js/fansports-admin.js', 'text/javascript')
                ->appendFile($this->baseUrl() . $this->appSetting->assestPath . 'admin/js/highcharts.js', 'text/javascript')
	        ->appendFile($this->baseUrl() . $this->appSetting->assestPath . 'admin/js/exporting.js', 'text/javascript')
                ->appendFile($this->baseUrl() . $this->appSetting->assestPath . 'admin/js/summernote.js', 'text/javascript');
        
                
                
               
                
        ?>   
        <link href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css" rel="stylesheet" type="text/css" />
        <script src="//cdn.ckeditor.com/4.5.3/full/ckeditor.js"></script>
    </head>    
<body class="skin-black sidebar-mini">
    <div class="wrapper"><!--Body Wrapper-->
<?php if($this->auth->hasIdentity()){
    if($this->session->storage->role == 2){ ?>
             <header class="main-header">

        <!-- Logo -->
        <a href="/admin" class="logo">
          <!-- mini logo for sidebar mini 50x50 pixels -->
          <span class="logo-mini"><img src="images/fansports-logo-mini.png" class="img-responsive m-top-xs center-block square-40"></span>
          <!-- logo for regular state and mobile devices -->
          <span class="logo-lg">
          	<span class="font-Titillium-Web">
            	<span class="text-gray">Ziingo</span>
            </span>
          </span>
        </a>

        <!-- Header Navbar: style can be found in header.less -->
        <nav class="navbar navbar-static-top" role="navigation">
          <!-- Sidebar toggle button-->
          <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
            <span class="sr-only">Toggle navigation</span>
          </a>
          <!-- Navbar Right Menu -->
          <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
              <!-- Messages: style can be found in dropdown.less-->
              <li class="dropdown messages-menu">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <i class="fa fa-envelope-o"></i>
                  <span class="label label-success">4</span>
                </a>
                <ul class="dropdown-menu">
                  <li class="header">You have 4 messages</li>
                  <li>
                    <!-- inner menu: contains the actual data -->
                    <ul class="menu">
                      <li><!-- start message -->
                        <a href="#">
                          <div class="pull-left">
                            <img src="dist/img/user2-160x160.jpg" class="img-circle" alt="User Image"/>
                          </div>
                          <h4>
                            Support Team
                            <small><i class="fa fa-clock-o"></i> 5 mins</small>
                          </h4>
                          <p>Why not buy a new awesome theme?</p>
                        </a>
                      </li><!-- end message -->
                      <li>
                        <a href="#">
                          <div class="pull-left">
                            <img src="dist/img/user3-128x128.jpg" class="img-circle" alt="user image"/>
                          </div>
                          <h4>
                            AdminLTE Design Team
                            <small><i class="fa fa-clock-o"></i> 2 hours</small>
                          </h4>
                          <p>Why not buy a new awesome theme?</p>
                        </a>
                      </li>
                      <li>
                        <a href="#">
                          <div class="pull-left">
                            <img src="dist/img/user4-128x128.jpg" class="img-circle" alt="user image"/>
                          </div>
                          <h4>
                            Developers
                            <small><i class="fa fa-clock-o"></i> Today</small>
                          </h4>
                          <p>Why not buy a new awesome theme?</p>
                        </a>
                      </li>
                      <li>
                        <a href="#">
                          <div class="pull-left">
                            <img src="dist/img/user3-128x128.jpg" class="img-circle" alt="user image"/>
                          </div>
                          <h4>
                            Sales Department
                            <small><i class="fa fa-clock-o"></i> Yesterday</small>
                          </h4>
                          <p>Why not buy a new awesome theme?</p>
                        </a>
                      </li>
                      <li>
                        <a href="#">
                          <div class="pull-left">
                            <img src="dist/img/user4-128x128.jpg" class="img-circle" alt="user image"/>
                          </div>
                          <h4>
                            Reviewers
                            <small><i class="fa fa-clock-o"></i> 2 days</small>
                          </h4>
                          <p>Why not buy a new awesome theme?</p>
                        </a>
                      </li>
                    </ul>
                  </li>
                  <li class="footer"><a href="#">See All Messages</a></li>
                </ul>
              </li>
              <!-- Notifications: style can be found in dropdown.less -->
              <li class="dropdown notifications-menu">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <i class="fa fa-bell-o"></i>
                  <span class="label label-warning">10</span>
                </a>
                <ul class="dropdown-menu">
                  <li class="header">You have 10 notifications</li>
                  <li>
                    <!-- inner menu: contains the actual data -->
                    <ul class="menu">
                      <li>
                        <a href="#">
                          <i class="fa fa-users text-aqua"></i> 5 new members joined today
                        </a>
                      </li>
                      <li>
                        <a href="#">
                          <i class="fa fa-warning text-yellow"></i> Very long description here that may not fit into the page and may cause design problems
                        </a>
                      </li>
                      <li>
                        <a href="#">
                          <i class="fa fa-users text-red"></i> 5 new members joined
                        </a>
                      </li>

                      <li>
                        <a href="#">
                          <i class="fa fa-shopping-cart text-green"></i> 25 sales made
                        </a>
                      </li>
                      <li>
                        <a href="#">
                          <i class="fa fa-user text-red"></i> You changed your username
                        </a>
                      </li>
                    </ul>
                  </li>
                  <li class="footer"><a href="#">View all</a></li>
                </ul>
              </li>
              <!-- Tasks: style can be found in dropdown.less -->
              <li class="dropdown tasks-menu">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <i class="fa fa-flag-o"></i>
                  <span class="label label-danger">9</span>
                </a>
                <ul class="dropdown-menu">
                  <li class="header">You have 9 tasks</li>
                  <li>
                    <!-- inner menu: contains the actual data -->
                    <ul class="menu">
                      <li><!-- Task item -->
                        <a href="#">
                          <h3>
                            Design some buttons
                            <small class="pull-right">20%</small>
                          </h3>
                          <div class="progress xs">
                            <div class="progress-bar progress-bar-aqua" style="width: 20%" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
                              <span class="sr-only">20% Complete</span>
                            </div>
                          </div>
                        </a>
                      </li><!-- end task item -->
                      <li><!-- Task item -->
                        <a href="#">
                          <h3>
                            Create a nice theme
                            <small class="pull-right">40%</small>
                          </h3>
                          <div class="progress xs">
                            <div class="progress-bar progress-bar-green" style="width: 40%" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
                              <span class="sr-only">40% Complete</span>
                            </div>
                          </div>
                        </a>
                      </li><!-- end task item -->
                      <li><!-- Task item -->
                        <a href="#">
                          <h3>
                            Some task I need to do
                            <small class="pull-right">60%</small>
                          </h3>
                          <div class="progress xs">
                            <div class="progress-bar progress-bar-red" style="width: 60%" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
                              <span class="sr-only">60% Complete</span>
                            </div>
                          </div>
                        </a>
                      </li><!-- end task item -->
                      <li><!-- Task item -->
                        <a href="#">
                          <h3>
                            Make beautiful transitions
                            <small class="pull-right">80%</small>
                          </h3>
                          <div class="progress xs">
                            <div class="progress-bar progress-bar-yellow" style="width: 80%" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
                              <span class="sr-only">80% Complete</span>
                            </div>
                          </div>
                        </a>
                      </li><!-- end task item -->
                    </ul>
                  </li>
                  <li class="footer">
                    <a href="#">View all tasks</a>
                  </li>
                </ul>
              </li>
              <!-- User Account: style can be found in dropdown.less -->
              <li class="dropdown user user-menu">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <!--<img src="dist/img/user2-160x160.jpg" class="user-image" alt="User Image"/>-->
                  <span class="hidden-xs"><?php // echo $this->session->storage->user_name; ?></span>
                </a>
                <ul class="dropdown-menu">
                  <!-- User image -->
                  <li class="user-header">
<!--                    <img src="dist/img/user2-160x160.jpg" class="img-circle" alt="User Image" />-->
                    <p>
                     <?php // echo $this->session->storage->user_name; ?>
                    </p>
                  </li>
                  <!-- Menu Body -->
                  <li class="user-body">
                    <div class="col-xs-4 text-center">
                      <a href="#">Followers</a>
                    </div>
                    <div class="col-xs-4 text-center">
                      <a href="#">Sales</a>
                    </div>
                    <div class="col-xs-4 text-center">
                      <a href="#">Friends</a>
                    </div>
                  </li>
                  <!-- Menu Footer-->
                  <li class="user-footer">
                    <div class="pull-left">
                      <a href="#" class="btn btn-default btn-flat">Profile</a>
                    </div>
                    <div class="pull-right">
                      <a href="/logout" class="btn btn-default btn-flat">Sign out</a>
                    </div>
                  </li>
                </ul>
              </li>
              <!-- Control Sidebar Toggle Button -->
              <li>
                <a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>
              </li>
            </ul>
          </div>

        </nav>
      </header>
      <!-- Left side column. contains the logo and sidebar -->
      <aside class="main-sidebar">
        <!-- sidebar: style can be found in sidebar.less -->
        <section class="sidebar">
          <!-- Sidebar user panel -->
          <div class="user-panel">
<!--            <div class="pull-left image">
              <img src="dist/img/user2-160x160.jpg" class="img-circle" alt="User Image" />
            </div>-->
            <div class="pull-left info">
              <p><?php // echo $this->session->storage->user_name; ?></p>

              <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
            </div>
          </div>
          <!-- search form -->
          <form action="#" method="get" class="sidebar-form">
            <div class="input-group">
              <input type="text" name="q" class="form-control" placeholder="Search..."/>
              <span class="input-group-btn">
                <button type='submit' name='search' id='search-btn' class="btn btn-flat"><i class="fa fa-search"></i></button>
              </span>
            </div>
          </form>
          <!-- /.search form -->
          <!-- sidebar menu: : style can be found in sidebar.less -->
          <ul class="sidebar-menu">
            <li class="header">MAIN NAVIGATION</li>
            <li class="active treeview">
              <a href="/admin/dashboard">
                <i class="fa fa-dashboard" ></i> <span>Dashboard</span>
              </a>
            </li>
            <li class="treeview">
              <a href="#">
                <i class="fa fa-futbol-o"></i>
                <span>Product Settings</span>
                <i class="fa fa-angle-left pull-right"></i>
                
              </a>
              <ul class="treeview-menu">
                <li><a href="/admin/contest-details"><i class="fa fa-circle-o"></i> Contest Details</a></li>
                <li><a href="/admin/contesttype-details"><i class="fa fa-circle-o"></i> Contest Type Details</a></li>
                <li><a href="/admin/add-newcontesttype"><i class="fa fa-circle-o"></i> Add New Contest Type</a></li>
                <li><a href="/admin/addnewcontest"><i class="fa fa-circle-o"></i> Add New Contest</a></li>
                <li><a href="/admin/contest-result"><i class="fa fa-circle-o"></i>Contest Result</a></li>
<!--                <li><a href="/admin/new-featuredcontest"><i class="fa fa-circle-o"></i> New Featured Contest</a></li>
                <li><a href="/admin/newfeatured-contestdetails"><i class="fa fa-circle-o"></i> New Featured Contest Details</a></li>-->
              </ul>
            </li>
            <li>
              <a href="pages/widgets.html">
                <i class="fa fa-bolt"></i>
                <span>Manage Orders</span>
                <i class="fa fa-angle-left pull-right"></i>
                <!--<small class="label pull-right bg-green">new</small>-->
              </a>
              <ul class="treeview-menu">
                <li><a href="/admin/offers"><i class="fa fa-circle-o"></i> order details</a></li>
               
              </ul>
            </li>
            <li class="treeview">
              <a href="#">
                <i class="fa fa-usd"></i>
                <span>Manage Users</span>
                <i class="fa fa-angle-left pull-right"></i>
              </a>
              <ul class="treeview-menu">
                <li><a href="/admin/depositor-details"><i class="fa fa-circle-o"></i>user Details</a></li>
              </ul>
            </li>
            <li class="treeview">
              <a href="#">
                <i class="fa fa-users"></i>
                <span>Transaction Manage</span>
                <i class="fa fa-angle-left pull-right"></i>
              </a>
              <ul class="treeview-menu">
                <li><a href="#"><i class="fa fa-circle-o"></i> Transaction Details</a></li>
               
              </ul>
            </li>
            <li class="treeview">
              <a href="#">
                <i class="fa fa-bar-chart"></i> <span>Site Settings</span>
                <i class="fa fa-angle-left pull-right"></i>
              </a>
              <ul class="treeview-menu">
                <li><a href="/admin/promotion-details"><i class="fa fa-circle-o"></i> Promotion Details</a></li>
                <li><a href="/admin/add-promotion-details"><i class="fa fa-circle-o"></i> Add Promotion Details</a></li>
              </ul>
            </li>
            <li class="treeview">
              <a href="#">
                <i class="fa fa-gamepad"></i> <span>Agents Manage</span>
                <i class="fa fa-angle-left pull-right"></i>
              </a>
              <ul class="treeview-menu">
                <li><a href="/admin/sports-details"><i class="fa fa-circle-o"></i> agent Details</a></li>
              </ul>
            </li>
            <li>
              <a href="#">
                <i class="fa fa-map-marker"></i> 
                <span>Log Manager</span>
                <i class="fa fa-angle-left pull-right"></i>
                <!--<small class="label pull-right bg-red">3</small>-->
              </a>
              <ul class="treeview-menu">
                <li><a href="/admin/ticket-details"><i class="fa fa-circle-o"></i>Transaction Log</a></li>
              </ul>
            </li>
          
          </ul>
        </section>
        <!-- /.sidebar -->
      </aside>
   <?php
   }
} 
?>

           
