<footer class="footer padding-md">
	<div class="container">
    	<div class="social text-center">
        	<ul class="list-inline list-unstyled">
            	<li class="facebook"><a href="#"><span><i class="fa fa-2x fa-facebook-square"></i></span></a></li>
                <li class="gplus"><a href="#"><span><i class="fa fa-2x fa-google-plus-square"></i></span></a></li>
                <li class="twitter"><a href="#"><span><i class="fa fa-2x fa-twitter-square"></i></span></a></li>
                <li class="pinterest"><a href="#"><span><i class="fa fa-2x fa-pinterest-square"></i></span></a></li>
            </ul>
        </div>
        <div class="text-center footer-menu">
        	<ul class="list-inline list-unstyled">
            	<li><a href="#">Demo Account</a></li>
                <li><a href="#">About Us</a></li>
                <li><a href="#">Contact Us</a></li>
                <li><a href="#">Advertise With us</a></li>
                <li><a href="#">Our Partners</a></li>
                <li><a href="#">Careers</a></li>
                <li><a href="#">Terms and Conditions</a></li>
                <li><a href="#">Privacy Policy</a></li>
            </ul>
        </div>
        <div class="text-center payment-gateways">
        	<ul class="list-inline list-unstyled">
            	<li><img class="img-responsive" src="images/cirrus.png"></li>
                <li><img class="img-responsive" src="images/mastercard.png"></li>
                <li><img class="img-responsive" src="images/mestrocard.png"></li>
                <li><img class="img-responsive" src="images/discover.png"></li>
                <li><img class="img-responsive" src="images/visa.png"></li>
                <li><img class="img-responsive" src="images/paypal.png"></li>
            </ul>
        </div>
        
        <div class="text-center">
        	<p>© Copyright 2015 Fansports. All Rights Reserved. </p>
        </div>
        
        
    </div>
</footer>
</html>