<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <?php
        # Title
        echo $this->headTitle();

        # Meta data
        echo $this->headMeta();

        # CSS
        echo $this->headLink()
                ->appendStylesheet($this->baseUrl() . $this->appSetting->assestPath . 'css/admin/bootstrap.min.css')
                ->appendStylesheet($this->baseUrl() . $this->appSetting->assestPath . 'css/admin/font-awesome.min.css')            
                ->appendStylesheet($this->baseUrl() . $this->appSetting->assestPath . 'css/admin/animate.css')
                ->appendStylesheet($this->baseUrl() . $this->appSetting->assestPath . 'css/admin/fansports-admin.css');


        # Javascript
        echo $this->headScript()
                                       
                ->appendFile($this->baseUrl() . $this->appSetting->assestPath . 'js/admin/jquery-1.11.2.min.js', 'text/javascript')
                ->appendFile($this->baseUrl() . $this->appSetting->assestPath . 'js/admin/bootstrap.min.js', 'text/javascript')
                ->appendFile($this->baseUrl() . $this->appSetting->assestPath . 'js/js/admin/fansports-admin.js', 'text/javascript');
                
        ?>

    </head>
   


