<?php
$allorderdetailsArray = $this->orderdetails;
//print_r($allorderdetailsArray);
?>
<div id="content" class="content">
    <ol class="breadcrumb pull-right">
        <li><a href="index.html">Home</a></li>
        <li><a href="javascript:;">Order Details</a></li>
        <li class="active">Order Details</li>
    </ol>
    <!-- end breadcrumb -->
    <!-- begin page-header -->
    <h1 class="page-header">Edit Order Details </h1>
    <!-- end page-header -->

    <!-- begin row -->
    <div class="row">
        <!-- begin col-12 -->
        <div class="col-md-12">
            <!-- begin panel -->
            <div class="panel pagination-theme clearfix m-b-0">
                <div class="panel-body">
                    <form class="" role="form" enctype="multipart/form-data" method="POST">
                        <div class="col-md-12">
                            <legend class="heading">Details:</legend>
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group has-success has-feedback m-b-10">
                                        <label class="control-label">Hotel Name</label>
                                        <input type="text" value="<?php
                                        if (isset($this->orderdetails[0]['hotel_name'])) {
                                            echo $this->orderdetails[0]['hotel_name'];
                                        }
                                        ?>" name="hotel_name" class="form-control" />
                                        <span class="fa fa-check form-control-feedback"></span>
                                    </div>

                                    <div class="form-group  m-b-10">
                                        <label class="control-label">Email</label>
                                        <input type="text" value="<?php
                                        if (isset($this->orderdetails[0]['email'])) {
                                            echo $this->orderdetails[0]['email'];
                                        }
                                        ?>" name="hotel_name" class="form-control" />

                                    </div>
                                    <div class="form-group  m-b-10">
                                        <label class="control-label">Order Date</label>
                                        <input type="text" value="<?php
                                        if (isset($this->orderdetails[0]['order_date'])) {
                                            echo $this->orderdetails[0]['order_date'];
                                        }
                                        ?>" name="hotel_name" class="form-control" />

                                    </div>
                                    <div class="form-group">
                                        <label class="control-label">Order Status</label>
                                        <select class="form-control selectpicker width-full" name="hotel_status" data-size="10">
                                            <option value="0" <?php
                                            if ($this->orderdetails[0]['order_status'] == 0) {
                                                echo "selected";
                                            }
                                            ?>>Pending</option>
                                            <option value="1" <?php
                                            if ($this->orderdetails[0]['order_status'] == 1) {
                                                echo "selected";
                                            }
                                            ?>>In Process</option>
                                            <option value="2" <?php
                                            if ($this->orderdetails[0]['order_status'] == 2) {
                                                echo "selected";
                                            }
                                            ?>>Delivered</option>
                                            <option value="3" <?php
                                            if ($this->orderdetails[0]['order_status'] == 3) {
                                                echo "selected";
                                            }
                                            ?>>Canceled</option>
                                            <option value="4" <?php
                                            if ($this->orderdetails[0]['order_status'] == 4) {
                                                echo "selected";
                                            }
                                            ?>>Dispatch</option>
                                        </select>
                                    </div>
                                    <div class="form-group">
                                        <label class="control-label">Pay Type</label>
                                        <select class="form-control selectpicker width-full" name="hotel_status" data-size="10">
                                            <option value="1" <?php
                                            if ($this->orderdetails[0]['pay_type'] == 1) {
                                                echo "selected";
                                            }
                                            ?>>COD</option>
                                            <option value="2" <?php
                                            if ($this->orderdetails[0]['pay_type'] == 2) {
                                                echo "selected";
                                            }
                                            ?>>PaYpaL</option>
                                            <option value="3" <?php
                                            if ($this->orderdetails[0]['pay_type'] == 2) {
                                                echo "selected";
                                            }
                                            ?>>No Payement GateWay</option>

                                        </select>
                                    </div>
                                    <div class="form-group m-b-10">
                                        <label class="control-label">Amount</label>
                                        <input type="text" value="<?php
                                        if ($this->orderdetails[0]['total_amount']) {
                                            echo $this->orderdetails[0]['total_amount'];
                                        }
                                        ?>" name="total_amount" class="form-control" />
                                    </div>
                                </div>

                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label class="control-label">Pay Status</label>
                                        <select class="form-control selectpicker width-full" name="hotel_status" data-size="10">
                                            <option value="1" <?php
                                            if ($this->orderdetails[0]['pay_status'] == 0) {
                                                echo "selected";
                                            }
                                            ?>>Pending</option>
                                            <option value="2" <?php
                                            if ($this->orderdetails[0]['pay_status'] == 1) {
                                                echo "selected";
                                            }
                                            ?>>Completed</option>
                                            <option value="3" <?php
                                            if ($this->orderdetails[0]['pay_status'] == 2) {
                                                echo "selected";
                                            }
                                            ?>>Failed</option>
                                            <option value="4" <?php
                                            if ($this->orderdetails[0]['pay_status'] == 3) {
                                                echo "selected";
                                            }
                                            ?>>Canceled</option>
                                            <option value="5" <?php
                                            if ($this->orderdetails[0]['pay_status'] == 5) {
                                                echo "selected";
                                            }
                                            ?>>No Acknowledgment</option>

                                        </select>
                                    </div>
                                    <div class="form-group">
                                        <label class="control-label">Delivery Status</label>
                                        <select class="form-control selectpicker width-full" name="hotel_status" data-size="10">
                                            <option value="1" <?php
                                            if ($this->orderdetails[0]['delivery_status'] == 0) {
                                                echo "selected";
                                            }
                                            ?>>Pending</option>

                                            <option value="2" <?php
                                            if ($this->orderdetails[0]['delivery_status'] == 1) {
                                                echo "selected";
                                            }
                                            ?>>Completed</option>
                                            <option value="3" <?php
                                            if ($this->orderdetails[0]['delivery_status'] == 2) {
                                                echo "selected";
                                            }
                                            ?>>Return/Canceled</option>
                                            <option value="4" <?php
                                            if ($this->orderdetails[0]['delivery_status'] == 3) {
                                                echo "selected";
                                            }
                                            ?>>Unable to Reach</option>
                                            <option value="5" <?php
                                            if ($this->orderdetails[0]['delivery_status'] == 4) {
                                                echo "selected";
                                            }
                                            ?>>No Acknowledgment</option>
                                        </select>
                                    </div>
                                    <div class="form-group">
                                        <label class="control-label">Delivery Type</label>
                                        <select class="form-control selectpicker width-full" name="hotel_status" data-size="10">
                                            <option value="1" <?php
                                            if ($this->orderdetails[0]['delivery_type'] == 1) {
                                                echo "selected";
                                            }
                                            ?>>Delivery to address</option>
                                            <option value="2" <?php
                                            if ($this->orderdetails[0]['delivery_type'] == 2) {
                                                echo "selected";
                                            }
                                            ?>>Pick up</option>
                                            <option value="3" <?php
                                            if ($this->hoteldetails[0]['delivery_type'] == 2) {
                                                echo "selected";
                                            }
                                            ?>>None of way choosen</option>

                                        </select>
                                    </div>
                                    <div class="form-group has-error has-feedback m-b-10">
                                        <label class="control-label">User Message</label>
                                        <textarea  name="address" class="form-control" rows="3"><?php
                                            if (isset($this->orderdetails[0]['user_message'])) {
                                                echo $this->orderdetails[0]['user_message'];
                                            }
                                            ?></textarea>
                                        <span class="fa fa-times form-control-feedback"></span>
                                    </div>


                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <!-- end panel -->
    </div>
    <!-- end col-12 -->
</div>
<!-- end row -->
