<div id="content" class="content">
    <!-- begin page-header -->
    <h1 class="page-header">Order Details </h1>
    <!-- end page-header -->

    <!-- begin row -->
    <div class="row">
        <!-- begin col-12 -->
        <div class="col-md-12">
            <!--  begin panel -->
            <div class="panel pagination-theme clearfix m-b-0">
                <div class="table-responsive">
                    <table id="data-table" data-order='[[1,"asc"]]' class="table table-bordered table-hover">
                        <thead>
                            <tr class="default">
                                <th>S.no</th>
                                <th>User Name</th>   
                                <th>Email</th>
                                <th>Hotel Name</th>
                                <th>Order ID</th>
                                <th>Order Date</th>
                                <th>Order Status</th>                         
                                <th>Amount</th>
                                <th>View/Delete</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php
                            if (isset($this->orderedproducts)) {
                                $i = 0;
                                foreach ($this->orderedproducts as $value) {
                                    ?>
                                    <tr>
                                        <td><?php echo ++$i; ?></td>
                                        <td><?php echo $value['uname']; ?></td>
                                        <td><?php echo $value['email']; ?></td>
                                        <td><?php echo $value['hotel_name']; ?></td>
                                        <td><?php echo $value['order_id']; ?></td>
                                        <td><?php echo date("j F , Y h:i:s A", strtotime($value['order_date'])); ?></td>                                       
                                        <td> <?php
                                            if ($value['order_status'] == 0) {
                                                echo 'Pending';
                                            } else if ($value['order_status'] == 1) {
                                                echo ' In Process';
                                            } else if ($value['order_status'] == 2) {
                                                echo ' Delivered';
                                            } else if ($value['order_status'] == 3) {
                                                echo 'Canceled';
                                            } else {
                                                echo 'Dispatch';
                                            }
                                            ?></td>

                                        <td><?php echo $value['total_amount']; ?></td>                                        
                                        <td class="text-center">
                                            <a data-id="<?php echo $value['hotel_name']; ?>" href="/agent/view-restuarent-orders/<?php echo $value['order_id']; ?>" class="btn btn-purple btn-icon btn-circle btn-sm">
                                                <i class="fa fa-eye"></i>
                                            </a>
<!--                                            <a data-id="<?php echo $value['hotel_name']; ?>" href="/agent/edit-restuarent-orders/<?php echo $value['order_id']; ?>" class="btn btn-success btn-icon btn-circle btn-sm">
                                                <i class="fa fa-pencil"></i>
                                            </a>-->

                                        </td>

                                    </tr> 
                                    <?php
                                }
                            }
                            ?>
                        </tbody>
                    </table>
                </div>
            </div>
            <!-- end panel -->
        </div>
        <!-- end col-12 -->
    </div>
    <!-- end row -->
</div>









