<style>
    #editCountry {
        display: none;
    }
</style>

<div id="content" class="content">
    <ol class="breadcrumb pull-right">
        <li><a href="/agent/dashboard">Dashboard</a></li>
        <li><a href="javascript:;">Settings</a></li>
        <li class="active"><a href="/agent/grocery-category">Grocery Category</a></li>
    </ol>
    <h1 class="page-header">Grocery Category </h1>
    <div class="row">
        <!-- begin col-12 -->
        <div class="col-md-12">
            <!-- begin panel -->
            <div class="panel pagination-theme clearfix m-b-0" id="addCountry">
                <div class="panel-heading">
                    <h4 class="panel-title">Add Grocery Category</h4>
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-md-10 col-md-offset-1">
                            <form class="" role="form" method="POST">
                                <div class="form-group row m-t-20 m-b-10">
                                    <label class="col-sm-2 control-label">Enter the Grocery Category</label>
                                    <div class="col-sm-10">
                                          <input type="text" class="form-control" name="categoryname"  placeholder="" required />
                                    </div>
                                </div>
                                 <div class="form-group row m-t-20 m-b-10">
                                    <label class="col-sm-2 control-label">Enter the Description</label>
                                    <div class="col-sm-10">
                                        <input type="text" class="form-control" name="cat_desc"  id="cat_desc" placeholder=""  />
                                    </div>
                                </div>
                                <div class="form-group row m-t-20 m-b-10">
                                    <label class="col-sm-2 control-label">Status</label>
                                    <div class="col-sm-5">
                                        <select  class="selectpicker width-full js-example-basic-hide-search " name="cat_status">
                                            <option value="1">
                                                Active
                                            </option>
                                            <option value="2">
                                                Deactivate
                                            </option>
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group text-right m-b-20">
                                    <button type="submit" class="btn btn-theme">SAVE</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <!-- end panel -->

            <!-- begin panel -->
            <div class="panel pagination-theme clearfix m-b-0" id="editCountry">

                <div class="panel editContent">
                    <div class="panel-body">
                        <h3 class="title-hero">Edit Grocery Category</h3>
                        <div class="example-box-wrapper">
                            <div class="row">
                                <div class="col-md-10 col-md-offset-1">
                                    <form class="form-horizontal bordered-row" method="POST" action="edit-grocery-category">
                                        <div class="form-group">
                                            <label class="col-sm-2 control-label">Category Name</label>
                                            <div class="col-sm-10">
                                                <input type="text" class="form-control" id="editcategory"  name="category" placeholder="" value="" required />
                                            </div>
                                            <div class="col-sm-10 hidden">
                                                <input type="text" class="form-control" id="categoryid"  name="category_id" placeholder="" value="" required />
                                            </div>
                                        </div>
                                          <div class="form-group">
                                            <label class="col-sm-2 control-label">Category Description</label>
                                            <div class="col-sm-10">
                                                <input type="text" class="form-control" id="editcategorydesc"  name="catdesc" placeholder="" value=""  />
                                            </div>
                                            <div class="col-sm-10 hidden">
                                                <input type="text" class="form-control" id="categorydesc"  name="cat_desc" placeholder="" value=""  />
                                            </div>
                                        </div>
                                        <div class="form-group pull-right">
                                            <button type="submit" name="categorybtn"  value="category" class="btn btn-alt btn-hover btn-primary">
                                                <span>UPDATE</span> <i class="glyph-icon icon-refresh"></i>
                                                <div class="ripple-wrapper"></div>
                                            </button>
                                            <button class="btn btn-alt btn-hover btn-info">
                                                <span>CANCEL</span> <i class="glyph-icon icon-trash"></i>
                                                <div class="ripple-wrapper"></div>
                                            </button>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- end panel -->
        </div>
        <!-- end col-12 -->
    </div>
    <!-- end row -->

    <!-- begin row -->
    <div class="row m-t-20">
        <!-- begin col-12 -->
        <div class="col-md-12">
            <!-- begin panel -->
            <div class="panel pagination-theme clearfix m-b-0">
                <div class="panel-heading">
                    <h4 class="panel-title">Country Details</h4>
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-md-12">
                            <table id="data-table" data-order='[[0,"asc"]]' class="table table-bordered table-hover">
                                <thead>
                                    <tr class="default">
                                        <th>S. No.</th>                            
                                <th>Category Name</th>
                                <th>Category Description</th>
                                <th>Status</th>
                                <th>Action</th>
                                <th>Edit/Delete</th>
                                    </tr>
                                </thead>
                                <tbody>

                                    <?php
                                    if (isset($this->categorydetails)) {
                                        $i = 1;
                                        foreach ($this->categorydetails as $value) {
                                            ?>
                                           <tr id="<?php echo $value['category_id']; ?>">
                                    <td><?php echo ++$i; ?></strong></td>                                 
                                    <td><?php echo $value['cat_name']; ?></td>
                                    <td><?php echo $value['cat_desc']; ?></td>
                                                <?php if ($value['cat_status'] == 1): ?>
                                                    <td id="activecategory_<?php echo $value['category_id']; ?>" class="grocerycategoryactive">Active</td>
                                                    <td class="center"><a style="cursor:pointer"  id="<?php
                                                        if (isset($value['category_id'])): echo "category_" . $value['category_id'];
                                                        endif;
                                                        ?>" class="grocerycategorydeactive" >
                                                            <span id="activeclass_<?php echo $value['category_id']; ?>" class="label label-danger">Deactivate</span></a></td>
                                                <?php else: ?>
                                                    <td id="activecategory_<?php echo $value['category_id']; ?>" class="grocerycategorydeactive">Suspended</td>
                                                    <td class="center" ><a style="cursor:pointer" id="<?php
                                                        if (isset($value['category_id'])): echo "category_" . $value['category_id'];
                                                        endif;
                                                        ?>" class="grocerycategoryactive" >
                                                            <span id="activeclass_<?php echo $value['category_id']; ?>"  class="label label-success">Activate</span></a></td>
                                                <?php endif; ?>
                                                <td class="text-center">
                                                    <a href="#" class="btn btn-purple btn-icon btn-circle btn-sm grocerycategoryedit" id="showEdit_<?php echo $value['category_id']; ?>">
                                                        <i class="fa fa-pencil"></i>
                                                    </a>
                                                    <a href="javascript:;" id="<?php echo "categorydelete_" . $value['category_id']; ?>" class="btn btn-danger btn-icon btn-circle btn-sm grocerycategorydelete">
                                                        <i class="fa fa-trash"></i>
                                                    </a>
                                                </td>
                                            </tr>
                                            <?php
                                        }
                                    }
                                    ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
            <!-- end panel -->
        </div>
        <!-- end col-12 -->
    </div>
    <!-- end row -->
</div>


<script>
    $(function() {
        $('.grocerycategoryedit').click(function() {
            $('#editCountry').show();
            $('#addCountry').hide();
        });
        $('.clearCountry').click(function() {
            $('#editCountry').hide();
            $('#addCountry').show();
        });
    });
</script>