<style>
    #editCuisine {
        display: none;
    }
</style>

<div id="content" class="content">
    <ol class="breadcrumb pull-right">
        <li><a href="/agent/dashboard">Dashboard</a></li>
        <li><a href="javascript:;">hotel Details</a></li>
        <li class="active"><a href="/agent/hotel-cuisine">hotel Cuisine</a></li>
    </ol>
    <h1 class="page-header">hotel Cuisine </h1>
    <div class="row" >
        <div class="col-md-12">
            <div class="panel addContent" id="addCuisine">
                <div class="panel-body">
                    <h3 class="title-hero">Add Cuisine</h3>
                    <div class="example-box-wrapper">
                        <div class="row">
                            <div class="col-md-10 col-md-offset-1">
                                <form class="form-horizontal bordered-row" method="POST">
                                    <div class="form-group">
                                        <label class="col-sm-2 control-label">Choose the Hotel</label>
                                        <div class="col-sm-10">
                                            <select class="js-example-responsive form-control" name="hotels" style="width:100%;" id="test">
                                                <option disabled selected>Select Hotel</option>
                                                <?php foreach ($this->cuisinedetails[1] as $value) { ?>
                                                    <option value="<?php echo $value['id'] ?>">
                                                        <?php echo $value['hotel_name'] ?>
                                                    </option>
                                                <?php } ?>
                                            </select>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-sm-2 control-label">Enter the Cuisine</label>
                                        <div class="col-sm-10">
                                            <input type="text" class="form-control" name="cuisinename" disabled
                                                   id="demo" placeholder="" required/>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-sm-2 control-label">Status</label>
                                        <div class="col-sm-5">
                                            <select
                                                class="js-example-responsive js-example-basic-hide-search form-control"
                                                name="cuisine_status">
                                                <option value="1">
                                                    Active
                                                </option>
                                                <option value="2">
                                                    Inactive
                                                </option>
                                            </select>
                                        </div>
                                    </div>
                                    <div class="form-group pull-right">
                                        <button type="submit" class="btn btn-alt btn-hover btn-primary">
                                            <span>SAVE</span> <i class="glyph-icon icon-arrow-right"></i>
                                            <div class="ripple-wrapper"></div>
                                        </button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
            <div class="panel editContent" id="editCuisine">
                <div class="panel-body">
                    <h3 class="title-hero">Edit Cuisine</h3>
                    <div class="example-box-wrapper">
                        <div class="row">
                            <div class="col-md-10 col-md-offset-1">
                                <form class="form-horizontal bordered-row" method="POST" action="/agent/edit-hotel-cuisines">
                                    <div class="form-group">
                                        <label class="col-sm-2 control-label">Cuisine Name</label>
                                        <div class="col-sm-10">
                                            <input type="text" class="form-control" id="editcuisinename" name="cuisine"
                                                   placeholder="" value="" required/>
                                        </div>
                                        <div class="col-sm-10 hidden">
                                            <input type="text" class="form-control" id="cuisineid" name="cuisine_id"
                                                   placeholder="" value="" required/>
                                        </div>
                                    </div>
                                    <div class="form-group pull-right">
                                        <button type="submit" name="cuisinebtn" value="cuisine"
                                                class="btn btn-alt btn-hover btn-primary">
                                            <span>UPDATE</span> <i class="glyph-icon icon-refresh"></i>
                                            <div class="ripple-wrapper"></div>
                                        </button>
                                        <button class="btn btn-alt btn-hover btn-info">
                                            <span>CANCEL</span> <i class="glyph-icon icon-trash"></i>
                                            <div class="ripple-wrapper"></div>
                                        </button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- begin row -->
    <div class="row m-t-20">
        <!-- begin col-12 -->
        <div class="col-md-12">
            <!-- begin panel -->
            <div class="panel pagination-theme clearfix m-b-0">
                <div class="panel-heading">
                    <h4 class="panel-title">hotel Cuisine</h4>
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-md-12">
                            <table id="data-table" data-order='[[0,"asc"]]' class="table table-bordered table-hover">
                                <thead>
                                <tr class="default">
                                    <th>S. No.</th>
                                    <th>Hotel Name</th>
                                    <th>Cuisine Name</th>
                                    <th>Status</th>
                                    <th>Action</th>
                                    <th>Edit/Delete</th>
                                </tr>
                                </thead>
                                <tbody>

                                <?php
                                if (isset($this->cuisinedetails[0])) {
                                    $i = 0;
                                    foreach ($this->cuisinedetails[0] as $value) {

                                        $i++;
                                        ?>
                                        <tr id="<?php echo $value['cuisine_id']; ?>">
                                            <td><strong><?php echo $i; ?></strong></td>
                                            <td><strong><?php echo $value['hotel_name']; ?></strong></td>
                                            <td><strong><?php echo $value['Cuisine_name']; ?></strong></td>


                                            <?php if ($value['cuisine_status'] == 1) { ?>
                                                <td>
                                                    <label id="activeclass_<?php echo $value['cuisine_id']; ?>"
                                                           class="label label-success js-check-change-field">ACTIVE</label>
                                                </td>

                                                <td class="text-center">
                                                    <input type="checkbox" data-render="switchery"
                                                           id="<?php if (isset($value['cuisine_id'])): echo "hotel_" . $value['cuisine_id'];
                                                           endif;
                                                           ?>" class="js-switch js-check-change hotelcuisinedeactive"
                                                           data-theme="lime"
                                                           checked/>
                                                </td>
                                            <?php } else { ?>
                                                <td>
                                                    <label id="activeclass_<?php echo $value['cuisine_id']; ?>"
                                                           class="label label-danger js-check-change-field">SUSPENDED</label>
                                                </td>
                                                <td class="text-center">
                                                    <input type="checkbox" data-render="switchery"
                                                           id="<?php if (isset($value['cuisine_id'])): echo "hotel_" . $value['cuisine_id'];
                                                           endif;
                                                           ?>" class="js-switch js-check-change hotelcuisineactive"
                                                           data-theme="lime"/>
                                                </td>
                                            <?php } ?>


                                            <td class="text-center">
                                                <a href="#" data_id="<?php echo $value['Cuisine_name']; ?>"
                                                   class="btn btn-purple btn-icon btn-circle btn-sm hotelcuisineedit"
                                                   id="showEdit_<?php echo $value['cuisine_id']; ?>">
                                                    <i class="fa fa-pencil"></i>
                                                </a>
                                                <a href="javascript:;"
                                                   id="<?php echo "cuisinedelete_" . $value['cuisine_id']; ?>"
                                                   class="btn btn-danger btn-icon btn-circle btn-sm hotelcuisinedelete">
                                                    <i class="fa fa-trash"></i>
                                                </a>
                                            </td>
                                        </tr>

                                        <?php
                                    }
                                }
                                ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
            <!-- end panel -->
        </div>
        <!-- end col-12 -->
    </div>
    <!-- end row -->
</div>

<!--<style>-->
<!--    #test .select2-search.select2-search--dropdown {-->
<!--        display: none;-->
<!--    }-->
<!--</style>-->

<script>
    $(function () {
        $('.hotelcuisineedit').click(function () {
            $('#editCuisine').show();
            $('#addCuisine').hide();
        });
        $('.clearCountry').click(function () {
            $('#editCuisine').hide();
            $('#addCuisine').show();
        });
    });
</script>

