<div id="page-title">
    <h2>Coupon Logs</h2>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="panel">
            <div class="panel-body">
                <h3 class="title-hero">Coupon Logs</h3>
                <div class="example-box-wrapper">
                    <table class="table table-striped table-bordered responsive no-wrap datatable-responsive" cellspacing="0" width="100%">
                        <thead>
                            <tr>
                                <th>S.No. </th>
                                <th>Coupon ID</th>                        
                                <th>Coupon Code</th>
                                <th>User Name</th>
                                <th>Product Name</th>
                                <th>Used On</th>
                                <th> Delete</th>

                            </tr>
                        </thead>
                        <tfoot>
                            <tr>
                                <th>S.No. </th>
                                <th>Coupon ID</th>                           
                                <th>Coupon Code</th>
                                <th>User Name</th>
                                <th>Product Name</th>
                                <th>Used On</th>
                                <th> Delete</th>

                            </tr>
                        </tfoot>
                        <tbody>
                            <?php
                            if (isset($this->couponsLog)) {
                                foreach ($this->couponsLog as $couponKey => $couponValue) {
                                    ?>
                                    <tr class="selectable" id="<?php echo $couponValue['coupon_id']; ?>">
                                        <td><?php echo ++$couponKey; ?></td>
                                        <td><?php echo $couponValue['coupon_id']; ?></td>
                                        <td><?php echo $couponValue['coupon_code']; ?></td>
                                        <td><?php echo $couponValue['first_name'] . " " . $couponValue['last_name']; ?></td>
                                        <td><?php
                                            for ($i = 0; $i < count($couponValue['product_id']); $i++) {
                                                echo $couponValue['product_id'][$i] . ',';
                                            }
                                            ?></td>
                                        <td><?php echo date('d F Y - h:i A', $couponValue['used_date']); ?></td>
                                        <td class="text-center">                                                                                           
                                            <a href="javascript:;" id="<?php echo "couponuserdelete_" . $couponValue['coupon_users_id']; ?>" class="btn btn-default deletecouponuser"><i class="glyph-icon icon-linecons-trash"></i></a>
                                        </td>
                                    </tr>
                                    <?php
                                }
                            }
                            ?>	
                        </tbody>
                    </table>
                    <!--//TABLE-->
                </div>
            </div>
            <!-- END EXAMPLE TABLE PORTLET-->
        </div>
    </div>
</div>



