<div id="page-title">
    <h2>Coupon Details</h2>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="panel">
            <div class="panel-body">
                <h3 class="title-hero">Edit/Remove Coupon Details</h3>
                <div class="example-box-wrapper">
                    <table class="table table-striped table-bordered responsive no-wrap datatable-responsive" cellspacing="0" width="100%">
                        <thead>
                            <tr>
                                <th>S.No. </th>
                                <th>Coupon ID</th>
                                <th>Coupon Code</th>
                                <th>Validity</th>
                                <th>Availability</th>
                                <th>Discount</th>
                                <th> Status </th>
                                <th> Action </th>
                                <th> Edit/Delete</th>

                            </tr>
                        </thead>
                        <tfoot>
                            <tr>
                                <th>S.No. </th>
                                <th>Coupon ID</th>
                                <th>Coupon Code</th>
                                <th>Validity</th>
                                <th>Availability</th>
                                <th>Discount</th>
                                <th> Status </th>
                                <th> Action </th>
                                <th> Edit/Delete</th>

                            </tr>
                        </tfoot>
                        <tbody>

                            <?php
                            if (isset($this->allcoupons)) {
                                $i=1;
                                foreach ($this->allcoupons as $couponValue) {
                             
                                        ?>
                                        <tr class="selectable" id="<?php echo $couponValue['coupon_id']; ?>">
                                             <td><?php echo $i; ?></td>
                                            <td><?php echo $couponValue['coupon_id']; ?></td>
                                            <td><?php echo $couponValue['coupon_code']; ?></td>
                                            <td><?php echo date('d F Y - h:i A', $couponValue['coupon_valid_from']); ?><br>to<br><?php echo date('d F Y - h:i A', $couponValue['coupon_valid_upto']); ?></td>
                                            <td><?php
                                                if ($couponValue['availability'] == 0)
                                                    echo "Unlimited";
                                                else if ($couponValue['availability'] == 1)
                                                    echo $couponValue['availability_value'];
                                                ?></td>
                                            <td>
                                                <?php
                                                if ($couponValue['discount_type'] == 0) {
                                                    echo $couponValue['discount_value'] . ' %';
                                                } else if ($couponValue['discount_type'] == 1) {
                                                    echo 'Rs. ' . $couponValue['discount_value'];
                                                }
                                                ?></td>
                                                <?php if ($couponValue['coupon_status'] == 1): ?>
                                                <td id="activecoupon_<?php echo $couponValue['coupon_id']; ?>" class="couponactive">Active</td>
                                                <td class="center"><a style="cursor:pointer"  id="<?php
                                                    if (isset($couponValue['coupon_id'])): echo "coupon_" . $couponValue['coupon_id'];
                                                    endif;
                                                    ?>" class="coupondeactive">
                                                        <span id="activeclass_<?php echo $couponValue['coupon_id']; ?>" class="bs-label label-danger">Deactivate</span></a></td>
                                            <?php else: ?>
                                                <td id="activecoupon_<?php echo $couponValue['coupon_id']; ?>" class="coupondeactive">Suspended</td>
                                                <td class="center" ><a style="cursor:pointer" id="<?php
                                                    if (isset($couponValue['coupon_id'])): echo "coupon_" . $couponValue['coupon_id'];
                                                    endif;
                                                    ?>" class="couponactive">
                                                        <span id="activeclass_<?php echo $couponValue['coupon_id']; ?>"  class="bs-label label-success">Activate</span></a></td>
                                            <?php endif; ?> 


                                            <td class="text-center">                                              
                                                <a href="/admin/edit-coupon/<?php echo $couponValue['coupon_id']; ?>" class="btn btn-default"><i class="glyph-icon icon-linecons-pencil"></i></a>
                                                <a href="javascript:;" id="<?php echo "coupondelete_" . $couponValue['coupon_id']; ?>" class="btn btn-default deletecoupon"><i class="glyph-icon icon-linecons-trash"></i></a>
                                            </td>
                                        </tr>
                                        <?php
                                        $i++;
                                    }
                                }
                      
                            ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>






<!--<style>
    th{text-align: center;}
    td{text-align: center;vertical-align:middle !important;}
</style>
<div class="page-content-wrapper">
    <div class="page-content">
        <div class="row">
            <div class="col-md-12">
                 BEGIN EXAMPLE TABLE PORTLET
                <div class="portlet light bordered">
                    <div class="portlet-title">
                        <div class="caption">
                            <i class="fa fa-list"></i>All Coupons
                        </div>
                        <div class="actions">
                            <a href="/admin/add-new-coupon" id="submit" name="formbutton" class="btn btn-circle btn-default" style="margin-left: 20px"><i class="fa fa-plus font-blue-hoki"></i>&nbsp;Add New Coupon</a>
                        </div>
                    </div>
                    <div class="portlet-body">
                        TABLE
                        <table class="dynamicTable table table-bordered table-condensed" style="width: 100%" id='coupon-table'>
                            <thead>
                                <tr>
                                    <th>Coupon ID</th>
                                    <th>Coupon Code</th>
                                    <th>Validity</th>
                                    <th>Availability</th>
                                    <th>Discount</th>
                                    <th>Edit/Delete</th>
                                    <th>Status</th>
                                </tr>
                            </thead>
                            <tbody>
<?php
if (isset($this->allcoupons)) {
    foreach ($this->allcoupons as $couponKey => $couponValue) {
        if ($couponValue['coupon_status'] != 2) {
            ?>
                                                                                <tr class="selectable" id="<?php echo $couponValue['coupon_id']; ?>">
                                                                                    <td><?php echo $couponValue['coupon_id']; ?></td>
                                                                                    <td><?php echo $couponValue['coupon_code']; ?></td>
                                                                                    <td><?php echo date('d F Y - h:i A', $couponValue['coupon_valid_from']); ?><br>to<br><?php echo date('d F Y - h:i A', $couponValue['coupon_valid_upto']); ?></td>
                                                                                    <td><?php
            if ($couponValue['availability'] == 0)
                echo "Unlimited";
            else if ($couponValue['availability'] == 1)
                echo $couponValue['availability_value'];
            ?></td>
                                                                                    <td>
            <?php
            if ($couponValue['discount_type'] == 0) {
                echo $couponValue['discount_value'] . ' %';
            } else if ($couponValue['discount_type'] == 1) {
                echo 'Rs. ' . $couponValue['discount_value'];
            }
            ?>
                                                                                    </td>
                                                                                    <td>
                                                                                        <a class='btn btn-default btn-sm edit' href='/admin/edit-coupon/<?php echo $couponValue['coupon_id']; ?>' style='margin-left: 5%;'><i class="fa fa-pencil"></i></a>
                                                                                        <button  data-id="<?php echo $couponValue['coupon_id']; ?>" id="<?php echo $couponValue['coupon_id']; ?>" class="btn btn-danger btn-sm delete-coupon" style='margin-left: 10%;'><i class="fa fa-trash-o"></i></button>
                                                                                    </td>
                                                                                    <td>
            <?php if ($couponValue['coupon_status'] == 1) { ?>
                                                                                                        <button style="margin-left: 10%;" class="btn btn-info btn-sm change-coupon-status" data-id="<?php echo $couponValue['coupon_id']; ?>">Active</button>
            <?php } elseif ($couponValue['coupon_status'] == 0) { ?>
                                                                                                        <button style="margin-left: 10%;" class="btn btn-danger btn-sm change-coupon-status" data-id="<?php echo $couponValue['coupon_id']; ?>">Inactive</button>
            <?php } ?>
                                                                                    </td>
                                                                                </tr>
            <?php
        }
    }
}
?>	
                            </tbody>
                        </table>
                        //TABLE
                    </div>
                </div>
                 END EXAMPLE TABLE PORTLET
            </div>
        </div>
    </div>
</div>


<script type="text/javascript">

    $(document).ready(function () {


        var table = $('#coupon-table');
        var oTable = table.dataTable({
            "lengthMenu": [
                [10, 20, 100, -1],
                [10, 20, 100, "All"]
            ],
            "bAutoWidth": false,
            "rowCallback": function (row, data) {

            },
            "columnDefs": [{// define columns sorting options(by default all columns are sortable extept the first checkbox column)
                    'orderable': false,
                    'targets': [5, 6]
                }]
        });

        $(document.body).on("click", ".change-coupon-status", function () {
            var obj = $(this);
            var couponId = $(this).attr('data-id');
            $.ajax({
                url: '/admin/coupons-ajax-handler',
                type: 'POST',
                datatype: 'json',
                data: {
                    method: 'changeCouponStatus',
                    couponId: couponId
                },
                success: function (response) {
                    if (response) {
                        if (obj.hasClass('btn-info')) {
                            obj.removeClass('btn-info');
                            obj.addClass('btn-danger');
                            obj.text('Inactive');
                        } else {
                            obj.removeClass('btn-danger');
                            obj.addClass('btn-info');
                            obj.text('Active');
                        }
                    }
                },
                error: function (response) {
                    bootbox.alert("An exception occurred, while changing the coupon status. Please reload the page and try again.");
                }
            });
        });

        $(document.body).on("click", ".delete-coupon", function (e) {
            e.preventDefault();
            var couponID = $(this).attr('data-id');
            bootbox.confirm("Are you sure you want to delete this Coupon?", function (result) {
                if (result) {
                    Metronic.blockUI({
                        boxed: true,
                        message: 'Deleting the coupon...'
                    });
                    $.ajax({
                        url: '/admin/coupons-ajax-handler',
                        type: 'POST',
                        datatype: 'json',
                        data: {
                            method: 'deleteCoupon',
                            couponId: couponID
                        },
                        success: function (response) {
                            Metronic.unblockUI();
                            if (response == 1) {
                                oTable.fnDeleteRow(document.getElementById(couponID));
                            }
                        },
                        error: function (response) {
                            Metronic.unblockUI();
                            bootbox.alert("An exception occurred, while deleting the selected coupon. Please reload the page and try again.");
                        }
                    });
                }
            });
        });
    });

</script>-->
