

<script src="/themes/agent/skin/js/jquery-1.8.2.min.js"></script>
<script src="/themes/agent/skin/js/jquery-ui.min.js"></script>
<script src="/themes/agent/skin/js/bootstrap.min.js"></script>
<!--[if lt IE 9]>
        <script src="assets/crossbrowserjs/html5shiv.js"></script>
        <script src="assets/crossbrowserjs/respond.min.js"></script>
        <script src="assets/crossbrowserjs/excanvas.min.js"></script>
<![endif]-->
<script src="/themes/agent/skin/js/jquery.slimscroll.min.js"></script>

<script>
    $(document).ready(function() {
        App.init();
        Dashboard.init();
        $('.dropdown-toggle').dropdown();
    });
</script>

<script src="/themes/agent/skin/js/apps.min.js"></script>
</body>
</html>