<?php
if ($this->auth->hasIdentity()) {
    if ($this->session->storage->role ==1||$this->session->storage->role == 4) {
        ?>
        <div id="footer" class="footer">
            <span class="pull-right">
                <a href="javascript:;" class="btn-scroll-to-top" data-click="scroll-top">
                    <i class="fa fa-arrow-up"></i> <span class="hidden-xs">Back to Top</span>
                </a>
            </span>
            &copy; 2016 Copyright <b>Ziingo</b>. A <a href="javascript:;">Worldjunction</a> LLC Company. 
        </div>
        <!-- end #footer -->

        <!-- end #content -->
        </div>
        <?php
    }
} else {
    ?>
    </div>


<?php }
?>

<?php echo $this->render('scripts.phtml'); ?>
</body>
</html>


