<!DOCTYPE html>

<html lang="en">


    <head>
        <meta charset="utf-8" />
        <title>Ziingo || Agent Panel</title>
        <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" name="viewport" />
        <meta content="" name="description" />
        <meta content="AllThatIsRam" name="author" />
        <link rel="icon" type="image/png" href="<?php echo $this->baseUrl() . $this->theme_base_path ?>/images/favicon.png">
        <link id="fontFamilySrc" rel="stylesheet" href="http://fonts.googleapis.com/css?family=Nunito:400,300,700">       

        <script src="/themes/agent/skin/js/pace.min.js"></script>
        <?php
        # Title
        echo $this->headTitle();

        # Meta data
        echo $this->headMeta();
        # CSS
        echo $this->headLink()
                ->appendStylesheet($this->baseUrl() . $this->theme_base_path . '/css/jquery-ui.min.css')
                ->appendStylesheet($this->baseUrl() . $this->theme_base_path . '/css/bootstrap.min.css')
                ->appendStylesheet($this->baseUrl() . $this->theme_base_path . '/css/font-awesome.min.css')
                ->appendStylesheet($this->baseUrl() . $this->theme_base_path . '/css/animate.min.css')
                ->appendStylesheet($this->baseUrl() . $this->theme_base_path . '/css/style.min.css')
                ->appendStylesheet($this->baseUrl() . $this->theme_base_path . '/css/custom.css')
                ->appendStylesheet($this->baseUrl() . $this->theme_base_path . '/css/dataTables.bootstrap.min.css')
                ->appendStylesheet($this->baseUrl() . $this->theme_base_path . '/css/responsive.bootstrap.min.css')
                ->appendStylesheet($this->baseUrl() . $this->theme_base_path . '/css/switchery.min.css')
                ->appendStylesheet($this->baseUrl() . $this->theme_base_path . '/css/custom.css')
                ->appendStylesheet($this->baseUrl() . $this->theme_base_path . '/css/jasny-bootstrap.min.css')
                ->appendStylesheet($this->baseUrl() . $this->theme_base_path . '/css/select2.min.css');

        if ($this->auth->hasIdentity()) {
            if ($this->session->storage->role == 1||$this->session->storage->role == 4) {

                echo $this->headScript()
                        ->appendFile($this->baseUrl() . $this->theme_base_path . '/js/jquery-1.9.1.min.js', 'text/javascript')
                        ->appendFile($this->baseUrl() . $this->theme_base_path . '/js/jquery-migrate-1.1.0.min.js', 'text/javascript')
                        ->appendFile($this->baseUrl() . $this->theme_base_path . '/js/jquery-ui.min.js', 'text/javascript')
                        ->appendFile($this->baseUrl() . $this->theme_base_path . '/js/bootstrap.min.js', 'text/javascript')
                        ->appendFile($this->baseUrl() . $this->theme_base_path . '/js/jquery.slimscroll.min.js', 'text/javascript')
                        ->appendFile($this->baseUrl() . $this->theme_base_path . '/js/jquery.cookie.js', 'text/javascript')
                        ->appendFile($this->baseUrl() . $this->theme_base_path . '/js/switchery.min.js', 'text/javascript')
                        ->appendFile($this->baseUrl() . $this->theme_base_path . '/js/jquery.dataTables.js', 'text/javascript')
                        ->appendFile($this->baseUrl() . $this->theme_base_path . '/js/dataTables.bootstrap.min.js', 'text/javascript')
                        ->appendFile($this->baseUrl() . $this->theme_base_path . '/js/dataTables.responsive.min.js', 'text/javascript')
                        ->appendFile($this->baseUrl() . $this->theme_base_path . '/js/select2.min.js', 'text/javascript')
                        ->appendFile($this->baseUrl() . $this->theme_base_path . '/js/jasny-bootstrap.min.js', 'text/javascript')
                        ->appendFile($this->baseUrl() . $this->theme_base_path . '/js/apps.min.js', 'text/javascript');
            }
        } else {
            echo $this->headScript()
                    ->appendFile($this->baseUrl() . $this->theme_base_path . '/js/jquery-1.9.1.min.js', 'text/javascript')
                    ->appendFile($this->baseUrl() . $this->theme_base_path . '/js/jquery-migrate-1.1.0.min.js', 'text/javascript')
                    ->appendFile($this->baseUrl() . $this->theme_base_path . '/js/jquery-ui.min.js', 'text/javascript')
                    ->appendFile($this->baseUrl() . $this->theme_base_path . '/js/bootstrap.min.js', 'text/javascript')
                    ->appendFile($this->baseUrl() . $this->theme_base_path . '/js/jquery.slimscroll.min.js', 'text/javascript')
                    ->appendFile($this->baseUrl() . $this->theme_base_path . '/js/jquery.cookie.js', 'text/javascript')
                    ->appendFile($this->baseUrl() . $this->theme_base_path . '/js/switchery.min.js', 'text/javascript')
                    ->appendFile($this->baseUrl() . $this->theme_base_path . '/js/jquery.dataTables.js', 'text/javascript')
                    ->appendFile($this->baseUrl() . $this->theme_base_path . '/js/dataTables.bootstrap.min.js', 'text/javascript')
                    ->appendFile($this->baseUrl() . $this->theme_base_path . '/js/dataTables.responsive.min.js', 'text/javascript')
                    ->appendFile($this->baseUrl() . $this->theme_base_path . '/js/select2.min.js', 'text/javascript')
                    ->appendFile($this->baseUrl() . $this->theme_base_path . '/js/jasny-bootstrap.min.js', 'text/javascript')
                    ->appendFile($this->baseUrl() . $this->theme_base_path . '/js/apps.min.js', 'text/javascript');
        }
        ?>   
    </head> 
    <body>


        <?php
        if ($this->auth->hasIdentity()) {
            if ($this->session->storage->role == 1||$this->session->storage->role == 4) {
                ?>
                <!-- begin #page-loader -->
                <div id="page-loader" class="page-loader fade in"><span class="spinner">Loading...</span></div>
                <!-- end #page-loader -->

                <!-- begin #page-container -->
                <div id="page-container" class="fade page-container page-header-fixed page-sidebar-fixed page-with-two-sidebar page-with-footer">
                    <!-- begin #header -->
                    <div id="header" class="header navbar navbar-default navbar-fixed-top">
                        <!-- begin container-fluid -->
                        <div class="container-fluid">
                            <!-- begin mobile sidebar expand / collapse button -->
                            <div class="navbar-header">
                                <a href="index.html" class="navbar-brand"><img src="<?php echo $this->baseUrl() . $this->theme_base_path ?>/images/logo.png" class="logo" alt="" /></a>
                                <button type="button" class="navbar-toggle" data-click="sidebar-toggled">
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                </button>
                            </div>
                            <!-- end mobile sidebar expand / collapse button -->

                            <!-- begin navbar-right -->
                            <ul class="nav navbar-nav navbar-right">
                                <li class="dropdown">
                                    <a href="javascript:;" data-toggle="dropdown" class="dropdown-toggle has-notify" data-click="toggle-notify">
                                        <i class="fa fa-bell"></i>
                                    </a>
                                    <ul class="dropdown-menu dropdown-notification pull-right">
                                        <li class="dropdown-header">Notifications (5)</li>
                                        <li class="notification-item">
                                            <a href="javascript:;">
                                                <div class="media"><i class="fa fa-exclamation-triangle"></i></div>
                                                <div class="message">
                                                    <h6 class="title">Server Error Reports</h6>
                                                    <div class="time">3 minutes ago</div>
                                                </div>
                                                <div class="option" data-toggle="tooltip" data-title="Mark as Read" data-click="set-message-status" data-status="unread" data-container="body">
                                                    <i class="fa fa-circle-o"></i>
                                                </div>
                                            </a>
                                        </li>
                                        <li class="notification-item">
                                            <a href="javascript:;">
                                                <div class="media"><img src="<?php echo $this->baseUrl() . $this->theme_base_path ?>/images/pic.jpg" alt="" /></div>
                                                <div class="message">
                                                    <h6 class="title">Solvia Smith</h6>
                                                    <p class="desc">Quisque pulvinar tellus sit amet sem scelerisque tincidunt.</p>
                                                    <div class="time">25 minutes ago</div>
                                                </div>
                                                <div class="option read" data-toggle="tooltip" data-title="Mark as Unread" data-click="set-message-status" data-status="read" data-container="body">
                                                    <i class="fa fa-circle-o"></i>
                                                </div>
                                            </a>
                                        </li>
                                        <li class="notification-item">
                                            <a href="javascript:;">
                                                <div class="media"><img src="<?php echo $this->baseUrl() . $this->theme_base_path ?>/images/pic.jpg" alt="" /></div>
                                                <div class="message">
                                                    <h6 class="title">Olivia</h6>
                                                    <p class="desc">Quisque pulvinar tellus sit amet sem scelerisque tincidunt.</p>
                                                    <div class="time">35 minutes ago</div>
                                                </div>
                                                <div class="option read" data-toggle="tooltip" data-title="Mark as Unread" data-click="set-message-status" data-status="read" data-container="body">
                                                    <i class="fa fa-circle-o"></i>
                                                </div>
                                            </a>
                                        </li>
                                        <li class="notification-item">
                                            <a href="javascript:;">
                                                <div class="media"><i class="fa fa-user-plus media-object"></i></div>
                                                <div class="message">
                                                    <h6 class="title"> New User Registered</h6>
                                                    <div class="time">1 hour ago</div>
                                                </div>
                                                <div class="option read" data-toggle="tooltip" data-title="Mark as Unread" data-click="set-message-status" data-status="read" data-container="body">
                                                    <i class="fa fa-circle-o"></i>
                                                </div>
                                            </a>
                                        </li>
                                        <li class="notification-item">
                                            <a href="javascript:;">
                                                <div class="media bg-success"><i class="fa fa-credit-card"></i></div>
                                                <div class="message">
                                                    <h6 class="title"> New Item Sold</h6>
                                                    <div class="time">2 hour ago</div>
                                                </div>
                                                <div class="option read" data-toggle="tooltip" data-title="Mark as Read" data-click="set-message-status" data-status="read" data-container="body">
                                                    <i class="fa fa-circle-o"></i>
                                                </div>
                                            </a>
                                        </li>
                                        <li class="dropdown-footer text-center">
                                            <a href="javascript:;">View more</a>
                                        </li>
                                    </ul>
                                </li>
                                <li class="dropdown navbar-user">
                                    <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown">
                                        <span class="image"><img src="<?php echo $this->baseUrl() . $this->theme_base_path ?>/images/pic.jpg" alt="" /></span>
                                        <span class="hidden-xs">  <?php
                                            if (isset($this->session->storage->loginname)) {
                                                echo $this->session->storage->loginname;
                                            }
                                            ?>
                                        </span> <b class="caret"></b>
                                    </a>
                                    <ul class="dropdown-menu pull-right">
                                        <li><a href="javascript:;">Edit Profile</a></li>
                                        <li><a href="javascript:;"><span class="badge badge-danger pull-right">2</span> Notifications</a></li>
                                        <li class="divider"></li>
                                        <li><a href="/agent/logout">Log Out</a></li>
                                    </ul>
                                </li>
                            </ul>
                            <!-- end navbar-right -->
                        </div>
                        <!-- end container-fluid -->
                    </div>
                    <!-- end #header -->

                    <!-- begin #sidebar -->
                    <div id="sidebar" class="sidebar">
                        <!-- begin sidebar scrollbar -->
                        <div data-scrollbar="true" data-height="100%">
                            <!-- begin sidebar nav -->
                            <ul class="nav">
                                <li class="nav-header">Overview</li>
                                <li class="active">
                                    <a href="/agent/dashboard">
                                        <i class="fa fa-home"></i>
                                        <span>Dashboard</span>
                                    </a>
                                </li>                              
                                <li class="has-sub">
                                    <a href="javascript:;">
                                        <i class="fa fa-cutlery"></i>
                                        <span>Hotel Details</span>
                                    </a>
                                    <ul class="sub-menu">
                                        <li><a href="/agent/hotel-details">Hotel Details</a></li>
                                        <li><a href="/agent/add-hotel-details">Add New Hotel</a></li>
                                    </ul>
                                </li>

<!--                                <li class="has-sub">
                                    <a href="javascript:;">
                                        <i class="fa fa-file-text-o"></i>
                                        <span>Order Details</span>
                                    </a>
                                    <ul class="sub-menu">
                                        <li><a href="/agent/restuarent-orders">Order Details</a></li>                                      
                                    </ul>
                                </li>-->

                                <li class="has-sub">
                                    <a href="javascript:;">
                                        <i class="fa fa-forumbee"></i>
                                        <span>Product Details</span>
                                    </a>
                                    <ul class="sub-menu">
                                        <li><a href="/agent/product-details">Product Details</a></li>
                                        <li><a href="/agent/add-product-details">Add New Product</a></li>
                                    </ul>
                                </li>

                                <li class="has-sub">
                                    <a href="javascript:;">
                                        <i class="fa fa-money"></i>
                                        <span>Payment Details</span>
                                    </a>
                                    <ul class="sub-menu">
                                        <li><a href="/agent/agent-payment-details">Agent Payment Details</a></li>                                        
                                    </ul>
                                </li>

                                <li class="divider has-minify-btn">
                                    <!-- begin sidebar minify button -->
                                    <a href="javascript:;" class="sidebar-minify-btn" data-click="sidebar-minify"><i class="fa fa-angle-left"></i></a>
                                    <!-- end sidebar minify button -->
                                </li>
                            </ul>
                            <!-- end sidebar nav -->
                        </div>
                        <!-- end sidebar scrollbar -->
                    </div>
                    <div class="sidebar-bg"></div>
                    <!-- end #sidebar -->

                    <!-- begin #content -->

                    <?php
                }
            } else {
                ?>

                <div id="page-loader" class="page-loader fade in"><span class="spinner">Loading...</span></div>
                <!-- end #page-loader -->

                <!-- begin #page-container -->
                <div id="page-container" class="fade page-container page-header-fixed page-sidebar-fixed page-with-two-sidebar page-with-footer">   
                <?php }
                ?>



