<?php
/*
  DEV :Priyanka Varanasi
  DESC: javascripts File for agent
  Design Date : 5/4/2016
 */
?>
<script type="text/javascript">
    $(document).ready(function() {
        App.init();
    });

    $(document).ready(function() {
        $('#login').click(function() {
            $('.login').show();
            $('.register').hide();
        });
        $('#forget').click(function() {
            $('.forget').show();
            $('.login').hide();
        });
        $('#blogin').click(function() {
            $('.forget').hide();
            $('.login').show();
        });
        $('#register').click(function() {
            $('.login').hide();
            $('.register').show();
        });

        $(".selectpicker").select2();
        $(".add-loc").click(function() {
            $(".new-location").show();
            $(".loc-disable").prop("disabled", true);
        });

        $('#data-table').dataTable();

//        var elems = Array.prototype.slice.call(document.querySelectorAll('.js-switch'));
//        elems.forEach(function(html) {
//            var switchery = new Switchery(html);
//        });

        /*
         * DEV :priyanka varanasi
         * Desc :  Deactivate hotel
         * Date : 18/12/2015
         */

        $(document.body).on('change', '.hoteldeactive', function() {
            var hotelid = $(this).attr('id');
            var hotelid = hotelid.replace("hotel_", "");

            console.log('deactivate called');
            $.ajax({
                url: './agent-ajax-handler',
                type: 'POST',
                datatype: 'HTML',
                data: {
                    method: 'hotelactive',
                    hotelid: hotelid
                },
                beforeSend: function() {

                },
                success: function(response) {
                    console.log(response);
                    var response = JSON.parse(response);
                    if (response.code == "200") {
                        var uid = response['data'].replace(/ /g, '');
                        $('#' + "activeclass_" + uid).html("SUSPENDED");
                        $('#' + "activeclass_" + uid).removeClass('label label-success');
                        $('#' + "activeclass_" + uid).addClass('label label-danger');
                        $('#hotel_' + uid).removeClass('hoteldeactive');
                        $('#hotel_' + uid).addClass('hotelactive');


                    } else {
                        alert('Request could not served');
                    }
                }
            });

        });
        /*
         * 
         * Modified script for hotel status  active
         */
        $(document.body).on('change', '.hotelactive', function() {
            var hotelid = $(this).attr('id');
            var hotelid = hotelid.replace("hotel_", "");

            console.log('activate called');
            $.ajax({
                url: './agent-ajax-handler',
                type: 'POST',
                datatype: 'HTML',
                data: {
                    method: 'hotelactive',
                    hotelid: hotelid
                },
                beforeSend: function() {

                },
                success: function(response) {
                    var response = JSON.parse(response);
                    if (response.code == "200") {
                        var uid = response['data'].replace(/ /g, '');
                        $('#' + "activeclass_" + uid).html("ACTIVE");
                        $('#' + "activeclass_" + uid).removeClass('label label-danger');
                        $('#' + "activeclass_" + uid).addClass('label label-success');
                        $('#hotel_' + uid).removeClass('hotelactive');
                        $('#hotel_' + uid).addClass('hoteldeactive');


                    } else {
                        alert('Request could not served');
                    }
                }
            });

        });

    });

    /*
     * DEV :sowmya
     * Desc : Deactivate product
     * Date : 5/5/2015
     */
    $(document.body).on('change', '.productdeactive', function() {
        var productid = $(this).attr('id');
        productid = productid.replace("product_", "");

        console.log('deactivate called');
        $.ajax({
            url: './agent-ajax-handler',
            type: 'POST',
            datatype: 'HTML',
            data: {
                method: 'productactive',
                productid: productid
            },
            beforeSend: function() {

            },
            success: function(response) {
                var response = JSON.parse(response);
                if (response.code == "200") {
                    var uid = response['data'].replace(/ /g, '');
                    $('#' + "activeclass_" + uid).html("SUSPENDED");
                    $('#' + "activeclass_" + uid).removeClass('label label-success');
                    $('#' + "activeclass_" + uid).addClass('label label-danger');
                    $('#product_' + uid).removeClass('productdeactive');
                    $('#product_' + uid).addClass('productactive');

                } else {
                    alert('Request could not served');
                }
            }
        });

    });
    /*
     * DEV :sowmya
     * Desc : Activate product
     * Date : 5/5/2016
     */
    $(document.body).on('change', '.productactive', function() {
        var productid = $(this).attr('id');
        productid = productid.replace("product_", "");
        console.log('activate called');
        $.ajax({
            url: './agent-ajax-handler',
            type: 'POST',
            datatype: 'HTML',
            data: {
                method: 'productactive',
                productid: productid
            },
            beforeSend: function() {

            },
            success: function(response) {
                var response = JSON.parse(response);
                if (response.code == "200") {
                    var uid = response['data'].replace(/ /g, '');
                    $('#' + "activeclass_" + uid).html("ACTIVE");
                    $('#' + "activeclass_" + uid).removeClass('label label-danger');
                    $('#' + "activeclass_" + uid).addClass('label label-success');
                    $('#product_' + uid).removeClass('productactive');
                    $('#product_' + uid).addClass('productdeactive');


                } else {

                    alert('Request could not served');

                }
            }

        });

    });

    /*
     * DEV :priyanka varanasi
     * Desc : Delete product
     * Date : 18/12/2015
     */

    $(document.body).on('click', '.deleteproduct', function() {
        var productid = $(this).attr('id');
        var deleteid = productid.replace("productdelete_", "");
        if (deleteid) {
            $.ajax({
                url: './agent-ajax-handler',
                type: 'POST',
                datatype: 'json',
                data: {
                    method: 'productdelete',
                    productid: deleteid
                },
                beforeSend: function() {

                },
                success: function(response) {

                    var response = JSON.parse(response);
                    if (response) {
                        var uid = response['data'].replace(/ /g, '');

                        $('#' + "productdelete_" + uid).parent().parent().remove();

                    }
                }


            });
        }
    });

    /*
     * DEV :priyanka varanasi
     * Desc : select states based on country id
     * Date : 18/12/2015
     */

    $(document.body).on('change', '.selectcountry', function() {
        var id = $(this).val();
        var element = "";
        if (id) {
            $.ajax({
                url: '/agent/agent-ajax-handler',
                type: 'POST',
                datatype: 'json',
                data: {
                    method: 'findstates',
                    countryid: id
                },
                beforeSend: function() {

                },
                success: function(response) {
                    $('#state').empty();
                    $('#city').empty();
                    $('#location').empty();
                    var response = JSON.parse(response);
                    console.log(response);
                    if (response.code == 200) {
                        $('#state').append('<option>Select State</option>');
                        $.each(response.data, function(i, a) {
                            $('#state').append('<option value="' + a.location_id + '">' + a.name + '</option>');
                        });

                    }
                }


            });
        }
    });

    /*
     * DEV :priyanka varanasi
     * Desc : select citys based on state id
     * Date : 18/12/2015
     */

    $(document.body).on('change', '.selectstate', function() {
        var id = $(this).val();

        if (id) {
            $.ajax({
                url: '/agent/agent-ajax-handler',
                type: 'POST',
                datatype: 'json',
                data: {
                    method: 'findcitys',
                    stateid: id
                },
                beforeSend: function() {

                },
                success: function(response) {

                    var response = JSON.parse(response);
                    $('#city').empty();
                    
                    if (response.code == 200) {
                        $('#city').append('<option> Select City </option>');
                        $.each(response.data, function(i, a) {

                            $('#city').append('<option value="' + a.location_id + '">' + a.name + '</option>');
                        });

                    }
                }


            });
        }
    });

    /*
     * DEV :priyanka varanasi
     * Desc : select locations based on city id
     * Date : 18/12/2015
     */

    $(document.body).on('change', '.selectcity', function() {
        var id = $(this).val();

        if (id) {
            $.ajax({
                url: '/agent/agent-ajax-handler',
                type: 'POST',
                datatype: 'json',
                data: {
                    method: 'findlocations',
                    locationid: id
                },
                beforeSend: function() {

                },
                success: function(response) {

                    var response = JSON.parse(response);
         
                    $('#location').empty();

                    if (response.code == 200) {
                        $('#location').append('<option>Select location</option>');
                        $.each(response.data, function(i, a) {
                            $('#location').append('<option value="' + a.location_id + '">' + a.name + '</option>');
                        });


                    }
                }


            });
        }
    });
  /*
     * DEV :priyanka varanasi
     * Desc : to get hotel cuisines
     * Date : 18/12/2015
     */
    $('#type_cusine').change(function() {
        var typevalue = $(this).val();
        $.ajax({
            url: './agent-ajax-handler',
            type: 'POST',
            datatype: 'HTML',
            data: {
                method: 'getcuisines',
                typevalue: typevalue
            },
            beforeSend: function() {

            },
            success: function(response) {

                var res = jQuery.parseJSON(response);
                console.log(res);
                if (res.code == 200) {
                    console.log(res.code);
                    $('#cuisine').html('');
                    $('#cuisine').append('<option disabled selected>Select Cuisine</option>');
                    $.each(res.data, function(i, a) {
                        $('#cuisine').append('<option value="' + a.cuisine_id + '">' + a.Cuisine_name + '</option>');
                    });
                    $('.show-cusine').show();
                    $('.show-category').hide();
                }
                else {
                    $('.show-cusine').show();
                    $('.show-category').hide();
                }

            }
        });
    });
      /*
     * DEV :priyanka varanasi
     * Desc : to get hotel category
     * Date : 18/12/2015
     */
    $('#type_category').change(function() {
        var typevalue = $(this).val();
        $.ajax({
            url: './agent-ajax-handler',
            type: 'POST',
            datatype: 'HTML',
            data: {
                method: 'getcategories',
                typevalue: typevalue
            },
            beforeSend: function() {

            },
            success: function(response) {
                var res = jQuery.parseJSON(response);
                if (res.code == 200) {

                    $('#category').html('');
                    $('#category').append('<option disabled selected>Select category</option>');
                    $.each(res.data, function(i, a) {
                        $('#category').append('<option value="' + a.category_id + '">' + a.cat_name + '</option>');
                    });
                    $('.show-category').show();
                    $('.show-cusine').hide();
                }


            }
        });
    });
    /*		
     * DEV :sreekanth		
     * Desc : edit product details		
     * Date : 2/5/2016		
     */
    $('#type_cusine2').change(function() {
        $('.show-cusine').show();
        $('.show-category').hide();

        var typevalue = $(this).val();
        $.ajax({
            url: './agent-ajax-handler',
            type: 'POST',
            datatype: 'HTML',
            data: {
                method: 'getcuisines',
                typevalue: typevalue
            },
            beforeSend: function() {

            },
            success: function(response) {

                var res = jQuery.parseJSON(response);
                console.log(res);
                if (res.code == 200) {
                    console.log(res.code);
                    $('#cuisine').html('');
                    $('#cuisine').append('<option disabled selected>Select Cuisine</option>');
                    $.each(res.data, function(i, a) {
                        $('#cuisine').append('<option value="' + a.cuisine_id + '">' + a.Cuisine_name + '</option>');
                    });
                    $('.show-cusine').show();
                    $('.show-category').hide();
                }
                else {		
                    $('.show-cusine').show();
                    $('.show-category').hide();
                }

            }
        });
    });

    /*		
     * DEV :sreekanth		
     * Desc : edit product		
     * Date : 2/5/2016		
     */
    $('#type_category2').change(function() {
        $('.show-category').show();
        $('.show-cusine').hide();
        var typevalue = $(this).val();
        $.ajax({
            url: './agent-ajax-handler',
            type: 'POST',
            datatype: 'HTML',
            data: {
                method: 'getcategories',
                typevalue: typevalue
            },
            beforeSend: function() {

            },
            success: function(response) {
                var res = jQuery.parseJSON(response);
                if (res.code == 200) {

                    $('#category').html('');
                    $('#category').append('<option disabled selected>Select category</option>');
                    $.each(res.data, function(i, a) {
                        $('#category').append('<option value="' + a.category_id + '">' + a.cat_name + '</option>');
                    });
                    $('.show-category').show();
                    $('.show-cusine').hide();
                }


            }
        });
    });
    /*
     * DEV :sowmya
     * Desc : Delete hotel
     * Date : 14/4/2016
     */

    $(document.body).on('click', '.deletehotel', function() {
        var hotelid = $(this).attr('id');
        var deleteid = hotelid.replace("hoteldelete_", "");
        if (deleteid) {
            $.ajax({
                url: './agent-ajax-handler',
                type: 'POST',
                datatype: 'json',
                data: {
                    method: 'hoteldelete',
                    hotelid: deleteid
                },
                beforeSend: function() {

                },
                success: function(response) {

                    var response = JSON.parse(response);
                    if (response) {
                        var uid = response['data'].replace(/ /g, '');

                        $('#' + "hoteldelete_" + uid).parent().parent().remove();

                    }
                }


            });
        }
    });
    /*
     * DEV :sowmya
     * Desc : Status  change for store
     * Date : 26/4/2016
     */
    $(document.body).on('change', '.storedeactive', function() {
        var storeid = $(this).attr('id');
        var storeid = storeid.replace("store_", "");

        console.log('deactivate called');
        $.ajax({
            url: './agent-ajax-handler',
            type: 'POST',
            datatype: 'HTML',
            data: {
                method: 'storeactive',
                storeid: storeid
            },
            beforeSend: function() {

            },
            success: function(response) {
                var response = JSON.parse(response);
                if (response.code == "200") {
                    var uid = response['data'].replace(/ /g, '');
                    $('#' + "activeclass_" + uid).html("SUSPENDED");
                    $('#' + "activeclass_" + uid).removeClass('label label-success');
                    $('#' + "activeclass_" + uid).addClass('label label-danger');
                    $('#store_' + uid).removeClass('storedeactive');
                    $('#store_' + uid).addClass('storeactive');


                } else {
                    alert('Request could not served');
                }
            }
        });

    });
    /*
     * DEV :sowmya
     * Desc : Status  change for store
     * Date : 26/4/2016
     */
    $(document.body).on('change', '.storeactive', function() {
        var storeid = $(this).attr('id');
        var storeid = storeid.replace("store_", "");

        console.log('activate called');
        $.ajax({
            url: './agent-ajax-handler',
            type: 'POST',
            datatype: 'HTML',
            data: {
                method: 'storeactive',
                storeid: storeid
            },
            beforeSend: function() {

            },
            success: function(response) {
                var response = JSON.parse(response);
                if (response.code == "200") {
                    var uid = response['data'].replace(/ /g, '');
                    $('#' + "activeclass_" + uid).html("ACTIVE");
                    $('#' + "activeclass_" + uid).removeClass('label label-danger');
                    $('#' + "activeclass_" + uid).addClass('label label-success');
                    $('#store_' + uid).removeClass('storeactive');
                    $('#store_' + uid).addClass('storedeactive');


                } else {
                    alert('Request could not served');
                }
            }
        });

    });
    /*
     * DEV :sowmya
     * Desc : Delete store
     * Date : 26/4/2016
     */

    $(document.body).on('click', '.deletestore', function() {
        var storeid = $(this).attr('id');
        var deleteid = storeid.replace("storedelete_", "");
        if (deleteid) {
            $.ajax({
                url: './agent-ajax-handler',
                type: 'POST',
                datatype: 'json',
                data: {
                    method: 'storedelete',
                    storeid: deleteid
                },
                beforeSend: function() {

                },
                success: function(response) {

                    var response = JSON.parse(response);
                    console.log(response);
                    if (response) {
                        var uid = response['data'].replace(/ /g, '');

                        $('#' + "storedelete_" + uid).parent().parent().remove();

                    }
                }


            });
        }
    });

    /*
     * DEV :sowmya
     * Desc : Status  change for reviews
     * Date : 27/4/2016
     */
    $(document.body).on('change', '.reviewdeactive', function() {
        var reviewid = $(this).attr('id');
        var reviewid = reviewid.replace("review_", "");

        console.log('deactivate called');
        $.ajax({
            url: './agent-ajax-handler',
            type: 'POST',
            datatype: 'HTML',
            data: {
                method: 'reviewactive',
                reviewid: reviewid
            },
            beforeSend: function() {

            },
            success: function(response) {
                var response = JSON.parse(response);
                if (response.code == "200") {
                    var uid = response['data'].replace(/ /g, '');
                    $('#' + "activeclass_" + uid).html("SUSPENDED");
                    $('#' + "activeclass_" + uid).removeClass('label label-success');
                    $('#' + "activeclass_" + uid).addClass('label label-danger');
                    $('#review_' + uid).removeClass('reviewdeactive');
                    $('#review_' + uid).addClass('reviewactive');
                }
            }
        });

    });
    /*
     * DEV :sowmya
     * Desc : Status  change for review
     * Date : 27/4/2016
     */
    $(document.body).on('change', '.reviewactive', function() {
        var reviewid = $(this).attr('id');
        var reviewid = reviewid.replace("review_", "");

        console.log('activate called');
        $.ajax({
            url: './agent-ajax-handler',
            type: 'POST',
            datatype: 'HTML',
            data: {
                method: 'reviewactive',
                reviewid: reviewid
            },
            beforeSend: function() {

            },
            success: function(response) {
                var response = JSON.parse(response);
                if (response.code == "200") {
                    var uid = response['data'].replace(/ /g, '');
                    $('#' + "activeclass_" + uid).html("ACTIVE");
                    $('#' + "activeclass_" + uid).removeClass('label label-danger');
                    $('#' + "activeclass_" + uid).addClass('label label-success');
                    $('#review_' + uid).removeClass('reviewactive');
                    $('#review_' + uid).addClass('reviewdeactive');
                }
            }
        });

    });
    /*
     * DEV :sowmya
     * Desc : Delete review
     * Date : 27/4/2016
     */

    $(document.body).on('click', '.deletereview', function() {
        var reviewid = $(this).attr('id');
        var deleteid = reviewid.replace("reviewdelete_", "");
        if (deleteid) {
            $.ajax({
                url: './agent-ajax-handler',
                type: 'POST',
                datatype: 'json',
                data: {
                    method: 'reviewdelete',
                    reviewid: deleteid
                },
                beforeSend: function() {

                },
                success: function(response) {

                    var response = JSON.parse(response);
                    console.log(response);
                    if (response) {
                        var uid = response['data'].replace(/ /g, '');

                        $('#' + "reviewdelete_" + uid).parent().parent().remove();

                    }
                }


            });
        }
    });
    /*
     * DEV :sowmya
     * Desc : edit storecategory
     * Date :23/4/2016
     */
     $(document.body).on('click', '.storecategoryedit', function() {
        var categoryid = $(this).attr('id');
        var cat_name = $(this).attr('dataname');
        var cat_desc = $(this).attr('datadesc');

        var categoryid = categoryid.replace("showEdit_", "");
       
                    $('.editContent').find('#editcategory').val('');
                    $('.editContent').find('#categoryid').val(categoryid);
                    $('.editContent').find('#editcategory').val(cat_name);
                    $('.editContent').find('#editcategorydesc').val(cat_desc);
                    $('.editContent').show();
                    $('.addContent').hide();

                

            });



    /*
     * DEV :sowmya
     * Desc : Delete store category
     * Date : 3/5/2016
     */

    $(document.body).on('click', '.storecategorydelete', function() {
        var deleteid = $(this).attr('id');
      
        var deleteid = deleteid.replace("categorydelete_", "");
       
        if (deleteid) {
            $.ajax({
                url: './agent-ajax-handler',
                type: 'POST',
                datatype: 'json',
                data: {
                    method: 'storecategorydelete',
                    categoryid: deleteid
                },
                beforeSend: function() {

                },
                 success: function(response) {
                    var response = JSON.parse(response);
                    console.log(response);
                    if (response) {
                        var uid = response['data'].replace(/ /g, '');

                        $('#' + "categorydelete_" + uid).parent().parent().remove();

                    }
                }


            });
        }
    });

    /*
     * DEV :sowmya
     * Desc : Deactivate store category
     * Date : 4/5/2016
     */
    $(document.body).on('change', '.storecategorydeactive', function() {
        var categoryid = $(this).attr('id');
        var categoryid = categoryid.replace("store_", "");

        console.log('deactivate called');
        $.ajax({
            url: './agent-ajax-handler',
            type: 'POST',
            datatype: 'HTML',
            data: {
                method: 'storecategoryactive',
                categoryid: categoryid
            },
            beforeSend: function() {

            },
            success: function(response) {
     var response = JSON.parse(response);
                    var uid = response['data'].replace(/ /g, '');
                    $('#' + "activeclass_" + uid).removeClass('label label-success');
                    $('#' + "activeclass_" + uid).addClass('label label-danger');
                    $('#' + "activeclass_" + uid).html("Activate");
                    $('#store_' + uid).removeClass('storecategorydeactive');
                    $('#store_' + uid).addClass('storecategoryactive');
                    $('#' + "activeclass_" + uid).html("Suspended");
               
            }
        });

    });
    /*
     * DEV :sowmya
     * Desc : Activate store category
     * Date : 5/5/2015
     */
    $(document.body).on('click', '.storecategoryactive', function() {
        var categoryid = $(this).attr('id');
        var categoryid = categoryid.replace("store_", "");
        console.log('activate called');
        $.ajax({
            url: './agent-ajax-handler',
            type: 'POST',
            datatype: 'HTML',
            data: {
                method: 'storecategoryactive',
                categoryid: categoryid
            },
            beforeSend: function() {

            },
            success: function(response) {
                     var response = JSON.parse(response);
                    var uid = response['data'].replace(/ /g, '');
                    $('#' + "activeclass_" + uid).removeClass('label label-danger');
                    $('#' + "activeclass_" + uid).addClass('label label-success');
                    $('#' + "activeclass_" + uid).html("Dectivate");
                    $('#store_' + uid).removeClass('storecategoryactive');
                    $('#store_' + uid).addClass('storecategorydeactive');
                    $('#' + "activeclass_" + uid).html("Active");


               
            }

        });

    });

    /*
     * DEV :sreekanth
     * Desc : country status change
     * Date : 2/5/2016
     */



    $(document.body).on('click', '.locationdeactive', function() {
        var locationid = $(this).attr('id');
        var locationid = locationid.replace("location_", "");
        console.log('deactivate called');
        $.ajax({
            url: './agent-ajax-handler',
            type: 'POST',
            datatype: 'HTML',
            data: {
                method: 'locationactive',
                locationid: locationid
            },
            beforeSend: function() {

            },
            success: function(response) {
                console.log(response);
                var uid = response.replace(/ /g, "");

                $('#' + "activeclass_" + uid).removeClass('bs-label label-danger');
                $('#' + "activeclass_" + uid).addClass('bs-label label-success');
                $('#' + "activeclass_" + uid).html("Activate");
                $('#location_' + uid).removeClass('locationdeactive');
                $('#location_' + uid).addClass('locationactive');
                $('#' + "activelocation_" + uid).html("Suspended");

            }
        });

    });
    /*
     * DEV :sreekanth
     * Desc : country status change
     * Date : 2/5/2016
     */
    $(document.body).on('click', '.locationactive', function() {
        var locationid = $(this).attr('id');
        var locationid = locationid.replace("location_", "");
        console.log('activate called');
        $.ajax({
            url: './agent-ajax-handler',
            type: 'POST',
            datatype: 'HTML',
            data: {
                method: 'locationactive',
                locationid: locationid
            },
            beforeSend: function() {

            },
            success: function(response) {
                var uid = response.replace(/ /g, '');
                $('#' + "activeclass_" + uid).removeClass('bs-label label-success');
                $('#' + "activeclass_" + uid).addClass('bs-label label-danger');
                $('#' + "activeclass_" + uid).html("Dectivate");
                $('#location_' + uid).removeClass('locationactive');
                $('#location_' + uid).addClass('locationdeactive');
                $('#' + "activelocation_" + uid).html("Active");

            }


        });

    });
  /*
     * DEV :sowmya
     * Desc : to  edit country
     * Date : 5/5/2016
     */
    $(document.body).on('click', '.countryedit', function() {
        var locationid = $(this).attr('id');
        var locationid = locationid.replace("showEdit_", "");
        $.ajax({
            url: './agent-ajax-handler',
            type: 'POST',
            datatype: 'HTML',
            data: {
                method: 'getlocation',
                locationid: locationid
            },
            beforeSend: function() {

            },
            success: function(response) {
                var res = jQuery.parseJSON(response);
                if (res.code == 200) {

                    $('.editContent').find('#editlocation').val('');
                    $('.editContent').find('#locationid').val(res.data['location_id']);
                    $('.editContent').find('#editlocation').val(res.data['name']);
                    1
                    $('.editContent').show();
                    $('.addContent').hide();

                } else {

                    window.location.reload(true);
                }

            }


        });
    });
  /*
     * DEV :sowmya
     * Desc : to  delete country
     * Date : 5/5/2016
     */
    $(document.body).on('click', '.countrydelete', function() {
        var deleteid = $(this).attr('id');
        var deleteid = deleteid.replace("countrydelete_", "");

        if (deleteid) {
            $.ajax({
                url: './agent-ajax-handler',
                type: 'POST',
                datatype: 'json',
                data: {
                    method: 'countrydelete',
                    deleteid: deleteid
                },
                beforeSend: function() {

                },
                success: function(response) {
                    var response = JSON.parse(response);
                    $('#' + "countrydelete_" + response).parent().parent().remove();
                }


            });
        }
    });
/*
     * DEV :sreekanth
     * Desc :  Deactivate  hotelcategory
     * Date : 4-may-16
     */

    $(document.body).on('click', '.hotelcategorydeactive', function () {
        var hotelid = $(this).attr('id');
        var hotelid = hotelid.replace("hotel_", "");

        console.log('deactivate called');
        $.ajax({
            url: './agent-ajax-handler',
            type: 'POST',
            datatype: 'HTML',
            data: {
                method: 'hotelcategorydeactive',
                hotelid: hotelid
            },
            beforeSend: function () {

            },
            success: function (response) {
                console.log(response);
                var response = JSON.parse(response);
                if (response.code == 200) {
                    var uid = response['data'].replace(/ /g, '');
                    $('#' + "activeclass_" + uid).html("SUSPENDED");
                    $('#' + "activeclass_" + uid).removeClass('label label-success');
                    $('#' + "activeclass_" + uid).addClass('label label-danger');
                    $('#hotel_' + uid).removeClass('hotelcategorydeactive');
                    $('#hotel_' + uid).addClass('hotelcategoryactive');


                } else {
                    alert('Request could not served');
                }
            }
        });

    });
    /*
     * DEV :sreekanth
     * Desc :  Deactivate  hotelcategory
     * Date : 4-may-16
     */
    $(document.body).on('click', '.hotelcategoryactive', function () {
        var hotelid = $(this).attr('id');
        var hotelid = hotelid.replace("hotel_", "");

        console.log('activate called');
        $.ajax({
            url: './agent-ajax-handler',
            type: 'POST',
            datatype: 'HTML',
            data: {
                method: 'hotelcategoryactive',
                hotelid: hotelid
            },
            beforeSend: function () {

            },
            success: function (response) {
                var response = JSON.parse(response);
                if (response.code == 200) {
                    var uid = response['data'].replace(/ /g, '');
                    $('#' + "activeclass_" + uid).html("ACTIVE");
                    $('#' + "activeclass_" + uid).removeClass('label label-danger');
                    $('#' + "activeclass_" + uid).addClass('label label-success');
                    $('#hotel_' + uid).removeClass('hotelcategoryactive');
                    $('#hotel_' + uid).addClass('hotelcategorydeactive');


                } else {
                    alert('Request could not served');
                }
            }
        });

    });

    //     * DEV :sreekanth
    //     * Desc :  edit  hotel category
    //     * Date : 4-may-16

    $(document.body).on('click', '.categoryedit', function () {
        var categoryid = $(this).attr('id');
        var categoryid = categoryid.replace("showEdit_", "");
        $.ajax({
            url: './agent-ajax-handler',
            type: 'POST',
            datatype: 'HTML',
            data: {
                method: 'getcategoriesByCategoryId',
                categoryid: categoryid
            },
            beforeSend: function () {

            },
            success: function (response) {
                var res = jQuery.parseJSON(response);
                if (res.code === 200) {

                    $('.editContent').find('#editcategory').val('');
                    $('.editContent').find('#categoryid').val(res.data['category_id']);
                    $('.editContent').find('#editcategory').val(res.data['cat_name']);
                    $('.editContent').find('#editcategorydesc').val(res.data['cat_desc']);
                    $('.editContent').show();
                    $('.addContent').hide();

                } else {

                    window.location.reload(true);
                }

            }


        });
    });

    //     * DEV :sreekanth
    //     * Desc :  delete   hotelcategory
    //     * Date : 5-may-16

    $(document.body).on('click', '.hotelcategorydelete', function () {
        var deleteid = $(this).attr('id');
        var deleteid = deleteid.replace("categorydelete_", "");

        if (deleteid) {
            $.ajax({
                url: '/agent/agent-ajax-handler',
                type: 'POST',
                datatype: 'json',
                data: {
                    method: 'hotelcategorydelete',
                    deleteid: deleteid
                },
                beforeSend: function () {

                },
                success: function (response) {
                    var response = JSON.parse(response);
                    $('#' + "categorydelete_" + response).parent().parent().remove();
                }


            });
        }
    });

 /*
     * DEV :sreekanth
     * Desc :  Deactivate  hotelcuisine
     * Date : 6-may-16
     */

    $(document.body).on('click', '.hotelcuisinedeactive', function () {
        var cuisineid = $(this).attr('id');
        var cuisineid = cuisineid.replace("hotel_", "");

        console.log('deactivate called');
        $.ajax({
            url: './agent-ajax-handler',
            type: 'POST',
            datatype: 'HTML',
            data: {
                method: 'changeHotelCuisineStatus',
                cuisineid: cuisineid
            },
            beforeSend: function () {

            },
            success: function (response) {
                console.log(response);
                var response = JSON.parse(response);
                if (response.code == 200) {
                    var uid = response['data'].replace(/ /g, '');
                    $('#' + "activeclass_" + uid).html("SUSPENDED");
                    $('#' + "activeclass_" + uid).removeClass('label label-success');
                    $('#' + "activeclass_" + uid).addClass('label label-danger');
                    $('#hotel_' + uid).removeClass('hotelcuisinedeactive');
                    $('#hotel_' + uid).addClass('hotelcuisineactive');


                } else {
                    alert('Request could not served');
                }
            }
        });

    });
    /*
     * DEV :sreekanth
     * Desc :  Deactivate  hotelcuisine
     * Date : 6-may-16
 */
    $(document.body).on('click', '.hotelcuisineactive', function () {
        var cuisineid = $(this).attr('id');
        var cuisineid = cuisineid.replace("hotel_", "");

        console.log('activate called');
        $.ajax({
            url: './agent-ajax-handler',
            type: 'POST',
            datatype: 'HTML',
            data: {
                method: 'changeHotelCuisineStatus',
                cuisineid: cuisineid
            },
            beforeSend: function () {

            },
            success: function (response) {
                var response = JSON.parse(response);
                if (response.code == 200) {
                    var uid = response['data'].replace(/ /g, '');
                    $('#' + "activeclass_" + uid).html("ACTIVE");
                    $('#' + "activeclass_" + uid).removeClass('label label-danger');
                    $('#' + "activeclass_" + uid).addClass('label label-success');
                    $('#hotel_' + uid).removeClass('hotelcuisineactive');
                    $('#hotel_' + uid).addClass('hotelcuisinedeactive');


                } else {
                    alert('Request could not served');
                }
            }
        });

    });

    //     * DEV :sreekanth
    //     * Desc :  edit  hotel cuisine
    //     * Date : 5-may-16

    $(document.body).on('click', '.hotelcuisineedit', function () {

        var categoryid = $(this).attr('id');
        var dataid = $(this).attr('data_id');
        var categoryid = categoryid.replace("showEdit_", "");
        $('.editContent').find('#editcategory').val('');
        $('.editContent').find('#cuisineid').val(categoryid);
        $('.editContent').find('#editcuisinename').val(dataid);
        $('.editContent').show();
        $('.addContent').hide();
    });

    //     * DEV :sreekanth
    //     * Desc :  delete   hotelcategory
    //     * Date : 5-may-16

    $(document.body).on('click', '.hotelcuisinedelete', function () {
        var deleteid = $(this).attr('id');
        var deleteid = deleteid.replace("cuisinedelete_", "");
        window.alert(deleteid);
        if (deleteid) {
            $.ajax({
                url: '/agent/agent-ajax-handler',
                type: 'POST',
                datatype: 'json',
                data: {
                    method: 'hotelcuisinedelete',
                    deleteid: deleteid
                },
                beforeSend: function () {

                },
                success: function (response) {
                    var response = JSON.parse(response);
                    $('#' + "cuisinedelete_" + response).parent().parent().remove();
                }


            });
        }
    });

    $(".js-example-responsive").select2();

    $(".js-example-basic-hide-search").select2({
        minimumResultsForSearch: Infinity
    });
    $('#test').change(function() {
        $("#demo").prop("disabled", false);
    });
     //     * DEV :sowmya
    //     * Desc :  delete   agent payement
    //     * Date : 5-may-16

    $(document.body).on('click', '.deletepayement', function () {
        var deleteid = $(this).attr('id');
        var deleteid = deleteid.replace("payementdelete_", "");

        if (deleteid) {
            $.ajax({
                url: '/agent/agent-ajax-handler',
                type: 'POST',
                datatype: 'json',
                data: {
                    method: 'payementdelete',
                    deleteid: deleteid
                },
                beforeSend: function () {

                },
                success: function (response) {
                    console.log(response);
//                       var response = JSON.parse(response);
                    if (response) {
                        var uid = response['data'].replace(/ /g, '');

                        $('#' + "payementdelete_" + uid).parent().parent().remove();

                    }
                }


            });
        }
    });
</script>