<?php
/*
  DEV :Priyanka Varanasi
  DESC: javascripts File for agent
  Design Date : 5/4/2016
 */
?>
<script type="text/javascript">
    $(document).ready(function() {
        App.init();
    });

    $(document).ready(function() {
        $('#login').click(function() {
            $('.login').show();
            $('.register').hide();
        });
        $('#forget').click(function() {
            $('.forget').show();
            $('.login').hide();
        });
        $('#blogin').click(function() {
            $('.forget').hide();
            $('.login').show();
        });
        $('#register').click(function() {
            $('.login').hide();
            $('.register').show();
        });

        $(".selectpicker").select2();
        $(".add-loc").click(function() {
            $(".new-location").show();
            $(".loc-disable").prop("disabled", true);
        });

        $('#data-table').dataTable();

//        var elems = Array.prototype.slice.call(document.querySelectorAll('.js-switch'));
//        elems.forEach(function(html) {
//            var switchery = new Switchery(html);
//        });

        /*
         * DEV :priyanka varanasi
         * Desc :  Deactivate hotel
         * Date : 18/12/2015
         */

        /*
         * 
         * Modified script for hotel status 
         */
        $(document.body).on('change', '.hoteldeactive', function() {
            var hotelid = $(this).attr('id');
            var hotelid = hotelid.replace("hotel_", "");

            console.log('deactivate called');
            $.ajax({
                url: './agent-ajax-handler',
                type: 'POST',
                datatype: 'HTML',
                data: {
                    method: 'hotelactive',
                    hotelid: hotelid
                },
                beforeSend: function() {

                },
                success: function(response) {
                    console.log(response);
                    var response = JSON.parse(response);
                    if (response.code == "200") {
                        var uid = response['data'].replace(/ /g, '');
                        $('#' + "activeclass_" + uid).html("SUSPENDED");
                        $('#' + "activeclass_" + uid).removeClass('label label-success');
                        $('#' + "activeclass_" + uid).addClass('label label-danger');
                        $('#hotel_' + uid).removeClass('hoteldeactive');
                        $('#hotel_' + uid).addClass('hotelactive');


                    } else {
                        alert('Request could not served');
                    }
                }
            });

        });
        /*
         * 
         * Modified script for hotel status 
         */
        $(document.body).on('change', '.hotelactive', function() {
            var hotelid = $(this).attr('id');
            var hotelid = hotelid.replace("hotel_", "");

            console.log('activate called');
            $.ajax({
                url: './agent-ajax-handler',
                type: 'POST',
                datatype: 'HTML',
                data: {
                    method: 'hotelactive',
                    hotelid: hotelid
                },
                beforeSend: function() {

                },
                success: function(response) {
                    var response = JSON.parse(response);
                    if (response.code == "200") {
                        var uid = response['data'].replace(/ /g, '');
                        $('#' + "activeclass_" + uid).html("ACTIVE");
                        $('#' + "activeclass_" + uid).removeClass('label label-danger');
                        $('#' + "activeclass_" + uid).addClass('label label-success');
                        $('#hotel_' + uid).removeClass('hotelactive');
                        $('#hotel_' + uid).addClass('hoteldeactive');


                    } else {
                        alert('Request could not served');
                    }
                }
            });

        });

    });

    /*
     * DEV :priyanka varanasi
     * Desc : Deactivate hotel
     * Date : 18/12/2015
     */
    $(document.body).on('change', '.productdeactive', function() {
        var productid = $(this).attr('id');
        productid = productid.replace("product_", "");

        console.log('deactivate called');
        $.ajax({
            url: './agent-ajax-handler',
            type: 'POST',
            datatype: 'HTML',
            data: {
                method: 'productactive',
                productid: productid
            },
            beforeSend: function() {

            },
            success: function(response) {
                var response = JSON.parse(response);
                if (response.code == "200") {
                    var uid = response['data'].replace(/ /g, '');
                    $('#' + "activeclass_" + uid).html("SUSPENDED");
                    $('#' + "activeclass_" + uid).removeClass('label label-success');
                    $('#' + "activeclass_" + uid).addClass('label label-danger');
                    $('#product_' + uid).removeClass('productdeactive');
                    $('#product_' + uid).addClass('productactive');

                } else {
                    alert('Request could not served');
                }
            }
        });

    });
    /*
     * DEV :priyanka varanasi
     * Desc : Activate hotel
     * Date : 18/12/2015
     */
    $(document.body).on('change', '.productactive', function() {
        var productid = $(this).attr('id');
        productid = productid.replace("product_", "");
        console.log('activate called');
        $.ajax({
            url: './agent-ajax-handler',
            type: 'POST',
            datatype: 'HTML',
            data: {
                method: 'productactive',
                productid: productid
            },
            beforeSend: function() {

            },
            success: function(response) {
                var response = JSON.parse(response);
                if (response.code == "200") {
                    var uid = response['data'].replace(/ /g, '');
                    $('#' + "activeclass_" + uid).html("ACTIVE");
                    $('#' + "activeclass_" + uid).removeClass('label label-danger');
                    $('#' + "activeclass_" + uid).addClass('label label-success');
                    $('#product_' + uid).removeClass('productactive');
                    $('#product_' + uid).addClass('productdeactive');


                } else {

                    alert('Request could not served');

                }
            }

        });

    });

    /*
     * DEV :priyanka varanasi
     * Desc : Delete product
     * Date : 18/12/2015
     */

    $(document.body).on('click', '.deleteproduct', function() {
        var productid = $(this).attr('id');
        var deleteid = productid.replace("productdelete_", "");
        if (deleteid) {
            $.ajax({
                url: './agent-ajax-handler',
                type: 'POST',
                datatype: 'json',
                data: {
                    method: 'productdelete',
                    productid: deleteid
                },
                beforeSend: function() {

                },
                success: function(response) {

                    var response = JSON.parse(response);
                    if (response) {
                        var uid = response['data'].replace(/ /g, '');

                        $('#' + "productdelete_" + uid).parent().parent().remove();

                    }
                }


            });
        }
    });

    /*
     * DEV :priyanka varanasi
     * Desc : slect states based on country id
     * Date : 18/12/2015
     */

    $(document.body).on('change', '.selectcountry', function() {
        var id = $(this).val();

        if (id) {
            $.ajax({
                url: './agent-ajax-handler',
                type: 'POST',
                datatype: 'json',
                data: {
                    method: 'findstates',
                    countryid: id
                },
                beforeSend: function() {

                },
                success: function(response) {

                    var response = JSON.parse(response);
                    if (response.code == 200) {
                        $.each(response.data, function(i, a) {
                            $('#state').append('<option value="' + a.location_id + '">' + a.name + '</option>');
                        });

                    }
                }


            });
        }
    });



    /*
     * DEV :priyanka varanasi
     * Desc : slect citys based on state id
     * Date : 18/12/2015
     */

    $(document.body).on('change', '.selectstate', function() {
        var id = $(this).val();

        if (id) {
            $.ajax({
                url: './agent-ajax-handler',
                type: 'POST',
                datatype: 'json',
                data: {
                    method: 'findcitys',
                    stateid: id
                },
                beforeSend: function() {

                },
                success: function(response) {

                    var response = JSON.parse(response);
                    if (response.code == 200) {
                        $.each(response.data, function(i, a) {
                            $('#city').append('<option value="' + a.location_id + '">' + a.name + '</option>');
                        });

                    }
                }


            });
        }
    });

    /*
     * DEV :priyanka varanasi
     * Desc : slect locations based on city id
     * Date : 18/12/2015
     */

    $(document.body).on('change', '.selectcity', function() {
        var id = $(this).val();

        if (id) {
            $.ajax({
                url: './agent-ajax-handler',
                type: 'POST',
                datatype: 'json',
                data: {
                    method: 'findlocations',
                    locationid: id
                },
                beforeSend: function() {

                },
                success: function(response) {

                    var response = JSON.parse(response);
                    if (response.code == 200) {
                        $.each(response.data, function(i, a) {
                            $('#location').append('<option value="' + a.location_id + '">' + a.name + '</option>');
                        });


                    }
                }


            });
        }
    });


    $('#type_cusine').change(function() {
        var typevalue = $(this).val();
        $.ajax({
            url: './agent-ajax-handler',
            type: 'POST',
            datatype: 'HTML',
            data: {
                method: 'getcuisines',
                typevalue: typevalue
            },
            beforeSend: function() {

            },
            success: function(response) {

                var res = jQuery.parseJSON(response);
                console.log(res);
                if (res.code === 200) {
                    console.log(res.code);
                    $('#cuisine').html('');
                    $('#cuisine').append('<option disabled selected>Select Cuisine</option>');
                    $.each(res.data, function(i, a) {
                        $('#cuisine').append('<option value="' + a.cuisine_id + '">' + a.Cuisine_name + '</option>');
                    });
                    $('.show-cusine').show();
                    $('.show-category').hide();
                }
                else {
//                    console.log('res.code');
                    $('.show-cusine').show();
                    $('.show-category').hide();
                }

            }
        });
    });
    $('#type_category').change(function() {
        var typevalue = $(this).val();
        $.ajax({
            url: './agent-ajax-handler',
            type: 'POST',
            datatype: 'HTML',
            data: {
                method: 'getcategories',
                typevalue: typevalue
            },
            beforeSend: function() {

            },
            success: function(response) {
                var res = jQuery.parseJSON(response);
                if (res.code === 200) {

                    $('#category').html('');
                    $('#category').append('<option disabled selected>Select category</option>');
                    $.each(res.data, function(i, a) {
                        $('#category').append('<option value="' + a.category_id + '">' + a.cat_name + '</option>');
                    });
                    $('.show-category').show();
                    $('.show-cusine').hide();
                }


            }
        });
    });
    /*
     * DEV :sowmya
     * Desc : Delete hotel
     * Date : 14/4/2016
     */

    $(document.body).on('click', '.deletehotel', function() {
        var hotelid = $(this).attr('id');
        var deleteid = hotelid.replace("hoteldelete_", "");
        if (deleteid) {
            $.ajax({
                url: './agent-ajax-handler',
                type: 'POST',
                datatype: 'json',
                data: {
                    method: 'hoteldelete',
                    hotelid: deleteid
                },
                beforeSend: function() {

                },
                success: function(response) {

                    var response = JSON.parse(response);
                    if (response) {
                        var uid = response['data'].replace(/ /g, '');

                        $('#' + "hoteldelete_" + uid).parent().parent().remove();

                    }
                }


            });
        }
    });
    /*
     * DEV :sowmya
     * Desc : Status  change for grocery
     * Date : 26/4/2016
     */
    $(document.body).on('change', '.grocerydeactive', function() {
        var groceryid = $(this).attr('id');
        var groceryid = groceryid.replace("grocery_", "");

        console.log('deactivate called');
        $.ajax({
            url: './agent-ajax-handler',
            type: 'POST',
            datatype: 'HTML',
            data: {
                method: 'groceryactive',
                groceryid: groceryid
            },
            beforeSend: function() {

            },
            success: function(response) {
                var response = JSON.parse(response);
                if (response.code == "200") {
                    var uid = response['data'].replace(/ /g, '');
                    $('#' + "activeclass_" + uid).html("SUSPENDED");
                    $('#' + "activeclass_" + uid).removeClass('label label-success');
                    $('#' + "activeclass_" + uid).addClass('label label-danger');
                    $('#grocery_' + uid).removeClass('grocerydeactive');
                    $('#grocery_' + uid).addClass('groceryactive');


                } else {
                    alert('Request could not served');
                }
            }
        });

    });
    /*
     * DEV :sowmya
     * Desc : Status  change for grocery
     * Date : 26/4/2016
     */
    $(document.body).on('change', '.groceryactive', function() {
        var groceryid = $(this).attr('id');
        var groceryid = groceryid.replace("grocery_", "");

        console.log('activate called');
        $.ajax({
            url: './agent-ajax-handler',
            type: 'POST',
            datatype: 'HTML',
            data: {
                method: 'groceryactive',
                groceryid: groceryid
            },
            beforeSend: function() {

            },
            success: function(response) {
                var response = JSON.parse(response);
                if (response.code === "200") {
                    var uid = response['data'].replace(/ /g, '');
                    $('#' + "activeclass_" + uid).html("ACTIVE");
                    $('#' + "activeclass_" + uid).removeClass('label label-danger');
                    $('#' + "activeclass_" + uid).addClass('label label-success');
                    $('#grocery_' + uid).removeClass('groceryactive');
                    $('#grocery_' + uid).addClass('grocerydeactive');


                } else {
                    alert('Request could not served');
                }
            }
        });

    });
    /*
     * DEV :sowmya
     * Desc : Delete grocery
     * Date : 26/4/2016
     */

    $(document.body).on('click', '.deletegrocery', function() {
        var groceryid = $(this).attr('id');
        var deleteid = groceryid.replace("grocerydelete_", "");
        if (deleteid) {
            $.ajax({
                url: './agent-ajax-handler',
                type: 'POST',
                datatype: 'json',
                data: {
                    method: 'grocerydelete',
                    groceryid: deleteid
                },
                beforeSend: function() {

                },
                success: function(response) {

                    var response = JSON.parse(response);
                    console.log(response);
                    if (response) {
                        var uid = response['data'].replace(/ /g, '');

                        $('#' + "grocerydelete_" + uid).parent().parent().remove();

                    }
                }


            });
        }
    });

    /*
     * DEV :sowmya
     * Desc : Status  change for reviews
     * Date : 27/4/2016
     */
    $(document.body).on('change', '.reviewdeactive', function() {
        var reviewid = $(this).attr('id');
        var reviewid = reviewid.replace("review_", "");

        console.log('deactivate called');
        $.ajax({
            url: './agent-ajax-handler',
            type: 'POST',
            datatype: 'HTML',
            data: {
                method: 'reviewactive',
                reviewid: reviewid
            },
            beforeSend: function() {

            },
            success: function(response) {
                var response = JSON.parse(response);
                if (response.code === "200") {
                    var uid = response['data'].replace(/ /g, '');
                    $('#' + "activeclass_" + uid).html("SUSPENDED");
                    $('#' + "activeclass_" + uid).removeClass('label label-success');
                    $('#' + "activeclass_" + uid).addClass('label label-danger');
                    $('#review_' + uid).removeClass('reviewdeactive');
                    $('#review_' + uid).addClass('reviewactive');
                }
            }
        });

    });
    /*
     * DEV :sowmya
     * Desc : Status  change for review
     * Date : 27/4/2016
     */
    $(document.body).on('change', '.reviewactive', function() {
        var reviewid = $(this).attr('id');
        var reviewid = reviewid.replace("review_", "");

        console.log('activate called');
        $.ajax({
            url: './agent-ajax-handler',
            type: 'POST',
            datatype: 'HTML',
            data: {
                method: 'reviewactive',
                reviewid: reviewid
            },
            beforeSend: function() {

            },
            success: function(response) {
                var response = JSON.parse(response);
                if (response.code === "200") {
                    var uid = response['data'].replace(/ /g, '');
                    $('#' + "activeclass_" + uid).html("ACTIVE");
                    $('#' + "activeclass_" + uid).removeClass('label label-danger');
                    $('#' + "activeclass_" + uid).addClass('label label-success');
                    $('#review_' + uid).removeClass('reviewactive');
                    $('#review_' + uid).addClass('reviewdeactive');
                }
            }
        });

    });
    /*
     * DEV :sowmya
     * Desc : Delete review
     * Date : 27/4/2016
     */

    $(document.body).on('click', '.deletereview', function() {
        var reviewid = $(this).attr('id');
        var deleteid = reviewid.replace("reviewdelete_", "");
        if (deleteid) {
            $.ajax({
                url: './agent-ajax-handler',
                type: 'POST',
                datatype: 'json',
                data: {
                    method: 'reviewdelete',
                    reviewid: deleteid
                },
                beforeSend: function() {

                },
                success: function(response) {

                    var response = JSON.parse(response);
                    console.log(response);
                    if (response) {
                        var uid = response['data'].replace(/ /g, '');

                        $('#' + "reviewdelete_" + uid).parent().parent().remove();

                    }
                }


            });
        }
    });

</script>