                                     
<div id="page-title">
    <h2>Admin Agent Transactions Details</h2>
    <p>The most complete user interface framework that can be used to create stunning admin dashboards and presentation websites.</p>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="panel">
            <div class="panel-body">
                <h3 class="title-hero">View Admin-User Transactions</h3>
                <div class="example-box-wrapper">
                    <table id="datatable-responsive" class="table table-striped table-bordered responsive no-wrap" cellspacing="0" width="100%">
                        <thead>
                            <tr>


                                <th>Agent Name</th>
                                <th>Email ID</th>
                                <th>Order ID</th>
                                <th>Transaction Status</th>
                                <th>Order Satus</th>
                                <th>Transaction Amount</th>
                               <th>Transaction Date</th>

                            </tr>
                        </thead>
                        <tfoot>
                            <tr>
                            <th>Agent Name</th>
                                <th>Email ID</th>
                                <th>Order ID</th>
                                <th>Transaction Status</th>
                                <th>Order Satus</th>
                                <th>Transaction Amount</th>
                               <th>Transaction Date</th>

                            </tr>
                        </tfoot>
                        <tbody>
                            <tr>
                                <td>Priya</td>
                                <td>priyankav@globussoft.com </td>
                                
                                <td>186</td>
                                <td>Pending</td>
                                <td>Pending</td>
                                <td>500</td>
                                <td>Not carried</td>
                                    
                            </tr>   
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>


