                                   
<div id="page-title">
    <h2>Admin Agent Transactions Details</h2>
    <p>The most complete user interface framework that can be used to create stunning admin dashboards and presentation websites.</p>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="panel">
            <div class="panel-body">
                <h3 class="title-hero">View/Delete Admin -Agent Transactions</h3>
                <div class="example-box-wrapper" id="user-transaction">
                    <!-- Nav tabs -->
                    <ul class="nav nav-pills" role="tablist">
                        <li role="presentation" class="active">
                            <a href="#success" aria-controls="success" role="tab" data-toggle="tab">Success</a>
                        </li>
                        <li role="presentation">
                            <a href="#pending" aria-controls="pending" role="tab" data-toggle="tab">Pending</a>
                        </li>
                        <li role="presentation">
                            <a href="#cancel" aria-controls="cancel" role="tab" data-toggle="tab">Cancel</a>
                        </li>
                        <li role="presentation">
                            <a href="#failed" aria-controls="failed" role="tab" data-toggle="tab">Failed</a>
                        </li>
                    </ul>
                    <!-- Tab panes -->
                    <div class="tab-content">
                        <div role="tabpanel" class="tab-pane fade in active" id="success">
                            <h3 class="title-hero">Successful Transactions</h3>
                            <table class="table table-striped table-bordered responsive no-wrap datatable-responsive" cellspacing="0" width="100%">
                                <thead>
                                    <tr>
                                        <th>S.No.</th>
                                        <th>Trans. ID</th>
                                        <th>Name</th>
                                        <th>Email ID</th>                                       
                                        <th>Trans. Type</th>
                                        <th>Trans. Amount</th>
                                        <th>Trans. Code</th>
                                        <th>Trans. Date</th>
                                        <th>Delete</th>
                                    </tr>
                                </thead>
                                <tfoot>
                                    <tr>
                                        <th>S.No.</th>
                                        <th>Trans. ID</th>
                                        <th>Name</th>
                                        <th>Email ID</th>                                       
                                        <th>Trans. Type</th>
                                        <th>Trans. Amount</th>
                                        <th>Trans. Code</th>
                                        <th>Trans. Date</th>
                                        <th>Delete</th>
                                    </tr>
                                </tfoot>
                                <tbody>
                                    <?php
                                    if (isset($this->successfullStatus)) {
                                        $i = 1;
                                        foreach ($this->successfullStatus as $value) {
                                            ?>
                                            <tr>
                                                <td><?php echo $i; ?></td>
                                                <td><?php echo $value['agent_tx_id']; ?></td>
                                                <td><?php echo $value['loginname']; ?></td>
                                                <td><?php echo $value['email']; ?></td>      
                                                <td><?php
                                                    if ($value['tx_type'] == 1) {
                                                        echo 'COD';
                                                    } else if ($value['tx_type'] == 2) {
                                                        echo "PaYpaL";
                                                    } else if ($value['tx_type'] == 3) {
                                                        echo "By Cheque";
                                                    } else {
                                                        echo "No Payement GateWay";
                                                    }
                                                    ?></td>                             
                                                <td><?php echo $value['tx_amount']; ?></td>
                                                <td><?php echo $value['tx_code']; ?></td>
                                                <td><?php echo date("j F , Y h:i:s A", strtotime($value['tx_date'])); ?></td>
                                                <td class="text-center">                                             
                                                    <a href="javascript:;" id="<?php echo "transdelete_" . $value['agent_tx_id']; ?>" class="btn btn-default deleteagenttrans"><i class="glyph-icon icon-linecons-trash"></i></a>
                                                </td>
                                            </tr>   
                                            <?php
                                            $i++;
                                        }
                                    }
                                    ?>

                                </tbody>
                            </table>
                        </div>
                        <div role="tabpanel" class="tab-pane fade" id="pending">
                            <h3 class="title-hero">Pending Transactions</h3>
                            <table class="table table-striped table-bordered responsive no-wrap datatable-responsive" cellspacing="0" width="100%">
                                <thead>
                                    <tr>
                                        <th>S.No.</th>
                                        <th>Trans. ID</th>
                                        <th>Name</th>
                                        <th>Email ID</th>                                       
                                        <th>Trans. Type</th>
                                        <th>Trans. Amount</th>
                                        <th>Trans. Code</th>
                                        <th>Trans. Date</th>
                                        <th>Delete</th>
                                    </tr>
                                </thead>
                                <tfoot>
                                    <tr>
                                        <th>S.No.</th>
                                        <th>Trans. ID</th>
                                        <th>Name</th>
                                        <th>Email ID</th>                                       
                                        <th>Trans. Type</th>
                                        <th>Trans. Amount</th>
                                        <th>Trans. Code</th>
                                        <th>Trans. Date</th>
                                        <th>Delete</th>

                                    </tr>
                                </tfoot>
                                <tbody>
                                    <?php
                                    if (isset($this->pendingStatus)) {
                                        $i = 1;
                                        foreach ($this->pendingStatus as $value) {
                                            ?>
                                            <tr>
                                                <td><?php echo $i; ?></td>
                                                <td><?php echo $value['agent_tx_id']; ?></td>
                                                <td><?php echo $value['loginname']; ?></td>
                                                <td><?php echo $value['email']; ?></td>      
                                                <td><?php
                                                    if ($value['tx_type'] == 1) {
                                                        echo 'COD';
                                                    } else if ($value['tx_type'] == 2) {
                                                        echo "PaYpaL";
                                                    } else if ($value['tx_type'] == 3) {
                                                        echo "By Cheque";
                                                    } else {
                                                        echo "No Payement GateWay";
                                                    }
                                                    ?></td>                             
                                                <td><?php echo $value['tx_amount']; ?></td>
                                                <td><?php echo $value['tx_code']; ?></td>
                                                <td><?php echo date("j F , Y h:i:s A", strtotime($value['tx_date'])); ?></td>
                                                <td class="text-center">                                             
                                                    <a href="javascript:;" id="<?php echo "transdelete_" . $value['agent_tx_id']; ?>" class="btn btn-default deleteagenttrans"><i class="glyph-icon icon-linecons-trash"></i></a>
                                                </td>
                                            </tr>   

                                            <?php
                                            $i++;
                                        }
                                    }
                                    ?> 
                                </tbody>
                            </table>
                        </div>
                        <div role="tabpanel" class="tab-pane fade" id="cancel">
                            <h3 class="title-hero">Cancelled Transactions</h3>
                            <table class="table table-striped table-bordered responsive no-wrap datatable-responsive" cellspacing="0" width="100%">
                                <thead>
                                    <tr>
                                        <th>S.No.</th>
                                        <th>Trans. ID</th>
                                        <th>Name</th>
                                        <th>Email ID</th>                                       
                                        <th>Trans. Type</th>
                                        <th>Trans. Amount</th>
                                        <th>Trans. Code</th>
                                        <th>Trans. Date</th>
                                        <th>Delete</th>
                                    </tr>
                                </thead>
                                <tfoot>
                                    <tr>
                                        <th>S.No.</th>
                                        <th>Trans. ID</th>
                                        <th>Name</th>
                                        <th>Email ID</th>                                       
                                        <th>Trans. Type</th>
                                        <th>Trans. Amount</th>
                                        <th>Trans. Code</th>
                                        <th>Trans. Date</th>
                                        <th>Delete</th>
                                    </tr>
                                </tfoot>
                                <tbody>
                                    <?php
                                    if (isset($this->failedStatus)) {
                                        $i = 1;
                                        foreach ($this->failedStatus as $value) {
                                            ?>
                                            <tr>
                                                <td><?php echo $i; ?></td>
                                                <td><?php echo $value['agent_tx_id']; ?></td>
                                                <td><?php echo $value['loginname']; ?></td>
                                                <td><?php echo $value['email']; ?></td>                                              
                                                <td><?php
                                                    if ($value['tx_type'] == 1) {
                                                        echo 'COD';
                                                    } else if ($value['tx_type'] == 2) {
                                                        echo "PaYpaL";
                                                    } else if ($value['tx_type'] == 3) {
                                                        echo "By Cheque";
                                                    } else {
                                                        echo "No Payement GateWay";
                                                    }
                                                    ?></td>                              
                                                <td><?php echo $value['tx_amount']; ?></td>
                                                <td><?php echo $value['tx_code']; ?></td>
                                                <td><?php echo date("j F , Y h:i:s A", strtotime($value['tx_date'])); ?></td>
                                                <td class="text-center">                                             
                                                    <a href="javascript:;" id="<?php echo "transdelete_" . $value['agent_tx_id']; ?>" class="btn btn-default deleteagenttrans"><i class="glyph-icon icon-linecons-trash"></i></a>
                                                </td>
                                            </tr>   

                                            <?php
                                            $i++;
                                        }
                                    }
                                    ?> 
                                </tbody>
                            </table>
                        </div>
                        <div role="tabpanel" class="tab-pane fade" id="failed">
                            <h3 class="title-hero">Failed Transactions</h3>
                            <table class="table table-striped table-bordered responsive no-wrap datatable-responsive" cellspacing="0" width="100%">
                                <thead>
                                    <tr>
                                        <th>S.No.</th>
                                        <th>Trans. ID</th>
                                        <th>Name</th>
                                        <th>Email ID</th>                                       
                                        <th>Trans. Type</th>
                                        <th>Trans. Amount</th>
                                        <th>Trans. Code</th>
                                        <th>Trans. Date</th>
                                        <th>Delete</th>
                                    </tr>
                                </thead>
                                <tfoot>
                                    <tr>
                                        <th>S.No.</th>
                                        <th>Trans. ID</th>
                                        <th>Name</th>
                                        <th>Email ID</th>                                       
                                        <th>Trans. Type</th>
                                        <th>Trans. Amount</th>
                                        <th>Trans. Code</th>
                                        <th>Trans. Date</th>
                                        <th>Delete</th>
                                    </tr>
                                </tfoot>
                                <tbody>
                                    <?php
                                    if (isset($this->cancelStatus)) {
                                        $i = 1;
                                        foreach ($this->cancelStatus as $value) {
                                            ?>
                                            <tr>
                                                <td><?php echo $i; ?></td>
                                                <td><?php echo $value['agent_tx_id']; ?></td>
                                                <td><?php echo $value['loginname']; ?></td>
                                                <td><?php echo $value['email']; ?></td>                                           
                                                <td><?php
                                                    if ($value['tx_type'] == 1) {
                                                        echo 'COD';
                                                    } else if ($value['tx_type'] == 2) {
                                                        echo "PaYpaL";
                                                    } else if ($value['tx_type'] == 3) {
                                                        echo "By Cheque";
                                                    } else {
                                                        echo "No Payement GateWay";
                                                    }
                                                    ?></td>                            
                                                <td><?php echo $value['tx_amount']; ?></td>
                                                <td><?php echo $value['tx_code']; ?></td>
                                                <td><?php echo date("j F , Y h:i:s A", strtotime($value['tx_date'])); ?></td>
                                                <td class="text-center">                                             
                                                    <a href="javascript:;" id="<?php echo "transdelete_" . $value['agent_tx_id']; ?>" class="btn btn-default deleteagenttrans"><i class="glyph-icon icon-linecons-trash"></i></a>
                                                </td>
                                            </tr>   

                                            <?php
                                            $i++;
                                        }
                                    }
                                    ?>  
                                </tbody>
                            </table>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>

<script>
    $('[data-toggle="tab"]').click(function(e) {
        e.preventDefault();
        $(this).parent().siblings().removeClass('active');
        $(this).parent().addClass('active');
        var id = $(this).attr('href');
        $(id).siblings().removeClass('in active');
        $(id).toggleClass('in active');
    });
</script>