<footer class="page-footer">
    <div class="container">
        <ul class="social-links">
            <li><a href="#"><span><i class="fa fa-2x fa-facebook-f"></i></span></a></li>
            <li><a href="#"><span><i class="fa fa-2x fa-twitter"></i></span></a></li>
            <li><a href="#"><span><i class="fa fa-2x fa-google-plus"></i></span></a></li>
            <li><a href="#"><span><i class="fa fa-2x fa-pinterest-p"></i></span></a></li>
            <li><a href="#"><span><i class="fa fa-2x fa-instagram"></i></span></a></li>
        </ul>
        <ul class="extra-links">
            <li><a href="#">About Us</a></li>
            <li><a href="#">Contact Us</a></li>
            <li><a href="#">FAQ</a></li>
            <li><a href="#">Terms & Conditions</a></li>
            <li><a href="#">Refunds & Cancellation Policy</a></li>
            <li><a href="#">Offer Terms</a></li>
            <li><a href="#">Partner With Us</a></li>
        </ul>

    </div>
    <div class="footer-copyright">
        <div class="container">
            <p class="center">&copy; 2016 Copyright Ziingo. A <a target="_blank" href="https://worldjunction.com" class="bold">Worldjunction</a> LLC Company </p>
        </div>
    </div>
</footer>
<script>
    $(document).ready(function() {
        Ziingo.initComponents();
        Layout.initCheckOutFrom();
        //Layout.initSweetAlert();
        Layout.initLayoutComponents();
        Layout.initRestaurantRating();
//        Layout.initDateTimePicker();
    });


</script>
</body>
</html>
<?php echo $this->render('script.phtml'); ?>
<?php echo $this->render('popups.phtml'); ?>

