
<!--location search modal-->
<div id="loginModal" class="modal loginModal">
    <button class="btn-floating modal-close modal-close-btn waves-effect waves-light"><i class="material-icons">clear</i></button>
    <div class="modal-content">
        <div class="row">
            <div class="col s12">
                <img src="/assets/images/logo.png" class="logo">
            </div>
        </div>
        <div id="loginContent" class="row no-m-bot">
            <form class="col s12 loginForm" method="post">
                <div class="row">
                    <div class="col s12">
                        <ul class="signup-social-list">
                            <li>
                                <button class="btn waves-effect waves-light fbc-login-button">
                                    <span><i class="fa fa-facebook"></i></span>FACEBOOK
                                </button>
                            </li>
                            <li>
                                <button class="btn waves-effect waves-light btn-twitter">
                                    <span><i class="fa fa-twitter"></i></span>
                                    TWITTER
                                </button>
                            </li>
                        </ul>
                    </div>
                    <div class="input-field col s12">
                        <input id="loginname" name="loginname" class="validate" type="email">
                        <label for="loginname">Email</label>
                    </div>
                    <div class="row">
                        <div class="input-field col s12">
                            <input  type="password" id="pwd" name="pwd" class="validate">
                            <label for="pwd">Password</label>
                        </div>
                    </div>
                    <div class="row">
                        <!--                        <div class="col s6 left-align">
                                                    <a class="btn waves-light waves-effect " data-toggle="modal" data-target="#myModal" id="forgotBtn"  >Forgot Password</a>
                                                </div>-->
                        <div class="pull-right">
                            <a onClick="forgotpd()" class="btn waves-light waves-effect ziingoForgotpassword" href="javascript:void(0);" >Forgot password?
                            </a>
                            <!--class="forgot_pass "-->
                        </div>
                        <div class="col s6 right-align">
                            <button  name="userform" value="ziingologin" class="btn waves-light waves-effect ziingologin">Login</button>
                        </div>
                    </div>
                    <span class="error" style="text-align:center "></span>
                    <span class="error" style="text-align:center"></span>
                    <div class="row no-m-bot">
                        <div class="col s12">
                            <p class="center">New User?<a href="/signup">Signup</a></p>
                        </div>
                    </div>
                </div>
            </form>     
        </div>


        <div class="my_account_block forgotpd clearfix hide">
            <div class="login">
                <h2>Forgot Password</h2>
                <form class="forgotpd_form" action="javascript:;" method="post" id="forgotpasswordform">
                    <p>
                        Enter your e-mail address below to reset your password.
                    </p>
                    <input type="email" name="loginname" placeholder="Email" id="loginname" />
                    <span class="suc-err"></span>
                    <div class="resetcode hide" id="resetCode">
                        <p>
                            Check Mail and Enter your reset code below to Reset password
                        </p>
                        <input type="text" name="resetcode" placeholder="Reset Code" id="resetcode"/>
                        <span class="code-suc-err"></span><br>
                    </div>
                    <div class="center">
                        <input type="button" onClick="login()" value="Back">
                        <input type="submit"  value="Send">
                    </div>
                </form>
            </div>                    
        </div>


        <div class="my_account_block enternewpw clearfix hide">
            <div class="login">
                <h2>Enter New Password</h2>
                <form class="EnterNewPw_form" action="javascript:void(0);" method="post" id="EnterNewPWform">
                    <p>
                        Enter new Password to reset your password.
                    </p>
                    <label for="pwd">New Password</label>
                    <input type="password" name="pwd" class="form-control" id="pwd" autocomplete="off" placeholder="Password">
                    <br><label for="repwd">Re-enter password</label>
                    <input type="password" name="repwd" class="form-control" id="repwd" autocomplete="off" placeholder="Re-enter Password">

                    <span class="pw-suc-err"></span><br>

                    <div class="center">
                        <input type="button" onClick="login()" value="Back">
                        <input type="submit"  value="Send">
                    </div>
                </form>
            </div>                    
        </div>
    </div>
</div>
<!--- modal ends here ----->

<!--location search modal-->
<div id="changePlaceModal" class="modal modal-small changePlaceModal red lighten-5">
    <button class="btn-floating modal-close modal-close-btn waves-effect waves-light"><i class="material-icons">clear</i></button>
    <div class="modal-content">
        <div class="row">
            <div class="col s12 center">
                <h4 class="font-DancingScript bold">Change Locality</h4>
            </div>
            <form class="col s12 m-top-md" method="Post">
                <div class="row">
                    <div class="col s12">
                        <div class="dropdown dropContent closed">
                            <div class="title city1">Choose your City</div>
                            <input type="hidden" value="" class="thiscity" name="city">
                            <ul id="cityslist" class="city2">
                                <?php
                                $this->citysinfo = json_decode($_COOKIE['citys'], true);
                                if ($this->citysinfo) {
                                    foreach ($this->citysinfo as $value) {
                                        ?>
                                        <li><span value="<?php echo $value['location_id']; ?>"><?php echo $value['name']; ?></span></li>

                                        <?php
                                    }
                                }
                                ?>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col s12">
                        <div class="dropdown dropContent closed">
                            <div class="title location1">Choose your nearest Location</div>
                            <input type="hidden" value="" class="thislocation" name="location">
                            <ul id="locationList" class="city2">
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="row m-top-md">
                    <div class="col s12 center">
                        <a href='' id = "addlocid" class="btn btn-alt waves-effect teal-text  waves-teal top5px" >Find Restaurants</a>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<!--- modal ends here ----->
<style>
    .help-block{
        color : rgb(251,0,7);
    }
    .error{
        color : rgb(251,0,7);
    }
    .dropdown.dropContent ul.city2 {
        width: 81.2%;
    }
    .dropdown.dropContent div.city1::after {
        right: 14%;
        top: 40%;
    }
    .dropdown.dropContent div.location1::after {
        right: 14%;
        bottom: 40%;
    }
    .city1, .location1 {
        color: rgba(0,0,0,0.7);
    }
    /*    body .lean-overlay:last-child {
            display: none !important;*/

</style>
<script type="text/javascript">
    function forgotpd() {
        $('.forgotpd').removeClass('hide');
        $('.logind').addClass('hide');
        $('.enternewpw').addClass('hide'); //emailID resetcode password1 password2
        $('.loginForm').addClass('hide');
        $('#loginname').prop('disabled', false);
        $('#resetCode').addClass('hide');
    }
    function login() {
        $('.logind').removeClass('hide');
        $('.forgotpd').addClass('hide');
        $('.enternewpw').addClass('hide');
        $('.loginForm').addClass('hide');
        $('#loginname').val('');
        $('#resetcode').val('');
        $('#pwd').val('');
        $('#repwd').val('');
        $('#loginname').prop('disabled', false);
    }
    function enternewpw() {
        $('.enternewpw').removeClass('hide');
        $('.forgotpd').addClass('hide');
        $('.logind').addClass('hide');
        $('.loginForm').addClass('hide');
        $('#pwd').val('');
        $('#repwd').val('');
        $('#loginname').prop('disabled', false);
    }
   
    $('#EnterNewPWform').validate({
        rules: {
            pwd: {
                required: true,
//                    passwordregex: true
            },
            repwd: {
                required: true,
                equalTo: "#pwd"
            }
        },
        messages: {
            pwd: {
                required: "Please Enter Password"
            },
            repwd: {
                required: "Please Re-enter Password"
            }
        }
    });
//        $("#forgotpasswordform").submit(function(e) {
//        submitHandler: function(form) {
//        $(document.body).on('click', '#forgotpasswordform', function() {

    $('#forgotpasswordform').validate({
        rules: {
            loginname: {
                required: true,
            },
            resetcode: {
                required: true,
            }
        },
        messages: {
            loginname: {
                required: "Email cannot be empty"
            },
            resetcode: {
                required: "Reset Code cannot be empty"
            }
        }
    });

    $('#forgotpasswordform').click(function(e) {
        e.preventDefault();
        var fpdemail = $('#loginname').val();
        console.log(fpdemail);
        var resetcode = $('#resetcode').val();
        console.log(resetcode);
        if ($("#forgotpasswordform").valid()) {
            if (resetcode == '' && fpdemail != '') {
                $.ajax({
                    url: '/authentication-ajax-handler',
                    type: 'POST',
                    dataType: 'json',
                    data: {
                        method: 'forgotpw',
                        loginname: fpdemail
                    },
                    success: function(response) {

//                            if (response['code'] == 200) {
                        if (response.code == 200) {
                            $('.suc-err').show();
                            $('.suc-err').html(response['message']);
                            $('.suc-err').css('color', 'green');
                            $('.suc-err').delay(4000).hide('slow');
                            $('#resetCode').removeClass('hide');
                            $('#loginname').prop('disabled', true);
                        } else {
                            $('.suc-err').show();
                            $('.suc-err').html(response);
                            $('.suc-err').css('color', 'red');
                            $('.suc-err').delay(4000).hide('slow');
                        }
                    }
                });
            } else {
                $.ajax({
                    url: '/authentication-ajax-handler',
                    type: 'POST',
                    dataType: 'json',
                    data: {
                        method: 'verifyResetCode',
                        loginname: fpdemail,
                        resetcode: resetcode
                    },
                    success: function(response) {
//                            if (response['code'] == 200) {
                        if (response.code == 200) {
                            $('.code-suc-err').show();
                            $('.code-suc-err').html(response['message']);
                            $('.code-suc-err').css('color', 'green');
                            $('.code-suc-err').delay(4000).hide('slow');
                            enternewpw();
                        } else {
                            $('.code-suc-err').show();
                            $('.code-suc-err').html(response);
                            $('.code-suc-err').css('color', 'red');
                            $('.code-suc-err').delay(4000).hide('slow');
                        }
                    }
                });
            }
        }
    });
//        $("#EnterNewPWform").submit(function(e) {
//        $(document.body).on('click', '#EnterNewPWform', function() {
    $('#EnterNewPWform').click(function(e) {
        e.preventDefault();
        var fpdemail = $('#loginname').val();
        var resetcode = $('#resetcode').val();
        var password1 = $('#pwd').val();
        var password2 = $('#repwd').val();
        if ($("#EnterNewPWform").valid()) {
            if (resetcode != '' && fpdemail != '' && password1 != '' && password2 != '') {
                $.ajax({
                    url: '/authentication-ajax-handler',
                    type: 'POST',
                    dataType: 'json',
                    data: {
                        method: 'resetPassword',
                        loginname: fpdemail,
                        pwd: password1,
                        repwd: password2,
                        resetcode: resetcode
                    },
                    success: function(response) {
//                            if (response['code'] == 200) {
                        if (response.code == 200) {
                            $('.pw-suc-err').show();
                            $('.pw-suc-err').html(response['message']);
                            $('.pw-suc-err').css('color', 'green');
                            $('.pw-suc-err').delay(4000).hide('slow');
                            $('#pwd').val('');
                            $('#repwd').val('');
                        } else {
                            $('.pw-suc-err').show();
                            $('.pw-suc-err').html(response);
                            $('.pw-suc-err').css('color', 'red');
                            $('.pw-suc-err').delay(4000).hide('slow');
                            $('#pwd').val('');
                            $('#repwd').val('');
                        }
                    }
                });
            }
        }
    });
</script>
