<!--location search modal-->
<div id="loginModal" class="modal loginModal">
    <button class="btn-floating modal-close modal-close-btn waves-effect waves-light"><i class="material-icons">clear</i></button>
    <div class="modal-content">
        <div class="row">
            <div class="col s12">
                <img src="/assets/images/logo.png" class="logo">
            </div>
        </div>
        <div id="loginContent" class="row no-m-bot">
            <form class="col s12 loginForm" method="post">
                <div class="row">
                    <div class="col s12">
                        <ul class="signup-social-list">
                            <li>
                                <button class="btn waves-effect waves-light fbc-login-button">
                                    <span><i class="fa fa-facebook"></i></span>FACEBOOK
                                </button>
                            </li>
                            <li>
                                <button class="btn waves-effect waves-light btn-twitter">
                                    <span><i class="fa fa-twitter"></i></span>
                                    TWITTER
                                </button>
                            </li>
                        </ul>
                    </div>
                    <div class="input-field col s12">
                        <input id="loginname" name="loginname" class="validate" type="email">
                        <label for="loginname">Email</label>
                    </div>
                    <div class="row">
                        <div class="input-field col s12">
                            <input  type="password" id="pwd" name="pwd" class="validate">
                            <label for="pwd">Password</label>
                        </div>
                    </div>
                    <div class="row">
                        <div class="pull-right">
                            <a  class="ziingoForgotpassword" href="javascript:void(0);" >Forgot password?</a>
                        </div>
                        <div class="col s12 center">
                            <button  name="userform" value="ziingologin" class="btn waves-light waves-effect ziingologin">Login</button>
                        </div>
                    </div>
                    <span class="error" style="text-align:center "></span>
                    <span class="error" style="text-align:center"></span>
                    <div class="row no-m-bot">
                        <div class="col s12">
                            <p class="center">New User?<a href="/signup">Signup</a></p>
                        </div>
                    </div>
                </div>
            </form>     
        </div>


        <div class="my_account_block forgotpwd clearfix hide">
            <div class="login">
                <h4 class="font-DancingScript bold center">Forgot Password</h4>
                <form class="ziingoForgotpassword1" action="javascript:;" method="post" id="forgotpasswordform" style="margin-top:3%;">
                    <p>
                        Enter your E-mail address below to reset your password.
                    </p>
                    <input type="email" name="EmailId" placeholder="Email" id="EmailId" />
                    <span class="suc-err"></span>
                    <div class="resetcode hide" id="resetCode">
                        <p>
                            Check Mail and Enter your reset code below to Reset password
                        </p>
                        <input type="text" name="resetcode" placeholder="ResetCode" id="reset"/>
                        <span class="code-suc-err"></span><br>
                    </div>
                    <div class="center">
                        <!--<input type="button"  value="Back">-->
                        <input type="submit" class="btn waves-light waves-effect forgetPassword" value="Verify" />
                    </div>
                </form>
            </div>                    
        </div>


        <div class="my_account_block enternewpw clearfix hide">
            <div class="login">
                <h4 class="font-DancingScript bold center">Enter New Password</h4>
                <form class="EnterNewPw_form" action="javascript:;" method="post" id="EnterNewPWform" style="margin-top:3%;">
                    <p>
                        Enter new Password to reset your password.
                    </p>
                    <label for="Password">New Password</label>
                    <input type="password" name="Password" class="form-control" id="Password" autocomplete="off" placeholder="Password" >
                    <br><label for="rePassword">Re-enter password</label>
                    <input type="password" name="rePassword" class="form-control" id="rePassword" autocomplete="off" placeholder="Re-enter Password" >

                    <span class="pw-suc-err"></span><br>

                    <div class="center">
                        <!--<input type="button"  value="Back">-->
                        <input type="button" class="btn waves-light waves-effect setNewPassword" value="Update Password" />
                    </div>
                </form>
            </div>                    
        </div>
    </div>
</div>
<!--- modal ends here ----->

<!--location search modal-->
<div id="changePlaceModal" class="modal modal-small changePlaceModal red lighten-5">
    <button class="btn-floating modal-close modal-close-btn waves-effect waves-light"><i class="material-icons">clear</i></button>
    <div class="modal-content">
        <div class="row">
            <div class="col s12 center">
                <h4 class="font-DancingScript bold">Change Locality</h4>
            </div>
            <form class="col s12 m-top-md" method="Post">
                <div class="row">
                    <div class="col s12">
                        <div class="dropdown dropContent closed">
                            <div class="title city1">Choose your City</div>
                            <input type="hidden" value="" class="thiscity" name="city">
                            <ul id="cityslist" class="city2">
                                <?php
                                $this->citysinfo = json_decode($_COOKIE['citys'], true);
                                if ($this->citysinfo) {
                                    foreach ($this->citysinfo as $value) {
                                        ?>
                                        <li><span value="<?php echo $value['location_id']; ?>"><?php echo $value['name']; ?></span></li>

                                        <?php
                                    }
                                }
                                ?>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col s12">
                        <div class="dropdown dropContent closed">
                            <div class="title location1">Choose your nearest Location</div>
                            <input type="hidden" value="" class="thislocation" name="location">
                            <ul id="locationList" class="city2">
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="row m-top-md">
                    <div class="col s12 center">
                        <a href='' id = "addlocid" class="btn btn-alt waves-effect teal-text  waves-teal top5px" >Find Restaurants</a>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<!--- modal ends here ----->
<style>
    .help-block{
        color : rgb(251,0,7);
    }
    .error{
        color : rgb(251,0,7);
    }
    .dropdown.dropContent ul.city2 {
        width: 81.2%;
    }
    .dropdown.dropContent div.city1::after {
        right: 14%;
        top: 40%;
    }
    .dropdown.dropContent div.location1::after {
        right: 14%;
        bottom: 40%;
    }
    .city1, .location1 {
        color: rgba(0,0,0,0.7);
    }
    /*    body .lean-overlay:last-child {
            display: none !important;*/

</style>
