<div id="page-title">
    <h2>Grocery Reviews</h2>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="panel">
            <div class="panel-body">
                <h3 class="title-hero">Grocery Reviews</h3>
                <div class="example-box-wrapper">
                    <table class="table table-striped table-bordered responsive no-wrap datatable-responsive" cellspacing="0" width="100%">
                        <thead>
                            <tr>
                                <th>S.No. </th> 
                                <th> Grocery Name</th>
                                <th> User Name </th>
                                <th> Email</th>                              
                                <th> Rating </th>
                                <th> Details</th>
                                <th> Review Date </th>
                                <th> Status </th>
                                <th> Action </th>
                                <th>Delete</th>

                            </tr>
                        </thead>
                        <tfoot>
                            <tr>
                                <th>S.No. </th>                                                           
                                <th> Grocery Name</th>
                                <th> User Name </th>
                                <th> Email</th>
                                <th> Rating </th>
                                <th> Details</th>
                                <th> Review Date </th>
                                <th> Status </th>
                                <th> Action </th>
                                <th>Delete</th>
                            </tr>
                        </tfoot>
                        <tbody>

                            <?php
                            if (isset($this->groceryReviews)) {
                                $i = 1;
                                foreach ($this->groceryReviews as $value) {
                                    ?>

                                    <tr>
                                        <td><?php echo $i; ?></td>
                                        <td><?php echo $value['Grocery_name']; ?></td>
                                        <td><?php echo $value['uname']; ?></td>
                                        <td><?php echo $value['email']; ?></td>                                     
                                        <td><?php echo $value['review_rating']; ?></td>
                                        <td><?php echo $value['review_description']; ?></td>
                                        <td><?php echo date("j F , Y h:i:s A", strtotime($value['review_date'])); ?></td>
                                        <?php if ($value['review_status'] == 1): ?>
                                            <td id="activereview_<?php echo $value['review_id']; ?>" class="reviewactive">Active</td>
                                            <td class="center"><a style="cursor:pointer"  id="<?php
                                if (isset($value['review_id'])): echo "review_" . $value['review_id'];
                                endif;
                                            ?>" class="reviewdeactive">
                                                    <span id="activeclass_<?php echo $value['review_id']; ?>" class="bs-label label-danger">Deactivate</span></a></td>
                                        <?php else: ?>
                                            <td id="activereview_<?php echo $value['review_id']; ?>" class="reviewdeactive">Suspended</td>
                                            <td class="center" ><a style="cursor:pointer" id="<?php
                                if (isset($value['review_id'])): echo "review_" . $value['review_id'];
                                endif;
                                            ?>" class="reviewactive">
                                                    <span id="activeclass_<?php echo $value['review_id']; ?>"  class="bs-label label-success">Activate</span></a></td>
                                        <?php endif; ?> 


                                        <td class="text-center">                                               
                                            <a href="javascript:;" id="<?php echo "reviewdelete_" . $value['review_id']; ?>" class="btn btn-default deletereview"><i class="glyph-icon icon-linecons-trash"></i></a>
                                        </td>
                                    </tr>
                                    <?php
                                    $i++;
                                }
                            }
                            ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>


