<main class="page-content">
    <section class="signup">
        <div class="parallax-container min-h-640 h-auto">
            <div class="parallax"><img src="assets/images/gallery/image-8.jpg" class="responsive-img"></div>
            <div class="parallax-content p-top-64">
                <div class="container">
                    <div class="row">
                        <div class="col s12 m10 offset-m1 l8 offset-l2">
                             <div class="signupContent m-bot-25">
                                 <a href="index.html" class="signup-home-btn waves-teal waves-effect"><span><i class="fa fa-2x fa-home"></i></span></a>
                                 <h3 class="section-title white-text">Signup</h3>
                                 <div class="row m-top-md">
                                     <div class="col s12">
                                         <ul class="signup-social-list">
                                             <li>
                                                 <button class="btn waves-effect waves-light btn-facebook">
                                                     <span><i class="fa fa-facebook"></i></span>
                                                     Facebook
                                                 </button>
                                             </li>
                                             <li>
                                                 <button class="btn waves-effect waves-light btn-twitter">
                                                     <span><i class="fa fa-twitter"></i></span>
                                                     Twitter
                                                 </button>
                                             </li>
                                         </ul>
                                     </div>
                                     <div class="col s12">
                                         <div class="row">
                                             <form class="col s12 signupForm" method="POST">
                                                 <div class="row">
                                                     <div class="input-field col s12">
                                                         <input type="text" id="fullName" name="name" class="validate">
                                                         <label for="fullName">User Name</label>
                                                     </div>
                                                 </div>
                                                 <div class="row">
                                                     <div class="input-field col s12">
                                                         <input type="email" name="email" id="userEmail" class="validate">
                                                         <label for="userEmail">Email Address</label>
                                                     </div>
                                                 </div>
                                                 <div class="row">
                                                     <div class="input-field col s12">
                                                         <input type="password" id="userPassword" name="password" class="validate">
                                                         <label for="userPassword">Password</label>
                                                     </div>
                                                 </div>
                                                 <div class="row">
                                                     <div class="col s12">
                                                         <p class="center">
                                                             <input type="checkbox" class="filled-in" value="on" name="agreeterms" id="aggrement" checked="checked" />
                                                             <label for="aggrement" class="white-text">I agree <a href="#">Terms & Conditions</a></label>
                                                         </p>
                                                     </div>
                                                 </div>
                                                 <div class="row">
                                                     <div class="col s12 center">
                                                         <button type="submit" class="btn waves-light waves-effect">Signup</button>
                                                     </div>
                                                 </div>
                                                 <div class="row">
                                                     <div class="col s12">
                                                         <p class="center white-text">
                                                             Existing User? <a class="modal-trigger" href="#loginModal">Login</a>
                                                         </p>
                                                     </div>
                                                 </div>
                                             </form>
                                         </div>
                                     </div>
                                 </div>
                             </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</main>