<div id="page-title">
    <h2>View/Edit Product</h2>
    <p>The most complete user interface framework that can be used to create stunning admin dashboards and presentation websites.</p>
</div>
<div class="row">
    <div class="col-md-12">
        <form class="form-horizontal bordered-row" enctype="multipart/form-data" method="POST">
            <div class="row">
                <div class="col-md-6">
                    <div class="panel">
                        <div class="panel-body">
                            <div class="example-box-wrapper">
                                <table class="table table-responsive">
                                    <tbody>
                                        <tr>
                                            <td>
                                                <label class="control-label">Product Name</label>
                                            </td>
                                            <td>
                                                <input type="text" class="form-control" name="name" value="" placeholder="" required />
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <label class="control-label">Product Description</label>
                                            </td>
                                            <td>
                                                <textarea class="form-control" name="prod_desc" value="" placeholder="" required><?php echo $this->allproductdetails['prod_desc'] ?></textarea>
                                            </td>
                                        </tr>
                                        <!--added by sowmya 18 march 2016-->
                                        <tr class="show-agent">
                                            <td>
                                                <label class="control-label">Agent Name</label>
                                            </td>
                                            <td>
                                                <select class="js-example-responsive form-control" name="agent_id"  id="agent_id" style="width:100%;">
                                                    <option disabled selected>Select Agent</option>
                                                    <?php foreach ($this->agentlist as $value) { ?>
                                                        <option value="<?php echo $value['agent_id'] ?>">
                                                            <?php echo $value['loginname'] ?>
                                                        </option>
                                                    <?php } ?>
                                                </select>
                                            </td>
                                        </tr>
                                        <tr class="show-hotel">
                                            <td>
                                                <label class="control-label">Hotel Name </label>
                                            </td>
                                            <td>
                                                <select class="js-example-responsive form-control" name="hotel_id" id="hotel_id" style="width:100%;" >
                                                    <option disabled selected>Select Hotel</option>
                                                    <?php // foreach ($this->hotelslist as $value) { ?>
<!--                                                        <option value="<?php // echo $value['agent_id'] ?>">-->
                                                    <?php //echo $value['hotel_name'] ?>
                                                    <!--                                                        </option>-->
                                                    <?php //} ?>
                                                </select>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <label class="control-label">Item Type</label>
                                            </td>
                                            <td>
                                                <label class="radio-inline">
                                                    <input type="radio" value="1"  name="item_type"  id=""> Hotel Items
                                                </label>
                                                <label class="radio-inline">
                                                    <input type="radio" value="2" name="item_type"  id=""> Grocerry Items
                                                </label>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <label class="control-label">Product Type</label>
                                            </td>
                                            <td>
                                                <label class="radio-inline">
                                                    <input type="radio" value="1" name="product_type"  id="type_category" /> Category
                                                </label>
                                                <label class="radio-inline">
                                                    <input type="radio" value="2"  name="product_type1"  id="type_cusine" /> Cusine
                                                </label>

                                            </td>
                                        </tr>
                                        <tr class="show-cusine">
                                            <td> Cusine : </td>
                                            <td>
                                                <select class="js-example-responsive form-control" id="cuisine" name="cusine_id" style="width:100%;">
                                                    <option disabled selected>Select Cusine</option>

                                                </select>
                                            </td>
                                        </tr>
                                        <tr class="show-category">
                                            <td> Category : </td>
                                            <td>
                                                <select class="js-example-responsive form-control"  id="category" name="category_id" style="width:100%;">
                                                    <option disabled selected>Select Category</option>

                                                </select>
                                            </td>
                                        </tr>

                                        <tr>
                                            <td>
                                                <label class="control-label">Product status</label>
                                            </td>
                                            <td>
                                                <select  class="js-example-responsive js-example-basic-hide-search form-control" name="prod_status"> 
                                                    <option value="1">
                                                        Active 
                                                    </option>
                                                    <option value="2">
                                                        Deactive 
                                                    </option>
                                                </select>
                                            </td>

                                        </tr>
                                        <tr>
                                            <td>
                                                <label class="control-label">Cost</label>
                                            </td>
                                            <td>
                                                <div class="input-group">
                                                    <span class="input-group-addon addon-inside bg-black">
                                                        <i class="glyph-icon icon-dollar"></i>
                                                    </span>
                                                    <input type="text" placeholder=""  name="cost" value="" class="form-control" />
                                                </div>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <label class="control-label">Delivery Timing</label>
                                            </td>
                                            <td>
                                                <div class="input-group">
                                                    <span class="input-group-addon addon-inside bg-black">
                                                        <i class="glyph-icon icon-clock-o"></i>
                                                    </span>
                                                    <input type="text" placeholder="" name="delivery_time" value="" class="form-control" />
                                                    <span class="input-group-addon">mins</span>
                                                </div>
                                            </td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="panel">
                        <div class="panel-body">
                            <div class="example-box-wrapper">
                                <table class="table table-responsive">
                                    <tbody>
                                        <tr>
                                            <td>
                                                <label class="control-label">Discount Type</label>
                                            </td>
                                            <td>
                                                <label class="radio-inline">
                                                    <input type="radio" value="1"  name="product_discount_type"  id=""> Percentage
                                                </label>
                                                <label class="radio-inline">
                                                    <input type="radio" value="2" name="product_discount_type"  id=""> Amount
                                                </label>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <label class="control-label">Discount</label>
                                            </td>
                                            <td>
                                                <input type="text" class="form-control" name="product_discount" value="" id="" placeholder="" required />
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <label class="control-label">Service Tax</label>
                                            </td>
                                            <td>
                                                <input type="text" class="form-control" name="servicetax" value="" id="" placeholder="" required />
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <label class="control-label">Product Image</label>
                                            </td>
                                            <td>
                                                <div class="fileinput fileinput-new" data-provides="fileinput">
                                                    <div class="fileinput-new thumbnail" style="width: 200px; height: 150px;">
                                                        <img src="http://placehold.it/200x150" alt="">
                                                    </div>
                                                    <div class="fileinput-preview fileinput-exists thumbnail" style="max-width: 200px; max-height: 150px;"></div>
                                                    <div>
                                                        <span class="btn btn-default btn-file">
                                                            <span class="fileinput-new">Select Image</span>
                                                            <span class="fileinput-exists">Replace</span>
                                                            <input type="file" name="fileToUpload">
                                                        </span>
                                                        <a href="#" class="btn btn-danger fileinput-exists" data-dismiss="fileinput">Remove</a>
                                                    </div>
                                                </div>
                                            </td>
                                        </tr>
                                    </tbody>
                                </table>
                                <div class="form-group pull-right">
                                    <button type="submit" class="btn btn-alt btn-hover btn-primary">
                                        <span>SAVE</span> <i class="glyph-icon icon-arrow-right"></i>
                                        <div class="ripple-wrapper"></div>
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>


<style>
    .show-cusine, .show-category {
        display: none;
    }
</style>