<?php
$cuisinesdDetails = $this->cuisineslist;
$categoryDetails = $this->categorylist;
?>
<div id="page-title">
    <h2>Edit Product Details</h2>
</div>
<div class="row">
    <div class="col-md-12">
        <form class="form-horizontal bordered-row" enctype="multipart/form-data" method="POST">
            <div class="row">
                <div class="col-md-6">
                    <div class="panel">
                        <div class="panel-body">
                            <div class="example-box-wrapper">
                                <table class="table table-responsive">
                                    <tbody>
                                        <tr>
                                            <td>
                                                <label class="control-label">Product Name</label>
                                            </td>
                                            <td>
                                                <input type="text" class="form-control" name="name" value="<?php echo $this->allproductdetails['name'] ?>" placeholder="" required />
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <label class="control-label">Product Description</label>
                                            </td>
                                            <td>
                                                <textarea class="form-control" name="prod_desc" value="<?php echo $this->allproductdetails['prod_desc'] ?>" placeholder="" required><?php echo $this->allproductdetails['prod_desc'] ?></textarea>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <label class="control-label">Agent Name</label>
                                            </td>
                                            <td>
                                                <input type="text" class="form-control" disabled="" name="" value="<?php echo $this->allproductdetails['loginname'] ?>" placeholder="" required />
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <label class="control-label">Hotel Name</label>
                                            </td>
                                            <td>
                                                <input type="text" class="form-control" disabled="" name="" value="<?php echo $this->allproductdetails['hotel_name'] ?>" placeholder="" required />
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <label class="control-label">Item Type</label>
                                            </td>
                                            <td>
                                                <label class="radio-inline">
                                                    <input type="radio" value="1" name="item_type" <?php
                                                    if (isset($this->allproductdetails['item_type'])) {
                                                        echo"checked";
                                                    }
                                                    ?> id=""> Hotel Items
                                                </label>
                                                <label class="radio-inline">
                                                    <input type="radio" value="2" name="item_type" <?php
                                                    if (isset($this->allproductdetails['item_type'])) {
                                                        echo"checked";
                                                    }
                                                    ?> id=""> Grocery Items
                                                </label>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <label class="control-label">Product Type</label>
                                            </td>
                                            <td>
                                                <label class="radio-inline">
                                                    <input type="radio" value="1" name="product_type"<?php
                                                    if (isset($this->allproductdetails['prod_type'])) {
                                                        echo"checked";
                                                    }
                                                    ?>  id="type_category" /> Category
                                                </label>
                                                <label class="radio-inline">
                                                    <input type="radio" value="2"  name="product_type1" <?php
                                                    if (isset($this->allproductdetails['prod_type'])) {
                                                        echo"checked";
                                                    }
                                                    ?> id="type_cusine" /> Cuisine
                                                </label>

                                            </td>
                                        </tr>
                                        <tr class="show-cusine">
                                            <td>  <label class="control-label">Cuisine :</label> </td>
                                            <td>
                                                <select class="js-example-responsive form-control" id="cuisine" name="cusine_id" style="width:100%;">

                                                        <?php foreach ($cuisinesdDetails as $value) { ?>
                                                        <option value="<?php echo $value['cuisine_id'] ?>">
                                                        <?php echo $value['Cuisine_name'] ?>
                                                        </option>
                                                    <?php }
                                                    ?>
                                                </select>
                                            </td>
                                        </tr>
                                        <tr class="show-category">
                                            <td> <label class="control-label"> Category : </label></td>
                                            <td>
                                                <select class="js-example-responsive form-control"  id="category" name="category_id" style="width:100%;">
                                                        <?php foreach ($categoryDetails as $value) { ?>
                                                        <option value="<?php echo $value['category_id'] ?>">
                                                        <?php echo $value['cat_name'] ?>
                                                        </option>
                                                    <?php }
                                                    ?>
                                                </select>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <label class="control-label">Cost</label>
                                            </td>
                                            <td>
                                                <div class="input-group">
                                                    <span class="input-group-addon addon-inside bg-black">
                                                        <i class="glyph-icon icon-dollar"></i>
                                                    </span>
                                                    <input type="text" placeholder=""  name="cost" value="<?php echo $this->allproductdetails['cost'] ?>" class="form-control" />
                                                </div>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <label class="control-label">Product status</label>
                                            </td>
                                            <td>
                                                <select  class="js-example-responsive js-example-basic-hide-search form-control" name="prod_status"> 
                                                    <option value="1" <?php
                                                    if ($this->allproductdetails['prod_status'] == 1) {
                                                        echo"checked";
                                                    }
                                                    ?>>
                                                        Active 
                                                    </option>
                                                    <option value="2" <?php
                                                    if ($this->allproductdetails['prod_status'] == 2) {
                                                        echo"checked";
                                                    }
                                                    ?>>
                                                        Inactive
                                                    </option>
                                                </select>
                                            </td>

                                        </tr>
                                        <tr>
                                            <td>
                                                <label class="control-label">Delivery Timing</label>
                                            </td>
                                            <td>
                                                <div class="input-group">
                                                    <span class="input-group-addon addon-inside bg-black">
                                                        <i class="glyph-icon icon-clock-o"></i>
                                                    </span>
                                                    <input type="text" placeholder="" name="delivery_time" value="<?php echo $this->allproductdetails['delivery_time'] ?>" class="form-control" />
                                                    <span class="input-group-addon">mins</span>
                                                </div>
                                            </td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="panel">
                        <div class="panel-body">
                            <div class="example-box-wrapper">
                                <table class="table table-responsive">
                                    <tbody>
                                        <tr>
                                            <td>
                                                <label class="control-label">Discount Type</label>
                                            </td>
                                            <td>
                                                <label class="radio-inline">
                                                    <input type="radio" value="1"  name="product_discount_type" <?php
                                                    if (isset($this->allproductdetails['product_discount_type'])) {
                                                        echo"checked";
                                                    }
                                                    ?> id=""> Percentage
                                                </label>
                                                <label class="radio-inline">
                                                    <input type="radio" value="2" name="product_discount_type" <?php
                                                    if (isset($this->allproductdetails['product_discount_type'])) {
                                                        echo"checked";
                                                    }
                                                    ?> id=""> Amount
                                                </label>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <label class="control-label">Discount</label>
                                            </td>
                                            <td>
                                                <input type="text" class="form-control" name="product_discount" value="<?php echo $this->allproductdetails['product_discount'] ?>" id="" placeholder="" required />
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <label class="control-label">Service Tax</label>
                                            </td>
                                            <td>
                                                <input type="text" class="form-control" name="servicetax" value="<?php echo $this->allproductdetails['servicetax'] ?>" id="" placeholder="" required />
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <label class="control-label">Product Image</label>
                                            </td>
                                            <td>
                                                <div class="fileinput fileinput-new" data-provides="fileinput">
                                                    <div class="fileinput-new thumbnail" style="width: 200px; height: 150px;">
                                                        <img src="<?php echo $this->allproductdetails['imagelink'] ?>" alt="">
                                                    </div>
                                                    <div class="fileinput-preview fileinput-exists thumbnail" style="max-width: 200px; max-height: 150px;"></div>
                                                    <div>
                                                        <span class="btn btn-default btn-file">
                                                            <span class="fileinput-new">Replace</span>
                                                            <span class="fileinput-exists">Replace</span>
                                                            <input type="file" name="fileToUpload">
                                                        </span>
                                                        <a href="#" class="btn btn-danger fileinput-exists" data-dismiss="fileinput">Remove</a>
                                                    </div>
                                                </div>
                                            </td>
                                        </tr>
                                    </tbody>
                                </table>
                                <div class="form-group pull-right">
                                    <button type="submit" class="btn btn-alt btn-hover btn-primary">
                                        <span>SAVE</span> <i class="glyph-icon icon-arrow-right"></i>
                                        <div class="ripple-wrapper"></div>
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

<!--<style>
    .show-cusine, .show-category,.addeddate {
        display: none;
    }
</style>-->

<!--<script>
     $(document).ready(function() {
        $(document.body).on('click', '.show-category', function() {
e.preventDefault();
        var obj = $(this);
        var selectedProjectName = obj.parents('tr').find("#category").attr('category_id');
        console.log(selectedProjectName);
      
    });
    });
    </script>-->