                                            
<div id="page-title">
    <h2>Product Details</h2>
    <p>The most complete user interface framework that can be used to create stunning admin dashboards and presentation websites.</p>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="panel">
            <div class="panel-body">
                <h3 class="title-hero">Filter Products By Hotel</h3>
                <div class="example-box-wrapper">
                    <div class="row">
                        <div class="col-md-10 col-md-offset-1">
                            <form class="form-horizontal bordered-row" method="POST">
                                <div class="form-group">
                                    <label class="col-sm-3 control-label">Choose the Hotel</label>
                                    <div class="col-sm-9">
                                        <select class="js-example-responsive form-control" name="hotelname" style="width:100%;">
                                            <option disabled selected>Select Hotel</option>
                                              <?php foreach ($this->hotelslist as $value) { ?>
                                                <option value="<?php echo $value['id'] ?>">
                                                    <?php echo $value['hotel_name'] ?>
                                                </option>
                                            <?php } ?>
                                        </select>
                                    </div>
                                </div>
                               
                            <div class="form-group pull-right">
                                    <button  type="submit"class="btn btn-alt btn-hover btn-primary">
                                        <span>CHECK</span> <i class="glyph-icon icon-arrow-right"></i>
                                        <div class="ripple-wrapper"></div>
                                    </button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="panel">
            <div class="panel-body">
                <h3 class="title-hero">View/Edit/Remove Products</h3>
                <div class="example-box-wrapper">
                     <table class="table table-striped table-bordered responsive no-wrap datatable-responsive" cellspacing="0" width="100%">
                        <thead>
                            <tr>
                                <th> Product Name </th>
                                <th> Hotel Name </th>
                                <th> Cost(&#36;) </th>
                                <th> Discount </th>
                                <th> Delivery Time(mins) </th>
                                <th> Status </th>
                                <th> Action </th>
                                 <th> View/Delete</th>
                                 
                            </tr>
                        </thead>
                        <tfoot>
                            <tr>
                                <th> Product Name </th>
                                <th> Hotel Name </th>
                                <th> Cost(&#36;) </th>
                                <th> Discount </th>
                                <th> Delivery Time(mins) </th>
                                <th> Status </th>
                                <th> Action </th>
                                <th> View/Delete </th>
                               
                            </tr>
                        </tfoot>
                        <tbody>
                           
                            <?php
                            
                             if(isset($this->productsbyhotels)){
                               
                                foreach ($this->productsbyhotels as $val) { ?>
                                 
                             <tr>
                                        <td><?php echo $val['name']; ?></td>
                                        <td><?php echo $val['hotel_name']; ?></td>
                                        <td><?php echo $val['cost']; ?></td>
                                        <td><?php echo $val['product_discount']; ?></td>
                                        <td><?php echo $val['delivery_time']; ?></td>
                                            <?php if ($val['prod_status'] == 1): ?>
                                            <td id="activeproduct_<?php echo $val['product_id']; ?>" class="productactive">Active</td>
                                            <td class="center"><a style="cursor:pointer"  id="<?php
                                    if (isset($val['product_id'])): echo "product_" . $val['product_id'];
                                    endif;
                                    ?>" class="productdeactive">
                                                    <span id="activeclass_<?php echo $val['product_id']; ?>" class="bs-label label-danger">Deactivate</span></a></td>
                                            <?php else: ?>
                                            <td id="activeproduct_<?php echo $val['product_id']; ?>" class="productdeactive">Suspended</td>
                                            <td class="center" ><a style="cursor:pointer" id="<?php
                                            if (isset($val['product_id'])): echo "product_" . $val['product_id'];
                                            endif;
                                            ?>" class="productactive">
                                                    <span id="activeclass_<?php echo $val['product_id']; ?>"  class="bs-label label-success">Activate</span></a></td>
        <?php endif; ?> 


                                        <td class="text-center">
                                            <a href="/admin/edit-product-details/<?php echo $val['product_id'];?>" class="btn btn-default"><i class="glyph-icon icon-linecons-eye"></i></a>
                                            <a href="javascript:;" id="<?php echo "productdelete_" . $val['product_id']; ?>" class="btn btn-default deleteproduct"><i class="glyph-icon icon-linecons-trash"></i></a>
                                        </td>
                                    </tr>
                             <?php }
                             } else{ if ($this->productdetails) {
                                foreach ($this->productdetails as $value) {
                                    ?>

                                    <tr>
                                        <td><?php echo $value['name']; ?></td>
                                        <td><?php echo $value['hotel_name']; ?></td>
                                        <td><?php echo $value['cost']; ?></td>
                                        <td><?php echo $value['product_discount']; ?></td>
                                        <td><?php echo $value['delivery_time']; ?></td>
                                            <?php if ($value['prod_status'] == 1): ?>
                                            <td id="activeproduct_<?php echo $value['product_id']; ?>" class="productactive">Active</td>
                                            <td class="center"><a style="cursor:pointer"  id="<?php
                                    if (isset($value['product_id'])): echo "product_" . $value['product_id'];
                                    endif;
                                    ?>" class="productdeactive">
                                                    <span id="activeclass_<?php echo $value['product_id']; ?>" class="bs-label label-danger">Deactivate</span></a></td>
                                            <?php else: ?>
                                            <td id="activeproduct_<?php echo $value['product_id']; ?>" class="productdeactive">Suspended</td>
                                            <td class="center" ><a style="cursor:pointer" id="<?php
                                            if (isset($value['product_id'])): echo "product_" . $value['product_id'];
                                            endif;
                                            ?>" class="productactive">
                                                    <span id="activeclass_<?php echo $value['product_id']; ?>"  class="bs-label label-success">Activate</span></a></td>
        <?php endif; ?> 


                                        <td class="text-center">
                                            <a href="/admin/edit-product-details/<?php echo $value['product_id'];?>" class="btn btn-default"><i class="glyph-icon icon-linecons-eye"></i></a>
                                            <a href="javascript:;" id="<?php echo "productdelete_" . $value['product_id']; ?>" class="btn btn-default deleteproduct"><i class="glyph-icon icon-linecons-trash"></i></a>
                                        </td>
                                    </tr>

    <?php }
                             } } ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
