<?php //echo "<pre>"; print_r($this->allproductdetails);die; ?>
<div id="page-title">
    <h2>View store Product Details</h2>
</div>
<div class="row">
    <div class="col-md-12">
        <form class="form-horizontal bordered-row" enctype="multipart/form-data" method="POST">
            <div class="row">
                <div class="col-md-6">
                    <div class="panel">
                        <div class="panel-body">
                            <div class="example-box-wrapper">
                                <table class="table table-responsive">
                                    <tbody>
                                        <tr>
                                            <td>
                                                <label class="control-label">Product ID</label>
                                            </td>
                                            <td>
                                                <?php echo $this->allproductdetails['product_id'] ?>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <label class="control-label">Product Name</label>
                                            </td>
                                            <td>
                                                <?php echo $this->allproductdetails['name'] ?>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <label class="control-label">Product Description</label>
                                            </td>
                                            <td>
                                                <?php echo $this->allproductdetails['prod_desc'] ?>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <label class="control-label">Agent Name</label>
                                            </td>
                                            <td>
                                                <?php echo $this->allproductdetails['loginname'] ?>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <label class="control-label">store Name</label>
                                            </td>
                                            <td>
                                                <?php echo $this->allproductdetails['store_name'] ?>
                                        </tr>

                                        <tr>
                                        <tr class="show-category">
                                            <td> <label class="control-label"> Category : </label></td>
                                            <td>
                                                <?php echo $this->allproductdetails['cat_name'] ?>
                                            </td>
                                        </tr>

                                        <tr>
                                            <td>
                                                <label class="control-label">Stock Quantity</label>
                                            </td>
                                            <td>                                  
                                                <?php echo $this->allproductdetails['stock_quantity'] ?>

                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <label class="control-label">Cost</label>
                                            </td>
                                            <td>
                                                <div class="input-group">
                                                    $<?php echo $this->allproductdetails['cost'] ?>
                                                </div>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <label class="control-label">Product status</label>
                                            </td>
                                            <td>
                                                <?php
                                                if ($this->allproductdetails['prod_status'] == 1) {
                                                    echo"Active";
                                                } else {
                                                    echo"Deactivate";
                                                }
                                                ?>
                                            </td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="panel">
                        <div class="panel-body">
                            <div class="example-box-wrapper">
                                <table class="table table-responsive">
                                    <tbody>

                                        <tr>
                                            <td>
                                                <label class="control-label">Delivery Timing</label>
                                            </td>
                                            <td>
                                                <div class="input-group">                                              
                                                    <?php echo $this->allproductdetails['delivery_time'] ?>
                                                    min
                                                </div>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <label class="control-label">Discount Type</label>
                                            </td>
                                            <td>
                                                <?php
                                                if ($this->allproductdetails['product_discount_type'] == 1) {
                                                    echo"Percentage";
                                                } else {
                                                    echo"Amount";
                                                }
                                                ?>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <label class="control-label">Discount</label>
                                            </td>
                                            <td>
                                                <?php echo $this->allproductdetails['product_discount'] ?>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <label class="control-label">Service Tax</label>
                                            </td>
                                            <td>
                                                <?php echo $this->allproductdetails['servicetax'] ?>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <label class="control-label">Product Image</label>
                                            </td>
                                            <td>
                                                <div class="fileinput fileinput-new" data-provides="fileinput">
                                                    <div class="fileinput-new thumbnail" style="width: 200px; height: 150px;">
                                                        <img src="<?php echo $this->allproductdetails['imagelink'] ?>" alt="<?php echo $this->allproductdetails['imagelink'] ?>">
                                                    </div>
                                                    <div class="fileinput-preview fileinput-exists thumbnail" style="max-width: 200px; max-height: 150px;"></div>

                                                </div>
                                            </td>
                                        </tr>
                                    </tbody>
                                </table>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

