
<div id="content" class="content">
    <!-- begin breadcrumb -->
    <ol class="breadcrumb pull-right">
        <li><a href="javascript:;">Home</a></li>
        <li><a href="javascript:;">Payment Details</a></li>
        <li class="active"><a href="/agent/agent-payment-details">Agent Payment Details</a></li>
    </ol>
    <!-- end breadcrumb -->
    <!-- begin page-header -->
    <h1 class="page-header">Agent Payment Details </h1>
    <!-- end page-header -->

    <!-- begin row -->
    <div class="row">
        <!-- begin col-12 -->
        <div class="col-md-12">       
            <div class="panel pagination-theme clearfix m-b-0">
                <table id="data-table" data-order='[[1,"asc"]]' class="table table-bordered table-hover">
                    <thead>
                        <tr>
                            <th class="success-emphasis-dark">S. No.</th>
                            <th class="success-emphasis-dark">Trans. ID</th>                                                                                                               
                            <th class="success-emphasis-dark">Transaction Type</th>
                            <th class="success-emphasis-dark">Transaction Amount</th>
                            <th class="success-emphasis-dark">Transaction Code </th>
                            <th class="success-emphasis-dark">Transaction Date </th>
                            <th class="success-emphasis-dark">Transaction status </th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php
                        if ($this->transactiondetails) {

                            $i = 1;
                            foreach ($this->transactiondetails as $value) {
                                ?>

                                <tr class="odd gradeX" id="<?php echo $value['agent_tx_id']; ?>" data-prod = "<?php echo $value['agent_tx_id']; ?>">
                                    <td><strong><?php echo $i; ?></strong></td>
                                    <td><strong><?php echo $value['agent_tx_id']; ?></strong></td>                                   
                                    <?php
                                    if (isset($value['tx_type'])) {
                                        if ($value['tx_type'] == 1) {
                                            ?>
                                            <td><strong>COD</strong></td>     
                                        <?php } else if ($value['tx_type'] == 2) { ?>
                                            <td><strong>Paypal</strong></td> 
                                        <?php } else { ?>                                                    
                                            <td><strong>Cheque</strong></td> 
                                        <?php } ?>
                                        <td><strong><?php echo $value['tx_amount']; ?></strong></td>
                                        <td><strong><?php echo $value['tx_code']; ?></strong></td>
                                        <td><strong><?php echo $value['tx_date']; ?></strong></td>
                                        <?php
                                        if (isset($value['tx_status'])) {
                                            if ($value['tx_status'] == 1) {
                                                ?>
                                                <td><strong>Success</strong></td>     
                                            <?php } else if ($value['tx_status'] == 2) { ?>
                                                <td><strong>Pending</strong></td> 
                                            <?php } else if ($value['tx_status'] == 3) { ?>

                                                <td><strong>Failed</strong></td
                                            <?php } else if ($value['tx_status'] == 4) { ?>

                                                <td><strong>Canceled</strong></td
                                                <?php
                                            }
                                        } else {
                                            ?>
                                            <td><strong>Unknown</strong></td>  

                                        <?php } ?>
                                        <?php
                                        $i++;
                                    }
                                }
                            }
                            ?>
                    </tbody>

                </table>
            </div>

        </div>
    </div>
</div>






