<?php
$allorderdetailsArray = $this->orderdetails;
?>
<div id="page-title">
    <h2>View Order Details</h2>
    <p>The most complete user interface framework that can be used to create stunning admin dashboards and presentation websites.</p>
</div>
<div class="row">
    <div class="col-md-12">
        <form class="form-horizontal bordered-row" enctype="multipart/form-data" method="POST">
            <div class="row">
                <div class="col-md-6">
                    <div class="panel">
                        <div class="panel-body">
                            <div class="example-box-wrapper">
                                <table class="table table-responsive">
                                    <tbody>
                                        <tr>
                                            <td>
                                                <label class="control-label">User Name</label>
                                            </td>
                                            <td>
                                                <?php echo $allorderdetailsArray['uname'] ?>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <label class="control-label">User Email</label>
                                            </td>
                                            <td>
                                                <?php echo $allorderdetailsArray['email'] ?>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <label class="control-label">Hotel Name</label>
                                            </td>
                                            <td>
                                                <?php echo $allorderdetailsArray['hotel_name'] ?>

                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <label class="control-label">Product Name</label>
                                            </td>
                                            <td>
                                                <?php echo $allorderdetailsArray['name'] ?>

                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <label class="control-label">Product Amount</label>
                                            </td>
                                            <td>
                                                <?php echo $allorderdetailsArray['product_amount'] ?>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <label class="control-label">Quantity</label>
                                            </td>
                                            <td>
                                                <?php echo $allorderdetailsArray['quantity'] ?>
                                            </td>
                                        </tr>                                      
                                        <tr>
                                            <td>
                                                <label class="control-label">Pay Type</label>
                                            </td>
                                            <td>
                                                <?php
                                                if ($allorderdetailsArray['pay_type'] == 0) {
                                                    echo" COD";
                                                } else {
                                                    echo" Paypal";
                                                }
                                                ?>                                              

                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <label class="control-label">Pay Amount</label>
                                            </td>
                                            <td>
                                                <?php echo $allorderdetailsArray['total_amount'] ?>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <label class="control-label">Pay Status</label>
                                            </td>
                                            <td>
                                                <?php
                                                if ($allorderdetailsArray['pay_status'] == 0) {
                                                    echo"Pending";
                                                } elseif ($allorderdetailsArray['pay_status'] == 1) {
                                                    echo"Completed";
                                                } elseif ($allorderdetailsArray['pay_status'] == 2) {
                                                    echo" Failed";
                                                } else {
                                                    echo" COD";
                                                }
                                                ?>
                                            </td> 
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="panel">
                        <div class="panel-body">
                            <div class="example-box-wrapper">
                                <table class="table table-responsive">
                                    <tbody>                                          
                                        <tr>
                                            <td>
                                                <label class="control-label">Order Status</label>
                                            </td>
                                            <td>  
                                                <?php
                                                if ($allorderdetailsArray['order_status'] == 0) {
                                                    echo"selected";
                                                } elseif ($allorderdetailsArray['order_status'] == 1) {
                                                    echo"In Process";
                                                } elseif ($allorderdetailsArray['order_status'] == 2) {
                                                    echo"Delivered";
                                                } elseif ($allorderdetailsArray['order_status'] == 3) {
                                                    echo"Canceled ";
                                                }echo"Dispatch ";
                                                {
                                                    
                                                }
                                                ?>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <label class="control-label">Delivery Status</label>
                                            </td>
                                            <td>
                                                <?php
                                                if ($allorderdetailsArray['delivery_status'] == 0) {
                                                    echo"Pending";
                                                } elseif ($allorderdetailsArray['delivery_status'] == 1) {
                                                    echo"Return/Cancel";
                                                } elseif ($allorderdetailsArray['delivery_status'] == 1) {
                                                    echo"Unable to Reach";
                                                } else {
                                                    echo"Pick up";
                                                }
                                                ?>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <label class="control-label">Delivery Type</label>
                                            </td>
                                            <td> <?php
                                                if ($allorderdetailsArray['delivery_type'] == 0) {
                                                    echo" Delivery to address";
                                                } else {
                                                    echo"Pick up";
                                                }
                                                ?>                                                     
                                            </td>
                                        </tr>                                                                                                                                                  
                                        <tr>
                                            <td>
                                                <label class="control-label">Delivery  Charge</label>
                                            </td>
                                            <td>
<?php echo $allorderdetailsArray['delivery_charge'] ?>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <label class="control-label">User Message</label>
                                            </td>
                                            <td>
<?php echo $allorderdetailsArray['user_message'] ?>
                                            </td>
                                        </tr>                                     
                                    </tbody>
                                </table>                                 
                            </div>
                        </div>
                    </div>
                </div>
            </div>
    </div>
</form>
</div>
</div>


