<div id="page-title">
    <h2> Order Details</h2>   
</div>
<div class="row">
    <div class="col-md-12">
        <div class="panel">
            <div class="panel-body">
                <h3 class="title-hero">View/Remove Order Details</h3>
                <div class="example-box-wrapper" id="user-transaction">
                    <!-- Nav tabs -->
                    <ul class="nav nav-pills" role="tablist">
                        <li role="presentation" class="active">
                            <a href="#pending" aria-controls="pending" role="tab" data-toggle="tab">Pending</a>
                        </li>
                        <li role="presentation" >
                            <a href="#approvedbyadmin" aria-controls="approvedbyadmin" role="tab" data-toggle="tab">Approved</a>
                        </li>                    
                        <li role="presentation">
                            <a href="#cancelled" aria-controls="cancelled" role="tab" data-toggle="tab">Canceled</a>
                        </li>

                    </ul>

                    <!-- Tab panes -->
                    <div class="tab-content">
                        <div role="tabpanel" class="tab-pane fade in active" id="pending">
                            <h3 class="title-hero">Pending Orders</h3>
                            <table  class="table table-striped table-bordered responsive no-wrap datatable-responsive" cellspacing="0" width="100%">
                                <thead>
                                    <tr>
                                        <th>S.no</th>
                                        <th>Hotel Name</th>            
                                        <th>User Name</th>                                       
                                        <th>Pay Type</th>
                                        <th>Pay Amount</th>
                                        <th>Pay Status</th>
                                        <th>Order ID</th>
                                        <th>Order Date</th>
                                        <th>Order Status</th>                                        
                                        <th>Action</th>
                                        <th>View/Delete Order</th>
                                    </tr>
                                </thead>
                                <tfoot>
                                    <tr>
                                        <th>S.no</th>
                                        <th>Hotel Name</th>   
                                        <th>User Name</th>                                       
                                        <th>Pay Type</th>
                                        <th>Pay Amount</th>
                                        <th>Pay Status</th>
                                        <th>Order ID</th>
                                        <th>Order Date</th>
                                        <th>Order Status</th>                                        
                                        <th>Action</th>
                                        <th>View/Delete Order</th>
                                    </tr>
                                </tfoot>
                                <tbody>
                                    <?php
                                    if (isset($this->pendingStatus)) {
                                        $i = 1;
                                        foreach ($this->pendingStatus as $value) {
                                            if ($value['Hotel_Store'] == 1) {
                                                ?>
                                                <tr>
                                                    <td><?php echo $i; ?></td>
                                                    <td><?php echo $value['hotel_name']; ?></td>
                                                    <td><?php echo $value['uname']; ?></td>
                                                    <td><?php
                                                        if ($value['tx_type'] == 1) {
                                                            echo 'COD';
                                                        } else {
                                                            echo "PaYpaL";
                                                        }
                                                        ?></td>
                                                    <td><?php echo $value['total_amount']; ?></td>
                                                    <td><?php
                                                        if ($value['tx_status'] == 1) {
                                                            echo 'Success';
                                                        } else if ($value['tx_status'] == 2) {
                                                            echo 'Pending';
                                                        } else if ($value['tx_status'] == 3) {
                                                            echo 'Failed';
                                                        } else {
                                                            echo 'Canceled';
                                                        }
                                                        ?></td>
                                                    <td><?php echo $value['order_id']; ?></td>
                                                    <td><?php echo date("m/d/Y", strtotime($value['order_date'])); ?></td>
                                                    <td id="demo"><?php
                                                        if ($value['order_status'] == 0) {
                                                            echo 'Pending';
                                                        } else if ($value['order_status'] == 1) {
                                                            echo 'Approved';
                                                        } else if ($value['order_status'] == 6) {
                                                            echo 'Canceled';
                                                        }
                                                        ?></td>
                                                    <td class="trigger">  
                                                        <select  class="js-example-responsive js-example-basic-hide-search form-control order_status" data-id="<?php echo $value['order_id']; ?>" name="order_status"> 
                                                            <option value="0" <?php
                                                            if ($value['order_status'] == 0) {
                                                                echo"selected";
                                                            }
                                                            ?>>
                                                                Pending
                                                            </option>
                                                            <option value="1" <?php
                                                            if ($value['order_status'] == 1) {
                                                                echo"selected";
                                                            }
                                                            ?>>
                                                                Approved
                                                            </option>                                                     
                                                            <option value="6" <?php
                                                            if ($value['order_status'] == 6) {
                                                                echo"selected";
                                                            }
                                                            ?>>
                                                                Canceled 
                                                            </option>                                                     
                                                        </select>
                                                    </td>

                                                    <td class="text-center">
                                                        <a href="/admin/view-order-details/<?php echo $value['order_id']; ?>" class="btn btn-default"><i class="glyph-icon icon-linecons-eye"></i></a>
                                                        <a href="javascript:;" id="<?php echo "orderdelete_" . $value['order_id']; ?>" class="btn btn-default deleteorder"><i class="glyph-icon icon-linecons-trash"></i></a></td>
                                                </tr>   

                                                <?php
                                                $i++;
                                            }
                                        }
                                    }
                                    ?>
                                </tbody>
                            </table>
                        </div>
                        <div role="tabpanel" class="tab-pane fade " id="approvedbyadmin">
                            <h3 class="title-hero">Approved Orders</h3>
                            <table  class="table table-striped table-bordered responsive no-wrap datatable-responsive" cellspacing="0" width="100%">
                                <thead>
                                    <tr>
                                        <th>S.no</th>
                                        <th>Hotel Name</th>                
                                        <th>User Name</th>                                       
                                        <th>Pay Type</th>
                                        <th>Pay Amount</th>
                                        <th>Pay Status</th>
                                        <th>Order ID</th>
                                        <th>Order Date</th>
                                        <th>Order Status</th>                                        
                                        <th>Action</th>
                                        <th>View/Delete Order</th>
                                    </tr>
                                </thead>
                                <tfoot>
                                    <tr>
                                        <th>S.no</th>
                                        <th>Hotel Name</th>                
                                        <th>User Name</th>                                       
                                        <th>Pay Type</th>
                                        <th>Pay Amount</th>
                                        <th>Pay Status</th>
                                        <th>Order ID</th>
                                        <th>Order Date</th>
                                        <th>Order Status</th>                                        
                                        <th>Action</th>
                                        <th>View/Delete Order</th>

                                    </tr>
                                </tfoot>
                                <tbody>
                                    <?php
                                    if (isset($this->processStatus)) {
                                        $i = 1;
                                        foreach ($this->processStatus as $value) {
                                            if ($value['Hotel_Store'] == 1) {
                                                ?>
                                                <tr>
                                                    <td><?php echo $i; ?></td>
                                                    <td><?php echo $value['hotel_name']; ?></td>
                                                    <td><?php echo $value['uname']; ?></td>
                                                    <td><?php
                                                        if ($value['tx_type'] == 1) {
                                                            echo 'COD';
                                                        } else {
                                                            echo "PaYpaL";
                                                        }
                                                        ?></td>
                                                    <td><?php echo $value['total_amount']; ?></td>
                                                    <td><?php
                                                        if ($value['tx_status'] == 1) {
                                                            echo 'Success';
                                                        } else if ($value['tx_status'] == 2) {
                                                            echo 'Pending';
                                                        } else if ($value['tx_status'] == 3) {
                                                            echo 'Failed';
                                                        } else {
                                                            echo 'Canceled';
                                                        }
                                                        ?></td>
                                                    <td><?php echo $value['order_id']; ?></td>
                                                    <td><?php echo date("m/d/Y", strtotime($value['order_date'])); ?></td>
                                                    <td>Approved</td>
                                                    <td>  
                                                        <select  class="js-example-responsive js-example-basic-hide-search form-control order_status" data-id="<?php echo $value['order_id']; ?>" name="order_status"> 
                                                            <option value="0" <?php
                                                            if ($value['order_status'] == 0) {
                                                                echo"selected";
                                                            }
                                                            ?>>
                                                                Pending
                                                            </option>
                                                            <option value="1" <?php
                                                            if ($value['order_status'] == 1) {
                                                                echo"selected";
                                                            }
                                                            ?>>
                                                                Approved
                                                            </option>                                                     
                                                            <option value="6" <?php
                                                            if ($value['order_status'] == 6) {
                                                                echo"selected";
                                                            }
                                                            ?>>
                                                                Canceled 
                                                            </option>  
                                                        </select>
                                                    </td>    
                                                    <td class="text-center">
                                                        <a href="/admin/view-order-details/<?php echo $value['order_id']; ?>" class="btn btn-default"><i class="glyph-icon icon-linecons-eye"></i></a>
                                                        <a href="javascript:;" id="<?php echo "orderdelete_" . $value['order_id']; ?>" class="btn btn-default deleteorder"><i class="glyph-icon icon-linecons-trash"></i></a>
                                                    </td>
                                                </tr>   

                                                <?php
                                                $i++;
                                            }
                                        }
                                    }
                                    ?>

                                </tbody>
                            </table>
                        </div>

                        <div role="tabpanel" class="tab-pane fade" id="cancelled">
                            <h3 class="title-hero">Canceled Orders</h3>
                            <table  class="table table-striped table-bordered responsive no-wrap datatable-responsive" cellspacing="0" width="100%">
                                <thead>
                                    <tr>
                                        <th>S.no</th>
                                        <th>Hotel Name</th>                
                                        <th>User Name</th>                                       
                                        <th>Pay Type</th>
                                        <th>Pay Amount</th>
                                        <th>Pay Status</th>
                                        <th>Order ID</th>
                                        <th>Order Date</th>
                                        <th>Order Status</th>                                        
                                        <th>Action</th>
                                        <th>View/Delete Order</th>
                                    </tr>
                                </thead>
                                <tfoot>
                                    <tr>
                                        <th>S.no</th>
                                        <th>Hotel Name</th>                
                                        <th>User Name</th>                                       
                                        <th>Pay Type</th>
                                        <th>Pay Amount</th>
                                        <th>Pay Status</th>
                                        <th>Order ID</th>
                                        <th>Order Date</th>
                                        <th>Order Status</th>                                        
                                        <th>Action</th>
                                        <th>View/Delete Order</th>

                                    </tr>
                                </tfoot>
                                <tbody>
                                    <?php
                                    if (isset($this->canceledStatus)) {
                                        $i = 1;
                                        foreach ($this->canceledStatus as $value) {
                                            if ($value['Hotel_Store'] == 1) {
                                                ?>
                                                <tr>
                                                    <td><?php echo $i; ?></td>
                                                    <td><?php echo $value['hotel_name']; ?></td>
                                                    <td><?php echo $value['uname']; ?></td>
                                                    <td><?php
                                                        if ($value['tx_type'] == 1) {
                                                            echo 'COD';
                                                        } else {
                                                            echo "PaYpaL";
                                                        }
                                                        ?></td>
                                                    <td><?php echo $value['total_amount']; ?></td>
                                                    <td><?php
                                                        if ($value['tx_status'] == 1) {
                                                            echo 'Success';
                                                        } else if ($value['tx_status'] == 2) {
                                                            echo 'Pending';
                                                        } else if ($value['tx_status'] == 3) {
                                                            echo 'Failed';
                                                        } else {
                                                            echo 'Canceled';
                                                        }
                                                        ?></td>
                                                    <td><?php echo $value['order_id']; ?></td>
                                                    <td><?php echo date("m/d/Y", strtotime($value['order_date'])); ?></td>
                                                    <td>Canceled</td>
                                                    <td>  
                                                        <select  class="js-example-responsive js-example-basic-hide-search form-control order_status" data-id="<?php echo $value['order_id']; ?>" name="order_status"> 
                                                            <option value="0" <?php
                                                            if ($value['order_status'] == 0) {
                                                                echo"selected";
                                                            }
                                                            ?>>
                                                                Pending
                                                            </option>
                                                            <option value="1" <?php
                                                            if ($value['order_status'] == 1) {
                                                                echo"selected";
                                                            }
                                                            ?>>
                                                                Approved
                                                            </option>                                                     
                                                            <option value="6" <?php
                                                            if ($value['order_status'] == 6) {
                                                                echo"selected";
                                                            }
                                                            ?>>
                                                                Canceled 
                                                            </option>  
                                                        </select>
                                                    </td>
                                                    <td class="text-center">
                                                        <a href="/admin/view-order-details/<?php echo $value['order_id']; ?>" class="btn btn-default"><i class="glyph-icon icon-linecons-eye"></i></a>
                                                        <a href="javascript:;" id="<?php echo "orderdelete_" . $value['order_id']; ?>" class="btn btn-default deleteorder"><i class="glyph-icon icon-linecons-trash"></i></a></td>
                                                </tr>   

                                                <?php
                                                $i++;
                                            }
                                        }
                                    }
                                    ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    $('[data-toggle="tab"]').click(function(e) {
        e.preventDefault();
        $(this).parent().siblings().removeClass('active');
        $(this).parent().addClass('active');
        var id = $(this).attr('href');
        $(id).siblings().removeClass('in active');
        $(id).toggleClass('in active');
    });
</script>