
<div id="page-title">
    <h2> Order Details</h2>
    <p>The most complete user interface framework that can be used to create stunning admin dashboards and presentation websites.</p>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="panel">
            <div class="panel-body">
                <h3 class="title-hero">View/Edit/Remove Order Details</h3>
                <div class="example-box-wrapper" id="user-transaction">
                    <!-- Nav tabs -->
                    <ul class="nav nav-pills" role="tablist">
                        <li role="presentation" class="active">
                            <a href="#pending" aria-controls="pending" role="tab" data-toggle="tab">Pending</a>
                        </li>
                        <li role="presentation" >
                            <a href="#inprocess" aria-controls="inprocess" role="tab" data-toggle="tab">In Process</a>
                        </li>
                        <li role="presentation">
                            <a href="#dispatch" aria-controls="dispatch" role="tab" data-toggle="tab">Dispatch</a>
                        </li>
                        <li role="presentation">
                            <a href="#delivered" aria-controls="delivered" role="tab" data-toggle="tab">Delivered</a>
                        </li>
                        <li role="presentation">
                            <a href="#cancelled" aria-controls="cancelled" role="tab" data-toggle="tab">Canceled</a>
                        </li>

                    </ul>

                    <!-- Tab panes -->
                    <div class="tab-content">
                        <div role="tabpanel" class="tab-pane fade in active" id="pending">
                            <h3 class="title-hero">Pending Orders</h3>
                            <table class="table table-striped table-bordered responsive no-wrap datatable-responsive" cellspacing="0" width="100%">
                                <thead>
                                    <tr>
                                        <th>S.no</th>
                                        <th>User Name</th>                                       
                                        <th>Pay Type</th>
                                        <th>Pay Amount</th>
                                        <th>Pay Status</th>
                                        <th>Order Date</th>
                                        <th>Order Status</th>                                        
                                        <th>Action</th>
<!--                                    <th>Delivery Status</th>
                                        <th>Delivery Type</th>-->
                                        <th>View/Delete Order</th>
                                    </tr>
                                </thead>
                                <tfoot>
                                    <tr>
                                        <th>S.no</th>
                                        <th>User Name</th>                                       
                                        <th>Pay Type</th>
                                        <th>Pay Amount</th>
                                        <th>Pay Status</th>
                                        <th>Order Date</th>
                                        <th>Order Status</th>                                        
                                        <th>Action</th>
<!--                                    <th>Delivery Status</th>
                                        <th>Delivery Type</th>-->
                                        <th>View/Delete Order</th>
                                    </tr>
                                </tfoot>
                                <tbody>
                                    <?php
                                    if (isset($this->pendingStatus)) {
                                        $i = 1;
                                        foreach ($this->pendingStatus as $value) {
                                            ?>
                                            <tr>
                                                <td><?php echo $i; ?></td>
                                                <td><?php echo $value['uname']; ?></td>
                                                <td><?php
                                                    if ($value['pay_type'] == 1) {
                                                        echo 'COD';
                                                    } else if ($value['pay_type'] == 2) {
                                                        echo "PaYpaL";
                                                    } else {
                                                        echo "No Payement GateWay";
                                                    }
                                                    ?></td>
                                                <td><?php echo $value['total_amount']; ?></td>
                                                <td><?php
                                                    if ($value['pay_status'] == 0) {
                                                        echo 'Pending';
                                                    } else if ($value['pay_status'] == 1) {
                                                        echo 'Completed';
                                                    } else if ($value['pay_status'] == 2) {
                                                        echo 'Failed';
                                                    } else if ($value['pay_status'] == 3) {
                                                        echo 'Canceled';
                                                    } else {
                                                        echo 'No Acknowledgement';
                                                    }
                                                    ?></td>
                                                <td><?php echo date("j F , Y h:i:s A", strtotime($value['order_date'])); ?></td>
                                                <td id="demo"><?php
                                                    if ($value['order_status'] == 0) {
                                                        echo 'Pending';
                                                    } else if ($value['order_status'] == 1) {
                                                        echo ' In Process';
                                                    } else if ($value['order_status'] == 2) {
                                                        echo ' Delivered';
                                                    } else if ($value['order_status'] == 3) {
                                                        echo 'Canceled';
                                                    } else {
                                                        echo 'Dispatch';
                                                    }?></td>
                                                <td class="trigger">  
                                                    <select  class="js-example-responsive js-example-basic-hide-search form-control" name="order_status" id="mySelect" > 
                                                        <option value="1" <?php
                                                        if ($value['order_status'] == 0) {
                                                            echo"selected";
                                                        }
                                                        ?>>
                                                            Pending
                                                        </option>
                                                        <option value="2" <?php
                                                        if ($value['order_status'] == 1) {
                                                            echo"selected";
                                                        }
                                                        ?>>
                                                            In Process
                                                        </option>
                                                        <option value="3" <?php
                                                        if ($value['order_status'] == 2) {
                                                            echo"selected";
                                                        }
                                                        ?>>
                                                            Delivered
                                                        </option>
                                                        <option value="4" <?php
                                                        if ($value['order_status'] == 3) {
                                                            echo"selected";
                                                        }
                                                        ?>>
                                                            Canceled 
                                                        </option>
                                                        <option value="5" <?php
                                                        if ($value['order_status'] == 4) {
                                                            echo"selected";
                                                        }
                                                        ?>>
                                                            Dispatch 
                                                        </option>
                                                    </select>
                                                </td>
        <!--                                                <td><?php
//                                                    if ($value['delivery_status'] == 0) {
//                                                        echo 'Pending';
//                                                    } else if ($value['delivery_status'] == 1) {
//                                                        echo 'Completed';
//                                                    } else if ($value['delivery_status'] == 2) {
//                                                        echo 'Return/Canceled';
//                                                    } else if ($value['delivery_status'] == 3) {
//                                                        echo 'Unable to Reach';
//                                                    } else {
//                                                        echo 'No Acknowledgement';
//                                                    }
                                                ?></td>-->
        <!--                                                <td><?php
//                                                    if ($value['delivery_type'] == 1) {
//                                                        echo 'Delivery to address';
//                                                    } else if ($value['delivery_type'] == 2) {
//                                                        echo 'Pick up';
//                                                    } else {
//                                                        echo 'None of way choosen';
//                                                    }
                                                ?></td>-->
                                                <td class="text-center">
                                                    <a href="/admin/edit-order-details/<?php echo $value['order_id']; ?>" class="btn btn-default"><i class="glyph-icon icon-linecons-eye"></i></a>
                                                    <a href="javascript:;" id="<?php echo "orderdelete_" . $value['order_id']; ?>" class="btn btn-default deleteorder"><i class="glyph-icon icon-linecons-trash"></i></a></td>
                                            </tr>   

                                            <?php
                                            $i++;
                                        }
                                    }
                                    ?>
                                </tbody>
                            </table>
                        </div>
                        <div role="tabpanel" class="tab-pane fade " id="inprocess">
                            <h3 class="title-hero">In Process Orders</h3>
                            <table class="table table-striped table-bordered responsive no-wrap datatable-responsive" cellspacing="0" width="100%">
                                <thead>
                                    <tr>
                                       <th>S.no</th>
                                        <th>User Name</th>                                       
                                        <th>Pay Type</th>
                                        <th>Pay Amount</th>
                                        <th>Pay Status</th>
                                        <th>Order Date</th>
                                        <th>Order Status</th>                                        
                                        <th>Action</th>
<!--                                        <th>Delivery Status</th>
                                        <th>Delivery Type</th>-->
                                        <th>View/Delete Order</th>
                                    </tr>
                                </thead>
                                <tfoot>
                                    <tr>
                                        <th>S.no</th>
                                        <th>User Name</th>                                       
                                        <th>Pay Type</th>
                                        <th>Pay Amount</th>
                                        <th>Pay Status</th>
                                        <th>Order Date</th>
                                        <th>Order Status</th>                                        
                                        <th>Action</th>
<!--                                    <th>Delivery Status</th>
                                        <th>Delivery Type</th>-->
                                        <th>View/Delete Order</th>

                                    </tr>
                                </tfoot>
                                <tbody>
                                    <?php
                                    if (isset($this->processStatus)) {
                                        $i = 1;
                                        foreach ($this->processStatus as $value) {
                                            ?>
                                            <tr>
                                                <td><?php echo $i; ?></td>
                                                <td><?php echo $value['uname']; ?></td>
                                                <td><?php
                                                    if ($value['pay_type'] == 1) {
                                                        echo 'COD';
                                                    } else if ($value['pay_type'] == 2) {
                                                        echo "PaYpaL";
                                                    } else {
                                                        echo "No Payement GateWay";
                                                    }
                                                    ?></td>
                                                <td><?php echo $value['total_amount']; ?></td>
                                                <td><?php
                                                    if ($value['pay_status'] == 0) {
                                                        echo 'Pending';
                                                    } else if ($value['pay_status'] == 1) {
                                                        echo 'Completed';
                                                    } else if ($value['pay_status'] == 2) {
                                                        echo 'Failed';
                                                    } else if ($value['pay_status'] == 3) {
                                                        echo 'COD';
                                                    } else {
                                                        echo 'No Acknowledgement';
                                                    }
                                                    ?></td>
                                                <td><?php echo date("j F , Y h:i:s A", strtotime($value['order_date'])); ?></td>
                                                <td>In Process</td>
                                                <td>  
                                                    <select  class="js-example-responsive js-example-basic-hide-search form-control" name="pay_status"> 
                                                        <option value="1" <?php
                                                        if ($value['order_status'] == 0) {
                                                            echo"selected";
                                                        }
                                                        ?>>
                                                            Pending
                                                        </option>
                                                        <option value="2" <?php
                                                        if ($value['order_status'] == 1) {
                                                            echo"selected";
                                                        }
                                                        ?>>
                                                            In Process
                                                        </option>
                                                        <option value="3" <?php
                                                        if ($value['order_status'] == 2) {
                                                            echo"selected";
                                                        }
                                                        ?>>
                                                            Delivered
                                                        </option>
                                                        <option value="4" <?php
                                                        if ($value['order_status'] == 3) {
                                                            echo"selected";
                                                        }
                                                        ?>>
                                                            Canceled 
                                                        </option>
                                                        <option value="5" <?php
                                                        if ($value['order_status'] == 4) {
                                                            echo"selected";
                                                        }
                                                        ?>>
                                                            Dispatch 
                                                        </option>
                                                    </select>
                                                </td>
        <!--                                                <td><?php
//                                                    if ($value['delivery_status'] == 0) {
//                                                        echo 'Pending';
//                                                    } else if ($value['delivery_status'] == 1) {
//                                                        echo 'Completed';
//                                                    } else if ($value['delivery_status'] == 2) {
//                                                        echo 'Return/Canceled';
//                                                    } else if ($value['delivery_status'] == 3) {
//                                                        echo 'Unable to Reach';
//                                                    } else {
//                                                        echo 'No Acknowledgement';
//                                            }
                                            ?></td>-->
    <!--                                                <td><?php
//                                                    if ($value['delivery_type'] == 1) {
//                                                        echo 'Delivery to address';
//                                                    } else if ($value['delivery_type'] == 2) {
//                                                        echo 'Pick up';
//                                                    } else {
//                                                        echo 'None of way choosen';
//                                                    }
                                            ?></td>-->
                                            <td class="text-center">
                                                <a href="/admin/edit-order-details/<?php echo $value['order_id']; ?>" class="btn btn-default"><i class="glyph-icon icon-linecons-eye"></i></a>
                                            <a href="javascript:;" id="<?php echo "orderdelete_" . $value['order_id']; ?>" class="btn btn-default deleteorder"><i class="glyph-icon icon-linecons-trash"></i></a>
                                            </td>
                                        </tr>   

                                        <?php
                                        $i++;
                                    }
                                    }
                                    ?>

                                </tbody>
                            </table>
                        </div>
                        <div role="tabpanel" class="tab-pane fade" id="dispatch">
                            <h3 class="title-hero">Dispatch Orders</h3>
                            <table class="table table-striped table-bordered responsive no-wrap datatable-responsive" cellspacing="0" width="100%">
                                <thead>
                                    <tr>
                                        <th>S.no</th>
                                        <th>User Name</th>                                       
                                        <th>Pay Type</th>
                                        <th>Pay Amount</th>
                                        <th>Pay Status</th>
                                        <th>Order Date</th>
                                        <th>Order Status</th>                                        
                                        <th>Action</th>
<!--                                        <th>Delivery Status</th>
                                        <th>Delivery Type</th>-->
                                        <th>View/Delete Order</th>
                                    </tr>
                                </thead>
                                <tfoot>
                                    <tr>
                                        <th>S.no</th>
                                        <th>User Name</th>                                       
                                        <th>Pay Type</th>
                                        <th>Pay Amount</th>
                                        <th>Pay Status</th>
                                        <th>Order Date</th>
                                        <th>Order Status</th>                                        
                                        <th>Action</th>
<!--                                        <th>Delivery Status</th>
                                        <th>Delivery Type</th>-->
                                        <th>View/Delete Order</th>

                                    </tr>
                                </tfoot>
                                <tbody>
                                    <?php
                                    if (isset($this->dispatchStatus)) {
                                        $i = 1;
                                        foreach ($this->dispatchStatus as $value) {
                                            ?>
                                            <tr>
                                                <td><?php echo $i; ?></td>
                                                <td><?php echo $value['uname']; ?></td>

                                                <td><?php
                                                    if ($value['pay_type'] == 1) {
                                                        echo 'COD';
                                                    } else if ($value['pay_type'] == 2) {
                                                        echo "PaYpaL";
                                                    } else {
                                                        echo "No Payement GateWay";
                                                    }
                                                    ?></td>
                                                <td><?php echo $value['total_amount']; ?></td>

                                                <td><?php
                                                    if ($value['pay_status'] == 0) {
                                                        echo 'Pending';
                                                    } else if ($value['pay_status'] == 1) {
                                                        echo 'Completed';
                                                    } else if ($value['pay_status'] == 2) {
                                                        echo 'Failed';
                                                    } else if ($value['pay_status'] == 3) {
                                                        echo 'COD';
                                                    } else {
                                                        echo 'No Acknowledgement';
                                                    }
                                                    ?></td>
                                                <td><?php echo date("j F , Y h:i:s A", strtotime($value['order_date'])); ?></td>
                                                <td>Dispatch</td>
                                                <td>  
                                                    <select  class="js-example-responsive js-example-basic-hide-search form-control" name="pay_status"> 
                                                        <option value="1" <?php
                                                        if ($value['order_status'] == 0) {
                                                            echo"selected";
                                                        }
                                                        ?>>
                                                            Pending
                                                        </option>
                                                        <option value="2" <?php
                                                        if ($value['order_status'] == 1) {
                                                            echo"selected";
                                                        }
                                                        ?>>
                                                            In Process
                                                        </option>
                                                        <option value="3" <?php
                                                        if ($value['order_status'] == 2) {
                                                            echo"selected";
                                                        }
                                                        ?>>
                                                            Delivered
                                                        </option>
                                                        <option value="4" <?php
                                                        if ($value['order_status'] == 3) {
                                                            echo"selected";
                                                        }
                                                        ?>>
                                                            Canceled 
                                                        </option>
                                                        <option value="5" <?php
                                                        if ($value['order_status'] == 4) {
                                                            echo"selected";
                                                        }
                                                        ?>>
                                                            Dispatch 
                                                        </option>
                                                    </select>
                                                </td>
        <!--                                                <td><?php
//                                                    if ($value['delivery_status'] == 0) {
//                                                        echo 'Pending';
//                                                    } else if ($value['delivery_status'] == 1) {
//                                                        echo 'Completed';
//                                                    } else if ($value['delivery_status'] == 2) {
//                                                        echo 'Return/Canceled';
//                                                    } else if ($value['delivery_status'] == 3) {
//                                                        echo 'Unable to Reach';
//                                                    } else {
//                                                        echo 'No Acknowledgement';
//                                                    }
                                                ?></td>
                                                <td><?php
//                                                    if ($value['delivery_type'] == 1) {
//                                                        echo 'Delivery to address';
//                                                    } else if ($value['delivery_type'] == 2) {
//                                                        echo 'Pick up';
//                                                    } else {
//                                                        echo 'None of way choosen';
//                                                    }
                                                ?></td>-->
                                                <td class="text-center">
                                                    <a href="/admin/edit-order-details/<?php echo $value['order_id']; ?>" class="btn btn-default"><i class="glyph-icon icon-linecons-eye"></i></a>
                                                <a href="javascript:;" id="<?php echo "orderdelete_" . $value['order_id']; ?>" class="btn btn-default deleteorder"><i class="glyph-icon icon-linecons-trash"></i></a></td>
                                            </tr>   

                                            <?php
                                            $i++;
                                        }
                                    }
                                    ?>
                                </tbody>
                            </table>
                        </div>
                        <div role="tabpanel" class="tab-pane fade" id="delivered">
                            <h3 class="title-hero">Delivered Orders</h3>
                            <table class="table table-striped table-bordered responsive no-wrap datatable-responsive" cellspacing="0" width="100%">
                                <thead>
                                    <tr>
                                       <th>S.no</th>
                                        <th>User Name</th>                                       
                                        <th>Pay Type</th>
                                        <th>Pay Amount</th>
                                        <th>Pay Status</th>
                                        <th>Order Date</th>
                                        <th>Order Status</th>                                        
                                        <th>Action</th>
<!--                                        <th>Delivery Status</th>
                                        <th>Delivery Type</th>-->
                                        <th>View/Delete Order</th>
                                    </tr>
                                </thead>
                                <tfoot>
                                    <tr>
                                       <th>S.no</th>
                                        <th>User Name</th>                                       
                                        <th>Pay Type</th>
                                        <th>Pay Amount</th>
                                        <th>Pay Status</th>
                                        <th>Order Date</th>
                                        <th>Order Status</th>                                        
                                        <th>Action</th>
<!--                                        <th>Delivery Status</th>
                                        <th>Delivery Type</th>-->
                                        <th>View/Delete Order</th>

                                    </tr>
                                </tfoot>
                                <tbody>
                                    <?php
                                    if (isset($this->deliveredStatus)) {
                                        $i = 1;
                                        foreach ($this->deliveredStatus as $value) {
                                            ?>
                                            <tr>
                                                <td><?php echo $i; ?></td>
                                                <td><?php echo $value['uname']; ?></td>

                                                <td><?php
                                                    if ($value['pay_type'] == 1) {
                                                        echo 'COD';
                                                    } else if ($value['pay_type'] == 2) {
                                                        echo "PaYpaL";
                                                    } else {
                                                        echo "No Payement GateWay";
                                                    }
                                                    ?></td>
                                                <td><?php echo $value['total_amount']; ?></td>

                                                <td><?php
                                                    if ($value['pay_status'] == 0) {
                                                        echo 'Pending';
                                                    } else if ($value['pay_status'] == 1) {
                                                        echo 'Completed';
                                                    } else if ($value['pay_status'] == 2) {
                                                        echo 'Failed';
                                                    } else if ($value['pay_status'] == 3) {
                                                        echo 'COD';
                                                    } else {
                                                        echo 'No Acknowledgement';
                                                    }
                                                    ?>
                                                </td>
                                               
                                                <td><?php echo date("j F , Y h:i:s A", strtotime($value['order_date'])); ?></td>
                                                <td>Delivered</td>
                                        <td><select  class="js-example-responsive js-example-basic-hide-search form-control" name="pay_status"> 
                                            <option value="1" <?php
                                            if ($value['order_status'] == 0) {
                                                echo"selected";
                                            }
                                            ?>>
                                                Pending
                                            </option>
                                            <option value="2" <?php
                                            if ($value['order_status'] == 1) {
                                                echo"selected";
                                            }
                                            ?>>
                                                In Process
                                            </option>
                                            <option value="3" <?php
                                            if ($value['order_status'] == 2) {
                                                echo"selected";
                                            }
                                            ?>>
                                                Delivered
                                            </option>
                                            <option value="4" <?php
                                            if ($value['order_status'] == 3) {
                                                echo"selected";
                                            }
                                            ?>>
                                                Canceled 
                                            </option>
                                            <option value="5" <?php
                                            if ($value['order_status'] == 4) {
                                                echo"selected";
                                            }
                                            ?>>
                                                Dispatch 
                                            </option>
                                        </select>
                                        </td>
        <!--                                                <td><?php
//                                                    if ($value['delivery_status'] == 0) {
//                                                        echo 'Pending';
//                                                    } else if ($value['delivery_status'] == 1) {
//                                                        echo 'Completed';
//                                                    } else if ($value['delivery_status'] == 2) {
//                                                        echo 'Return/Cancelled';
//                                                    } else if ($value['delivery_status'] == 3) {
//                                                        echo 'Unable to Reach';
//                                                    } else {
//                                                        echo 'No Acknowledgement';
//                                                    }
                                        ?></td>-->
        <!--                                                <td><?php
//                                                    if ($value['delivery_type'] == 1) {
//                                                        echo 'Delivery to address';
//                                                    } else if ($value['delivery_type'] == 2) {
//                                                        echo 'Pick up';
//                                                    } else {
//                                                        echo 'None of way choosen';
//                                                    }
                                        ?></td>-->
                                        <td class="text-center">
                                            <a href="/admin/edit-order-details/<?php echo $value['order_id']; ?>" class="btn btn-default"><i class="glyph-icon icon-linecons-eye"></i></a>
                                        <a href="javascript:;" id="<?php echo "orderdelete_" . $value['order_id']; ?>" class="btn btn-default deleteorder"><i class="glyph-icon icon-linecons-trash"></i></a></td>
                                        </tr>   

                                        <?php
                                        $i++;
                                    }
                                }
                                ?>
                                </tbody>
                            </table>
                        </div>
                        <div role="tabpanel" class="tab-pane fade" id="cancelled">
                            <h3 class="title-hero">Canceled Orders</h3>
                            <table class="table table-striped table-bordered responsive no-wrap datatable-responsive" cellspacing="0" width="100%">
                                <thead>
                                    <tr>
                                       <th>S.no</th>
                                        <th>User Name</th>                                       
                                        <th>Pay Type</th>
                                        <th>Pay Amount</th>
                                        <th>Pay Status</th>
                                        <th>Order Date</th>
                                        <th>Order Status</th>                                        
                                        <th>Action</th>
<!--                                        <th>Delivery Status</th>
                                        <th>Delivery Type</th>-->
                                        <th>View/Delete Order</th>
                                    </tr>
                                </thead>
                                <tfoot>
                                    <tr>
                                        <th>S.no</th>
                                        <th>User Name</th>                                       
                                        <th>Pay Type</th>
                                        <th>Pay Amount</th>
                                        <th>Pay Status</th>
                                        <th>Order Date</th>
                                        <th>Order Status</th>                                        
                                        <th>Action</th>
<!--                                        <th>Delivery Status</th>
                                        <th>Delivery Type</th>-->
                                        <th>View/Delete Order</th>

                                    </tr>
                                </tfoot>
                                <tbody>
                                    <?php
                                    if (isset($this->canceledStatus)) {
                                        $i = 1;
                                        foreach ($this->canceledStatus as $value) {
                                            ?>
                                            <tr>
                                                <td><?php echo $i; ?></td>
                                                <td><?php echo $value['uname']; ?></td>

                                                <td><?php
                                                    if ($value['pay_type'] == 1) {
                                                        echo 'COD';
                                                    } else if ($value['pay_type'] == 2) {
                                                        echo "PaYpaL";
                                                    } else {
                                                        echo "No Payement GateWay";
                                                    }
                                                    ?></td>
                                                <td><?php echo $value['total_amount']; ?></td>

                                                <td><?php
                                                    if ($value['pay_status'] == 0) {
                                                        echo 'Pending';
                                                    } else if ($value['pay_status'] == 1) {
                                                        echo 'Completed';
                                                    } else if ($value['pay_status'] == 2) {
                                                        echo 'Failed';
                                                    } else if ($value['pay_status'] == 3) {
                                                        echo 'COD';
                                                    } else {
                                                        echo 'No Acknowledgement';
                                                    }
                                                    ?></td>
                                                <td><?php echo date("j F , Y h:i:s A", strtotime($value['order_date'])); ?></td>
                                                <td>Canceled</td>
                                                <td>  
                                                    <select  class="js-example-responsive js-example-basic-hide-search form-control" name="pay_status"> 
                                                        <option value="1" <?php
                                                        if ($value['order_status'] == 0) {
                                                            echo"selected";
                                                        }
                                                        ?>>
                                                            Pending
                                                        </option>
                                                        <option value="2" <?php
                                                        if ($value['order_status'] == 1) {
                                                            echo"selected";
                                                        }
                                                        ?>>
                                                            In Process
                                                        </option>
                                                        <option value="3" <?php
                                                        if ($value['order_status'] == 2) {
                                                            echo"selected";
                                                        }
                                                        ?>>
                                                            Delivered
                                                        </option>
                                                        <option value="4" <?php
                                                        if ($value['order_status'] == 3) {
                                                            echo"selected";
                                                        }
                                                        ?>>
                                                            Canceled 
                                                        </option>
                                                        <option value="5" <?php
                                                        if ($value['order_status'] == 4) {
                                                            echo"selected";
                                                        }
                                                        ?>>
                                                            Dispatch 
                                                        </option>
                                                    </select>
                                                </td>
        <!--                                                <td><?php
//                                                    if ($value['delivery_status'] == 0) {
//                                                        echo 'Pending';
//                                                    } else if ($value['delivery_status'] == 1) {
//                                                        echo 'Completed';
//                                                    } else if ($value['delivery_status'] == 2) {
//                                                        echo 'Return/Canceled';
//                                                    } else if ($value['delivery_status'] == 3) {
//                                                        echo 'Unable to Reach';
//                                                    } else {
//                                                        echo 'No Acknowledgement';
//                                                    }
                                                ?></td>
                                                <td><?php
//                                                    if ($value['delivery_type'] == 1) {
//                                                        echo 'Delivery to address';
//                                                    } else if ($value['delivery_type'] == 2) {
//                                                        echo 'Pick up';
//                                                    } else {
//                                                        echo 'None of way choosen';
//                                                    }
                                                ?></td>-->
                                                <td class="text-center">
                                                    <a href="/admin/edit-order-details/<?php echo $value['order_id']; ?>" class="btn btn-default"><i class="glyph-icon icon-linecons-eye"></i></a>
                                                <a href="javascript:;" id="<?php echo "orderdelete_" . $value['order_id']; ?>" class="btn btn-default deleteorder"><i class="glyph-icon icon-linecons-trash"></i></a></td>
                                            </tr>   

                                            <?php
                                            $i++;
                                        }
                                    }
                                    ?>
                                </tbody>
                            </table>
                        </div>

                    </div>

                </div>
            </div>
        </div>
    </div>
</div>

<script>
    $('[data-toggle="tab"]').click(function(e) {
        e.preventDefault();
        $(this).parent().siblings().removeClass('active');
        $(this).parent().addClass('active');
        var id = $(this).attr('href');
        $(id).siblings().removeClass('in active');
        $(id).toggleClass('in active');
    });
</script>