


<div id="page-title">
    <h2> Order Details</h2>
    <p>The most complete user interface framework that can be used to create stunning admin dashboards and presentation websites.</p>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="panel">
            <div class="panel-body">
                <h3 class="title-hero">View Order Details</h3>
                <div class="example-box-wrapper" id="user-transaction">
                    <!-- Nav tabs -->
                    <ul class="nav nav-pills" role="tablist">
                        <li role="presentation" class="active">
                            <a href="#inprocess" aria-controls="inprocess" role="tab" data-toggle="tab">In Process</a>
                        </li>
                        <li role="presentation">
                            <a href="#cancelled" aria-controls="cancelled" role="tab" data-toggle="tab">Cancelled</a>
                        </li>
                        <li role="presentation">
                            <a href="#delivered" aria-controls="delivered" role="tab" data-toggle="tab">Delivered</a>
                        </li>

                    </ul>

                    <!-- Tab panes -->
                    <div class="tab-content">
                        <div role="tabpanel" class="tab-pane fade in active" id="inprocess">
                            <h3 class="title-hero">In Process Orders</h3>
                            <table class="table table-striped table-bordered responsive no-wrap datatable-responsive" cellspacing="0" width="100%">
                                <thead>
                                    <tr>
                                        <th>S.no</th>
                                        <th>User Email</th>
                                        <th>Order Date</th>
                                        <th>Order Status</th>
                                        <th>Pay Type</th>
                                        <th>Pay Amount</th>
                                        <th>Pay Status</th>
                                        <th>Delivery Status</th>
                                        <th>Delivery Type</th>
                                        <th>View Order</th>
                                    </tr>
                                </thead>
                                <tfoot>
                                    <tr>
                                        <th>S.no</th>
                                        <th>User Email</th>
                                        <th>Order Date</th>
                                        <th>Order Status</th>
                                        <th>Pay Type</th>
                                        <th>Pay Amount</th>
                                        <th>Pay Status</th>
                                        <th>Delivery Status</th>
                                        <th>Delivery Type</th>
                                        <th>View Order</th>

                                    </tr>
                                </tfoot>
                                <tbody>
                                    <?php
                                    if (isset($this->processStatus)) {
                                        $i = 1;
                                        foreach ($this->processStatus as $value) {
                                            ?>
                                            <tr>
                                                <td><?php echo $i; ?></td>
                                                <td><?php echo $value['email']; ?></td>
                                                <td><?php echo date("j F , Y h:i:s A", strtotime($value['order_date'])); ?></td>
                                                <td>In Process</td>
                                                <td><?php
                                                    if ($value['pay_type'] == 1) {
                                                        echo 'COD';
                                                    } else if ($value['pay_type'] == 2) {
                                                        echo "PaYpaL";
                                                    } else {
                                                        echo "No Payement GateWay";
                                                    }
                                                    ?></td>
                                                <td><?php echo $value['total_amount']; ?></td>

                                                <td><?php
                                                    if ($value['pay_status'] == 0) {
                                                        echo 'Pending';
                                                    } else if ($value['pay_status'] == 1) {
                                                        echo 'completed';
                                                    } else if ($value['pay_status'] == 2) {
                                                        echo 'Failed';
                                                    } else if ($value['pay_status'] == 3) {
                                                        echo 'COD';
                                                    } else {
                                                        echo 'No Acknowledgement';
                                                    }
                                                    ?></td>
                                                <td><?php
                                                    if ($value['delivery_status'] == 0) {
                                                        echo 'Pending';
                                                    } else if ($value['delivery_status'] == 1) {
                                                        echo 'completed';
                                                    } else if ($value['delivery_status'] == 2) {
                                                        echo 'Return/Cancelled';
                                                    } else if ($value['delivery_status'] == 3) {
                                                        echo 'Unable to Reach';
                                                    } else {
                                                        echo 'No Acknowledgement';
                                                    }
                                                    ?></td>
                                                <td><?php
                                                    if ($value['delivery_type'] == 1) {
                                                        echo 'Delivery to address';
                                                    } else if ($value['delivery_type'] == 2) {
                                                        echo 'pick up';
                                                    } else {
                                                        echo 'None of way choosen';
                                                    }
                                                    ?></td><td class="text-center">
                                                    <a href="/admin/edit-order-details/<?php echo $value['order_id']; ?>" class="btn btn-default"><i class="glyph-icon icon-linecons-eye"></i></a><td>
                                            </tr>   

                                            <?php
                                            $i++;
                                        }
                                    }
                                    ?>

                                </tbody>
                            </table>
                        </div>
                        <div role="tabpanel" class="tab-pane fade" id="cancelled">
                            <h3 class="title-hero">Cancelled Orders</h3>
                            <table class="table table-striped table-bordered responsive no-wrap datatable-responsive" cellspacing="0" width="100%">
                                <thead>
                                    <tr>
                                        <th>S.no</th>
                                        <th>User Email</th>
                                        <th>Order Date</th>
                                        <th>Order Status</th>
                                        <th>Pay Type</th>
                                        <th>Pay Amount</th>
                                        <th>Pay Status</th>
                                        <th>Delivery Status</th>
                                        <th>Delivery Type</th>
                                        <th>View Order</th>
                                    </tr>
                                </thead>
                                <tfoot>
                                    <tr>
                                        <th>S.no</th>
                                        <th>User Email</th>
                                        <th>Order Date</th>
                                        <th>Order Status</th>
                                        <th>Pay Type</th>
                                        <th>Pay Amount</th>
                                        <th>Pay Status</th>
                                        <th>Delivery Status</th>
                                        <th>Delivery Type</th>
                                        <th>View Order</th>

                                    </tr>
                                </tfoot>
                                <tbody>
                                    <?php
                                    if (isset($this->canceledStatus)) {
                                        $i = 1;
                                        foreach ($this->canceledStatus as $value) {
                                            ?>
                                            <tr>
                                                <td><?php echo $i; ?></td>
                                                <td><?php echo $value['email']; ?></td>
                                                <td><?php echo date("j F , Y h:i:s A", strtotime($value['order_date'])); ?></td>
                                                <td>Cancelled</td>
                                                <td><?php
                                                    if ($value['pay_type'] == 1) {
                                                        echo 'COD';
                                                    } else if ($value['pay_type'] == 2) {
                                                        echo "PaYpaL";
                                                    } else {
                                                        echo "No Payement GateWay";
                                                    }
                                                    ?></td>
                                                <td><?php echo $value['total_amount']; ?></td>

                                                <td><?php
                                                    if ($value['pay_status'] == 0) {
                                                        echo 'Pending';
                                                    } else if ($value['pay_status'] == 1) {
                                                        echo 'completed';
                                                    } else if ($value['pay_status'] == 2) {
                                                        echo 'Failed';
                                                    } else if ($value['pay_status'] == 3) {
                                                        echo 'COD';
                                                    } else {
                                                        echo 'No Acknowledgement';
                                                    }
                                                    ?></td>
                                                <td><?php
                                                    if ($value['delivery_status'] == 0) {
                                                        echo 'Pending';
                                                    } else if ($value['delivery_status'] == 1) {
                                                        echo 'completed';
                                                    } else if ($value['delivery_status'] == 2) {
                                                        echo 'Return/Cancelled';
                                                    } else if ($value['delivery_status'] == 3) {
                                                        echo 'Unable to Reach';
                                                    } else {
                                                        echo 'No Acknowledgement';
                                                    }
                                                    ?></td>
                                                <td><?php
                                                    if ($value['delivery_type'] == 1) {
                                                        echo 'Delivery to address';
                                                    } else if ($value['delivery_type'] == 2) {
                                                        echo 'pick up';
                                                    } else {
                                                        echo 'None of way choosen';
                                                    }
                                                    ?></td><td class="text-center">
                                                    <a href="/admin/edit-order-details/<?php echo $value['order_id']; ?>" class="btn btn-default"><i class="glyph-icon icon-linecons-eye"></i></a><td>
                                            </tr>   

                                            <?php
                                            $i++;
                                        }
                                    }
                                    ?>
                                </tbody>
                            </table>
                        </div>
                        <div role="tabpanel" class="tab-pane fade" id="delivered">
                            <h3 class="title-hero">Delivered Orders</h3>
                            <table class="table table-striped table-bordered responsive no-wrap datatable-responsive" cellspacing="0" width="100%">
                                <thead>
                                    <tr>
                                        <th>S.no</th>
                                        <th>User Email</th>
                                        <th>Order Date</th>
                                        <th>Order Status</th>
                                        <th>Pay Type</th>
                                        <th>Pay Amount</th>
                                        <th>Pay Status</th>
                                        <th>Delivery Status</th>
                                        <th>Delivery Type</th>
                                        <th>View Order</th>
                                    </tr>
                                </thead>
                                <tfoot>
                                    <tr>
                                        <th>S.no</th>
                                        <th>User Email</th>
                                        <th>Order Date</th>
                                        <th>Order Status</th>
                                        <th>Pay Type</th>
                                        <th>Pay Amount</th>
                                        <th>Pay Status</th>
                                        <th>Delivery Status</th>
                                        <th>Delivery Type</th>
                                        <th>View Order</th>

                                    </tr>
                                </tfoot>
                                <tbody>
                                    <?php
                                    if (isset($this->deliveredStatus)) {
                                        $i = 1;
                                        foreach ($this->deliveredStatus as $value) {
                                            ?>
                                            <tr>
                                                <td><?php echo $i; ?></td>
                                                <td><?php echo $value['email']; ?></td>
                                                <td><?php echo date("j F , Y h:i:s A", strtotime($value['order_date'])); ?></td>
                                                <td>Delivered</td>
                                                <td><?php
                                                    if ($value['pay_type'] == 1) {
                                                        echo 'COD';
                                                    } else if ($value['pay_type'] == 2) {
                                                        echo "PaYpaL";
                                                    } else {
                                                        echo "No Payement GateWay";
                                                    }
                                                    ?></td>
                                                <td><?php echo $value['total_amount']; ?></td>

                                                <td><?php
                                                    if ($value['pay_status'] == 0) {
                                                        echo 'Pending';
                                                    } else if ($value['pay_status'] == 1) {
                                                        echo 'completed';
                                                    } else if ($value['pay_status'] == 2) {
                                                        echo 'Failed';
                                                    } else if ($value['pay_status'] == 3) {
                                                        echo 'COD';
                                                    } else {
                                                        echo 'No Acknowledgement';
                                                    }
                                                    ?></td>
                                                <td><?php
                                                    if ($value['delivery_status'] == 0) {
                                                        echo 'Pending';
                                                    } else if ($value['delivery_status'] == 1) {
                                                        echo 'completed';
                                                    } else if ($value['delivery_status'] == 2) {
                                                        echo 'Return/Cancelled';
                                                    } else if ($value['delivery_status'] == 3) {
                                                        echo 'Unable to Reach';
                                                    } else {
                                                        echo 'No Acknowledgement';
                                                    }
                                                    ?></td>
                                                <td><?php
                                                    if ($value['delivery_type'] == 1) {
                                                        echo 'Delivery to address';
                                                    } else if ($value['delivery_type'] == 2) {
                                                        echo 'pick up';
                                                    } else {
                                                        echo 'None of way choosen';
                                                    }
                                                    ?><td class="text-center">
                                                    <a href="/admin/edit-order-details/<?php echo $value['order_id']; ?>" class="btn btn-default"><i class="glyph-icon icon-linecons-eye"></i></a><td>
                                            </tr>   

                                            <?php
                                            $i++;
                                        }
                                    }
                                    ?>
                                </tbody>
                            </table>
                        </div>

                    </div>

                </div>
            </div>
        </div>
    </div>
</div>

<script>
    $('[data-toggle="tab"]').click(function(e) {
        e.preventDefault();
        $(this).parent().siblings().removeClass('active');
        $(this).parent().addClass('active');
        var id = $(this).attr('href');
        $(id).siblings().removeClass('in active');
        $(id).toggleClass('in active');
    });
</script>