<link href="/assets/global/css/plugins.css" media="screen" rel="stylesheet" type="text/css" >
<link rel="stylesheet" type="text/css" href="/assets/global/plugins/select2/select2.css"/>
<link rel="stylesheet" type="text/css" href="/assets/global/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.css"/>
<link rel="stylesheet" type="text/css" href="/assets/global/plugins/bootstrap-datepicker/css/datepicker.css"/>
<link href="/assets/global/css/components.css" id="style_components" rel="stylesheet" type="text/css"/>

<div class="page-content-wrapper">
    <div class="page-content">
        <div class="row">
            <div class="col-md-12">
                <div class="portlet light">
                    <div class="portlet-title">
                        <div class="caption">
                            <i class="fa fa-reply font-green-sharp"></i>
                            <span class="caption-subject font-green-sharp bold uppercase">Refund Request</span>
                            <span class="caption-helper">manage refund request...</span>
                        </div>
                    </div>
                    <div class="portlet-body">
                        <div class="table-container">
                            <div class="table-actions-wrapper">
                                <span>
                                </span>
                                <select class="table-group-action-input form-control input-inline input-small input-sm" name="group_action">                                  
                                    <option value="">Select...</option>
                                    <option value="0">Pending</option>
                                    <option value="1">In-Process</option>
                                    <option value="2">Delivered</option>
                                    <option value="3">Canceled</option>
                                    <option value="4">Dispatch</option>
                                    <!--<option value="6">Delivered</option>-->
                                </select>
                                <button class="btn btn-sm yellow table-group-action-submit"><i class="fa fa-check"></i> Submit</button>
                            </div>
                            <table class="table table-striped table-bordered table-hover text-center" id="datatable_orders">
                                <thead>
                                    <tr role="row" class="heading text-center">
                                        <th width="2%"><input type="checkbox" class="group-checkable"></th>
                                        <th width="5%">Order&nbsp;#</th>
                                        <th width="15%">Purchased&nbsp;On</th>
                                        <th width="15%">Customer&nbsp;Email</th>
                                        <th width="15%">Product&nbsp;Name</th>
                                        <th width="10%">Purchased&nbsp;Price</th>
                                        <th width="10%">Payment&nbsp;Type</th>
                                        <th width="10%">Status</th>
                                        <th width="8%">Actions</th>
                                    </tr>
                                    <tr role="row" class="filter">
                                        <td></td>
                                        <td><input type="text" class="form-control form-filter input-sm" name="order_id"></td>
                                        <td>
                                            <div class="input-group date date-picker margin-bottom-5" data-date-format="yyyy-mm-dd">
                                                <input type="text" class="form-control form-filter input-sm" readonly name="order_date_from" placeholder="From">
                                                <span class="input-group-btn">
                                                    <button class="btn btn-sm default" type="button"><i class="fa fa-calendar"></i></button>
                                                </span>
                                            </div>
                                            <div class="input-group date date-picker" data-date-format="yyyy-mm-dd">
                                                <input type="text" class="form-control form-filter input-sm" readonly name="order_date_to" placeholder="To">
                                                <span class="input-group-btn">
                                                    <button class="btn btn-sm default" type="button"><i class="fa fa-calendar"></i></button>
                                                </span>
                                            </div>
                                        </td>
                                        <td><input type="text" class="form-control form-filter input-sm" name="order_customer_email"></td>
                                        <td><input type="text" class="form-control form-filter input-sm" name="product_name"></td>
                                        <td>
                                            <div class="margin-bottom-5">
                                                <input type="text" class="form-control form-filter input-sm margin-bottom-5 clearfix" name="order_purchase_price_from" placeholder="From"/>
                                            </div>
                                            <input type="text" class="form-control form-filter input-sm" name="order_purchase_price_to" placeholder="To"/>
                                        </td>
                                        <td>
                                            <!--<input type="text" class="form-control form-filter input-sm" name="payment_type">-->
                                            <select name="payment_type" class="form-control form-filter input-sm">
                                                <option value="">Select...</option>
                                                <option value="0">COD</option>
                                                <option value="1">PayPal</option>
                                            </select>
                                        </td>
                                        <td>
                                            <select name="order_status" class="form-control form-filter input-sm">
                                                <option value="">Select...</option>
                                                <option value="0">Pending</option>
                                                <option value="1">In-Process</option>
                                                <option value="2">Delivered</option>
                                                <option value="3">Canceled</option>
                                                <option value="4">Dispatch</option>

                                            </select>
                                        </td>
                                        <td>
                                            <div class="margin-bottom-5">
                                                <button class="btn btn-sm yellow filter-submit margin-bottom"><i class="fa fa-search"></i> Search</button>
                                            </div>
                                            <button class="btn btn-sm red filter-cancel"><i class="fa fa-times"></i> Reset</button>
                                        </td>
                                    </tr>
                                </thead>
                                <tbody>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<!-- MODAL FOR REASON-->
<div aria-hidden="true" role="basic" tabindex="-1" id="modal-reason" class="modal fade" style="display: none;">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button aria-hidden="true" data-dismiss="modal" class="close" type="button"></button>
                <h4 class="modal-title">Refund Reason for Order #<b><span id="setOrderId"></span></b></h4>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-12">
                        <p id="reason"></p>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button data-dismiss="modal" class="btn default">Close</button>
                <button class="btn blue" id="approve-refund-request" type="button">Approve</button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
<!--//MODAL FOR REASON-->

<script src="/assets/global/plugins/jquery.blockui.min.js" type="text/javascript"></script>
<script src="/assets/global/plugins/uniform/jquery.uniform.min.js" type="text/javascript"></script>
<script type="text/javascript" src="/assets/global/plugins/select2/select2.min.js"></script>
<script type="text/javascript" src="/assets/global/plugins/datatables/media/js/jquery.dataTables.min.js"></script>
<script type="text/javascript" src="/assets/global/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.js"></script>
<script type="text/javascript" src="/assets/global/plugins/bootstrap-datepicker/js/bootstrap-datepicker.js"></script>

<script src="/assets/global/scripts/metronic.js" type="text/javascript"></script>
<script type="text/javascript" src="/assets/admin/pages/scripts/components-pickers.js"></script>
<script src="/assets/global/scripts/datatable.js"></script>
<script src="/assets/global/plugins/bootstrap-fileinput/bootstrap-fileinput.js" type="text/javascript"></script>



<script type="text/javascript">
    jQuery(document).ready(function() {
        Metronic.init(); // init metronic core components
        ComponentsPickers.init();
    });
    var EcommerceOrders = function() {

        var initPickers = function() {
            //init date pickers
            $('.date-picker').datepicker({
                rtl: Metronic.isRTL(),
                autoclose: true
            });
        }

        var handleOrders = function() {

            var grid = new Datatable();

            grid.init({
                src: $("#datatable_orders"),
                onSuccess: function(grid) {
                    // execute some code after table records loaded
                },
                onError: function(grid) {
                    // execute some code on network or other general error
                },
                loadingMessage: 'Loading...',
                dataTable: {// here you can define a typical datatable settings from http://datatables.net/usage/options
                    // Uncomment below line("dom" parameter) to fix the dropdown overflow issue in the datatable cells. The default datatable layout
                    // setup uses scrollable div(table-scrollable) with overflow:auto to enable vertical scroll(see: assets/global/scripts/datatable.js).
                    // So when dropdowns used the scrollable div should be removed.
                    //"dom": "<'row'<'col-md-8 col-sm-12'pli><'col-md-4 col-sm-12'<'table-group-actions pull-right'>>r>t<'row'<'col-md-8 col-sm-12'pli><'col-md-4 col-sm-12'>>",

                    "lengthMenu": [
                        [10, 20, 50, 100, 150, -1],
                        [10, 20, 50, 100, 150, "All"] // change per page values here
                    ],
                    "pageLength": 10, // default record count per page
                    "ajax": {
                        "url": "/admin/order-listing-ajax-handler", // ajax source
                        "data": {
                            "method": 'allOrders'
                        }
                    },
                    "order": [
                        [1, "asc"]
                    ], // set first column as a default sort by asc
                    "columnDefs": [{// define columns sorting options(by default all columns are sortable extept the first checkbox column)
                            'orderable': false,
                            'targets': [0, 7, 8]
                        }]
                }
            });

            // handle group actionsubmit button click
            grid.getTableWrapper().on('click', '.table-group-action-submit', function(e) {
                e.preventDefault();
                var action = $(".table-group-action-input", grid.getTableWrapper());
                if (action.val() != "" && grid.getSelectedRowsCount() > 0) {
                    grid.setAjaxParam("customActionType", "group_action");
                    grid.setAjaxParam("customActionValue", action.val());
                    grid.setAjaxParam("orderId", grid.getSelectedRows());
                    grid.getDataTable().ajax.reload();
                    grid.clearAjaxParams();
                } else if (action.val() == "") {
                    Metronic.alert({
                        type: 'danger',
                        icon: 'warning',
                        message: 'Please select an action',
                        container: grid.getTableWrapper(),
                        place: 'prepend'
                    });
                } else if (grid.getSelectedRowsCount() === 0) {
                    Metronic.alert({
                        type: 'danger',
                        icon: 'warning',
                        message: 'No record selected',
                        container: grid.getTableWrapper(),
                        place: 'prepend'
                    });
                }
            });

        }

        return {
            //main function to initiate the module
            init: function() {

                initPickers();
                handleOrders();
            }

        };

    }();
   

    $(document).ready(function() {
         EcommerceOrders.init();
        $(document.body).on('click', ".refund-reason", function() {
            var obj = $(this);
            var orderId = obj.attr("order-id");
            $("#setOrderId").text(orderId);
            $("#reason").text(obj.attr("refund-reason"));
        });
        $("#approve-refund-request").click(function() {
            $.ajax({
                url: "/admin/order-ajax-handler",
                type: 'POST',
                datatype: 'json',
                data: {
                    method: 'approveRefundReason',
                    orderId: $("#setOrderId").text()
                },
                success: function(response) {
                    $('#datatable_orders').DataTable().ajax.reload();
                    $('#modal-reason').modal('hide');
                },
                error: function(response) {
                }
            });
        });
    });
</script>

