
<div id="page-title">
    <h2>Notification Log</h2>
    <p>The most complete notification interface framework that can be used to create stunning admin dashboards and presentation websites.</p>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="panel">
            <div class="panel-body">
                <h3 class="title-hero">Notification Log</h3>
                <div class="example-box-wrapper">
                    <table class="table table-striped table-bordered responsive no-wrap datatable-responsive" cellspacing="0" width="100%">
                        <thead>
                            <tr>
                                <th>S.No. </th>        
                                <th> Notification ID </th>
                                <th>Receiver Name</th>
                                <th>Sender Name</th> 
                                <th>Message</th>                              
                                <th>Send Date</th>                            
                                <th>Status</th>
                                <th>Delete</th>

                            </tr>
                        </thead>
                        <tfoot>
                            <tr>
                                <th>S.No. </th>        
                                <th> Notification ID </th>
                                <th>Receiver Name</th>
                                <th>Sender Name</th> 
                                <th>Message</th>                              
                                <th>Send Date</th>                            
                                <th>Status</th>
                                <th>Delete</th>

                            </tr>
                        </tfoot>
                        <tbody>

                            <?php
                            if (isset($this->data)) {
                                $i =1;
                                foreach ($this->data as $collectionData) {
                                    ?>
                                    <tr>
                                        <td><?php echo $i; ?></td>
                                          <td><?php echo $collectionData['notification_id']; ?></td> 
                                        <td><?php
                                            echo $collectionData['receiver_fname'];
                                            echo ' ';
                                            echo $collectionData['receiver_lname'];
                                            ?></td>

                                        <td><?php
                                            echo $collectionData['sender_fname'];
                                            echo ' ';
                                            echo $collectionData['sender_lname'];
                                            ?>
                                        </td>
                                        <td><?php echo $collectionData['notification_message']; ?></td>                                  
                                        <td class="center"><span class="small">(<?php echo gmdate("F d, Y h:mA", $collectionData['sent_date']); ?>)</span></td>
                                        <td class="center">
                                            <?php
                                            if ($collectionData['status'] == 0) {
                                                echo "Unseen";
                                            }
                                            if ($collectionData['status'] == 1) {
                                                echo "Seen";
                                            }
                                            ?>
                                        </td>
                                        <td class="text-center">                                               
                                            <a href="javascript:;" id="<?php echo "notificationdelete_" . $collectionData['notification_id']; ?>" class="btn btn-default deletenotification"><i class="glyph-icon icon-linecons-trash"></i></a>
                                        </td>
                                    </tr>
                                    <?php
                                    $i++;
                                }
                            }
                            ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>