                                     
<div id="page-title">
    <h2>Send User Notification</h2>
    <p>The most complete user interface framework that can be used to create stunning admin dashboards and presentation websites.</p>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="panel">
            <div class="panel-body">
                <h3 class="title-hero">Send Notification</h3>
                <form class="row" role="form" method="post">
                    <div class="form-group col-md-12">
                        <label class="control-label"> Message</label>
                        <textarea class="form-control" type="text" autocomplete="off" placeholder="message" name="message" id="messagecontent"></textarea>
                    </div>
                    <div class="form-group col-md-12 text-right">
                        <button  class="btn btn-info" id="sendbtn"> Send </button>   
                        <span class="notification-suc-err"></span><br>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="panel">
            <div class="panel-body">
                <h3 class="title-hero">Send User Notification</h3>
                <div class="example-box-wrapper">
                    <table class="table table-striped table-bordered responsive no-wrap datatable-responsive" cellspacing="0" width="100%" >
                        <thead>
                            <tr>
                                <th><input type="checkbox" id="selectall" class="select-all"/></th>                            
                                <th>S.No.</th>                            
                                <th>User name</th>  
                                <th>User Email</th>
                                <th>Registration Date</th>
                            </tr>
                        </thead>
                        <tfoot>
                            <tr>
                                <th><input type="checkbox" class="select-all"/></th>                            
                                <th>S.No.</th>                            
                                <th>User name</th>  
                                <th>User Email</th>
                                <th>Registration Date</th>

                            </tr>
                        </tfoot>
                        <tbody>
                            <?php
                            if (isset($this->data)) {
                                $row = 0;
                                foreach ($this->data as $collectionData) {     // echo '<pre>';print_r($collectionData);die;
                                    ?>
                                    <tr class="selectable">
                                        <td><input class="case" type="checkbox" name="case" id="<?php echo $collectionData['user_id']; ?>"/></td>
                                        <td><?php echo ++$row; ?></td>
                                        <td><?php
                                            echo $collectionData['first_name'];
                                            echo ' ';
                                            echo $collectionData['last_name'];
                                            ?></td>                                 
                                        <td><?php echo $collectionData['email']; ?></td>
                                        <td><?php echo $collectionData['reg_date']; ?></td>
                                    </tr>
                                    <?php
                                }
                            }
                            ?>	
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<script>

    $(document.body).on('click', '.case', function() {
        var obj = $(this);
        if (obj.hasClass('checked'))
            obj.removeClass('checked');
        else
            obj.addClass('checked');

    });
    jQuery(document).ready(function() {
        $("#selectall").change(function() {
            var obj = $(this);
            $(".case").prop('checked', obj.prop("checked"));

            if (obj.hasClass('checked')) {
                $(".case").removeClass('checked');
                obj.removeClass('checked');
            }
            else {
                $(".case").addClass('checked');
                obj.addClass('checked');
            }
        });


        $(document.body).on("click", "#sendbtn", function(e) {
            e.preventDefault();
            var obj = $(this);
            var sel = [];
            $('.case.checked').each(function() {
                sel.push($(this).attr('id'));
            });
            var message = $('#messagecontent').val();

            if (($('#messagecontent').val() !== "") && (sel !== '')) {

                $.ajax({
                    url: '/admin/notification-ajax-handler',
                    type: 'POST',
                    datatype: 'json',
                    data: {
                        method: 'sendNotification',
                        UserID: sel,
                        Message: message
                    },
                    success: function(response) {
                        console.log(response);
                        if (response) {
                            while (sel.length)
                                sel.pop();
                            $('.case').removeAttr('checked');
                            $('.case').parent().removeClass('checked');
                            $('#selectall').removeAttr('checked');
                            $('#selectall').parent().removeClass('checked');
                            $('#messagecontent').val('');
                            $('#descriptioncontent').val('');
                            $('.notification-suc-err').show();
                            $('.notification-suc-err').html(response);
                            $('.notification-suc-err').css('color', 'green');
                            $('.notification-suc-err').delay(3000).hide('slow');
                        }
                    }
                });
                $('.case.checked').each(function() {
                    $(this).removeClass('checked');
                });
            } else {
                $('.notification-suc-err').show();
                $('.notification-suc-err').html('Please provide Message and select Checkbox');
                $('.notification-suc-err').css('color', 'red');
                $('.notification-suc-err').delay(3000).hide('slow');
            }
        });

    });
</script>
